### ISSUE TITLE
Problems with CANCEL request processing

### ISSUE THREAD

**Issue by gavllew** [versatica/JsSIP#112]
OK, buckle your seat belts and hold on - we're going for a bit of a tour.

CANCEL request hits `UA.receiveRequest()`:
1. Line 410: `JsSIP.Transactions.checkTransaction()`: returning `true` means no matching invite server transaction, and the request goes no further.  Line 641 returns `true` if the transaction exists, but has progressed beyond `STATUS_PROCEEDING` - however it does not reply with 481, so the CANCEL request gets no response.
2. Assume there is an IST in `STATUS_PROCEEDING`.  Code proceeds to UA line 463.  The CANCEL request always gets a 200 response, even if the code subsequently reaches line 468 (session cannot be found).
3. `RTCSession.receiveRequest`: only processes the CANCEL if `this.status === C.STATUS_WAITING_FOR_ANSWER`, but attempts to reply to the INVITE with 487 regardless (transaction layer should stop this if 200 has actually been sent, but this is confusing and may produce a race condition).  I think the CANCEL response should also be generated here, only sending a 200 if the 487 is sent.
4. Regarding the status check - note that `RTCSession.answer()` has several asynchronous calls between checking the status on line 276, and setting the status on line 200.  This creates a potential race condition between the 487 and the 200 - I suspect the 487 is actually sent, but JsSIP would continue as if it were a 200.

**Comment by NurullahDemirel** [comment]
@jmillan can you help me please
{originator: 'remote', message: IncomingResponse, cause: 'Bad Media Description'}
cause: "Bad Media Description"
message: IncomingResponse
body: "v=0\r\no=FreeSWITCH 1636453467 1636453468 IN IP4 64.16.228.31\r\ns=FreeSWITCH\r\nc=IN IP4 64.16.228.31\r\nt=0 0\r\na=msid-semantic: WMS a672n8Ly8bADwkVtjFkNzmuEMC4AOK7O\r\nm=audio 17380 UDP/TLS/RTP/SAVPF 8 126 13\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:126 telephone-event/8000\r\na=rtpmap:13 CN/8000\r\na=sendrecv\r\na=ptime:20\r\na=mid:0\r\na=fingerprint:sha-256 A4:97:D5:45:74:E4:7F:65:17:5F:93:4B:D2:2F:58:3C:FA:4E:10:49:D1:67:EB:F9:AF:CC:2D:3B:3D:C5:7C:26\r\na=setup:active\r\na=rtcp:17381 IN IP4 64.16.228.31\r\na=ice-ufrag:MaGcm1GZtBq8boNJ\r\na=ice-pwd:jktdtB6DasaUz0Mb0jedaK2u\r\na=candidate:9820504285 1 udp 2130706431 64.16.228.31 17380 typ host generation 0\r\na=candidate:9820504285 2 udp 2130706430 64.16.228.31 17381 typ host generation 0\r\na=end-of-candidates\r\na=ssrc:2396877466 cname:H5HU3ii2jIvGTg02\r\na=ssrc:2396877466 msid:a672n8Ly8bADwkVtjFkNzmuEMC4AOK7O a0\r\na=ssrc:2396877466 mslabel:a672n8Ly8bADwkVtjFkNzmuEMC4AOK7O\r\na=ssrc:2396877466 label:a672n8Ly8bADwkVtjFkNzmuEMC4AOK7Oa0\r\n"
call_id: "6nj4d5eu8hj3ri3kl9bi"
cseq: 8517
data: "SIP/2.0 200 OK\r\nVia: SIP/2.0/TCP efu1bvqdq33l.invalid;rport=33868;received=78.180.56.47;branch=z9hG4bK3982537\r\nRecord-Route: <sip:10.255.0.1;transport=tcp;r2=on;lr;ftag=4au4bfl2r0>\r\nRecord-Route: <sip:192.76.120.10:7443;transport=ws;r2=on;lr;ftag=4au4bfl2r0>\r\nFrom: \"Alice ¶€ĸøĸø\" <sip:info89383@sip.telnyx.com>;tag=4au4bfl2r0\r\nTo: <sip:+905380692297@sip.telnyx.com>;tag=9gc21t2eBN9gc\r\nCall-ID: 6nj4d5eu8hj3ri3kl9bi\r\nCSeq: 8517 INVITE\r\nContact: <sip:+905380692297@10.13.142.4:5070;transport=tcp>\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REFER, NOTIFY\r\nSupported: path\r\nAllow-Events: talk, hold, conference, refer\r\nContent-Type: application/sdp\r\nContent-Disposition: session\r\nContent-Length: 955\r\n\r\nv=0\r\no=FreeSWITCH 1636453467 1636453468 IN IP4 64.16.228.31\r\ns=FreeSWITCH\r\nc=IN IP4 64.16.228.31\r\nt=0 0\r\na=msid-semantic: WMS a672n8Ly8bADwkVtjFkNzmuEMC4AOK7O\r\nm=audio 17380 UDP/TLS/RTP/SAVPF 8 126 13\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:126 telephone-event/8000\r\na=rtpmap:13 CN/8000\r\na=sendrecv\r\na=ptime:20\r\na=mid:0\r\na=fingerprint:sha-256 A4:97:D5:45:74:E4:7F:65:17:5F:93:4B:D2:2F:58:3C:FA:4E:10:49:D1:67:EB:F9:AF:CC:2D:3B:3D:C5:7C:26\r\na=setup:active\r\na=rtcp:17381 IN IP4 64.16.228.31\r\na=ice-ufrag:MaGcm1GZtBq8boNJ\r\na=ice-pwd:jktdtB6DasaUz0Mb0jedaK2u\r\na=candidate:9820504285 1 udp 2130706431 64.16.228.31 17380 typ host generation 0\r\na=candidate:9820504285 2 udp 2130706430 64.16.228.31 17381 typ host generation 0\r\na=end-of-candidates\r\na=ssrc:2396877466 cname:H5HU3ii2jIvGTg02\r\na=ssrc:2396877466 msid:a672n8Ly8bADwkVtjFkNzmuEMC4AOK7O a0\r\na=ssrc:2396877466 mslabel:a672n8Ly8bADwkVtjFkNzmuEMC4AOK7O\r\na=ssrc:2396877466 label:a672n8Ly8bADwkVtjFkNzmuEMC4AOK7Oa0\r\n"
from: NameAddrHeader {_uri: URI, _parameters: {…}, _display_name: 'Alice ¶€ĸøĸø'}
from_tag: "4au4bfl2r0"
headers: {Via: Array(1), Record-Route: Array(2), From: Array(1), To: Array(1), Call-ID: Array(1), …}
method: "INVITE"
reason_phrase: "OK"
sdp: null
status_code: 200
to: NameAddrHeader {_uri: URI, _parameters: {…}, _display_name: undefined}
to_tag: "9gc21t2eBN9gc"
via: {protocol: 'SIP', transport: 'TCP', host_type: 'IPv4', host: 'efu1bvqdq33l.invalid', rport: 33868, …}
via_branch: "z9hG4bK3982537"
[[Prototype]]: IncomingMessage
originator: "remote"

**Comment by ibc** [comment]
@NurullahDemirel please don't pollute this CLOSED issue with unrelated questions and don't mention people here. Check the mailing list and read about WebRTC.
