### ISSUE TITLE
Multiple instances not working

### ISSUE THREAD

**Issue by glutorange** [versatica/JsSIP#157]
I've created a few JsSIP instances:

$.jsSip = []; // init

$.each(sipIds,function(id,sipId){
$.jsSip[sipId] = new JsSIP.UA({ 'ws_servers': wsServer,
'sip:' + sipId + '@myserver.net',
'password': myPassword,
'instance_id' : UUIDjs.create(4)});
});

When i start the instances in anonther loop via

$.jsSip[sipId].start() 

only the last instance is started.

I've tested with 0.3.0 and 0.3.7 in Chrome (31.0.1612.0 dev) and Firefox (23.0 and 26.0a1 (2013-08-21)).

Any suggestions?

**Comment by AbdulBsit** [comment]
@glutorange have you figured it out? Facing the same issue
