### ISSUE TITLE
Provide API to allow to change Media while in call

### ISSUE THREAD

**Issue by sdellutri** [versatica/JsSIP#209]
I would like to have an API which would allow me to change media while still in the same call.  Use case is for changing audio or video device.  For example change to the front or rear camera or change microphone or line-in device.
Perhaps this could be through the hold/unhold mechanism.
thank you

**Comment by johnryan** [comment]
@ibc stumbled on this issue while trying to accomplish the same thing. It looks like the link you referenced back in 2014 no longer exists so I was wondering if this is possible with the new architecture? I was able to set the device when making a call or answering but not during a call.

**Comment by ibc** [comment]
You can always get the [peerconnection](http://jssip.net/documentation/3.1.x/api/session/#attribute_connection), add/remove streams/tracks, and later call [renegotiate](http://jssip.net/documentation/3.1.x/api/session/#method_renegotiate).
