### ISSUE TITLE
Allow SIP credentials to be changed without restarting the UA instance

### ISSUE THREAD

**Issue by giavac** [versatica/JsSIP#241]
I'm working with a JsSIP-based client, which SIP credentials change relatively often, for security reasons.
It may happen that they need to change during a call, so the app needs to use new credentials to refresh registration while a call is active.
Empirically I've seen it's not possible to change the SIP credentials without reinitialize the client (and so an active call would be dropped).
It would be very useful to be able to "inject" new SIP credentials and keep refreshing registrations without the need to restart the UA.
Thanks.

**Comment by ibc** [comment]
Since 0.7.9 "password" can be changed in runtime:

244c9fd89f82b5707dbfdd4bf1db7c1c49bf7e4a
