### ISSUE TITLE
Version 0.4.2 is not working with FreeSwitch

### ISSUE THREAD

**Issue by IlyaRu** [versatica/JsSIP#262]
Dear colleagues,

I made two similar examples:
http://cloud001.cxwebservice.com/test_030.html
http://cloud001.cxwebservice.com/test_042.html

The difference is in versions of JsSIP (0.3.0 vs 0.4.2) and event name (started vs confirmed). Connection established, but there is no sound in 0.4.2. What to do? :-)

**Comment by jmillan** [comment]
What about newer versions?

Anyone else out there using FreeSwitch?

**Comment by hoene** [comment]
I have tested 0.5 with Freeswitch... It worked after some minor modifications.

15950c15950
<           request.reply(488);
---
>           request.reply(500);

 CH

**Comment by ibc** [comment]
Sorry @hoene, that is not a solution at all.

**Comment by fxalgrain** [comment]
Hi everybody, 

I m using JsSIP last version with a Freeswitch server too.

I have the same issue, works fine on Firefox and no sound on Chrome.
