### ISSUE TITLE
Optional Callbacks for getUserMedia() states

### ISSUE THREAD

**Issue by humancalendar** [versatica/JsSIP#272]
This is a feature request (I'm new here so I don't know what the proper protocol is for this sort of thing).

It would be handy if there were a way to define optional callbacks for the three getUserMedia() states. (Browser is asking for permission, got local media stream, unable to get user media). Currently I'm just hacking in my own function calls at the appropriate places (next to the debug() calls) in JsSIP, but it would be nice to not have to drop in my own callbacks each time I upgrade JsSIP.

In my application I need to modify the UI help messages depending on the state of camera/microphone permission. I've noticed a lot of users (especially Chrome) aren't aware that the browser is awaiting permission, and I need to immediately change the UI accordingly to help them out and direct their attention where they need to click.  The same goes for when they click "deny", I need to know about it immediately so I can let them know what to do.

Thanks for your work on this..it has been working out great so far.

**Comment by Niketufjo** [comment]
I had asked for something very similar too.
See my pull-request #159, back in 0.3
It was denied at the time, as you added the 'connecting' event.
Unfortunately, this events never seem to trigger for me in 0.5...

**Comment by humancalendar** [comment]
Niketufjo, I was able to do this (by using adapter.js with jssip).  In my main js file I have:

   // Request the microphone
    navigator.getUserMedia({ audio: true, video: false },
                           function(stream) {

                               /// SUCCESS ///
                              /// callback_success()

                             // Pass the created stream to JSSIP
                               //  otherwise JSSIP will do another getUserMedia request
                               var options = { 'mediaStream' : stream};

                               // Make the call
                               try {
                                   MyPhone.call('webrtc', options);
                               } catch(e){
                                   throw(e);
                               }
                           },
                           function(e) {

                               /// FAILURE ///
                               //  callback_failure()
                           }
    );
