### ISSUE TITLE
Offering in sdp audio and video - Respons with only audio

### ISSUE THREAD

**Issue by boazsela** [versatica/JsSIP#289]
Hi all,
I'm trying to connect JsSIP demo to my GateWay (SIP client) that doesn't support video.
When i'm offering just audio voice work great and all good.
In case i mark the video in JsSIP so in the sdp offering m=audio and m=video the GateWay respons with m=audio active and m=video disactive (mark as port 0).
In this case i have oneway voice(voice only at the GW).

Anyone know how to handle with this case?
This is bug in JsSIP demo or in Web-RTC protocol?

Thanks

**Comment by ibc** [comment]
Please, use the JsSIP public mailing list for questions. Thanks.
