### ISSUE TITLE
0.6.0 Can't get localStream in RTCSession object?

### ISSUE THREAD

**Issue by rusekr** [versatica/JsSIP#290]
Hello!

Earlier RTCSession object had methods getLocalStreams and getRemoteStreams.

Now I can't find replacement.

Even event "addstream" will return only remote stream. And potentially only one stream (not checked).

From where to get localStreams in RTCSession object?

ps. http://jssip.net/documentation/0.6.x/getting_started/ example of outgoing calls here seems outdated.

Thanks!

**Comment by ibc** [comment]
2015-01-14 14:39 GMT+01:00 Sergey Krasnikov <notifications@github.com>:

> Earlier RTCSession object had methods getLocalStreams and getRemoteStreams.
>
> Now I can't find replacement.
>
http://jssip.net/documentation/0.6.x/api/session/#attribute_connection


> Even event "addstream" will return only remote stream.
>
As the native PeerConnection.onaddstream does.



> And potentially only one stream (not checked).
>
The event is fired as many times as the native onaddstream, which depends
on how many streams the remote offers. Note however that currently just
Chrome supports multiple streams and by just using a deprecated spec. So
assume a single remote stream.



> From where to get localStreams in RTCSession object?
>
> ps. http://jssip.net/documentation/0.6.x/getting_started/ example of
> outgoing calls here seems outdated.
>
> Thanks, updated.



-- 
Iñaki Baz Castillo
<ibc@aliax.net>

**Comment by rusekr** [comment]
Thanks! Understood and applied  :)

**Comment by martinkomitsky** [comment]
It's lost again :(
From the [latest](https://jssip.net/documentation/3.3.x/getting_started/) version down to `2.0.x` I didn't find any correct info about basic call, but thanks to this issue my problem is now solved
