### ISSUE TITLE
INVITE has Session-Expires: 60 , some SIP backend complaint about it .

### ISSUE THREAD

**Issue by goseeped** [versatica/JsSIP#297]
Some back-ends like asterisk complaint for Session timers RFC4028 . so if you see the INVITE generated by jssip it is setting Session-Expires: 60 when the minimum should be 90. so after updates i get all broken at this moment.

<--- SIP read from WS:186.XX.XX.XX:37072 --->
INVITE sip:conference@59.XX.XX.XX SIP/2.0
Via: SIP/2.0/WS 11g5nllcpe3g.invalid;branch=z9hG4bK1612764
Max-Forwards: 69
To: <sip:conference@59.XX.XX.XX>
From: "101" <sip:101@59.XX.XX.XX>;tag=sse2oh0p7c
Call-ID: t3mtc5mkgqra3158ihq2
CSeq: 1515 INVITE
Authorization: Digest algorithm=MD5, username="101", realm="59.XX.XX.XX", nonce="6f6d0b56", uri="sip:conference@59.XX.XX.XX", response="ae4f444caeb26b8fd86b7444badc1b55"
Contact: <sip:lt4b9peb@11g5nllcpe3g.invalid;transport=ws;ob>
Content-Type: application/sdp
Session-Expires: 60
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: timer,ice,outbound
User-Agent: JsSIP 0.6.10
Content-Length: 1630

v=0
o=Mozilla-SIPUA-34.0 8538 0 IN IP4 0.0.0.0
s=SIP Call
t=0 0
a=ice-ufrag:1789f407
a=ice-pwd:c0242a0bf9ddf108b177ad844dd1e654
a=fingerprint:sha-256 46:06:6E:A6:0D:E1:63:96:60:69:8B:05:6D:03:FC:D7:A4:AE:D5:A2:3C:3E:B8:20:66:EF:4D:A6:06:17:EB:45
m=audio 9 RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=rtpmap:109 opus/48000/2
a=ptime:20
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=rtcp-mux
a=candidate:0 1 UDP 2122252543 192.168.2.106 42774 typ host
a=candidate:0 2 UDP 2122252542 192.168.2.106 41709 typ host
a=candidate:1 1 UDP 1686110207 186.XX.XX.XX 42774 typ srflx raddr 192.168.2.106 rport 42774
a=candidate:1 2 UDP 1686110206 186.XX.XX.XX 41709 typ srflx raddr 192.168.2.106 rport 41709
m=video 9 RTP/SAVPF 120 126 97
c=IN IP4 0.0.0.0
a=rtpmap:120 VP8/90000
a=rtpmap:126 H264/90000
a=fmtp:126 profile-level-id=42e01f;packetization-mode=1
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42e01f
a=sendrecv
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=setup:actpass
a=rtcp-mux
a=candidate:0 1 UDP 2122252543 192.168.2.106 40516 typ host
a=candidate:0 2 UDP 2122252542 192.168.2.106 45271 typ host
a=candidate:1 1 UDP 1686110207 186.XX.XX.XX 40516 typ srflx raddr 192.168.2.106 rport 40516
a=candidate:1 2 UDP 1686110206 186.XX.XX.XX 45271 typ srflx raddr 192.168.2.106 rport 45271

Thanks for the great Job, let me now your comments

**Comment by ibc** [comment]
Thanks! fixed in 0.6.11.

**Comment by goseeped** [comment]
Wow inaki thanks , i test it change to 90. :)

What i don't understand is why at the second 45 jssip send an UPDATE.

UPDATE sip:conference@59.XX.XX.XX:5060;transport=ws SIP/2.0
Via: SIP/2.0/WS 192.0.2.213;branch=z9hG4bK2290103
Max-Forwards: 69
To: <sip:conference@54.159.201.158>;tag=as01e55fd1
From: "101" <sip:101@54.159.201.158>;tag=npbhudodm8
Call-ID: 7bmfflpel0cd6seu4ss2
CSeq: 1188 UPDATE
Contact: <sip:gig1b6i5@192.0.2.213;transport=ws;ob>
Session-Expires: 90;refresher=uac
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: timer,ice,outbound
User-Agent: JsSIP 0.6.11
Content-Length: 0

Actually if  the other end in this case b2bua send in his last 200 OK that he support only:

Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

Shouldn't jssip send re-invite or something .

Thanks for you effort and for this amazing library.

**Comment by ibc** [comment]
I won't implement Session-Timers with reINVITE given that reINVITE requires sending the SDP and, hence, inspecting the SDP response each time (it may have changed). UPDATE with no SDP is the way to go for this task.

Anyhow you can disable Session-Timers in JsSIP:

http://jssip.net/documentation/0.6.x/api/ua_configuration_parameters/#parameter_session_timers

**Comment by goseeped** [comment]
Got it, thanks
