### ISSUE TITLE
Don't send our media when remote put the call on hold

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#298]
In certain cases JsSIP sends its media to the peer even if the peer has put the call on hold. It shouldn't. It happens, for example, in this case:

- A calls to B without video.
- B answers with video.
- B puts the call on hold (due SDP renegotiation A does not send media to B).
- A adds his video to the call (but B remains on hold).
- B receives video from A !!! (it should not).

**Comment by ibc** [comment]
The key here is that when A adds his video it sends a reINVITE/UPDATE with "sendrecv" and B replies with also "sendrecv". So "hold" in fact ends. The problem is that both A and B "think" that B is still on hold (no other event has notified them about the oposite).

Obviously A cannot force B to unhold, so what it should happen is the following:

* A calls to B without video.
* B answers with video.
* B puts the call on hold (due SDP renegotiation A does not send media to B).
* A adds his video to the call.
  * So A sends reINVITE with "recvonly" and mutes his media (A does not want to send media to B while B is on hold).
  * B knows that he is on hold, so should reply 200 with "sendonly".
* Then A receives the 200, inspects the direction attributes and decides whether it must fire "remote unhold" or not (if true, unmute his media).

Thoughts?

**Comment by ibc** [comment]
The key is: if B peer is on local hold he should ensure that a new SDP offer from A should produce a 200 response with "sendonly" attribute (and B's media still muted until B decides to unhold himself).

It is up to A whether he sends a reoffer to B with "recvonly" or "sendrecv" while B is on hold, but nothing should change in B which has decided to be on hold.

**Comment by ibc** [comment]
From RFC 3264, it is 100% valid to offer with "sendrecv" and reply with "sendonly":

> If an offered media stream is listed as sendrecv the corresponding
   stream in the answer MAY be marked as
   sendonly, recvonly, sendrecv, or inactive.

**Comment by jmillan** [comment]
The direction of each SDP offer and answer going out of RTCSession should be such as:

``
if (local_hold && remote_hold) direction = inactive;
else if (local_hold) direction = sendonly;
else if (remote_hold) direction = recvonly;
```
The hold() method doesn't have to deal with the media direction anymore then, but it must be set for every outgoing SDP just before sending it.

**Comment by ibc** [comment]
Exactly what I'm doing right now :)

But:

> else if (remote_hold) direction = recvonly;

Not 100% agree. A may be able to "try" to send and recv video by sending a new offer even if B put the call previously on hold. It is a task of B to keep on hold (and hopefully by also indicating it in the SDP answer).

**Comment by jmillan** [comment]
If the other party puts me on hold means that she is not willing to receive my media. I would then not insist on that, and even if I add ontoher stream and re-negotiate, I'd let her decide when she want's to hear and see me.

Otherwise we would be forcing the other party to hold/unhold us, which gets out of any desirable scope IMHO.

**Comment by ibc** [comment]
If I put you on hold you can later send me a reoffer with "sendrecv". It is my task to keep my self on hold (I won't send you my media) and will indicate it by replying with "recvonly".

It is perfectly valid. In any case, we must be ready for that.

**Comment by hanweimin** [comment]
all:
  When A and B are having video calls, the video screen cannot be restored if A or B hold is passed through unhold again, why?

**Comment by ibc** [comment]
Please, don't assume that usage problems are bugs in the library. Hold and unhold stuff works perfectly in JsSIP.
