### ISSUE TITLE
Don't disable local MediaStream when hold()

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#299]
Currently, when `hold()` is called the local MediaStream is disabled:

```
function toogleMuteVideo(mute) {
  var streamIdx, trackIdx, tracks,
    localStreams = this.connection.getLocalStreams();

  for (streamIdx in localStreams) {
    tracks = localStreams[streamIdx].getVideoTracks();
    for (trackIdx in tracks) {
      tracks[trackIdx].enabled = !mute;
    }
  }
}
```

This means that even the local video element is "stopped" (black video). Couldn't we just stop sending our media without disabling it locally?

**Comment by jmillan** [comment]
Yes, that would make sense if RTCPeerConnection behaves accordingly when setting the SDP direction attribute on the description passed to setLocalDescription(),

**Comment by ibc** [comment]
So, you mean that the only way to avoid PeerConnection to send our media is by disabling the local tracks, am I right?

**Comment by ibc** [comment]
The solution is to call `clone()` on the local MediaStream and use the cloned one into the HTML video element (remember to also close it when done).

P.S: just implemented in Chrome.
