### ISSUE TITLE
Missing info in docs about STUN/TURN settings

### ISSUE THREAD

**Issue by mtirsel** [versatica/JsSIP#301]
Please add info about these settings. They just disappeared in version 0.6 and I need to set them up else no RTC on my network is possible. I spent many hours in docs and source code but without any success.  Thanks!

**Comment by ibc** [comment]
http://jssip.net/documentation/0.6.x/api/ua/#method_call
http://jssip.net/documentation/0.6.x/api/session/#method_answer
