### ISSUE TITLE
on "Request Timeout" BYE is not sent

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#302]
This is an important issue. Flow:

* JsSIP in an established session with a peer.
* JsSIP sends in-dialog UPDATE or reINVITE (INFO not tested).
* No answer from the peer so "Request Timeout" is fired and the call ended, but...

There is no BYE from JsSIP !!

For **sure** it MUST be (unless the transport is down, of course).

**Comment by jmillan** [comment]
True,

The RTCSession `onRequestTimeout()` and `onDialogError()` should call `terminate()` instead of merely invoke `failed()` or `ended()`, so the corresponding ending SIP message is sent.

The requests `BYE`, `CANCEL` sent by `terminate()` are sent without any event handler, meaning that a timeout or another error in those messages will not call again `onRequestTimeout`, avoiding this evil loop.

**Comment by ibc** [comment]
just that? I mean, it is just about replacing:

```
RTCSession.prototype.onRequestTimeout = function() {
  debug('onRequestTimeout');

  if(this.status !== C.STATUS_TERMINATED) {
    if (this.status === C.STATUS_CONFIRMED) {
      ended.call(this, 'system', null, JsSIP_C.causes.REQUEST_TIMEOUT);
    } else {
      failed.call(this, 'system', null, JsSIP_C.causes.REQUEST_TIMEOUT);
    }
  }
};
```

with this?:

```
RTCSession.prototype.onRequestTimeout = function() {
  debug('onRequestTimeout');

  if(this.status !== C.STATUS_TERMINATED) {
    this.terminate( WHAT HERE? );
  }
};

```

**Comment by jmillan** [comment]
Yes, mostly that.

``
RTCSession.prototype.onRequestTimeout = function() {
  debug('onRequestTimeout');

  if(this.status !== C.STATUS_TERMINATED) {
    this.terminate( {status_code: 408, reason_phrase: JsSIP_C.causes.REQUEST_TIMEOUT} );
  }
};
``

That will generate a BYE with the corresponding Reason header field.

I'd need to do the corresponding tests though in case this breaks something that I can't spot now.

**Comment by ibc** [comment]
I'll commit it (no new version yet).

**Comment by jmillan** [comment]
:+1:

**Comment by ibc** [comment]
I've tested it (just the request timeout when sending an UPDATE or reINVITE). Indeed it sends a BYE. The only "problem" is that now "ended" is fired with "BYE" as cause.

**Comment by jmillan** [comment]
Not an issue anymore 2cbebf5eb9c482557eaade2176eb5d8ddeeffda6

**Comment by ibc** [comment]
Great!

Just one question: I get this error:

`SIP call ended: [cause: Request Timeout, originator: local]`

Does it make sense that "originator" is "local" in this case? (I sent an UPDATE for which there was not response).

**Comment by jmillan** [comment]
I think "Request Timeout" should be taken as: "A request I've sent hasn't been responded on time". I mean that the direction is implicit in this error. Anyway 'remote' may be more accurate.

**Comment by ibc** [comment]
Let's close this bug, it's fixed.
