### ISSUE TITLE
There are no session event on incomming call

### ISSUE THREAD

**Issue by kvishnivetsky** [versatica/JsSIP#303]
There is a bug in RTCSession.prototype.answer method:
eventHanlers propertie, set in options object is ignored by answer method
Here is a patch:
diff --git a/dist/jssip.js b/dist/jssip.js
index 01c5381..8fb1366 100644
--- a/dist/jssip.js
+++ b/dist/jssip.js
@@ -13880,6 +13880,7 @@ RTCSession.prototype.answer = function(options) {
     pcConfig = options.pcConfig || {iceServers:[]},
     rtcConstraints = options.rtcConstraints || null,
     rtcAnswerConstraints = options.rtcAnswerConstraints || null;
+    eventHandlers = options.eventHandlers || {};
 
   this.rtcAnswerConstraints = rtcAnswerConstraints;
   this.rtcOfferConstraints = options.rtcOfferConstraints || null;
@@ -13907,6 +13908,11 @@ RTCSession.prototype.answer = function(options) {
 
   this.status = C.STATUS_ANSWERED;
 
+  // Set event handlers
+  for (event in eventHandlers) {
+    this.on(event, eventHandlers[event]);
+  }
+
   // An error on dialog creation will fire 'failed' event
   if (! createDialog.call(this, request, 'UAS')) {
     request.reply(500, 'Error creating dialog');

**Comment by jmillan** [comment]
That's right,

These events are typically set on UA `newRTCSession` event callback, but since `UA.call()` method does allow the eventHandlers object, the `RTCSession.answer()` should allow them too, for consistency.

**Comment by ibc** [comment]
I do not agree. At the time of answer() so many events have already fired
(connecting, progress). If so we should also allow events in reject() (to
set the failed event) and so on. IMHO no sense.

**Comment by jmillan** [comment]
Of course the callbacks for the events which have already fired are worthless defining; this is a matter of documentation.

The `RTCSession.answer()` as well as `RTCSession.connect()` are the logical points where a session starts. Currently, apart from the UA `newRTCSession` event, the user can set the session event handlers  when making the call `UA.call()` but not when answering. For me is very logical and more consistent to be able to set the callbacks when answering as well as when making the call.

**Comment by ibc** [comment]
I cannot agree. `answer()` can only be called within the `ua.on('newRTCSession')`. In that block (where we get the `session` instance) we set all the session events. What is the point in setting some of them there ("progress") and set some others later ("confirmed", "ended") after `answer()` is called?

Really, it makes no sense.

**Comment by jmillan** [comment]
Both outgoing and incoming RTCSession event handlers can be set in the `ua.on('newRTCSession')` event callback. There is no need to do it at `ua.call()` nor at `RTCSession.answer()` at all. The same callbacks can be set to the RTCSession regardless its direction (as done in tryit.jssip.net for example)

On the other hand, one can establish a call `ua.call()` and pass the event handlers right when calling, but the receiver cannot do it when answering `RTCSession.answer()`. It seems to me consistent to have it in both places or at none.

It's not a core problem, but more a cosmetic fact.

**Comment by ibc** [comment]
I'm about propose that we modify the current behavior. It makes no real sense that "newRTCSession" or "newMessage" is fired for both incoming and outgoing calls. In fact I already made `ua.call()` and `ua.sendMessage()` to return the corresponding `RTCSession` or `Message` instance so the developer can set events in the context in which he called `call()`.

Of course there is no context for incoming calls or messages, and that's the reason we handle them in UA events.

I strongly suggest that "newRTCSession" and "newMessage" are just fired for incoming calls/messages.

**Comment by ibc** [comment]
After coding many UI's for JsSIP I'm pretty sure this is the right way. There is no real benefit on handling outgoing calls on "newRTCSession" event.

**Comment by jmillan** [comment]
mmm.., care must be taken here. If you set the callbacks to the `RTCSession` instance returned by `ua.call()`, you're missing the chance to act upon some `RTCSession.on('failure')` situations (ie: gUM failure, local description creation failure) and also the  `RTCSession.on('connecting')` event.

**Comment by jmillan** [comment]
I mean, you're very free to obviate those events, but some others need to act upon a gUM failure/reject.

**Comment by ibc** [comment]
No, I mean:

```
var session = ua.call('1234', {
  eventsHandler: { ... }
});

jQuery('#holdButton').click(function() {
  session.hold();  // Have the session here, in *context*
});
```

**Comment by jmillan** [comment]
I get it. The motivation of firing `ua.on('newRTCSession')`for both directions was having, or being able to have, a single point where the event handlers for the session could be set, regardless it's direction. Don't you find it something good to have now?

**Comment by ibc** [comment]
> Don't you find it something good to have now?

No. After coding N UI's for JsSIP I absolutely think that **context** is the important stuff. We can have local context on outgoing calls (if we use the session returned by `call()`) and we cannot have local context for incoming calls (because it is fired by an external network event).

Having to handle outgoing calls without context just to get the same behavior as in incoming calls is an artificial limitation rather than a benefit.

**Comment by jmillan** [comment]
Outgoing calls can be already handled with context thanks to returning the instance on `ua.call()`. That's perfect. They don't need to be handled on `ua.on('newRTCSession')`.

I'm not against firing `ua.on('newMessage')`, `ua.on('newRTCSession')` only for incoming instances. User implementations would have to adhere to it and thats all.

**Comment by ibc** [comment]
Anyhow, the original issue was not about that, my fault XD

**Comment by jmillan** [comment]
Apropos to the original issue, same. If we adopt that the event handlers for the incoming `RTCSession` must be set before `RTCSession.answer()`, it's Ok. Otherwise, if we permit setting them on `RTCSEssion.answer()` is Ok too. It's just a matter of consensus.

**Comment by kvishnivetsky** [comment]
Hi, Guys.
BTW: Tere is "one way audio" in Mozilla FireFox v35.0.1 on Ubuntu Desktop and MS Windows 7 64bit(corp license). And my path gives me a chance to handle 'addstream' event and assign incomming media stream to video/audio HTML5 element.

**Comment by jmillan** [comment]
@kvishnivetsky,

you can define the RTCSession event handlers on the `ua.on('newRTCSession')` event callback just before answering. You don't need to pass the event handlers on `RTCSession.answer()` for that.

**Comment by kvishnivetsky** [comment]
Ok, I see. Let's then set there session-level event handlers for both types of calls i.e. inbound and outbound.

**Comment by kvishnivetsky** [comment]
Done. See pull request for changes.

**Comment by kvishnivetsky** [comment]
Also, I moved ACK sending for 200 OK/SDP out of SDP seccess handler, cause this ACK is and ACKnoledgement for RECV message from net, but not parsing or verification/validation ACKnoledgment.

**Comment by jmillan** [comment]
@kvishnivetsky 

Apropos the initial issue. You can set the RTCSession event handlers for the incoming call in the `ua.on('newRTCSession')` event handler, as documented.

Any change in the API regarding to this will be properly documented.
