### ISSUE TITLE
JsSIP pushing video in m line even though Video was disabled, resulting in error 488

### ISSUE THREAD

**Issue by cvmathur** [versatica/JsSIP#305]
Hello,

I was trying web to PSTN call using Cisco SIP server with Kamailio as proxy and I can see from the Chrome console that JsSIP is sending video information in m line and a lines respectively even though video was disabled as a result, 200 OK bore port = 0 for video. 
Now, 200 OK also carried media-server information in Contact header and proxy information in o and c lines but (not sure why) - 
1. JsSIP reported an error: Failed to parse SessionDescription. m=video 0 RTP/SAVPF Expects at least 4 fields.
2. JsSIP chose the information present in Contact header to send the ACK
3. JsSIP sent BYE with reason '488 Not Acceptable Here'

Logs are as below - 
jssip.js:21352 JsSIP:RTCSession new +22m
jssip.js:21352 JsSIP:RTCSession connect() +1ms
jssip.js:21352 rtcninja:Connection new | original pcConfig: +7ms Object {iceServers: Array[0]}
jssip.js:21352 rtcninja:Connection new | processed pcConfig: +7ms Object {iceServers: Array[0]}
jssip.js:21352 JsSIP:RTCSession newRTCSession +4ms
jssip.js:21352 rtcninja:Adapter getUserMedia() | constraints: +21ms Object {audio: true, video: false}
jssip.js:21352 rtcninja:Adapter getUserMedia() | success +1s
jssip.js:21352 rtcninja:Connection addStream() | stream: +0ms MediaStream {onremovetrack: null, onaddtrack: null, onended: null, ended: false, id: "PNXP72ZT4pegOXihi5834xFJ30B1oVKJyVFQ"…}
jssip.js:21352 JsSIP:RTCSession session connecting +2ms
jssip.js:21352 JsSIP:RTCSession createLocalDescription() +1ms
jssip.js:21352 rtcninja:Connection createOffer() +0ms
jssip.js:21352 rtcninja:Connection createOffer() | success +4ms
jssip.js:21352 rtcninja:Connection setLocalDescription() +1ms
jssip.js:21352 rtcninja:Connection onnegotiationneeded() +10ms
jssip.js:21352 rtcninja:Connection onsignalingstatechange() | signalingState: have-local-offer +50ms
jssip.js:21352 rtcninja:Connection setLocalDescription() | success +2ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m0(audio) candidate:1136844497 1 udp 2122260223 14.98.10.42 60189 typ host generation 0 +4ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m0(audio) candidate:1136844497 2 udp 2122260223 14.98.10.42 60189 typ host generation 0 +1ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m1(video) candidate:1136844497 1 udp 2122260223 14.98.10.42 60189 typ host generation 0 +0ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m1(video) candidate:1136844497 2 udp 2122260223 14.98.10.42 60189 typ host generation 0 +1ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m0(audio) candidate:222372385 1 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0 +150ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m0(audio) candidate:222372385 2 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0 +0ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m1(video) candidate:222372385 1 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0 +1ms
jssip.js:21352 rtcninja:Connection onicecandidate() | m1(video) candidate:222372385 2 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0 +0ms
jssip.js:21352 rtcninja:Connection onicecandidate() | end of candidates +55ms
jssip.js:21352 JsSIP:Transport sending WebSocket message:

INVITE sip:919650926333@157.238.178.153 SIP/2.0
Route: <sip:125.99.186.126:10080;transport=ws;lr>
Via: SIP/2.0/TCP 192.0.2.51;branch=z9hG4bK9989745
Max-Forwards: 69
To: <sip:919650926333@157.238.178.153>
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
Call-ID: rubceuvog9trrhicg37v
CSeq: 5464 INVITE
Contact: <sip:pfbpdf80@192.0.2.51;transport=ws;ob>
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: ice,outbound
User-Agent: JsSIP 0.6.4
Content-Length: 2574

v=0
o=- 7154212215086411470 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS PNXP72ZT4pegOXihi5834xFJ30B1oVKJyVFQ
m=audio 60189 RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 14.98.10.42
a=rtcp:60189 IN IP4 14.98.10.42
a=candidate:1136844497 1 udp 2122260223 14.98.10.42 60189 typ host generation 0
a=candidate:1136844497 2 udp 2122260223 14.98.10.42 60189 typ host generation 0
a=candidate:222372385 1 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0
a=candidate:222372385 2 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0
a=ice-ufrag:VtZ5qAfrYzTxoAHf
a=ice-pwd:AopcZ4ABDAKTwcEv0Ffdt5AN
a=ice-options:google-ice
a=fingerprint:sha-256 07:3F:5F:45:8C:5B:2B:6C:01:7D:9F:EB:50:5F:EB:46:A5:C4:D0:3E:BD:57:6D:71:FC:FE:AF:91:42:74:EB:0B
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:870897274 cname:SguWiL3TVCTsuZgY
a=ssrc:870897274 msid:PNXP72ZT4pegOXihi5834xFJ30B1oVKJyVFQ 67ae9b0b-fa70-4719-a35e-12de77abf397
a=ssrc:870897274 mslabel:PNXP72ZT4pegOXihi5834xFJ30B1oVKJyVFQ
a=ssrc:870897274 label:67ae9b0b-fa70-4719-a35e-12de77abf397
m=video 60189 RTP/SAVPF 100 116 117 96
c=IN IP4 14.98.10.42
a=rtcp:60189 IN IP4 14.98.10.42
a=candidate:1136844497 1 udp 2122260223 14.98.10.42 60189 typ host generation 0
a=candidate:1136844497 2 udp 2122260223 14.98.10.42 60189 typ host generation 0
a=candidate:222372385 1 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0
a=candidate:222372385 2 tcp 1518280447 14.98.10.42 0 typ host tcptype active generation 0
a=ice-ufrag:VtZ5qAfrYzTxoAHf
a=ice-pwd:AopcZ4ABDAKTwcEv0Ffdt5AN
a=ice-options:google-ice
a=fingerprint:sha-256 07:3F:5F:45:8C:5B:2B:6C:01:7D:9F:EB:50:5F:EB:46:A5:C4:D0:3E:BD:57:6D:71:FC:FE:AF:91:42:74:EB:0B
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100

 +13ms
jssip.js:21352 JsSIP:Transport received WebSocket text message:

SIP/2.0 100 trying -- your call is important to us
Via: SIP/2.0/TCP 192.0.2.51;branch=z9hG4bK9989745;rport=52519;received=14.98.10.42
To: <sip:919650926333@157.238.178.153>
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
Call-ID: rubceuvog9trrhicg37v
CSeq: 5464 INVITE
Server: kamailio (4.2.2 (x86_64/linux))
Content-Length: 0

 +311ms
jssip.js:21352 JsSIP:RTCSession receiveInviteResponse() +12ms
jssip.js:21352 JsSIP:Transport received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 192.0.2.51;rport=52519;received=14.98.10.42;branch=z9hG4bK9989745
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
To: <sip:919650926333@157.238.178.153>;tag=CEE92464-1B78
Date: Wed, 11 Feb 2015 07:24:42 GMT
Call-ID: rubceuvog9trrhicg37v
Server: Cisco-SIPGateway/IOS-12.x
CSeq: 5464 INVITE
Allow: INVITE, OPTIONS, BYE, CANCEL, ACK, PRACK, COMET, REFER, SUBSCRIBE, NOTIFY, INFO, UPDATE, REGISTER
Allow-Events: telephone-event
Contact: <sip:8887999561919650926333@199.27.244.6:5060>
Record-Route: <sip:157.238.178.153;lr=on>,<sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:5090;r2=on;lr=on>,<sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:10080;transport=ws;r2=on;lr=on>
Content-Disposition: session;handling=required
Content-Type: application/sdp
Content-Length: 0

 +871ms
jssip.js:21352 JsSIP:RTCSession receiveInviteResponse() +16ms
jssip.js:21352 JsSIP:Dialog new UAC dialog created with status EARLY +1ms
jssip.js:21352 JsSIP:RTCSession session progress +0ms
jssip.js:21352 JsSIP:Transport received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.0.2.51;rport=52519;received=14.98.10.42;branch=z9hG4bK9989745
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
To: <sip:919650926333@157.238.178.153>;tag=CEE92464-1B78
Date: Wed, 11 Feb 2015 07:24:42 GMT
Call-ID: rubceuvog9trrhicg37v
Server: Cisco-SIPGateway/IOS-12.x
CSeq: 5464 INVITE
Allow: INVITE, OPTIONS, BYE, CANCEL, ACK, PRACK, COMET, REFER, SUBSCRIBE, NOTIFY, INFO, UPDATE, REGISTER
Allow-Events: telephone-event
Contact: <sip:8887999561919650926333@199.27.244.6:5060>
Record-Route: <sip:157.238.178.153;lr=on>,<sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:5090;r2=on;lr=on>,<sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:10080;transport=ws;r2=on;lr=on>
Content-Type: application/sdp
Content-Length: 664

v=0
o=CiscoSystemsSIP-GW-UserAgent 2316 9329 IN IP4 125.99.186.126
s=SIP Call
c=IN IP4 125.99.186.126
t=0 0
a=ice-lite
m=audio 31406 RTP/SAVPF 0 126 100
c=IN IP4 125.99.186.126
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=rtpmap:100 X-NSE/8000
a=fmtp:100 192-194
a=direction:active
a=sendrecv
a=rtcp:31406
a=rtcp-mux
a=setup:active
a=fingerprint:sha-1 19:20:8B:A1:21:7A:F6:DC:CC:5F:93:1C:AD:87:B8:79:1D:82:CB:7F
a=ice-ufrag:GrtXRx2z
a=ice-pwd:FpnGrWYGiRCshuPTUhbxMeCqF5nv
a=candidate:eXTcQtyPehJo7hZS 1 UDP 2130706431 125.99.186.126 31406 typ host
m=video 0 RTP/SAVPF
c=IN IP4 125.99.186.126
a=direction:active

 +10ms
jssip.js:21352 JsSIP:RTCSession receiveInviteResponse() +9ms
jssip.js:21352 JsSIP:Dialog dialog rubceuvog9trrhicg37vlbk2lhbdmcCEE92464-1B78  changed to CONFIRMED state +2ms
jssip.js:21352 rtcninja:Connection setRemoteDescription() +1ms
jssip.js:21510 rtcninja:ERROR:Connection setRemoteDescription() | error: +1ms Failed to parse SessionDescription. m=video 0 RTP/SAVPF Expects at least 4 fields.
jssip.js:21352 JsSIP:RTCSession acceptAndTerminate() +1ms
jssip.js:21352 JsSIP:RTCSession sendRequest() +1ms
jssip.js:21352 JsSIP:RTCSession:Request new | ACK +1ms
jssip.js:21352 JsSIP:Transport sending WebSocket message:

ACK sip:8887999561919650926333@199.27.244.6:5060 SIP/2.0
Route: <sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:10080;transport=ws;r2=on;lr=on>
Route: <sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:5090;r2=on;lr=on>
Route: <sip:157.238.178.153;lr=on>
Via: SIP/2.0/TCP 192.0.2.51;branch=z9hG4bK4424563
Max-Forwards: 69
To: <sip:919650926333@157.238.178.153>;tag=CEE92464-1B78
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
Call-ID: rubceuvog9trrhicg37v
CSeq: 5464 ACK
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: outbound
User-Agent: JsSIP 0.6.4
Content-Length: 0

 +4ms
jssip.js:21352 JsSIP:RTCSession sendRequest() +2ms
jssip.js:21352 JsSIP:RTCSession:Request new | BYE +1ms
jssip.js:21352 JsSIP:Transport sending WebSocket message:

BYE sip:8887999561919650926333@199.27.244.6:5060 SIP/2.0
Route: <sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:10080;transport=ws;r2=on;lr=on>
Route: <sip:yhTeAGV2x5wZVAV9Y7p+J2AOYgoqzSc=@125.99.186.126:5090;r2=on;lr=on>
Route: <sip:157.238.178.153;lr=on>
Via: SIP/2.0/TCP 192.0.2.51;branch=z9hG4bK5374066
Max-Forwards: 69
To: <sip:919650926333@157.238.178.153>;tag=CEE92464-1B78
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
Call-ID: rubceuvog9trrhicg37v
CSeq: 5465 BYE
Reason: SIP ;cause=488; text="Not Acceptable Here"
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: outbound
User-Agent: JsSIP 0.6.4
Content-Length: 0

 +4ms
jssip.js:21352 JsSIP:RTCSession session failed +2ms
jssip.js:21352 JsSIP:RTCSession close() +1ms
jssip.js:21352 JsSIP:Transport received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.0.2.51;rport=52519;received=14.98.10.42;branch=z9hG4bK5374066
From: "1399004090" <sip:1399004090@157.238.178.153>;tag=lbk2lhbdmc
To: <sip:919650926333@157.238.178.153>;tag=CEE92464-1B78
Date: Wed, 11 Feb 2015 07:24:43 GMT
Call-ID: rubceuvog9trrhicg37v
Server: Cisco-SIPGateway/IOS-12.x
Content-Length: 0
CSeq: 5465 BYE

 +472ms
jssip.js:21352 JsSIP:RTCSession:Request onSuccessResponse +5ms
jssip.js:21352 JsSIP:InviteClientTransaction Timer B expired for transaction z9hG4bK9989745 +30s
jssip.js:21352 JsSIP:InviteClientTransaction Timer M expired for transaction z9hG4bK9989745 +1s

Please help me if I am doing anything wrong here !

Warm Regds,
Rahul

**Comment by ibc** [comment]
Please, use the JsSIP mailing list for questions, don't open an issue for that.

BTW, if your INVITE includes a "m=video" line (note the "a=recvonly") is because you have told JsSIP to include it. Please figure out which options you provided `call()` with. If you are just reusing the code at http://tryit.jssip.net then, again, figure out what options you are passing to `call()` and why:

http://jssip.net/documentation/0.6.x/api/ua/#method_call
