### ISSUE TITLE
rtcConstraints argument has no effect

### ISSUE THREAD

**Issue by nicketson** [versatica/JsSIP#306]
http://jssip.net/documentation/0.6.x/api/ua/#method_call

The rtcConstraints argument referenced above is passed to rtcninja.RTCPeerConnection constructor but rtcninja does not use it. 

I created an issue and uploaded a fix here:
https://github.com/eface2face/rtcninja.js/issues/9

**Comment by ibc** [comment]
The `rtcConstraints` argument in the `RTCPeerConnection` is deprecated in the latest WebRTC draft:

http://www.w3.org/TR/webrtc/#interface-definition

Constraints must be set in `createOffer()` and `createAnswer()`. That's why rtcninja ignores it.

**Comment by rshpount** [comment]
How can we provide googIPv6 to the peer connection? It looks like this parameter is ignored by chrome when passed in createOffer.

On the other hand, if rtcConstraints are ignored, should they be removed from JSSip?

**Comment by ibc** [comment]
> How can we provide googIPv6 to the peer connection? It looks like this parameter is ignored by chrome when passed in createOffer.

Interesting. Well, anyhow that should not be a place to enable IPv6 support :)


> On the other hand, if rtcConstraints are ignored, should they be removed from JSSip?

Are there other useful PC constraints that do not work in `createOffer`?

Note that I'm a bit against the deprecated `rtcConstraints` in rtcninja since managing that with the new/future spec (`updateConfig()`, etc) is tedious.

**Comment by rshpount** [comment]
Not sure about other constraints but this is the only place to manage IPv6 candidates in the current version of Chrome and we need a solution for the current interop problems (like Firefox not being able to parse IP6 address in the c= line). I would hope this fix is accepted until other ways to manage IPv6 support are implemented despite rtcConstraints being deprecated.

**Comment by ibc** [comment]
ok, I will do it soon and notify it here.

**Comment by ibc** [comment]
Done in 0.6.19

**Comment by ibc** [comment]
@rshpount you may interested in Chrome 42 news:

https://mail.google.com/mail/u/0/?pli=1#inbox/14beaa47e3d68dd6

> Gathering of IPv6 candidates is now enabled by default. This is currently in the process of rolling out; applications can still explicitly disable v6 if needed by setting googIPv6 to false in the PeerConnection ctor.

Note that it says "PeerConnection ctor", may be those custom vendor options are now in `pcConfig` instead of in `pcConstraints`?

**Comment by rshpount** [comment]
Either location for those options is fine for me as long as we have a place to set the googIPv6 parameter. I will try to see what other options are only settable in PeerConnection ctor. On the other hand, it would be better long term to ask google to move these settings into createOffer via a chrome bug report.

**Comment by rshpount** [comment]
FYI: We see Chrome 40 on Time Warner network (which has IPv6 enabled) collecting IPv6 candidates  without googIPv6 constraint set. This is causing all sorts of interop issues including issues on calls with Firefox. IPv6 is not supposed to be enabled in the browser but IPv6 candidates periodically show up anyway.

**Comment by ibc** [comment]
wow

**Comment by joeGitHubK** [comment]
Hi guys,
This issue is still there, did anyone managed to make sipjs or jsSIP working with chrome? this option gooIPv6 make sipjs and jsSIP useless on chrome in its last release, at least for freeswitch solutions

**Comment by rshpount** [comment]
@joeGitHubK We got this working. Please see https://github.com/turbobridge/WebCall for details.

**Comment by ibc** [comment]
The issue is not still there as you can pass "rtcConstraints" to the [UA.call](http://jssip.net/documentation/0.6.x/api/ua/#method_call) method.

So, JsSIP **does** work with Chrome. And if it does not work with FreeSwitch due to some IPv6 related "issue"  then  that is a **bug** in FreeSwitch rather than in JsSIP.
