### ISSUE TITLE
Code line 16056 testing length body.

### ISSUE THREAD

**Issue by mfrlinux** [versatica/JsSIP#307]
In my SIP application is sent a DTMF with 4 field more in the body .

Line 16056 does not accept DTMF:

```
    if (body.length === 2) {
      if (reg_tone.test(body[0])) {
        this.tone = body[0].replace(reg_tone,'$2');
      }
      if (reg_duration.test(body[1])) {
        this.duration = parseInt(body[1].replace(reg_duration,'$2'), 10);
      }
    }
```

Change:

```
 if (body.length >= 2) {
      if (reg_tone.test(body[0])) {
        this.tone = body[0].replace(reg_tone,'$2');
      }
      if (reg_duration.test(body[1])) {
        this.duration = parseInt(body[1].replace(reg_duration,'$2'), 10);
      }
    }
```

**Comment by ibc** [comment]
Sorry is is hard to understand what you mean. Can you describe better the problem?

**Comment by mfrlinux** [comment]
My application is sent 4 fields in the body in SIP Message.
But your code accept only 2 fileds in the body.
So your code makes my application does not receive DTMF .
My solution was to modify the code on the line below ,
if (body.length >= 2) {
....
}

**Comment by jmillan** [comment]
Is it actually allowed to send more than one signal (digit) for each INFO request?

**Comment by jmillan** [comment]
Not as far I can see. The body should have two lines, one for the digit or signal and one for the duration.

**Comment by ibc** [comment]
DTMF in INFO requests is just a proprietary solution which never became a standard.

Cisco uses this format:

```
Content-Type: application/dtmf-relay

Signal=5
Duration=160
```

**Comment by jmillan** [comment]
Yes, I know,

I've never seen more than one DTMF coming in one INFO request. The format used by Cisco does use a single one per  packet as well as [this](https://tools.ietf.org/html/draft-kaplan-dispatch-info-dtmf-package-00) old draft.

**Comment by rshpount** [comment]
I would guess this is to deal with more parameters per single DTMF tone, not with more then one DTMF tone per message. I think some gateways do send more parameters, such as amplitude. Actually some gateways only send the Signal and do not provide duration. An example of their offending SIP INFO message would be helpful here. Ideally the code that iterates through INFO body and matches individual lines to signal and duration would be more robust then code that expects two lines in exact sequence.

**Comment by jmillan** [comment]
I must agree with you @rshpount

**Comment by mfrlinux** [comment]
Contains Signal and Duration. But I think it has some \n after the Duration.
![discarteddtmf](https://cloud.githubusercontent.com/assets/4224070/6525063/9973137e-c3df-11e4-9563-0548b63e9e61.png)
![receivedtmf](https://cloud.githubusercontent.com/assets/4224070/6525064/9973f9a6-c3df-11e4-934b-02fc97b5d142.png)

**Comment by ibc** [comment]
@jmillan may we make the DTMF body parser more generic so we allow more lines but we just process the tone (first line) and the duration (second line, if any)? We may also allow \r\n or just \n line separators.

**Comment by jmillan** [comment]
Yes, absolutely.

**Comment by jmillan** [comment]
I'm a bit busy right now with other things, but let me do it when I get some time.

**Comment by ibc** [comment]
:+1:

**Comment by mfrlinux** [comment]
thanks guys

**Comment by ibc** [comment]
Great. JsSIP 0.6.20 released.

**Comment by mfrlinux** [comment]
Tested. It's ok.
