### ISSUE TITLE
for ... in in toggleMuteAudio, toggleMuteVideo

### ISSUE THREAD

**Issue by pavelsc** [versatica/JsSIP#308]
I think this is a bad idea, because it is incompatible with libraries which use Array.prototype methods. Can you please replace them with this at 15771 line?
```
function toogleMuteAudio(mute) {
  var streamIdx, trackIdx, tracks, localStreamsLen, tracksLen,
    localStreams = this.connection.getLocalStreams();

  for (streamIdx = 0, localStreamsLen = localStreams.length; streamIdx < localStreamsLen; streamIdx++) {
    tracks = localStreams[streamIdx].getAudioTracks();
    for (trackIdx = 0, tracksLen = tracks.length; trackIdx < tracksLen; trackIdx++) {
      tracks[trackIdx].enabled = !mute;
    }
  }
}

function toogleMuteVideo(mute) {
  var streamIdx, trackIdx, tracks, localStreamsLen, tracksLen,
    localStreams = this.connection.getLocalStreams();

  for (streamIdx = 0, localStreamsLen = localStreams.length; streamIdx < localStreamsLen; streamIdx++) {
    tracks = localStreams[streamIdx].getVideoTracks();
    for (trackIdx = 0, tracksLen = tracks.length; trackIdx < tracksLen; trackIdx++) {
      tracks[trackIdx].enabled = !mute;
    }
  }
}
```

**Comment by jmillan** [comment]
You're probably right @pavelsc .

I think those libraries should make those methods non 'enumerable' though.

We'll check it. Thanks

**Comment by pavelsc** [comment]
I can't describe for in issue far better than it was discussed here http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea
Thanks

**Comment by jmillan** [comment]
Yes, I know. 

I wonder why a library extends an object with `enumerable` properties when they should not be so.

**Comment by jmillan** [comment]
Will change it anyway. We're not denying the use of such libraries.

**Comment by ibc** [comment]
@pavelsc for future references to the code, please don't take the bundle file under `dist/` but the specific file under `lib/` ;)

**Comment by ibc** [comment]
I'm fixing it. BTW if you find this dangerous usage elsewhere in the code, please report ;)

**Comment by jmillan** [comment]
@ibc I'm with it. Will commit right now

**Comment by ibc** [comment]
opps, it's also done here XD

ok, let's chat!
