### ISSUE TITLE
Some questions on JSSIP

### ISSUE THREAD

**Issue by RVN-BR** [versatica/JsSIP#309]
Hi Everyone... this looks like a fantastic project...

I have some questions... I'm installing to for some tests, but wondering some things...

- Is it possible to use this in iOS or Android? (Is there a sort of jssip sdk for any of those platforms?) or is it possible to use other webrtc toolkits to connect with say oversip or similar?
- Is it possible to record audio/video on the server side?
- just as a confirmation, the communication is being done peer-server-peer, right?  not peer-to-peer.
- Is it possible to add other people in a call? (like conference? including audio/video?)

- I'm not sure if its appropriate but has anyone dont some comparisons of the opentok platform and something like this?  I udnerstnad the objectives are different.  Opentok is a service, etc, etc, but I like the fact oversip is node based and open and jssip is also open, so it is best for developers to add/remove fatures in order to tailor to our own needs...   Thanks for any answers!

Thanks so much for the answers...

**Comment by saghul** [comment]
> Is it possible to use this in iOS or Android? (Is there a sort of jssip sdk for any of those platforms?) or is it possible to use other webrtc toolkits to connect with say oversip or similar?

JsSIP is a SIP library written in JavaScript. You can use it on any platform as long as you have something that resembles a browser and has WebSocket support. The WebRTC API must be provided by the browser or some other component, it's not part of JsSIP, so no, there is no mobile SDK.

> Is it possible to record audio/video on the server side?

Sure. But JsSIP is a *client* library, so it's out of its scope.

> just as a confirmation, the communication is being done peer-server-peer, right? not peer-to-peer.
> 

Signaling yes, media goes P2P.

> Is it possible to add other people in a call? (like conference? including audio/video?)
> 

For that you either need a server that does the mixing, or establish multiple concurrent sessions locally.

> I'm not sure if its appropriate but has anyone dont some comparisons of the opentok platform and something like this? I udnerstnad the objectives are different. Opentok is a service, etc, etc, but I like the fact oversip is node based and open and jssip is also open, so it is best for developers to add/remove fatures in order to tailor to our own needs... Thanks for any answers!

Both OverSIP and JsSIP are building blocks, but you'll need more components to build a fully-fledged service like OpenTok. Since I'm here I'll also say OpenTok is a terrible name, since there is nothing open about its server side that I know of.

**Comment by RVN-BR** [comment]
Hi Saghul,

Thanks for your quick response! I like it when thigns flow dynamically! :)

> JsSIP is a SIP library written in JavaScript. You can use it on any platform as long as you have something that resembles a browser and has WebSocket support. The WebRTC API must be provided by the browser or some other component, it's not part of JsSIP, so no, there is no mobile SDK.

Understood.  I was wodnering if there was some other library or demo app that was available... I tried connecting to the sample site with bower and it just doesnt work...  Maybe there is another proejct that does somethig similar?

>> Is it possible to record audio/video on the server side?

> Sure. But JsSIP is a client library, so it's out of its scope.
Again, sorry for not being clear... I'm mixing up OverSIP with JSSIP because theyr are both maintained by same main developer...

>> just as a confirmation, the communication is being done peer-server-peer, right? not peer-to-peer.

> Signaling yes, media goes P2P.

Again, my ignorance, I was referring to using oversip in the middle... this can be done? to make sure all comms go through oversip in a secure (wss or other) fashion?


>> Is it possible to add other people in a call? (like conference? including audio/video?)

> For that you either need a server that does the mixing, or establish multiple concurrent sessions locally.

Will search better to see if oversip supports this... or maybe something else?

>> I'm not sure if its appropriate but has anyone dont some comparisons of the opentok platform and something like this? I udnerstnad the objectives are different. Opentok is a service, etc, etc, but I like the fact oversip is node based and open and jssip is also open, so it is best for developers to add/remove fatures in order to tailor to our own needs... Thanks for any answers!

> Both OverSIP and JsSIP are building blocks, but you'll need more components to build a fully-fledged service like OpenTok. Since I'm here I'll also say OpenTok is a terrible name, since there is nothing open about its server side that I know of.

Yes, I tend to agree... when I saw opentok I though "wow, holy grail"... but in fact "open" is their client libraries (maybe not even all) and you are forced to use and buy minutes on their platform.  I havent evaluaed it yet to say if its good or bad, but I'd prefer something with less lock in and more flexibility... I was looking for something that allows similar customization and more openness... so baiscally a JS client for browser (tick for jssip), mobile demo code (maybe this exists outside of jssip but with the required formats?) and the server cmponent (could oversip or kurento or others do the trick?)

Also, I'm sorry if this is innapropriate to ask, but why is there a spinoff of jssip (sip.js), is there anywhere I can find objective differnces?

Thanks so much for all the answers! I'm looking forward for a good solid solution...

"main" goals so far:
+ (main) light voice based implementation on the browser to connect to a "nasty sip proxy" that doesnt handle tunneling or nat traversal (jssip + oversip = holy grail?)
+ (secondary) add fatures such as browser client-server-client chatting/video/voice with recording (jssip+xxxxx? xxx = oversip? xxx=easyrtc? kurento? webrtc2sip?) 
+ (third) add above feature to mobile apps (not necessary in browser initially, but would be good if technology is there)

**Comment by ibc** [comment]
Please, let's use the JsSIP public mailing list for questions. This is the bug tracker.
