### ISSUE TITLE
If terminate() is called on 'progress' a timer gets running

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#316]
Similar to #315. If `terminate()` is called on "progress" event, some timer gets running and the Node script does not exit even if `ua.stop()` is called (not until such a timer fires).

**Comment by ibc** [comment]
Same happens if `terminate()` is called on "newRTCSession" event.

**Comment by jmillan** [comment]
I'd say INVITE transactions are the ones holding the timer here.

**Comment by ibc** [comment]
Yep, checking it. I've also added (still not commited) a check before emitting "progress":

```
// Fire 'newRTCSession' event.
  newRTCSession.call(this, 'remote', request);

  // The user may have rejected the call in the 'newRTCSession' event.
  if (this.status === C.STATUS_TERMINATED) {
    return;
  }

  // Reply 180.
  request.reply(180, null, ['Contact: ' + self.contact]);

  // Fire 'progress' event.
  // TODO: Document that 'response' field in 'progress' event is null for
  // incoming calls.
  progress.call(self, 'local', null);
```

**Comment by ibc** [comment]
Confirmed that some timer of 32 seconds (0.5 x 64) is created after emitting "newRTCSession" and calling `terminate()` on it.

**Comment by ibc** [comment]
Confirmed that it is due some Timer F.

**Comment by ibc** [comment]
I was wrong, will remove some wrong comments and update according.

**Comment by ibc** [comment]
It is due the Timer H called when the final response is sent to reject the incoming INVITE. There is no easy solution for this, the UA does not access to those server transactions when it comes to `stop()`. Any idea?

**Comment by ibc** [comment]
In fact, Timer H is never canceled in the `InviteServerTransaction` instance. The same would happen with some other timer in the `NonInviteServerTransaction` class.

**Comment by ibc** [comment]
When the INVITE server transaction replies a [3456]XX response, it runs the Timer I (timeout 0), whose callback destroys the transaction from the UA `ist` list. Should we remove that so that the transaction is removed when the Timer H fires instead?

**Comment by ibc** [comment]
Confirmed. If I remove the call to `destroyTransaction()` within the `InviteServerTransaction.prototype.timer_I()` method, then the ist remains in the UA list and it is closed with `onTransportError()` when calling `ua.stop()`. I will commit it.
