### ISSUE TITLE
Bad Media Description

### ISSUE THREAD

**Issue by gudge25** [versatica/JsSIP#317]
ASTERISK 11.17

<--- Reliably Transmitting (NAT) to 85.175.99.32:38868 --->
SIP/2.0 200 OK
Via: SIP/2.0/WS iv25n184rkvd.invalid;branch=z9hG4bK7355973;received=85.175.99.32;rport=38868
From: <sip:540ebf70a18c88896b018d3e@178.62.136.125>;tag=l5fnptssig
To: <sip:289528795094@178.62.136.125>;tag=as6d886397
Call-ID: vkf21jal4gh5992d2g5q
CSeq: 4234 INVITE
Server: Asterisk PBX 13.3.2
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:289528795094@31.186.99.61:5060;transport=WS>
Content-Type: application/sdp
Content-Length: 418

v=0
o=root 1296162881 1296162881 IN IP4 31.186.99.61
s=Asterisk PBX 13.3.2
c=IN IP4 31.186.99.61
t=0 0
m=audio 17202 RTP/SAVPF 8 0 126
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=maxptime:150
a=connection:new
a=setup:active
a=fingerprint:SHA-256 C2:B4:F5:83:49:84:2B:12:08:05:AD:81:41:46:F5:0E:2E:38:20:34:BC:DB:0E:6A:CF:26:AD:46:DE:83:38:E5
a=sendrecv

JSSIP
http://pastebin.com/zGe8cfYV

**Comment by gudge25** [comment]
we have no OPUS  and it worked before !

**Comment by jmillan** [comment]
JsSIP logs should tell you which exactly the SDP error is. Check it please.

**Comment by ibc** [comment]
Please, use the mailing list. This is not a bug in JsSIP.
