### ISSUE TITLE
use UDP/TLS/RTP/SAVPF token in SDP to specify RTP/SAVPF RTP profile

### ISSUE THREAD

**Issue by juha-h** [versatica/JsSIP#320]
Currently SIP UA using JsSIP library writes token RTP/SAVPF on SDP m line(s) of outgoing INVITE requests to describe RTP/SAVPF RTP profile, e.g.,

```
m=audio 35070 RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
```

According to RFC 5764 this in incorrect.  The token shall be UDP/TLS/RTP/SAVPF instead:

> 8  Session Description for RTP/SAVP over DTLS
>
>   This specification defines new tokens to describe the protocol used in SDP media descriptions ("m=" lines and their associated  parameters).  The new values defined for the proto field are:
>
>   o  When a RTP/SAVP or RTP/SAVPF [RFC5124] stream is transported over
      DTLS with the Datagram Congestion Control Protocol (DCCP), then
      the token SHALL be DCCP/TLS/RTP/SAVP or DCCP/TLS/RTP/SAVPF
      respectively.
>
   o  When a RTP/SAVP or RTP/SAVPF stream is transported over DTLS with
      UDP, the token SHALL be UDP/TLS/RTP/SAVP or UDP/TLS/RTP/SAVPF
      respectively.

Correct behavior can be achieved by the diff below (perhaps a check should be added that description type is "offer" and that sdp is defined). 

I would like to make JsSIP UA to use the correct profile token either always or if configured to do so.  Current non-standard behavior makes outgoing calls to fail if callee only understands standardized token of RTP/SAVPF RTP profile.

-- Juha

```js
diff -c /usr/src/orig/JsSIP/dist/jssip-0.6.28.js jssip-0.6.28.js
*** /usr/src/orig/JsSIP/dist/jssip-0.6.28.js	2015-06-02 22:04:23.548861053 +0300
--- jssip-0.6.28.js	2015-06-05 12:40:53.018796520 +0300
***************
*** 22243,22248 ****
--- 22243,22250 ----
  
  	var self = this;
  
+         description.sdp = description.sdp.replace(/ RTP\/SAVP/gi, " UDP/TLS/RTP/SAVP");
+ 	
  	this.pc.setLocalDescription(
  		description,
  		// success.
```

**Comment by ibc** [comment]
This will be feasible by adding new conf options or, even better, a callback that is called with the parsed SDP object before it is sent to the remote (for outgoing SDPs) or before it is processed by the `RTCSession` instance (for incoming SDPs).

**Comment by dpocock** [comment]
Here is the workaround in JSCommunicator, I would prefer to see this done at a lower level in the stack, e.g. JsSIP and then the hack can be removed from JSCommunicator

https://github.com/opentelecoms-org/jscommunicator/blob/master/JSCommManager.js#L195

**Comment by ibc** [comment]
I strongly prefer providing an event for the user/app to do this (instead of handling with dirty hacks in the core library just for certain PBX's browsers).

**Comment by ibc** [comment]
@juha-h two comments:

1. This is not how "JsSIP writes the SDP" but how the browser writes it. JsSIP does not modify it.
1. RFC 5764 is not 100% valid and there are discussions in the WebRTC group about this. WebRTC uses ICE so UDP and TCP candidates can be offered and chosen as media path. This means that pre-defining the layer 4 transport (UDP or TCP) within a fixed SDP attribute is a no sense.

**Comment by ibc** [comment]
Mangling the SDP before it leaves the browser and before passing them to the browser's WebRTC stack will be feasible once #372 is merged, so let's close this issue.

**Comment by juha-h** [comment]
I�aki Baz Castillo writes:

> Mangling the SDP before it leaves the browser and before passing them
> to the browser's WebRTC stack will be feasible once #372 is merged, so
> let's close this issue.

Fine, Juha
