### ISSUE TITLE
No Audio if oudbound call picked up after 8 seconds in Asterisk

### ISSUE THREAD

**Issue by sarumjanuch** [versatica/JsSIP#322]
Hi Guys, I am almost sure that it is not issue in yours library, but just in case. Many people expirience same issue, maybe we will find some answers here. We are using Asterisk as backend. When you place outgoing call from WebRTC extensions to anywhere else, if callee picks up call in 7 seconds everything is fine, if in 8, then call will have no audio. During debugging i find out, that in normal call asterisk sends dtls client_hello after 200 OK, and receiving server_hello back from browser. Meanwhile in the bad call i can see that after some period of time asterisk start sending client_hello, and browser don't respond to them, which causes that there is no dtls handshake happened, it don't know what ciphers etc.. And in jssip i see that . Additional strange thing. I did trace packets on my machine where client(browser) is running, and i don't see any client_hello packets coming from server to client, but i do see that server is sending them. My suspicions is that because there is no mapped address yet, because i see that XOR-MAPPED-ADDRESS, is coming only after 200 OK, and as previously told all client_hello packets are sent before 200 OK if wait more than 7 seconds. My question is next, when jssip should become ready to receive client_hello messasges? And when it should ignore them
And when it should ignore them? I would be really appreciate for any help, any ideas or points to RFC quotes, that can explain something, at least something that will help to understand how asterisk violates standard. Just FYI all clients are effected(jssip,sip.js,sipml5). I would be grateful for any attention here.

**Comment by ibc** [comment]
Hi @sarumjanuch. I prefer those kinds of questions to be made in the [JsSIP public mailing list](https://groups.google.com/group/jssip) as, as you noticed, this is not an issue in JsSIP (it may be an issue in browser(s) and/or Asterisk). So I will reply to some questions but please let's continue it in the mailing list.

> when jssip should become ready to receive client_hello messasges? And when it should ignore them

JsSIP does nothing to receive DTLS client_hello. That's native WebRTC stuff at 100%. JsSIP is just responsible of negotiating the SDPs.

>  I would be grateful for any attention here.

Honestly I don't use Asterisk for long time so I¡m not aware of its WebRTC status. Please open a thread in the mailing list so other users of JsSIP & Asterisk can report their feedback.

Regards.
