### ISSUE TITLE
make session timer values configurable

### ISSUE THREAD

**Issue by juha-h** [versatica/JsSIP#324]
currently it is possible to enable/disable session timer, but it is not possible to configure these values:

SESSION_EXPIRES: 90,
MIN_SESSION_EXPIRES: 60

it would be nice if they were added to ua configuration parameters.

**Comment by ibc** [comment]
You can pass `sessionTimersExpires` value in both `ua.call()` and `session.answer()`:

http://jssip.net/documentation/0.6.x/api/ua/#method_call
http://jssip.net/documentation/0.6.x/api/session/#method_answer

**Comment by juha-h** [comment]
I�aki Baz Castillo writes:

> You can pass `sessionTimersExpires` value in both `ua.call()` and
> `session.answer()`:
> 
> http://jssip.net/documentation/0.6.x/api/ua/#method_call
> http://jssip.net/documentation/0.6.x/api/session/#method_answer

OK, thanks for the info.  I still didn't figure out how I can affect
MIN_SESSION_EXPIRES.

What happens if INVITE is received where Session-Expires is below
MIN_SESSION_EXPIRES, say 30, and I call answer() with
sessionTimersExpires value 90 or Session-Expires is INVITE is smaller
than sessionTimersExpires value in answer()?  Is jssip replying with 422
and Min-SE that includes sessionTimersExpires value?

-- Juha

**Comment by ibc** [comment]
If the incoming request has "Session-Expires" below MIN_SESSION_EXPIRES then JsSIP uses MIN_SESSION_EXPIRES:

```javascript
  if (request.session_expires && request.session_expires >= JsSIP_C.MIN_SESSION_EXPIRES) {
    this.sessionTimers.currentExpires = request.session_expires;
    session_expires_refresher = request.session_expires_refresher || 'uas';
  }
  else {
    this.sessionTimers.currentExpires = this.sessionTimers.defaultExpires;
    session_expires_refresher = 'uas';
  }
```

Note that the RFC clearly states that both "Session-Expires" and "Min-SE" cannot be below 90 seconds. JsSIP does not use its MIN_SESSION_EXPIRES by default (in outgoing calls), but it does accept incoming values equal or greater than 60.

P.S.: The "Min-SE" header is not implemented, nor the 422 response. If a SIP device is setting a value less than 90 it is a bug (the RFC 4028 does not allow that at all).
