### ISSUE TITLE
JSSIP does not close camera on IE w/ Temasys Plugin

### ISSUE THREAD

**Issue by nethertek** [versatica/JsSIP#326]
Running the TryIt Demo, the camera does not turn off after the session has terminated. Whilst this may appear to be a problem with the Temasys plugin, the following demo shows that Temasys does indeed turn off the camera:

https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/munge-sdp/index.html

This is an issue because no further calls can be made. The camera remains blocked, resulting in User Denied Media Access.

**Comment by ibc** [comment]
We don't accept bug reports based on what it happens in the Tryit JsSIP demo. It is just spaghetti code written 3 years ago.

Please try JsSIP + Temasys plugin within your own well written application and report an issue if the same happens. Said that, the cam is turned off in JsSIP + Temasys plugin apps I write so this seems to be an issue in the Tryit demo (not a bug in JsSIP).

**Comment by nethertek** [comment]
Perhaps, but this is also occurring with the latest jssip version. So it remains a bug in JSSIP.

**Comment by ibc** [comment]
No. It may be a bug in how the Tryit demo is coded, but not in JsSIP. Have you tried with your own application?

**Comment by nethertek** [comment]
Yes
