### ISSUE TITLE
JSSIP does not close camera on IE w/ Temasys Plugin

### ISSUE THREAD

**Issue by nethertek** [versatica/JsSIP#327]
The camera does not turn off after the session has terminated. Whilst this may appear to be a problem with the Temasys plugin, the following demo shows that Temasys does indeed turn off the camera:

https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/munge-sdp/index.html

This is an issue because no further calls can be made. The camera remains blocked, resulting in User Denied Media Access.

**Comment by ibc** [comment]
This is obviously a duplicated report. #326

**Comment by nethertek** [comment]
I re-opened it without mentioning TryIt, because you closed it without investigating it.
