### ISSUE TITLE
Sip 180 Ringing doesn't generate local ringing

### ISSUE THREAD

**Issue by Garffan** [versatica/JsSIP#329]
Hi, I have some problem with outgoing calls. When I make call, I don't hear a dial tone. I make a call, from Google Chrome to Kamailio.
 Logs (jssip): 
<pre>
SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 03bgstcjlhhh.invalid;rport=41947;received=85.175.99.32;branch=z9hG4bK2378069
Record-Route: <sip:xx.xx.xx.xx:5xxxx;nat=yes;lr=on>
From: <sip:554b56b85cf9fc95321c1bd6@xx.xx.xx.xx>;tag=l4cfqj1vpe
To: <sip:18xxxxxxxxxxx@xx.xx.xx.xx>;tag=as544399b8
Call-ID: 8u3vg6aju6c0mnd30s40
CSeq: 6575 INVITE
Server: Cisco
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:18xxxxxxxxx@xx.xx.xx.xx:5xxxx>
Content-Length: 0

+140ms
jssip.js:21621 JsSIP:RTCSession receiveInviteResponse() +20ms
jssip.js:21621 JsSIP:Dialog new UAC dialog created with status EARLY +1ms
jssip.js:21621 JsSIP:RTCSession session progress +1ms
</pre>

But If I make call from Google Chrome to Asterisk (w/o Kamailio), I hear a dial tone, it works perfect.
Logs (jssip):
<pre>
SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 7acf0vbkdr7c.invalid;rport=41881;received=xx.xx.xx.xx;branch=z9hG4bK3084019
Record-Route: <sip:xx.xx.xx.xx:5xxx;nat=yes;lr=on>
From: <sip:554b56b85cf9fc95321c1bd6@xx.xx.xx.xx>;tag=6uqjplq959
To: <sip:18xxxxxxxxxxx@xx.xx.xx.xx>;tag=as1cbba0bd
Call-ID: up1gfee2nbg9cdjtvo31
CSeq: 432 INVITE
Server: Cisco
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:18xxxxxxxxxxx@xx.xx.xx.xx:5xxxx>
Content-Length: 0

jssip.js:21621 JsSIP:RTCSession receiveInviteResponse() +11ms
jssip.js:21621 JsSIP:Dialog new UAC dialog created with status EARLY +1ms
jssip.js:21621 JsSIP:RTCSession session progress +1ms
</pre>

As you can see, there is no difference between them. But, in first case there is a dial tone, and in second case there is no.

Please, help me.

Google Chrome (Version 43.0.2357.134 unknown (64-bit), Linux, Ubuntu). JsSIP v0.6.34

**Comment by jmillan** [comment]
This is not a bug, please post your question in the jssip mailing list. `jssip@googlegroups.com`
