### ISSUE TITLE
No event to indicate that a disconnected UserAgent has stopped

### ISSUE THREAD

**Issue by olegstolyar** [versatica/JsSIP#330]
if a UA is disconnected when user tries to make a call, we would still need to stop it and then start it again.  However, there is no event that would fire when stop is complete to let us know that it's safe to start it again.

**Comment by jmillan** [comment]
Hi,

More than notifying when the UA stops, I find it more interesting that UA.start() properly restarts even if it's actually closing. It should wait until closing is done and later start itself, transparently.

**Comment by olegstolyar** [comment]
Other solutions could be:
1. Add a restart() method
2. Add a connect() method to force a connection attempt on a started UA
3. (Ideal from my point of view but not sure how hard it would be) In ua.call() method check if UA is not connected, attempt to connect it and then transparently go ahead with the call.

**Comment by jmillan** [comment]
>Other solutions could be:
>1. Add a restart() method

the start() method should manage
>2. Add a connect() method to force a connection attempt on a started UA

A connect() method relies to much in the user. start() and stop() methods should manage connections.
>3. (Ideal from my point of view but not sure how hard it would be) In ua.call() method check if UA is not 
connected, attempt to connect it and then transparently go ahead with the call.

You can call ua.isConnected() before doing a call. You also can handle the 'failure' event in the session callbacks.

JsSIP already has a transparent mechanism for connection recovery and properly notifies when a connection is established and disconnected.

**Comment by jmillan** [comment]
Ready in 0.7.3.

```
ua.stop()
ua.start() // asynchronously restart as soon as the stop process has finished
```

ua.on('connect', function(){}); // Fired when UA started/re-started and on transport reconnection after a failure.

Am I wrong or does this fix the issue presented?

**Comment by olegstolyar** [comment]
I think it should do it.

**Comment by jmillan** [comment]
I think its just cleaner to handle the restart action on the `UA.start()` method. Indeed it was the intention but there is a bug which has been just fixed.

Could you please confirm this solves the issue you're facing @olegstolyar ?

**Comment by jmillan** [comment]
The purpose of this issue was being able to 'know' when the `UA` could be started after having stopped it.

Since version 0.7.3, `UA.start()` asynchronously restarts even if it's currently processing a previous `UA.stop()`
