### ISSUE TITLE
New API to replace Transport

### ISSUE THREAD

**Issue by rscreene** [versatica/JsSIP#331]
We would like to multiplex JsSIP and application messages over an existing WebSocket connection that is opened by, and continues to be used by, the application.  The application expects an enevelope around each message indicating whether it is a message that should be processed internally, or a SIP message that should be passed to JsSIP.  Essentially we would like to implement our own Transport module for JsSIP.

As discussed here https://groups.google.com/forum/#!topic/jssip/Gzwh22z-EzE the
best way would be to create an API that would offer the services to the applicat
ion.

As a minimum the application would be expected to implement connect(), disconnec
t() and send() methods. And the application would be able to notify the UA of a
received SIP message and any transport status update.

**Comment by ibc** [comment]
Nice to have, but it will take some time until implemented.

**Comment by jmillan** [comment]
To be closed as soon as #374 is merged

**Comment by jmillan** [comment]
closing...
