### ISSUE TITLE
JsSIP rejecting call with BYE ( Reason: SIP ;cause=488; text="Not Acceptable Here")  when asterisk send 200 OK

### ISSUE THREAD

**Issue by dki123** [versatica/JsSIP#332]
Hi everyone,

I am try to run jssip demo with asterisk and  getting strange behaviour when i try to do test call from jsSIP through (http://tryit.jssip.net/).

Here is details description
Asterisk Version : Asterisk 13.2.0 (without OPUS codec).

Registration details :: sip.conf

[general]
realm=XXX.XXX.XXX.XXX ; Replace this with your IP address
udpbindaddr=0.0.0.0 ; Replace this with your IP address
transport=udp
disallow=all
allow=g722
allow=gsm
allow=ulaw
allow=alaw
allow=vp8
nat=force_rport,comedia
videosupport=yes

[1060] ; This will be WebRTC client
type=friend
username=1060 ; The Auth user for SIP.js
host=dynamic ; Allows any host to register
secret=password ; The SIP Password for SIP.js
encryption=yes ; Tell Asterisk to use encryption for this peer
avpf=yes ; Tell Asterisk to use AVPF for this peer
icesupport=yes ; Tell Asterisk to use ICE for this peer
context=js1 ; Tell Asterisk which context to use when this peer is dialing
directmedia=no ; Asterisk will relay media for this peer
transport=udp,ws,wss ; Asterisk will allow this peer to register on UDP or WebSockets
force_avp=yes ; Force Asterisk to use avp. Introduced in Asterisk 11.11
dtlsenable=yes ; Tell Asterisk to enable DTLS for this peer
dtlsverify=no ; Tell Asterisk to not verify your DTLS certs
dtlscertfile=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS cert file is
dtlsprivatekey=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS private key is
dtlssetup=actpass ; Tell Asterisk to use actpass SDP parameter when setting up DTLS

[1061] ; This will be WebRTC client
type=friend
username=1061 ; The Auth user for SIP.js
host=dynamic ; Allows any host to register
secret=password ; The SIP Password for SIP.js
encryption=yes ; Tell Asterisk to use encryption for this peer
avpf=yes ; Tell Asterisk to use AVPF for this peer
icesupport=yes ; Tell Asterisk to use ICE for this peer
context=js1 ; Tell Asterisk which context to use when this peer is dialing
directmedia=no ; Asterisk will relay media for this peer
transport=udp,ws,wss ; Asterisk will allow this peer to register on UDP or WebSockets
force_avp=yes ; Force Asterisk to use avp. Introduced in Asterisk 11.11
dtlsenable=yes ; Tell Asterisk to enable DTLS for this peer
dtlsverify=no ; Tell Asterisk to not verify your DTLS certs
dtlscertfile=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS cert file is
dtlsprivatekey=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS private key is
dtlssetup=actpass ; Tell Asterisk to use actpass SDP parameter when setting up DTLS
---------------
Dial-plan
----------------------
[js1]
exten => _X.,1,Answer()
exten => _X.,2,MusiconHold(default,500)

-------------------------------------------------------------
SIP debug
------------------------------------------------------------

[Aug  5 11:43:52] <--- SIP read from WS:180.211.111.106:42974 --->
[Aug  5 11:43:52] INVITE sip:11111@XXX.XXX.XXX.XXX SIP/2.0
[Aug  5 11:43:52] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK9916822
[Aug  5 11:43:52] Max-Forwards: 69
[Aug  5 11:43:52] To: <sip:11111@XXX.XXX.XXX.XXX>
[Aug  5 11:43:52] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:52] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:52] CSeq: 159 INVITE
[Aug  5 11:43:52] X-Can-Renegotiate: false
[Aug  5 11:43:52] Contact: <sip:pm9r3luj@192.0.2.29;transport=ws;ob>
[Aug  5 11:43:52] Content-Type: application/sdp
[Aug  5 11:43:52] Session-Expires: 90
[Aug  5 11:43:52] Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER
[Aug  5 11:43:52] Supported: timer,ice,replaces,outbound
[Aug  5 11:43:52] User-Agent: JsSIP 0.7.3
[Aug  5 11:43:52] Content-Length: 1753
[Aug  5 11:43:52] 
[Aug  5 11:43:52] v=0
[Aug  5 11:43:52] o=mozilla...THIS_IS_SDPARTA-38.0 4294967295 0 IN IP4 0.0.0.0
[Aug  5 11:43:52] s=-
[Aug  5 11:43:52] t=0 0
[Aug  5 11:43:52] a=sendrecv
[Aug  5 11:43:52] a=fingerprint:sha-256 FD:1D:D2:98:34:46:38:8E:A3:80:91:C2:61:2C:70:B1:54:AD:A9:45:95:69:B2:35:E1:B3:B7:E3:34:D6:C6:DE
[Aug  5 11:43:52] a=group:BUNDLE sdparta_0 sdparta_1
[Aug  5 11:43:52] a=ice-options:trickle
[Aug  5 11:43:52] a=msid-semantic:WMS *
[Aug  5 11:43:52] m=audio 51083 RTP/SAVPF 109 9 0 8
[Aug  5 11:43:52] c=IN IP4 180.211.111.106
[Aug  5 11:43:52] a=candidate:0 1 UDP 2122252543 172.18.100.72 51083 typ host
[Aug  5 11:43:52] a=candidate:0 2 UDP 2122252542 172.18.100.72 14886 typ host
[Aug  5 11:43:52] a=candidate:1 1 UDP 1686110207 180.211.111.106 51083 typ srflx raddr 172.18.100.72 rport 51083
[Aug  5 11:43:52] a=candidate:1 2 UDP 1686110206 180.211.111.106 14886 typ srflx raddr 172.18.100.72 rport 14886
[Aug  5 11:43:52] a=sendrecv
[Aug  5 11:43:52] a=end-of-candidates
[Aug  5 11:43:52] a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
[Aug  5 11:43:52] a=ice-pwd:b9182102250657c9e285ce83ec1928dc
[Aug  5 11:43:52] a=ice-ufrag:47b20cd1
[Aug  5 11:43:52] a=mid:sdparta_0
[Aug  5 11:43:52] a=msid:{56075dea-5229-4124-a587-75997797c1ca} {6031a2aa-f4d1-43c1-a609-de5647bbad26}
[Aug  5 11:43:52] a=rtcp-mux
[Aug  5 11:43:52] a=rtpmap:109 opus/48000/2
[Aug  5 11:43:52] a=rtpmap:9 G722/8000/1
[Aug  5 11:43:52] a=rtpmap:0 PCMU/8000
[Aug  5 11:43:52] a=rtpmap:8 PCMA/8000
[Aug  5 11:43:52] a=setup:actpass
[Aug  5 11:43:52] a=ssrc:1236542414 cname:{912cd9a6-70d4-4283-b277-2813129a36bb}
[Aug  5 11:43:52] m=video 35087 RTP/SAVPF 120
[Aug  5 11:43:52] c=IN IP4 180.211.111.106
[Aug  5 11:43:52] a=candidate:0 1 UDP 2122252543 172.18.100.72 35087 typ host
[Aug  5 11:43:52] a=candidate:0 2 UDP 2122252542 172.18.100.72 35573 typ host
[Aug  5 11:43:52] a=candidate:1 1 UDP 1686110207 180.211.111.106 35087 typ srflx raddr 172.18.100.72 rport 35087
[Aug  5 11:43:52] a=candidate:1 2 UDP 1686110206 180.211.111.106 35573 typ srflx raddr 172.18.100.72 rport 35573
[Aug  5 11:43:52] a=recvonly
[Aug  5 11:43:52] a=end-of-candidates
[Aug  5 11:43:52] a=fmtp:120 max-fs=12288;max-fr=60
[Aug  5 11:43:52] a=ice-pwd:b9182102250657c9e285ce83ec1928dc
[Aug  5 11:43:52] a=ice-ufrag:47b20cd1
[Aug  5 11:43:52] a=mid:sdparta_1
[Aug  5 11:43:52] a=rtcp-fb:120 nack
[Aug  5 11:43:52] a=rtcp-fb:120 nack pli
[Aug  5 11:43:52] a=rtcp-fb:120 ccm fir
[Aug  5 11:43:52] a=rtcp-mux
[Aug  5 11:43:52] a=rtpmap:120 VP8/90000
[Aug  5 11:43:52] a=setup:actpass
[Aug  5 11:43:52] <------------->
[Aug  5 11:43:52] --- (15 headers 47 lines) ---
[Aug  5 11:43:52] Using INVITE request as basis request - j5so04hc8cpaftvhupta
[Aug  5 11:43:52] Found peer '1060' for '1060' from 180.211.111.106:42974
[Aug  5 11:43:52] 
[Aug  5 11:43:52] <--- Reliably Transmitting (NAT) to 180.211.111.106:42974 --->
[Aug  5 11:43:52] SIP/2.0 401 Unauthorized
[Aug  5 11:43:52] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK9916822;received=180.211.111.106;rport=42974
[Aug  5 11:43:52] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:52] To: <sip:11111@XXX.XXX.XXX.XXX>;tag=as470e3ea5
[Aug  5 11:43:52] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:52] CSeq: 159 INVITE
[Aug  5 11:43:52] Server: Asterisk PBX 13.2.0
[Aug  5 11:43:52] Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
[Aug  5 11:43:52] Supported: replaces, timer
[Aug  5 11:43:52] WWW-Authenticate: Digest algorithm=MD5, realm="XXX.XXX.XXX.XXX", nonce="58f0c244"
[Aug  5 11:43:52] Content-Length: 0
[Aug  5 11:43:52] 
[Aug  5 11:43:52] 
[Aug  5 11:43:52] <------------>
[Aug  5 11:43:52] Scheduling destruction of SIP dialog 'j5so04hc8cpaftvhupta' in 32000 ms (Method: INVITE)
[Aug  5 11:43:52] 
[Aug  5 11:43:52] <--- SIP read from WS:180.211.111.106:42974 --->
[Aug  5 11:43:52] ACK sip:11111@XXX.XXX.XXX.XXX SIP/2.0
[Aug  5 11:43:52] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK9916822
[Aug  5 11:43:52] To: <sip:11111@XXX.XXX.XXX.XXX>;tag=as470e3ea5
[Aug  5 11:43:52] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:52] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:52] CSeq: 159 ACK
[Aug  5 11:43:52] Content-Length: 0
[Aug  5 11:43:52] 
[Aug  5 11:43:52] <------------->
[Aug  5 11:43:52] --- (7 headers 0 lines) ---
[Aug  5 11:43:53] 
[Aug  5 11:43:53] <--- SIP read from WS:180.211.111.106:42974 --->
[Aug  5 11:43:53] INVITE sip:11111@XXX.XXX.XXX.XXX SIP/2.0
[Aug  5 11:43:53] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK7606581
[Aug  5 11:43:53] Max-Forwards: 69
[Aug  5 11:43:53] To: <sip:11111@XXX.XXX.XXX.XXX>
[Aug  5 11:43:53] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:53] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:53] CSeq: 160 INVITE
[Aug  5 11:43:53] Authorization: Digest algorithm=MD5, username="1060", realm="XXX.XXX.XXX.XXX", nonce="58f0c244", uri="sip:11111@XXX.XXX.XXX.XXX", response="414d403ebfc31d7a0a0a92eab5805d8f"
[Aug  5 11:43:53] X-Can-Renegotiate: false
[Aug  5 11:43:53] Contact: <sip:pm9r3luj@192.0.2.29;transport=ws;ob>
[Aug  5 11:43:53] Content-Type: application/sdp
[Aug  5 11:43:53] Session-Expires: 90
[Aug  5 11:43:53] Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER
[Aug  5 11:43:53] Supported: timer,ice,replaces,outbound
[Aug  5 11:43:53] User-Agent: JsSIP 0.7.3
[Aug  5 11:43:53] Content-Length: 1753
[Aug  5 11:43:53] 
[Aug  5 11:43:53] v=0
[Aug  5 11:43:53] o=mozilla...THIS_IS_SDPARTA-38.0 4294967295 0 IN IP4 0.0.0.0
[Aug  5 11:43:53] s=-
[Aug  5 11:43:53] t=0 0
[Aug  5 11:43:53] a=sendrecv
[Aug  5 11:43:53] a=fingerprint:sha-256 FD:1D:D2:98:34:46:38:8E:A3:80:91:C2:61:2C:70:B1:54:AD:A9:45:95:69:B2:35:E1:B3:B7:E3:34:D6:C6:DE
[Aug  5 11:43:53] a=group:BUNDLE sdparta_0 sdparta_1
[Aug  5 11:43:53] a=ice-options:trickle
[Aug  5 11:43:53] a=msid-semantic:WMS *
[Aug  5 11:43:53] m=audio 51083 RTP/SAVPF 109 9 0 8
[Aug  5 11:43:53] c=IN IP4 180.211.111.106
[Aug  5 11:43:53] a=candidate:0 1 UDP 2122252543 172.18.100.72 51083 typ host
[Aug  5 11:43:53] a=candidate:0 2 UDP 2122252542 172.18.100.72 14886 typ host
[Aug  5 11:43:53] a=candidate:1 1 UDP 1686110207 180.211.111.106 51083 typ srflx raddr 172.18.100.72 rport 51083
[Aug  5 11:43:53] a=candidate:1 2 UDP 1686110206 180.211.111.106 14886 typ srflx raddr 172.18.100.72 rport 14886
[Aug  5 11:43:53] a=sendrecv
[Aug  5 11:43:53] a=end-of-candidates
[Aug  5 11:43:53] a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
[Aug  5 11:43:53] a=ice-pwd:b9182102250657c9e285ce83ec1928dc
[Aug  5 11:43:53] a=ice-ufrag:47b20cd1
[Aug  5 11:43:53] a=mid:sdparta_0
[Aug  5 11:43:53] a=msid:{56075dea-5229-4124-a587-75997797c1ca} {6031a2aa-f4d1-43c1-a609-de5647bbad26}
[Aug  5 11:43:53] a=rtcp-mux
[Aug  5 11:43:53] a=rtpmap:109 opus/48000/2
[Aug  5 11:43:53] a=rtpmap:9 G722/8000/1
[Aug  5 11:43:53] a=rtpmap:0 PCMU/8000
[Aug  5 11:43:53] a=rtpmap:8 PCMA/8000
[Aug  5 11:43:53] a=setup:actpass
[Aug  5 11:43:53] a=ssrc:1236542414 cname:{912cd9a6-70d4-4283-b277-2813129a36bb}
[Aug  5 11:43:53] m=video 35087 RTP/SAVPF 120
[Aug  5 11:43:53] c=IN IP4 180.211.111.106
[Aug  5 11:43:53] a=candidate:0 1 UDP 2122252543 172.18.100.72 35087 typ host
[Aug  5 11:43:53] a=candidate:0 2 UDP 2122252542 172.18.100.72 35573 typ host
[Aug  5 11:43:53] a=candidate:1 1 UDP 1686110207 180.211.111.106 35087 typ srflx raddr 172.18.100.72 rport 35087
[Aug  5 11:43:53] a=candidate:1 2 UDP 1686110206 180.211.111.106 35573 typ srflx raddr 172.18.100.72 rport 35573
[Aug  5 11:43:53] a=recvonly
[Aug  5 11:43:53] a=end-of-candidates
[Aug  5 11:43:53] a=fmtp:120 max-fs=12288;max-fr=60
[Aug  5 11:43:53] a=ice-pwd:b9182102250657c9e285ce83ec1928dc
[Aug  5 11:43:53] a=ice-ufrag:47b20cd1
[Aug  5 11:43:53] a=mid:sdparta_1
[Aug  5 11:43:53] a=rtcp-fb:120 nack
[Aug  5 11:43:53] a=rtcp-fb:120 nack pli
[Aug  5 11:43:53] a=rtcp-fb:120 ccm fir
[Aug  5 11:43:53] a=rtcp-mux
[Aug  5 11:43:53] a=rtpmap:120 VP8/90000
[Aug  5 11:43:53] a=setup:actpass
[Aug  5 11:43:53] <------------->
[Aug  5 11:43:53] --- (16 headers 47 lines) ---
[Aug  5 11:43:53] Using INVITE request as basis request - j5so04hc8cpaftvhupta
[Aug  5 11:43:53] Found peer '1060' for '1060' from 180.211.111.106:42974
[Aug  5 11:43:53]   == Using SIP VIDEO CoS mark 6
[Aug  5 11:43:53]   == Using SIP RTP CoS mark 5
[Aug  5 11:43:53] Found RTP audio format 109
[Aug  5 11:43:53] Found RTP audio format 9
[Aug  5 11:43:53] Found RTP audio format 0
[Aug  5 11:43:53] Found RTP audio format 8
[Aug  5 11:43:53] Found audio description format opus for ID 109
[Aug  5 11:43:53] Found audio description format G722 for ID 9
[Aug  5 11:43:53] Found audio description format PCMU for ID 0
[Aug  5 11:43:53] Found audio description format PCMA for ID 8
[Aug  5 11:43:53] Found RTP video format 120
[Aug  5 11:43:53] Found video description format VP8 for ID 120
[Aug  5 11:43:53] Capabilities: us - (g722|gsm|ulaw|alaw|vp8), peer - audio=(ulaw|alaw|g722|opus)/video=(vp8)/text=(nothing), combined - (g722|ulaw|alaw|vp8)
[Aug  5 11:43:53] Non-codec capabilities (dtmf): us - 0x1 (telephone-event|), peer - 0x0 (nothing), combined - 0x0 (nothing)
[Aug  5 11:43:53] Peer audio RTP is at port 180.211.111.106:51083
[Aug  5 11:43:53] Peer video RTP is at port 180.211.111.106:35087
[Aug  5 11:43:53] Looking for 11111 in js1 (domain XXX.XXX.XXX.XXX)
[Aug  5 11:43:53] sip_route_dump: route/path hop: <sip:pm9r3luj@192.0.2.29;transport=ws;ob>
[Aug  5 11:43:53] 
[Aug  5 11:43:53] <--- Transmitting (NAT) to 180.211.111.106:42974 --->
[Aug  5 11:43:53] SIP/2.0 100 Trying
[Aug  5 11:43:53] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK7606581;received=180.211.111.106;rport=42974
[Aug  5 11:43:53] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:53] To: <sip:11111@XXX.XXX.XXX.XXX>
[Aug  5 11:43:53] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:53] CSeq: 160 INVITE
[Aug  5 11:43:53] Server: Asterisk PBX 13.2.0
[Aug  5 11:43:53] Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
[Aug  5 11:43:53] Supported: replaces, timer
[Aug  5 11:43:53] Session-Expires: 90;refresher=uas
[Aug  5 11:43:53] Contact: <sip:11111@XXX.XXX.XXX.XXX:5060;transport=WS>
[Aug  5 11:43:53] Content-Length: 0
[Aug  5 11:43:53] 
[Aug  5 11:43:53] 
[Aug  5 11:43:53] <------------>
[Aug  5 11:43:53]     -- Executing [11111@js1:1] Answer("SIP/1060-00000005", "") in new stack
[Aug  5 11:43:53] Audio is at 18944
[Aug  5 11:43:53] Video is at XXX.XXX.XXX.XXX:21952
[Aug  5 11:43:53] Adding codec g722 to SDP
[Aug  5 11:43:53] Adding codec ulaw to SDP
[Aug  5 11:43:53] Adding codec alaw to SDP
[Aug  5 11:43:53] Adding video codec vp8 to SDP
[Aug  5 11:43:53] Adding codec gsm to SDP
[Aug  5 11:43:53] 
[Aug  5 11:43:53] <--- Reliably Transmitting (NAT) to 180.211.111.106:42974 --->
[Aug  5 11:43:53] SIP/2.0 200 OK
[Aug  5 11:43:53] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK7606581;received=180.211.111.106;rport=42974
[Aug  5 11:43:53] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:53] To: <sip:11111@XXX.XXX.XXX.XXX>;tag=as184e3b0a
[Aug  5 11:43:53] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:53] CSeq: 160 INVITE
[Aug  5 11:43:53] Server: Asterisk PBX 13.2.0
[Aug  5 11:43:53] Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
[Aug  5 11:43:53] Supported: replaces, timer
[Aug  5 11:43:53] Session-Expires: 90;refresher=uas
[Aug  5 11:43:53] Contact: <sip:11111@XXX.XXX.XXX.XXX:5060;transport=WS>
[Aug  5 11:43:53] Content-Type: application/sdp
[Aug  5 11:43:53] Require: timer
[Aug  5 11:43:53] Content-Length: 660
[Aug  5 11:43:53] 
[Aug  5 11:43:53] v=0
[Aug  5 11:43:53] o=root 502830292 502830292 IN IP4 XXX.XXX.XXX.XXX
[Aug  5 11:43:53] s=Asterisk PBX 13.2.0
[Aug  5 11:43:53] c=IN IP4 XXX.XXX.XXX.XXX
[Aug  5 11:43:53] b=CT:384
[Aug  5 11:43:53] t=0 0
[Aug  5 11:43:53] m=audio 18944 RTP/SAVPF 9 0 8 3
[Aug  5 11:43:53] a=rtpmap:9 G722/8000
[Aug  5 11:43:53] a=rtpmap:0 PCMU/8000
[Aug  5 11:43:53] a=rtpmap:8 PCMA/8000
[Aug  5 11:43:53] a=rtpmap:3 GSM/8000
[Aug  5 11:43:53] a=maxptime:150
[Aug  5 11:43:53] a=connection:new
[Aug  5 11:43:53] a=setup:active
[Aug  5 11:43:53] a=fingerprint:SHA-256 8D:A1:F0:24:72:1F:CB:43:67:09:01:00:AE:2B:59:7E:95:60:35:CF:02:B1:CE:C3:DC:C5:0D:2B:AB:63:B3:20
[Aug  5 11:43:53] a=sendrecv
[Aug  5 11:43:53] m=video 21952 RTP/SAVPF 120
[Aug  5 11:43:53] a=connection:new
[Aug  5 11:43:53] a=setup:active
[Aug  5 11:43:53] a=fingerprint:SHA-256 8D:A1:F0:24:72:1F:CB:43:67:09:01:00:AE:2B:59:7E:95:60:35:CF:02:B1:CE:C3:DC:C5:0D:2B:AB:63:B3:20
[Aug  5 11:43:53] a=rtpmap:120 VP8/90000
[Aug  5 11:43:53] a=rtcp-fb:* ccm fir
[Aug  5 11:43:53] a=sendrecv
[Aug  5 11:43:53] 
[Aug  5 11:43:53] <------------>
[Aug  5 11:43:54] 
[Aug  5 11:43:54] <--- SIP read from WS:180.211.111.106:42974 --->
[Aug  5 11:43:54] ACK sip:11111@XXX.XXX.XXX.XXX:5060;transport=ws SIP/2.0
[Aug  5 11:43:54] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK3937638
[Aug  5 11:43:54] Max-Forwards: 69
[Aug  5 11:43:54] To: <sip:11111@XXX.XXX.XXX.XXX>;tag=as184e3b0a
[Aug  5 11:43:54] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:54] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:54] CSeq: 160 ACK
[Aug  5 11:43:54] Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER
[Aug  5 11:43:54] Supported: outbound
[Aug  5 11:43:54] User-Agent: JsSIP 0.7.3
[Aug  5 11:43:54] Content-Length: 0
[Aug  5 11:43:54] 
[Aug  5 11:43:54] <------------->
[Aug  5 11:43:54] --- (11 headers 0 lines) ---
[Aug  5 11:43:54]     -- Executing [11111@js1:2] MusicOnHold("SIP/1060-00000005", "default,500") in new stack
[Aug  5 11:43:54]     -- Started music on hold, class 'default', on channel 'SIP/1060-00000005'
[Aug  5 11:43:55] 
[Aug  5 11:43:55] <--- SIP read from WS:180.211.111.106:42974 --->
[Aug  5 11:43:55] BYE sip:11111@XXX.XXX.XXX.XXX:5060;transport=ws SIP/2.0
[Aug  5 11:43:55] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK757670
[Aug  5 11:43:55] Max-Forwards: 69
[Aug  5 11:43:55] To: <sip:11111@XXX.XXX.XXX.XXX>;tag=as184e3b0a
[Aug  5 11:43:55] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:55] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:55] CSeq: 161 BYE
[Aug  5 11:43:55] Reason: SIP ;cause=488; text="Not Acceptable Here"
[Aug  5 11:43:55] Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER
[Aug  5 11:43:55] Supported: outbound
[Aug  5 11:43:55] User-Agent: JsSIP 0.7.3
[Aug  5 11:43:55] Content-Length: 0
[Aug  5 11:43:55] 
[Aug  5 11:43:55] <------------->
[Aug  5 11:43:55] --- (12 headers 0 lines) ---
[Aug  5 11:43:55] Scheduling destruction of SIP dialog 'j5so04hc8cpaftvhupta' in 32000 ms (Method: BYE)
[Aug  5 11:43:55] 
[Aug  5 11:43:55] <--- Transmitting (NAT) to 180.211.111.106:42974 --->
[Aug  5 11:43:55] SIP/2.0 200 OK
[Aug  5 11:43:55] Via: SIP/2.0/WS 192.0.2.29;branch=z9hG4bK757670;received=180.211.111.106;rport=42974
[Aug  5 11:43:55] From: "sipforwebrtc" <sip:1060@XXX.XXX.XXX.XXX>;tag=3j8srdohhl
[Aug  5 11:43:55] To: <sip:11111@XXX.XXX.XXX.XXX>;tag=as184e3b0a
[Aug  5 11:43:55] Call-ID: j5so04hc8cpaftvhupta
[Aug  5 11:43:55] CSeq: 161 BYE
[Aug  5 11:43:55] Server: Asterisk PBX 13.2.0
[Aug  5 11:43:55] Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
[Aug  5 11:43:55] Supported: replaces, timer
[Aug  5 11:43:55] Content-Length: 0
[Aug  5 11:43:55] 
[Aug  5 11:43:55] 
[Aug  5 11:43:55] <------------>
[Aug  5 11:43:55]     -- Stopped music on hold on SIP/1060-00000005
[Aug  5 11:43:55]   == Spawn extension (js1, 11111, 2) exited non-zero on 'SIP/1060-00000005'
============================================================================

**Comment by dki123** [comment]
Why you have close this issue may i know the reason does this mean that this is already solved or something wrong

**Comment by ibc** [comment]
Use the JsSIP public mailing list for questions. As said many times, we don't accept bug reports about the Tryit JsSIP demo and/or Asterisk. You may want to ask in Asterisk forums.

**Comment by llongoria** [comment]
I have the same problem, is there any solution?

**Comment by ladanikevin** [comment]
I have the same problem, is there any solution?
