### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by SirLouen** [versatica/JsSIP#333]
Any ideas supporting webrtc based on microsoft edge? sip registration is going fine, but failing during invite (error webrtc not support):
SCRIPT5022: NOT_SUPPORTED_ERROR: WebRTC not supported
jssip.js (14210,5)

**Comment by ibc** [comment]
Please, use the JsSIP public mailing list for questions. This is the bug tracker.

Microsoft Edge does **NOT** implement WebRTC but just `getUserMedia`.
