### ISSUE TITLE
handling network changes by jssip

### ISSUE THREAD

**Issue by vertika-19** [versatica/JsSIP#335]
Using jssip for signaling and Webrtc on client side on browser. When I change network interface I expect  ice to be gathered again but nothing shows up.

If I connect a new network it just shows in the log Onicecandidate() : end of candidates

Please explain how to gather ice candidates again ,renegotiate the new candidate and continue the originally established rtp call

**Comment by jmillan** [comment]
This is not an issue but a question. Please send an email to the jssip mailing list.

**Comment by vertika-19** [comment]
Ok thanks
