### ISSUE TITLE
using node-websocket 1.0.22

### ISSUE THREAD

**Issue by dpocock** [versatica/JsSIP#336]
node-websocket 1.0.22 and beyond bring in a newer version of node-nan, 2.0.x

We have had to use the newer version of node-websocket in Debian unstable because node-nan 2 is there:  http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799656

Is node-nan 2.x OK with JsSIP?  Will this be supported in a subsequent JsSIP release?

**Comment by ibc** [comment]
I've already replied in the mailing list. JsSIP 0.7.6 was released yesterday with node-websocket 1.0.22:

https://github.com/versatica/JsSIP/commit/286267626a2a7b3b3b562ca4e5ad0878950551ad#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
