### ISSUE TITLE
How to maintain the running call when network interface changes after call is running.

### ISSUE THREAD

**Issue by vertika-19** [versatica/JsSIP#339]
followed from here-
https://groups.google.com/forum/#!searchin/jssip/network$20change/jssip/ZWIrmXK7yiQ/zSAc0lq1BQAJ

Requirement-
 Call established successfully from network interface 1 .Network 1 disconnects and a new network 2 is connected.

I wanted the running call to continue without any network change and when the websocket connection re-establishes rtp should start flowing again .
AS network changed so there is a need to give our sdp to remote and do ice-renegotiation again.
When successful call should re-establish without any disruption

 Status - 
I'm using renegotiate when ws reconnects and checking other states 
It successfully sends re-invite and does ice-negotiation and call recovers automatically

Problem -
If i'm connecting to new network very quickly then above is done and call successfully continues .
But if there is delay in connecting to the new network then transport error comes and session is closed and then i'm not even able to renegotiate as the call is lost

Please look into it 

Code - 
var optionsRenegotiate = {
   'rtcOfferConstraints' : {  'OfferToReceiveAudio': true,'OfferToReceiveVideo': false,'iceRestart' : true }
};
 con = session.connection;

 con.oniceconnectionstatechange = function(e) {
                if(con.iceConnectionState === 'disconnected' ) {
 //as ice disconnection could be due to small n/w error which jssip/webrtc handles automatically
                    var sleep = setTimeout(function() {} , 1000);
//If the ice is still disconnected i.e it couldn't be recovered then try renegotiate
                    if(con.iceConnectionState === 'disconnected') {
                          renegTries = 0;
                        var renegotiateTimer = setInterval( checkAndRenegotiate , 4000);  
                        function checkAndRenegotiate() {  
                        renegTries++ ;
                        if(renegTries === 5) {
                            clearInterval(renegotiateTimer);
                            renegotiateTimer = null;
                      }
   if(con.iceConnectionState === 'disconnected' && ua.isConnected() && session.dialog && session.isReadyToReOffer()) {  
                                session.renegotiate( optionsRenegotiate, 
                                function() {
                                    console.log("log: renegotiate success" , renegotiateTimer); 
                                    renegotiateSent = true;
                                    clearInterval(renegotiateTimer);
                                    renegotiateTimer = null;
                                } );
                    }
                }; }

Chrome logs:

JsSIP:Transport WebSocket disconnected (code: 1006) +51ms
jssip.js:22483 JsSIP:Transport WebSocket abrupt disconnection +2ms
JsSIP:Transport trying to reconnect to WebSocket ws://ip:port (reconnection attempt 1) +5ms
jssip.js:22483 rtcninja:RTCPeerConnection onicecandidate() | end of candidates +34s
jssip.js:22483 JsSIP:Transport connecting to WebSocket ws://ip:port+4s
WebSocket connection to 'ws://ip:port    ' failed: Error in connection establishment: net::ERR_INTERNET_DISCONNECTED
jssip.js:22483 JsSIP:Transport WebSocket connection error: Event +14ms
jssip.js:22483 JsSIP:Transport WebSocket disconnected (code: 1006) +7ms
jssip.js:22483 JsSIP:Transport WebSocket abrupt disconnection +1ms
jssip.js:22483 JsSIP:UA transport ws://ip:port
     failed | connection state set to 2 +1ms
sSIP:ERROR:RTCSession onTransportError() +7ms
jssip.js:22483 JsSIP:RTCSession terminate() +2ms
jssip.js:22483 JsSIP:RTCSession terminating session +1ms
jssip.js:22483 JsSIP:RTCSession sendRequest() +2ms
jssip.js:22483 JsSIP:RTCSession:Request new | BYE +2ms
jssip.js:22483 JsSIP:Transport unable to send message, WebSocket is not open +8ms
jssip.js:22483 JsSIP:NonInviteClientTransaction transport error occurred, deleting transaction z9hG4bK7227076 +2ms
jssip.js:22658 JsSIP:ERROR:RTCSession:Request onTransportError +2ms
jssip.js:22483 JsSIP:RTCSession session ended +2ms
jssip.js:22483 JsSIP:RTCSession close() +2ms
jssip.js:22483 rtcninja:RTCPeerConnection close() +4s
jssip.js:22483 JsSIP:RTCSession close() | closing local MediaStream +9ms
jssip.js:22483 rtcninja:Adapter closeMediaStream() | calling stop() on all the MediaStreamTrack +10ms
jssip.js:22483 JsSIP:Dialog dialog e57v6khgur31lbpc7dha5ampfe6bonvjUF06cFj5vyH deleted +4ms
JsSIP:UA next connection attempt in 2 seconds +11ms
jssip.js:20056 log: nextRetry 2
jssip.js:22483 rtcninja:RTCPeerConnection oniceconnectionstatechange() | iceConnectionState: closed +17ms
jssip.js:22483 rtcninja:RTCPeerConnection onsignalingstatechange() | signalingState: closed +2ms
jssip.js:22483 JsSIP:Transport connecting to WebSocket ws://ip:port +2s
...
.
..
.
after few attempts
JsSIP:Transport WebSocket ws://ip:port connected +1s
jssip.js:22483 JsSIP:Transport sending WebSocket message:

and sends register and successfully registers

**Comment by jmillan** [comment]
Hi @vertika-19,

Sorry for the long delay. Any chance we can get the full browser console log, not only since the WebSocket disconnection?

**Comment by jmillan** [comment]
Hi @vertika-19,

Please, try with current master branch and let us know how it works.

**Comment by davies147** [comment]
Hi, I have submitted a pull request with a small patch which I believe fixes this issue.

https://github.com/versatica/JsSIP/pull/388

Give it a go.
Regards,
Steve

**Comment by jmillan** [comment]
Closing this issue since it is related to old JsSIP version. It's most probably fixed in newer releases. Still I'll carefully check #388
