### ISSUE TITLE
ReferenceError: JsSIP is not defined

### ISSUE THREAD

**Issue by jl2035** [versatica/JsSIP#345]
I feel a little stupid for asking this. I installed the module and copied the code from the README file. When I tried to run I get this exception:

var ua = new JsSIP.UA(configuration);
             ^
ReferenceError: JsSIP is not defined
    at Object.<anonymous> (/home/user/siptest/test.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Do I have to somehow require it in my test.js file?

**Comment by ibc** [comment]
Not a bug. Use the mailing list.

**Comment by jl2035** [comment]
I don't understand. What mailing list?

**Comment by jl2035** [comment]
Can you please respond? This was very rude from you. You can't just close the issue like that, with no relevant explanation.

**Comment by ibc** [comment]
Oh yes! I can close it!

BTW your question has no "relevant explanation". You are running JsSIP from Node... and you don't know that you must load JsSIP as ***any** Node library, is that???

```js
var JsSIP = require('jssip');
```

BTW: http://lmgtfy.com/?q=jssip+mailing+list&l=1

**Comment by jl2035** [comment]
Yes that was it, thanks. I hope that was not to hard?!

Sorry, but somehow you have to deal with noobs. We will copy the code from the documentation and expect it will work. If not we will report the issue (being it a bug or not).

And then someday, some other noob will search the web and find this. Imagine he just finds some guy asking the same question he would, and sees that nobody helped him. This just sucks.

And finally: Please read my initial question again. I was suspecting this is the problem and I basically asked: "Do I have to somehow require it in my test.js file?" And instead of saying "Yes", you said: "Not a bug. Use the mailing list." So I hope my moment of frustration is understood.
