### ISSUE TITLE
No getUserMedia is prompt on INVITE without SDP

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#346]
Following #91:

> When sending an invite without sdp to a JSSIP client (acting as UAS in the call flow)and subsequently answering a call via the answer method without passing any options . The user isn't prompted for permission to access the devices via the browser it will just generate a 200 ok with SDP with video and audio params consequently doesn't send video or audio since the devices aren't accessed.

**Comment by jmillan** [comment]
Since no `mediaConstraints` nor `mediaStream` are passed to the `options` object, then I find it legit that the use is not prompted for device access.

I would just throw and exception in this case since there's missing information for correct operation

**Comment by jmillan** [comment]
It is responsibility of the user to use the JsSIP API properly.

If no mediaConstraints nor mediaStream are provided to RTCSession::answer(), and an offer with an empty SDP is being answered, then the resulting output is a choice of the WebRTC engine.

The required method options must be always used.
