### ISSUE TITLE
Usage of reserved words long, short and interface

### ISSUE THREAD

**Issue by choene** [versatica/JsSIP#347]
In 0.7.10, some reserved JavaScript word are used such as long, short and interface.

This causes problems with my minification.

My modifications are attached
[rsvwords.diff.txt](https://github.com/versatica/JsSIP/files/50589/rsvwords.diff.txt)

**Comment by ibc** [comment]
Such a code is not JsSIP code but code in a dependency. There is little we can do in JsSIP land.

**Comment by ibc** [comment]
At the end, `long`, `short` and `interface` are not JavaScript keywords (regardless they are defined as `reserved words` by some ECMAScript specification). Feel free to send a PR to the project of the JsSIP dependency using them if you wish, but this is not a bug in JsSIP.
