### ISSUE TITLE
newRTCSession event not fired on node.js 

### ISSUE THREAD

**Issue by aabegg** [versatica/JsSIP#349]
### I 'm doing some test with Node.js and JsSip . I have the problem that the event newRTCSession never fires .

This works flawlessly
```javascript
var ua = new JsSIP.UA(configuration);

ua.on('connected', function(e){
  console.log("PHONE CONNECTED");
});

ua.on('registered', function(e){ console.log("PHONE REGISTERED");});
ua.on('unregistered', function(e){ console.log("PHONE UNREGISTERED"); });
ua.on('registrationFailed', function(e){ console.log("PHONE REGISTRATION FAILED"); });

ua.start();

```

### But

This event will never be executed . There is also no error
```javascript
ua.on('newRTCSession', function(e){
  console.log("NEW RTC CALL");
  console.log(e);
});
```

It concerns only the Node.js application . In my browser everything works properly .

**Comment by saghul** [comment]
Node does not have a RTCPeerConnection, it's not WebRTC capable, unless you made a module yourself.

**Comment by ibc** [comment]
If you properly enable JsSIP DEBUG you will notice the exact error (already explained by @saghul).
