### ISSUE TITLE
Destination URI empty when callee hangs using kamailio

### ISSUE THREAD

**Issue by jpamies** [versatica/JsSIP#350]
When callee hangs Kamailio receives the BYE message and $du is null. When hangs who made the call $du is filled and kamailio is able to forward BYE message to the callee.

To fix this, we do a workaround on kamailio.cfg :
```
if ($du == "") {
  handle_ruri_alias();
  switch ($rc) {
...
    case 2: 
    reg_fetch_contacts("location","$tu","callee");
    $du = $(ulc(callee=>received)[0]);
    break;
...
  }
}
```

thanks

**Comment by ibc** [comment]
I don't think this is a JsSIP issue :)

**Comment by jpamies** [comment]
Ok, I guess is kamailio module fault then. I was expecting JsSIP working out of the box with it, :) 
I think pseudo-variable $du shouldn't be null. 

thanks

**Comment by ibc** [comment]
If there is a bug in JsSIP don't hesitase to report it, but please don't report it by showing variables of another SIP device/platform (I may not know what $du is, even if I do know it) :)

**Comment by jpamies** [comment]
Sure, sorry for wasting your time.
