### ISSUE TITLE
Conference disconnect

### ISSUE THREAD

**Issue by mizutechvoip** [versatica/JsSIP#354]
I am testing JsSIP conference in the following environment:
-OS: Windows 7 with latest upgrades
-Browser: Firefox 43.0.4
-Server: Freeswitch v.1.14.15: https://freeswitch.org/
-UAC1: JsSIP latest (downloaded yesterday)
-UAC2: Mizu Webphone: http://www.mizu-voip.com/Software/WebPhone.aspx
-UAC3: X-Lite: http://www.counterpath.com/x-lite/

Call is always disconnecting after 30 seconds.

Steps to reproduce the problem:
-Register from JsSIP, mizu webphone and X-Lite to freeswith
-make call from JsSIP to mizu webphone
-add X-Lite to conference
-call is disconnected after 30 seconds

The same is working fine if I am using webphone or another simpl5 instance instead if JsSIP.

**Comment by ibc** [comment]
As you will understand I cannot test your environment. So please, enable full debug in your JsSIP based web application and check who and why disconnects the session. If you find a **real** bug in JsSIP feel free to report it here.
