### ISSUE TITLE
DTLS negotiation too early causes no RTP audio

### ISSUE THREAD

**Issue by dtwright** [versatica/JsSIP#357]
I'm working with JsSIP on Chrome, and believe I've found a bug where JsSIP is starting the DTLS negotiation before ICE nomination finishes, which means the DTLS negotiation is often invalid and no audio packets can travel successfully. I get working audio on an otherwise identical setup using SIPml instead of JsSIP, which is what leads me to believe it is a JsSIP bug rather than something lower level in the browser. 

I originally opened a bug with rtpengine (which is what I'm using to do the audio proxying on the back end), and working on that lead me to believe this is a JsSIP bug. That thread also has further details: https://github.com/sipwise/rtpengine/issues/212

**Comment by ibc** [comment]
> JsSIP is starting the DTLS negotiation before ICE nomination finishes

This is imposible. That's is not up to the JS application. ICE and DTLS stuff procedures are handled by the native WebRTC stack of the browser.

Not a JsSIP issue. Sure.

**Comment by dtwright** [comment]
ok, great – do you have a theory about why SIPml appears to work reliably with no other differences in the back-end setup, then? I wouldn't have thought it was the job of JS code to do this (nor would I expect that it has direct access to that level of the link setup...), but there's clearly different behavior happening **somewhere**. You may not think it's a bug per se (and it might not be) but some other JS sip library doesn't seem to be affected by it so there might be a work around. NBD if you don't want to look at it further.

**Comment by ibc** [comment]
No idea. Maybe SIPml5 mangles the received SDP (from the server) and adds "a=ice-lite" to it to force non aggressive nomination. Just wondering.
