### ISSUE TITLE
Ephemeral Authentication for SIP

### ISSUE THREAD

**Issue by tilman22** [versatica/JsSIP#363]
Hi,

in JSSIP, it is possilble to specify credentials for SIP when initiating the UA. These credentials are then used as long as the UA lives (i.e. maybe for several hours/days).

We want to use ephemeral credentials for SIP (a WebServer created these credentials and the kamailio checks them using the ephemeral module). But these credentials are only valid for a short period of time.

Is it possible in JSSIP to update the SIP credentials? Or to get called-back when authentication takes place?

Tilman

**Comment by ibc** [comment]
Please, use the public mailing list for questions. This is the bug/issue tracker of JsSIP.

You can change some params while running: http://jssip.net/documentation/0.7.x/api/ua/#method_set

If registration fails you will get the proper `registrationFailed` error. Just check the documentation regarding it.
