### ISSUE TITLE
JsSIP 500 Internal Error when receiving re-INVITE

### ISSUE THREAD

**Issue by 62mkv** [versatica/JsSIP#365]
Hi

We've having issues with jsSIP 0.7.17 in Chrome 49 on Ubuntu 15.10 (SIP server: Asterisk 13.7.0/WSS). 

The issue is as follows: 
1) Asterisk is placing a call on "jsSIP"-ped peer. (oh, by the way, we're using hack_via_wss from https://github.com/versatica/JsSIP/pull/359, otherwise we would not be able to receive INVITEs at all!!)
2) jsSIP receives INVITE with a=setup:actpass attribute in SDP
3) jsSIP answers with "SIP/2.0 100 Trying"
4) jsSIP answers with "SIP/2.0 180 Ringing"
5) user picks up a call, jsSIP answers with "SIP/2.0 200 OK", having "a=setup:active" in SDP
6) Asterisk answers with "ACK SIP/2.0" 
7) Asterisk sends a re-INVITE with ;tag in To: header and "a=setup:passive" in SDP.
8) jsSIP answers with "SIP/2.0 100 Trying"
9) Then an error occurs: rtcninja:ERROR:RTCPeerConnection setLocalDescription() | error: +2ms Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.

It seems like Chrome (as it's a browser error, I suppose) can not realize that the second INVITE is a re-INVITE, and this leads to critical error.

This behaviour is not occuring in FF, there we can accept INVITEs

Is this a bug in our integration of jsSIP, jsSIP itself, Chrome or Asterisk, or whatever else ? 

Many thanks! I attached the whole session,  dumped from the Chrome console; and also the whole session from the FF console

UPD: Oops, it's not possible to attach .zip file here (althought it's mentioned among suggested formats). So I've uploaded it on a Dropbox: https://www.dropbox.com/s/9pcd7a9tfc0t2np/rtcninja-reinvite-setup.zip?dl=0

**Comment by 62mkv** [comment]
UPD: this might have something to do with https://bugs.chromium.org/p/webrtc/issues/detail?id=2782. But this should be fixed in Chrome 49, or am I wrong ? Although, I don't think I'll be able to post a bug there... are we the only ones to come across this behaviour ?

**Comment by ibc** [comment]
The a=setup attribute in a SDP offer (let it be in the initial INVITE or in a reINVITE) MUST be "actpass" as per RFC spec. This is a known bug in Asterisk. Please report it.

**Comment by 62mkv** [comment]
Done: https://issues.asterisk.org/jira/browse/ASTERISK-25864
