### ISSUE TITLE
What needs to be changed to use JSSIP over plain UDP, when jsSIP is used as a Node.js module?

### ISSUE THREAD

**Issue by n-samir** [versatica/JsSIP#368]
I want to initiate calls from a Node.js app server used with Kurento Media server. I want my app server to initiate a SIP call to an Asterisk server. The only missing piece I have now is a Node JS module that will talk to Asterisk over UDP and not websockets. Most of the JSlibraries use RFC 7118 implementation which requires the SIP server/registrar to have websockets support. I do not want to use Asterisk's support for webRTC directly.

**Comment by ibc** [comment]
Please, let's use Github to report issues/bugs. Use the JsSIP mailing list for questions and wishes.
