### ISSUE TITLE
Replace "useinbandfec" with "cbr" in the Offer SDP

### ISSUE THREAD

**Issue by codetopper** [versatica/JsSIP#369]
In JS 0.3, the outgoing INIVTE contains the offer SDP 

```
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10; useinbandfec=1
```

I want to replace the useinbandfec=1 to cbr=1
I added this line in setLocalDescription function

`sessionDescription.sdp = sessionDescription.sdp.replace("useinbandfec=1", "cbr=1");`

```
setLocalDescription:`` function(sessionDescription, onFailure) {
    sessionDescription.sdp = sessionDescription.sdp.replace("useinbandfec=1", "cbr=1");
    this.peerConnection.setLocalDescription(
      sessionDescription,
      function(){},
      function(e) {
        console.error(LOG_PREFIX +'unable to set local description');
        console.error(e);
        onFailure();
      }
    );
  },

```

After this change, the useinbandfec was removed but it didn't replace with cbr

Offer SDP
```
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
```

Please suggest how can I make this change.
Thanks for the help.

**Comment by jmillan** [comment]
Hi,

There is an issue already to provide API callbacks for the purpose of modifying the SDP: #320.

**Comment by codetopper** [comment]
@jmillan : Thanks for the prompt reply. I checked the issue:#320 but couldn't find the API callback in v0.3 that can modify the attribute in the parsed SDP object.
Here, using this line in the setLocalDescription function I can successfully modify the Offer SDP.

`sessionDescription.sdp = sessionDescription.sdp.replace("useinbandfec=1", "useinbandfec=0");`

**From**
```
a=fmtp:111 minptime=10; useinbandfec=1
```
**To**
```
a=fmtp:111 minptime=10; useinbandfec=0
```

But, this doesn't work only when I try to replace "useinbandfec=1" with some other string.
The code yields to output 

`sessionDescription.sdp = sessionDescription.sdp.replace("useinbandfec=1", "cbr-=1");`

```
a=fmtp:111 minptime=10
```

Looks like the replace method can parse the "useinband=1" str but is having issues during substitution. Due to which the "; useinbandfec=1"  string disappears in the SDP object and isn't replaced as

```
a=fmtp:111 minptime=10; cbr=1
```

If I'm missing something here, please correct me.
Thanks for the help

**Comment by codetopper** [comment]
I think I have found the issue.
In setLocalDescription property, the SDP offer is changed successfully

`a=fmtp:111 minptime=10; cbr=1`

But, in createOfferOnSucces it didn't update

`a=fmtp:111 minptime=10; useinbandfec=1`

Can you please tell what API should I use in order to make this change ?

**Comment by jmillan** [comment]
Check the docs: http://jssip.net/documentation/0.7.x/api/session/#event_sending

Any question please use public mailing list. This is not a bug.
