### ISSUE TITLE
Cseq in Ack for Delayed 407 - Invite Client Transaction

### ISSUE THREAD

**Issue by vertika-19** [versatica/JsSIP#370]
I think there is some issue with cseq in the sip messages sent from chrome browser 
Check Cseq if they are correct ?

Scenario - 

INVITE sip:1435@***************** SIP/2.0
Via: SIP/2.0/WSS 0lufrd75qctr.invalid;branch=z9hG4bK5499764
Max-Forwards: 69
To: <sip:1435@*****************>
From: <sip:1002@*****************>;tag=70ni8hngla
Call-ID: esq7ca7cmsq4ffap975e
CSeq: 1934 INVITE

SIP/2.0 100 Trying
Via: SIP/2.0/WS 0lufrd75qctr.invalid;branch=z9hG4bK5499764
From: <sip:1002@*****************>;tag=70ni8hngla
To: <sip:1435@*****************>
CSeq: 1934 INVITE

SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/WS 0lufrd75qctr.invalid;branch=z9hG4bK5499764
From: <sip:1002@*****************>;tag=70ni8hngla
To: <sip:1435@*****************>;tag=877QjDygtyUyc
CSeq: 1934 INVITE

ACK sip:1435@***************** SIP/2.0
Via: SIP/2.0/WSS 0lufrd75qctr.invalid;branch=z9hG4bK5499764
To: <sip:1435@*****************>;tag=877QjDygtyUyc
From: <sip:1002@*****************>;tag=70ni8hngla
CSeq: 1934 ACK

INVITE sip:1435@***************** SIP/2.0
Via: SIP/2.0/WSS 0lufrd75qctr.invalid;branch=z9hG4bK5560934
Max-Forwards: 69
To: <sip:1435@*****************>
From: <sip:1002@*****************>;tag=70ni8hngla
CSeq: 1935 INVITE

SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/WS 0lufrd75qctr.invalid;branch=z9hG4bK5499764
From: <sip:1002@*****************>;tag=70ni8hngla
To: <sip:1435@*****************>;tag=877QjDygtyUyc
CSeq: 1934 INVITE

ACK sip:1435@***************** SIP/2.0
Via: SIP/2.0/WSS 0lufrd75qctr.invalid;branch=z9hG4bK5560934
To: <sip:1435@*****************>;tag=877QjDygtyUyc
From: <sip:1002@*****************>;tag=70ni8hngla
CSeq: 1935 ACK

Though this last Ack is for delayed 407  but it has CSeq : 1935 ........ as it is ACK for request ( 1st Invite ) so it should have CSeq as 1934 I think .

Please check this.

Thank you

**Comment by jmillan** [comment]
Hi @vertika-19,

Thanks for reporting the issue. Would you be so kind to apply the following patch and report here the results?

````
iff --git a/lib/RequestSender.js b/lib/RequestSender.js
index a83b7bc..00cb69e 100644
--- a/lib/RequestSender.js
+++ b/lib/RequestSender.js
@@ -125,7 +125,6 @@ RequestSender.prototype = {
           cseq = this.request.dialog.local_seqnum += 1;
         } else {
           cseq = this.request.cseq + 1;
-          this.request.cseq = cseq;
         }
         this.request.setHeader('cseq', cseq +' '+ this.method);
````

Thanks!

**Comment by jmillan** [comment]
@vertika-19 friendly ping

**Comment by ibc** [comment]
@vertika-19 friendly ping number 2

**Comment by jmillan** [comment]
NOTE: Got it. We are using the same request object reference for both inviteclientransactions...
A OutgoingRequest.clone() method must be created so the initial request and the authenticated one are actually different objects.
