### ISSUE TITLE
Some deprecated stuff on Firefox

### ISSUE THREAD

**Issue by scgm11** [versatica/JsSIP#373]
WebRTC interfaces with the "moz" prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated. jssip.js:24802:12
onaddstream is deprecated! Use peerConnection.ontrack instead. <unknown>
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

just to let you know, its possible to replace the moz prefix now.

**Comment by ibc** [comment]
It can be replaced now, but then tons of non updated Firefox users will complain.

I'm pretty sure Firefox won't remove that "deprecated" API soon.

**Comment by jmillan** [comment]
To be changed in rtcninja.js in a future, when Firefox versions using 'moz' prefix are too old to be out there or have some critical security issue.

Let me please close it. Thanks for reporting @scgm11.

**Comment by Demitrius** [comment]
JSSIP stop working in FF 48 (don't know how about 47)

**conslose log**

_WebRTC interfaces with the "moz" prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.

onaddstream is deprecated! Use peerConnection.ontrack instead.

navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia_
