### ISSUE TITLE
Bad Media Description error node-webkit

### ISSUE THREAD

**Issue by eupdate** [versatica/JsSIP#375]
When i get call to the remote i got following error. **BAD MEDIA DESCRIPTION**. How could i fix this issue ?

Object {originator: "remote", message: IncomingResponse, cause: "Bad Media Description"}cause: "Bad Media Description"message: IncomingResponsebody: "v=0
↵o=FreeSWITCH 1464154879 1464154880 IN IP4 192.168.20.2
↵s=FreeSWITCH
↵c=IN IP4 192.168.20.2
↵t=0 0
↵a=msid-semantic: WMS YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWo
↵m=audio 16936 RTP/SAVPF 9 126 106
↵a=rtpmap:9 G722/8000
↵a=rtpmap:126 telephone-event/8000
↵a=rtpmap:106 CN/8000
↵a=ptime:20
↵a=fingerprint:sha-256 34:D4:64:D0:CF:1E:CD:5A:19:D2:55:D8:43:C0:27:F8:2F:32:53:A1:14:56:FF:D3:BC:99:BC:2F:12:02:C2:D0
↵a=setup:active
↵a=rtcp-mux
↵a=rtcp:16936 IN IP4 192.168.20.2
↵a=ssrc:2873703095 cname:DzyxW14ID59BRyNy
↵a=ssrc:2873703095 msid:YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWo a0
↵a=ssrc:2873703095 mslabel:YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWo
↵a=ssrc:2873703095 label:YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWoa0
↵a=ice-ufrag:oTGDow0PNIwdOiri
↵a=ice-pwd:IQFvHA3bv2CdrfBFZ89ev0T8
↵a=candidate:1510549051 1 udp 659136 192.168.20.2 16936 typ host generation 0
↵"call_id: "gmucn1d2701phg56p34t"cseq: 4605data: "SIP/2.0 200 OK
↵Via: SIP/2.0/WS bd5b32futq4t.invalid;branch=z9hG4bK2888403;received=192.168.20.101;rport=48963
↵From: <sip:50@192.168.20.2:5080>;tag=ttm0mpjrsr
↵To: <sip:0773785291@192.168.20.2:5080>;tag=UjNtpmmtjU4XN
↵Call-ID: gmucn1d2701phg56p34t
↵CSeq: 4605 INVITE
↵Contact: <sip:0773785291@192.168.20.2:5080;transport=udp>
↵User-Agent: FreeSWITCH-mod_sofia/1.4.26+git~20160119T163808Z~c1a3a280c2~64bit
↵Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
↵Supported: timer, path, replaces
↵Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
↵Session-Expires: 120;refresher=uas
↵Content-Type: application/sdp
↵Content-Disposition: session
↵Content-Length: 833
↵Remote-Party-ID: "Outbound Call" <sip:0773785291@192.168.20.2>;party=calling;privacy=off;screen=no
↵
↵v=0
↵o=FreeSWITCH 1464154879 1464154880 IN IP4 192.168.20.2
↵s=FreeSWITCH
↵c=IN IP4 192.168.20.2
↵t=0 0
↵a=msid-semantic: WMS YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWo
↵m=audio 16936 RTP/SAVPF 9 126 106
↵a=rtpmap:9 G722/8000
↵a=rtpmap:126 telephone-event/8000
↵a=rtpmap:106 CN/8000
↵a=ptime:20
↵a=fingerprint:sha-256 34:D4:64:D0:CF:1E:CD:5A:19:D2:55:D8:43:C0:27:F8:2F:32:53:A1:14:56:FF:D3:BC:99:BC:2F:12:02:C2:D0
↵a=setup:active
↵a=rtcp-mux
↵a=rtcp:16936 IN IP4 192.168.20.2
↵a=ssrc:2873703095 cname:DzyxW14ID59BRyNy
↵a=ssrc:2873703095 msid:YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWo a0
↵a=ssrc:2873703095 mslabel:YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWo
↵a=ssrc:2873703095 label:YxMk4xCGVMbA7WzlQZgipF0wAqSQzgWoa0
↵a=ice-ufrag:oTGDow0PNIwdOiri
↵a=ice-pwd:IQFvHA3bv2CdrfBFZ89ev0T8
↵a=candidate:1510549051 1 udp 659136 192.168.20.2 16936 typ host generation 0
↵"from: NameAddrHeaderfrom_tag: "ttm0mpjrsr"headers: Objectmethod: "INVITE"reason_phrase: "OK"session_expires: 120session_expires_refresher: "uas"status_code: 200to: NameAddrHeaderto_tag: "UjNtpmmtjU4XN"via: Objectvia_branch: "z9hG4bK2888403"__proto__: IncomingMessageoriginator: "remote"__proto__: Object

**Comment by eupdate** [comment]
@ibc  is there any fix for this ?

**Comment by ibc** [comment]
Basic usage questions in the public mailing list, please.
