### ISSUE TITLE
JsSIP.Socket: No way to set via_transport

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#376]
When using JsSIP with the well known `ws_servers` parameters, JsSIP 1.0.X creates a `WebSocket` interface (based on `JsSIP.Socket`). However, since `hack_via_ws` and `hack_via_tcp` have been removed, there is no way to set those "hacks".

`WebSocket.js` provides a `via_transport` setter, but `Transport` does not provide an API for that. Even worse, `UA` does not even provide an API to retrieve the `Transport` instance. In fact, we don't want to provide the `Transport` via API, but therefore we don't have a way to override the VIA transport (which is required in many scenarios).

**Comment by jmillan** [comment]
Hi,

It is a doc issue. My fault. You can set it on UA.on('connected') event. Which provides the Socket instance. [*]

Or we can expose JsSIP.WebSocketInterface so the user can use the setters before submitting the Sockets to UA:

[*]: http://jssip.net/documentation/1.0.x/api/ua/#event_connected

**Comment by ibc** [comment]
Setting static stuff (the hacked Via transport field) within the "connected" event does not seem nice IMHO. Users want to set the desired settings at the beginning rather than once something happens.

Exposing the `JsSIP.WebSocketInterface` seems much better for me. But then I wonder whether we really want to keep the `ws_servers` UA setting...

**Comment by jmillan** [comment]
> Exposing the JsSIP.WebSocketInterface seems much better for me. But then I wonder whether we really want to keep the ws_servers UA setting...

Yes, I do agree that exposing `JsSIP.WebSocketInterface` is nicer (although nothing prevents them to use the 'connected' event for that as well). I would leave `ws_servers` and let those who need hacks create the Socket instance themselves.

**Comment by jmillan** [comment]
closing..
