### ISSUE TITLE
"sdp" event should also provide the Request instance

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#379]
Example use case:

* Create an INVITE with `Content-Type: multipart/mixed` and a body having both a SDP (`Content-Type: application/sdp`) and a resource list (`Content-Type: application/resource-lists+xml`).

Unfortunately JsSIP does not allow overriding the `Content-Type` of an ongoing INVITE, and the "sdp" event just provides the raw SDP string.

A non API-breaking feature could be also providing the `request` or `response` within the "sdp" event.

@jmillan do you see something wrong with that?

**Comment by ibc** [comment]
After digging into the code for a while, I find very complex to provide the corresponding `Request` or `Response` in all the cases in which "sdp" is fired.

**Comment by jmillan** [comment]
Lets forget about this issue for now. I prefer to add support to multipart message body as we commented in a recent conversation ;-)-

**Comment by ibc** [comment]
Yep.
