### ISSUE TITLE
rtcninja is outdated

### ISSUE THREAD

**Issue by skaynetmen** [versatica/JsSIP#383]
rtcninja is outdated. Do you have any plans to replace it with [webrtc/adapter](https://github.com/webrtc/adapter)?

Latest firefox deprecated mozGetUserMedia, mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate, RTCPeerConnection.onaddstream  etc.

**Comment by ibc** [comment]
JsSIP won't never include a library (`adapter.js`) that pollutes the `window` global namespace.

> Latest firefox deprecated mozGetUserMedia, mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate, RTCPeerConnection.onaddstream  etc.

But it works, right?

**Comment by skaynetmen** [comment]
![screenshot](http://joxi.net/1A55yXMuKBOeOA.png)

**Comment by ibc** [comment]
Which is the question? The current version of webrtc-adapter no longer pollutes the global namespace with custom stuff so it is acceptable.
