### ISSUE TITLE
No CANCEL message after terminating a ringing call

### ISSUE THREAD

**Issue by hoene** [versatica/JsSIP#385]
Using jssip 202, I call a media server, which does late codec negotiation.
After receiving a 180 RINGING message, I terminate the call.

Then, jssip does not sent a CANCEL message and thus, the call is not terminated at the media server side.

**Comment by hoene** [comment]
JsSIP:RTCSession receiveInviteResponse() +12ms
jssip.min.js?1467042568000:22521 JsSIP:WebSocketInterface received WebSocket message +412ms
jssip.min.js?1467042568000:22521 JsSIP:Transport received text message:

SIP/2.0 180 Ringing
v:SIP/2.0/WSS 9bptllb33id9.invalid;branch=z9hG4bK6355076;received=10.200.200.1;rport=39788
From: "Christian Hoene" <sip:1111@sipcast.symonics.com>;tag=a933gu2ol0
t:<sip:3333@sipcast.symonics.com>;tag=DyZp41NF82UjK
Call-ID: 32jnh6va1etc8docrrgm
CSeq: 5056 INVITE
m:<sip:3333@10.200.200.1:5060;transport=udp>
User-Agent:SY160624
Accept:application/sdp
Allow:INVITE,ACK,BYE,CANCEL,OPTIONS,MESSAGE,INFO,UPDATE,REGISTER,REFER,NOTIFY,PUBLISH,SUBSCRIBE
k:path,replaces
u:talk,hold,conference,presence,as-feature-event,dialog,line-seize,call-info,sla,include-session-description,presence.winfo,message-summary,refer
l:0
Remote-Party-ID:"Outbound Call"<sip:tssmbhpv@sipcast.symonics.com>;party=calling;privacy=off;screen=no


 +1ms
jssip.min.js?1467042568000:22521 JsSIP:RTCSession receiveInviteResponse() +8ms
jssip.min.js?1467042568000:22521 JsSIP:Dialog new UAC dialog created with status EARLY +2ms
jssip.min.js?1467042568000:22521 JsSIP:RTCSession session progress +2ms
sipcast.js?1467042678000:305 e progress Object {originator: "remote", response: IncomingResponse} undefined
jssip.min.js?1467042568000:22521 JsSIP:RTCSession terminate() +5s
jssip.min.js?1467042568000:22521 JsSIP:RTCSession canceling session +3ms
jssip.min.js?1467042568000:22521 JsSIP:RTCSession session failed +5ms
jssip.min.js?1467042568000:22521 JsSIP:RTCSession close() +1ms
jssip.min.js?1467042568000:22521 JsSIP:RTCSession close() | closing local MediaStream +4ms
jssip.min.js?1467042568000:22521 JsSIP:Dialog dialog 32jnh6va1etc8docrrgma933gu2ol0DyZp41NF82UjK deleted +1ms

**Comment by hoene** [comment]
This solves the problem:

hoene@dev4:~/git/JsSIP/lib$ git diff 2.0.2
diff --git a/lib/Transactions.js b/lib/Transactions.js
index 22a31c4..a2d22d7 100644
--- a/lib/Transactions.js
+++ b/lib/Transactions.js
@@ -272,7 +272,7 @@ InviteClientTransaction.prototype.cancel_request = function(tr, reason) {
   this.cancel += 'Content-Length: 0\r\n\r\n';
 
   // Send only if a provisional response (>100) has been received.
-  if(this.state === C.STATUS_PROCEEDING) {
+  if(this.state === C.STATUS_PROCEEDING || this.state === STATUS_1XX_RECEIVED) {
     this.transport.send(this.cancel);
   }

**Comment by hoene** [comment]
ok, I agree, this is not the right bug fix. But then again, it pin points to the problem

**Comment by ibc** [comment]
Again, you are mixing `RTCSession` (STATUS_1XX_RECEIVED) states and `Transaction` states (STATUS_PROCEEDING).  Your path above is wrong, you have not checked it at all given that `STATUS_1XX_RECEIVED` does not even exist in the Transactions.js file.

Please, paste the whole debug since the INVITE is sent until `terminate()` is called.

**Comment by hoene** [comment]
Yes, you are right. My bug fix is not correct.

[jssip-no-cancel.txt](https://github.com/versatica/JsSIP/files/336652/jssip-no-cancel.txt)

**Comment by ibc** [comment]
Please, place a breakpoint at `RTCSession.prototype.terminate` and paste here the value of `this.status` (an integer).

**Comment by choene** [comment]
The this.status  is 6 (terminated).

 

(see also the output of myd)

 

 

Von: Iñaki Baz Castillo [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. Juni 2016 11:35
An: versatica/JsSIP <JsSIP@noreply.github.com>
Betreff: Re: [versatica/JsSIP] No CANCEL message after terminating a ringing call (#385)

 

Please, place a breakpoint at RTCSession.prototype.terminate and paste here the value of this.status (an integer).

**Comment by ibc** [comment]
May I have access to your server so I send an INVITE and try to cancel it after ringing?

**Comment by davies147** [comment]
I am also havibng this issue - I THINK I know what is causing it.

The call to terminate calls `this.request.cancel(cancel_reason);`, which is defined inside `InviteClientTransaction` as 

```
  this.request.cancel = function(reason) {
    tr.cancel_request(tr, reason);
  };
```

My best guess is that the first non-authorized INVITE is sent out, and failes (state = 6) and then when the 2nd INVITE goes out, the above `this.request.cancel` is no longer bound to the right scope, and is trying to cancel the 1st INVITE and not the 2nd

? Perhaps ?

**Comment by ibc** [comment]
I've full traces reproducing the issue. I've copied them (by replacing IPs and s on) in the wiki:

https://github.com/versatica/JsSIP/wiki/CANCEL_issue

@davies147 I think you are right.

**Comment by ibc** [comment]
@jmillan tells me that this regression was probably introduced here: ed175663b09b1881dc76075abadf7299df9bbd80

**Comment by ibc** [comment]
The bug is identified. Working on it.

**Comment by Jaykah** [comment]
Has anyone confirmed that CANCEL is working pre- https://github.com/versatica/JsSIP/commit/ed175663b09b1881dc76075abadf7299df9bbd80 ?

**Comment by Jaykah** [comment]
Confirmed, CANCEL is working fine pre- https://github.com/versatica/JsSIP/commit/ed175663b09b1881dc76075abadf7299df9bbd80

Are you expecting to release a fix anytime soon? If not, it's probably best to add a note to Readme so that people are aware of this.

Thanks!

**Comment by ibc** [comment]
Holidays, guys.

**Comment by testtestvoip** [comment]
I'm looking forward to solving  this bug.  I hope, @ibc, you are going to fix it and make a release soon. Thank you in advance.

**Comment by runInCloud** [comment]
I'm looking forward to solving  this bug.  I hope, @ibc, you are going to fix it and make a release soon. Thank you in advance.

**Comment by ibc** [comment]
@runInCloud We will handle this issue when possible. Donations/contributions usually help when a feature or bugfix is needed.
