### ISSUE TITLE
Echo cancellation problem on mobile browsers

### ISSUE THREAD

**Issue by pfuerholz** [versatica/JsSIP#387]
I just tried JsSIP via your Try-It page https://tryit.jssip.net/ and noticed a very strong echo problem when using my mobile phone, a Samsung Galaxy S4. It tested it with the standard browser (Internet, V. 4.0.10-53) and Chrome (V. 51.0.2704.81).
On my desktop computer the Try-It page worked fine with Firefox and Chrome.

**Comment by ibc** [comment]
Sorry, we don't provide support for the Tryit demo app. It's not our "JsSIP reference app".

**Comment by pfuerholz** [comment]
Thanks for your quick answer. 
Could you then please answer me following questions?
- Is JsSIP tested on mobile browsers? (According to http://www.jssip.net/documentation/misc/interoperability/ ('...here a list of ...') Chrome on Android should work though.)
- What is your JsSIP reference app?
- Is there another forum supporting the Try-It application? (I just came via http://www.jssip.net/ to the site here...)
Thanks in advance!

**Comment by ibc** [comment]
> Is JsSIP tested on mobile browsers? (According to http://www.jssip.net/documentation/misc/interoperability/ ('...here a list of ...') Chrome on Android should work though.)

Yes, it's tested on mobiles, specially in Cordova apps.

> What is your JsSIP reference app?

We don't have a public JsSIP reference app.

> Is there another forum supporting the Try-It application? (I just came via http://www.jssip.net/ to the site here...) Thanks in advance!

There is not such a forum. We encourage users of JsSIP to read the API doc of JsSIP and just report issues once they build their own app based on JsSIP.

**Comment by pfuerholz** [comment]
Thanks for your answers. I am glad it is tested on mobiles as well.
