### ISSUE TITLE
use of reserved keywords

### ISSUE THREAD

**Issue by hoene** [versatica/JsSIP#389]
To minify my code, I use minify-maven-plugin:1.7.4:minify

It has some problems with reserved keywords ("short","long", and "interface") that are used in jssip.

I changed the jssip code to 

...

module.exports = function(val, options){
   options = options || {};
   if ('string' == typeof val) return parse(val);
-  return options.long
Add a comment to this line
-    ? long(val)
-    : short(val);
+  return options["long"]
+    ? myLong(val)
+    : myShort(val);
 };
 
 /**

....

  * @api private
  */
 
-function short(ms) {
+function myShort(ms) {
   if (ms >= d) return Math.round(ms / d) + 'd';
   if (ms >= h) return Math.round(ms / h) + 'h';
   if (ms >= m) return Math.round(ms / m) + 'm';

...

  * @api private
  */
 
-function long(ms) {
+function myLong(ms) {
   return plural(ms, d, 'day')
     || plural(ms, h, 'hour')
     || plural(ms, m, 'minute')

....

 		typeof options.plugin.isInstalled === 'function' &&
 		options.plugin.isInstalled()
 	) {
-		var pluginiface = options.plugin.interface;
+		var pluginiface = options.plugin["interface"];
 
 		hasWebRTC = true;
 		getUserMedia = pluginiface.getUserMedia;

and know, the minification process does work.

**Comment by jmillan** [comment]
Hi,

None of the words mentioned belong to JsSIP code itself but to other modules. Looks like the minifier you're using is too strict when it comes to use 3rd party modules.
