### ISSUE TITLE
Adapter/Adapter.getUserMedia jssip-2.0.2.js:23091

### ISSUE THREAD

**Issue by wadelee1986** [versatica/JsSIP#390]
How to resolve  this problem ;

![image](https://cloud.githubusercontent.com/assets/19798109/16546047/426d1d44-4170-11e6-8636-9f45f7413dfb.png)

**Comment by wadelee1986** [comment]
program  stop here

**Comment by jmillan** [comment]
Please, debug your code a bit more. This is not a library issue. Use breakpoints or more debug lines to follow your code's flow.
