### ISSUE TITLE
Problem with hold() in JsSIP v2.0.2

### ISSUE THREAD

**Issue by aitorfdezmaseda** [versatica/JsSIP#392]
When I put a call on hold with Firefox, Asterisx receives no signal. On the contrary, when the call is from the Chrome appears in Asterisk "Music is on hold". What can be happening?
In my code I make a call to a call is made to JsSIP.rtcninja.canRenegotiate in Chrome returns true, Firefox returns false. Can this be the problem?
Thanks!!

versions:
JsSIP v2.0.2,
firefox 43
chrome v.47.0.2526.106

**Comment by ibc** [comment]
Please, use the mailing list for questions.
