### ISSUE TITLE
problems between rtpengine linphone and jssip

### ISSUE THREAD

**Issue by martingerman81** [versatica/JsSIP#394]
Hello,

We are integrating WebRTC using JsSIP, with mobile users using linphone. Also, we are using Kamailio with a rtpengine module to make calls between JsSIP and linphone.

This approach works fine when we are using chrome, but in the case of firefox the event iceconnectionchange (state = 'connected' ) doesn't arrive.

We have found a workaround, we have put an alert on the following function and the event arrives.
this.connection.onaddstream = function(event, stream) {
  self.emit('addstream', {stream: stream});
};

Any idea what could be happening? Why on chrome it works but doesn't on firefox?

Thanks!

Best regards,
  Martín.

**Comment by jmillan** [comment]
Hi @martingerman81, 

Please, enable the JsSIP logs and attach them so we can check them.

**Comment by martingerman81** [comment]
Hi, 
I have attached the JsSIP log.
BR,
  Martín.


[jssip_firefox.txt](https://github.com/versatica/JsSIP/files/408363/jssip_firefox.txt)

**Comment by jmillan** [comment]
Have you checked the firefox `about:webrtc` log and the ICE traffic?

**Comment by jmillan** [comment]
BTW, enabling rtcninja.js debug logs may show something relevant. Just enable all the logs `'*'`

http://jssip.net/documentation/2.0.x/api/debug/

**Comment by martingerman81** [comment]
Hi,

I have attached the new logs, I have enabled all the logs.

[about_webrtc.txt](https://github.com/versatica/JsSIP/files/408548/about_webrtc.txt)
[jssip_firefox_2.txt](https://github.com/versatica/JsSIP/files/408549/jssip_firefox_2.txt)

**Comment by ibc** [comment]
2016-08-05 13:01 GMT+02:00 martingerman81 <notifications@github.com>:

> This approach works fine when we are using chrome, but in the case of
> firefox the event iceconnectionchange (state = 'connected' ) doesn't arrive.
>
> We have found a workaround, we have put an alert on the following function
> and the event arrives.
> this.connection.onaddstream = function(event, stream) {
> self.emit('addstream', {stream: stream});
> };
>
"addstream" event fires when the remote SDP has been received. It has no
relationship with the missing "iceconnectionchange" event.



> Any idea what could be happening? Why on chrome it works but doesn't on
> firefox?
>
No idea, but your scenario involves rtpengine. If stuff fails at pure
WebRTC media level that's not a bug of JsSIP.



-- 
Iñaki Baz Castillo
<ibc@aliax.net>

**Comment by jmillan** [comment]
@martingerman81,

Check the STUN traffic between client and server, you should see the differences when you set that alert and when you don't. That can bring you some light on the issue.

As @ibc says, being a pure media problem it's nothing to do with JsSIP, although we'd like to know about the cause if you finally find the problem.

**Comment by martingerman81** [comment]
Many thanks @ibc and @jmillan for your help,  I will inform you about the progress on this issue.

**Comment by martingerman81** [comment]
Hi @ibc and @jmillan,

We have solved the problem. The problem was wrong configuration on JsSIP, the gatheringTimeoutAfterRelay parameters was 1 instead of 1000, but the poblems only was on firefox, on chrome with this parameter in 1 it worked.

Close the issue.

Thanks!

**Comment by ibc** [comment]
Chrome provides local ICE candidates even immediately, while Firefox does not.
