### ISSUE TITLE
Websocket disconnects

### ISSUE THREAD

**Issue by cveazey2236** [versatica/JsSIP#395]
We are seeing an issue in Firefox that kills the websocket connection at ~5 min into a call. FF browser logs consistently show:

The connection to wss://uswrs.incontact.com:8070/ was interrupted while the page was loading.
https://home-b3.incontact.com/inContact/MAX/js/lib/jssip-2.0.2.min.js?v=16.2.012.0160
Line 46

TypeError: e is undefined
https://home-b3.incontact.com/inContact/MAX/js/modules/icSoftPhone.js?v=16.2.012.0160
Line 1

Any thoughts?

**Comment by ibc** [comment]
JsSIP does not disconnect the WebSocket. Maybe your SIP server closes it after N minutes without messages. Or your NAT router. No idea.

To be clear: this is not a bug in JsSIP.
