### ISSUE TITLE
Trying to send unregister transport while websocket connection is closed

### ISSUE THREAD

**Issue by markhorsman** [versatica/JsSIP#396]
Hello guys,

I've noticed something in my logs while using your library for registering a SIP account.
When my websocket connection is closed (abrupt disconnect) is see that it tries to send an unregister package to our SIP server. This obviously fails because there is not websocket connection. 

I was wondering if this is a bug or that I'm just missing something (I'm still learning)?

jssip-2.0.2.min.js?v=1470648823940:15 JsSIP:WebSocketInterface send() +0ms
jssip-2.0.2.min.js?v=1470648823940:15 JsSIP:WebSocketInterface WebSocket wss://sipserver:wssport closed +7s
jssip-2.0.2.min.js?v=1470648823940:15 JsSIP:WebSocketInterface WebSocket abrupt disconnection +0ms

jssip-2.0.2.min.js?v=1470648823940:15 JsSIP:UA stop() +16ms
jssip-2.0.2.min.js?v=1470648823940:15 JsSIP:Transport send() +0ms
jssip-2.0.2.min.js?v=1470648823940:15 JsSIP:ERROR:Transport unable to send message, transport is not connected +0ms

I also noticed that after disconnecting, there is no reconnect attempt afterwards. 
Do I have to build this in myself or can I set this somewhere in the UA instance?

With kind regards,

Mark Horsman
Tam One

**Comment by ibc** [comment]
Hi, please use the public mailing list for questions.
