### ISSUE TITLE
Browserify not resolving package.json

### ISSUE THREAD

**Issue by plantsmiles** [versatica/JsSIP#399]
I'm trying to use JsSIP with broswerify like this:

`var JsSIP = require('jssip');`

Basically like any other npm module, however when loading my project in the browser i get

`app.js:2 Uncaught Error: Cannot find module '../../package.json'`

Looking through the source it's used to provide version numbers in a few places.  Also whats strange is that in the JsSIP source the path is only `'../package.json'`.

Anyway, just wondering if anyone has had luck pulling this into the browser via browserify?  I saw a page about the JsSIP actually using browserify itself, but I think it was under the 0.5.x version.

Thanks!

**Comment by ibc** [comment]
This just works. I use the `jssip` npm module every day within browserified projects.

Indeed, `lib/JsSIP.js` and `lib/Constans.js` load the package.json file using `require()`, which correctly points to the proper relative location of the json file.

Check your browserify stuff, something is wrong in there.

**Comment by plantsmiles** [comment]
Thank you, just crossed this off the list! Cheers.
