### ISSUE TITLE
JsSIP:ERROR:Socket missing or invalid JsSIP.Socket url property

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#401]
``` js
var socket = new JsSIP.WebSocketInterface('wss://foo.com');

var ua = new JsSIP.UA({
    'sockets'           : [socket],
    'uri'               : 'sip:qweqwe@qweqweqwe.com',
});
```

This produces a error in the console:

```
JsSIP:ERROR:Socket missing or invalid JsSIP.Socket url property
```

However, things do work and the WS connection is established and so on.

I think this happens because in `UA.js` there is:

``` js
      if (Socket.isSocket(sockets)) {
        sockets = [{socket: sockets}];
      } else if (Array.isArray(sockets) && sockets.length) {
        length = sockets.length;
        for (idx = 0; idx < length; idx++) {
          if (Socket.isSocket(sockets[idx])) {
            sockets[idx] = {socket: sockets[idx]};
          }
        }
      } else {
        return;
      }
```

The first `Socket.isSocket()`  returns false because `sockets` is an array, so `Socket.isSocket` function logs such an error.

I will remove such a log because it is confusing in valid scenarios.

**Comment by MelodyHacker** [comment]
var socket = new JsSIP.WebSocketInterface('wss://192.168.100.123:8089/ws');
var configuration = {
        sockets  : [ socket ],
        uri      : 'sip:3000@192.168.100.123',
        password : '3000'
};
i can connect it

**Comment by ibc** [comment]
Mailing list, please.
