### ISSUE TITLE
Reconnect is slow on mac + chrome

### ISSUE THREAD

**Issue by mdavid5** [versatica/JsSIP#402]
Hi,
I've noticed a re-connection bug:
The reconnection logic is fired only on the socket disconnect event:

this.socket.ondisconnect  = onDisconnect.bind(this);
.
.
function onDisconnect(error, code, reason) {
  // this function is called minutes after the connection is lost
   .
   .
   reconnect.call(this, error);
}

However this disconnect event is fired only few minutes (!!!!) after the connection is down in chrome. (even after the connection is restored - when the client is in wrong state, ofc) 

The issue is only on mac and with chrome. I've tested the re-connection with firefox and with win + chrome and it works fine.

The rtcConnection iceconnectionstatechange fires and the terminate logic starts when the connection is down (JsSIP_C.causes.RTP_TIMEOUT) but no re-connection logic called here.

Maybe the mac chrome browser itself is the problem here? Or the re-connection logic should be used in this RTP_TIMEOUT case?

**Comment by ibc** [comment]
There is nothing we can do at JsSIP to detect WebSocket disconnection before the browser reports it. And that depends on the kernel, TCP timeouts, etc etc.

However, I reported a similar problem years ago (it's supposed to be fixed, but cannot confirm how it currently behaves). Please, check this:

https://bugs.chromium.org/p/chromium/issues/detail?id=426798

I'll close this issue because there is nothing JsSIP can do to mitigate this issue.

**Comment by mdavid5** [comment]
Yes it should work correctly but it does not. One thing I can do here is to close the websocket manually.  Maybe jssip could do this automatically on RTP timeout. I'am doing that on the ended event handler:

ended: function(e){
  var endedNormally = e.cause == jssip.C.causes.BYE || e.cause == jssip.C.causes.CANCELED;
  if(!endedNormally)
      newRTCSession.ua.transport.socket.ws.close();
}

By doing this the re-connection logic handles the situation fine on chromium + mac too.

**Comment by jmillan** [comment]
Hi @mdavid5,

That logic may work for you and not for others. RTP timeout does not need to require a WS reconnection, and indeed it has nothing to do with WS. Use it if it freely if it works for you though.

On the other hand, if you would like to detect the WS connection failures before the browser does, then you can send periodic keep-alives on top of the WS connection as long as the WS server you're using can handle them. ie:

````JavaScript
ua.on('connected', function(){
    // Managing Client-Initiated Connections in the Session Initiation Protocol
    // https://tools.ietf.org/html/rfc5626#section-3.5.1
    keepalive = setInterval(function(){
      ua.transport.send('\r\n\r\n');
    }, frequency);
````

- Your WS server must ignore the keepalive or respond accordingly with a single CRLF, which JsSIP will ignore.
- In case the WS connection is dead, the corresponding JsSIP disconnection event will be fired when trying to send the keep-alive, then you can decide to re-connect or not

**Comment by ibc** [comment]
>  One thing I can do here is to close the websocket manually. Maybe jssip could do this automatically on RTP timeout.

Absolutely no.

Do it at your convenience if you wish. When a JsSIP  `RTCSession` is closed you get the exact closure cause it the corresponding callback, so feel free to close your entire app when that happens, but of course that's not something JsSIP will do by itself.
