### ISSUE TITLE
Parser is setting 'parsed' variable to undefined, then trying to find it's length.

### ISSUE THREAD

**Issue by joshfarrant** [versatica/JsSIP#404]
I've recently noticed a few errors coming from the Parser module.

```TypeError: Cannot read property 'length' of undefined```

It appears that [these](https://github.com/versatica/JsSIP/blob/master/lib/Parser.js#L94-L98) are the offending lines for most of these cases, however the same issue is repeated a few times in that module. The issue is as follows:

```
if (parsed === -1) {
  parsed = undefined;
}

length = parsed.length;
```

If `parsed` is set to `-1`, then it will be reassigned to `undefined`, and so will throw the above error when trying to read it's length.

I'd be happy to submit a PR to fix this issue if that would be beneficial.

**Comment by ibc** [comment]
A PR would be certainly appreciated. However I would prefer, first, to know where the error happens. Can you paste the SIP message producing the parsing error?

**Comment by joshfarrant** [comment]
Unfortunately not. The error was reported through internal error tracking and the trace doesn't include the received SIP message. I'll have a look into fixing the error and will get back to you with a PR shortly.

**Comment by ibc** [comment]
ok, thanks a lot

**Comment by jmillan** [comment]
Right, there's in fact a related issue already #386

**Comment by joshfarrant** [comment]
Ah, missed that one. I'll still have a look into fixing it.

**Comment by jmillan** [comment]
👍
