### ISSUE TITLE
3.0.0 stuck on confirmed

### ISSUE THREAD

**Issue by scgm11** [versatica/JsSIP#409]
Hi,

Im testing 3.0.0  just change from 2.X the configuration socket to -->

var socket = new JsSIP.WebSocketInterface(myendpoint);
 var configuration = {
        'sockets': [socket],
        'uri': 'sip:' + num + '@' + host,
        'password': pass,
        'session_timers': false
    };

if there is anything else to change maybe a breaking changes in the doc could be useful for people upgrading.

The call get stuck in confimed, attached log
[log.txt](https://github.com/versatica/JsSIP/files/604264/log.txt)

**Comment by ibc** [comment]
The 3.0.x API doc explains what has changed.

I don't know why your Asterisk is sending a BYE to your JsSIP after the call is confirmed, but that is not a bug in JsSIP. Please, check the logs in Asterisk.

**Comment by scgm11** [comment]
the bye is sent when I end the other side of the call, changing to 2.X branch works ok and 3.X not.
The call after I answer stays on Confirmed event Ringing.....

Documentation is the first place I go to check, I even check the code to see the changes, on the docs I found: Parameters removed from previous version (that goes nowhere), and a changes section was a suggestion so its easy to see what changes without comparing the docs. I may have missed some change and that is why is not working?

best regards

**Comment by ibc** [comment]
> the bye is sent when I end the other side of the call, changing to 2.X branch works ok and 3.X not.
The call after I answer stays on Confirmed event Ringing.....

Nothing has changed for that to suddenly fail. I see nothing wrong in the log, everything is correct.

Please describe in detail what the issue is. Telling that "the call get stuck in confirmed" is not enough.

**Comment by ibc** [comment]
BTW, this is probably due to an error in Asterisk (as the 99% of "JsSIP issues" reported here):

https://issues.asterisk.org/jira/browse/ASTERISK-24330

Assuming that `myendpoint` is a `wss://` URL, add a [contact_uri](http://jssip.net/documentation/3.0.x/api/ua_configuration_parameters/#parameter_contact_uri) to your `JsSIP.UA` settings as follows:

```js
{
  contact_uri : 'sip:SOME_USER@RANDOM_DOMAIN;transport=wss;ob>
}
```

It may work. However this is not something that has changed from 2.X to 3.X, so feel free to properly detail the issue.

**Comment by scgm11** [comment]
same behaviour.

I attach 3 logs 2 jssip 1001 and 1002 and then sip debug from asterisk.
asterisk 13.13.0-rc1 (tested on 2.X working ok) the only changes made from 2.0.5 is changing the UA configuration. I will try on Wednesday to analyze it further.








[asterisk.txt](https://github.com/versatica/JsSIP/files/604952/asterisk.txt)
[1002.txt](https://github.com/versatica/JsSIP/files/604953/1002.txt)
[1001.txt](https://github.com/versatica/JsSIP/files/604954/1001.txt)

**Comment by ibc** [comment]
Please. Detail the issue. I still don't know what it is so I don't know what "same behavior" means. I won't check any log if I don't really know what the problem is.

**Comment by ibc** [comment]
Also, Asterisk is an endpoint, not a proxy so try to reproduce the issue by just using an endpoint connected to Asterisk and try to send BYE from both the browser and Asterisk. That should reproduce the issue.
