### ISSUE TITLE
How get remote stream on 3.0.0

### ISSUE THREAD

**Issue by fxalgrain** [versatica/JsSIP#410]
Hello,

I m  trying to update to 3.0.0 but I have an issue to get the remote media. 

Previously, we get 'addStream' event but it was removed. 

So my question is : how to get the remote media stream now ?

Regards,

**Comment by ibc** [comment]
Please, questions in the mailing list. This is the bug tracker.

BTW: http://jssip.net/documentation/3.0.x/api/session/#attribute_connection

**Comment by fxalgrain** [comment]
Thanks. 
I found by myself.

**Comment by kachkaev** [comment]
@fxalgrain could you please share your solution? Same issue here.

**Comment by ibc** [comment]
@fxalgrain: http://jssip.net/documentation/3.0.x/api/session/#attribute_connection

**Comment by fxalgrain** [comment]
@kachkaev The connection is set on the session after we answer it. So we can do something like this


    session.answer({
        mediaConstraints: {
            audio: true,
            video: false
        }
    });

    session.connection.ontrack = function(e){
        var stream =  e.streams[0];
        //...
    };
