### ISSUE TITLE
addEventListener('addstream',...) is triggered in wrong place

### ISSUE THREAD

**Issue by MobiSciLab** [versatica/JsSIP#412]
According to the document, for incoming call, connection (instance of RTCPeerConnection) must wait for "accepted" event, however it is never called when I put below code in "accepted" callback, but it is ok when I put it right after answer():
**[Working]**
session.answer(options);
session.connection.addEventListener('addstream', (event) =>
{
	console.log("Debug: addstream............");
	views.remoteView.src = event.stream;
}); 

**[Not Working]**
session.on("accepted",
		function() {
		console.log("Debug: accepted....");
		session.connection.addEventListener('addstream', (event) =>
{
	console.log("Debug: addstream............");
	views.remoteView.src = event.stream;
}); 										
													
});

**Comment by ibc** [comment]
Good catch. We should probably recommend the `session.on('peerconnection')` event so the app can set event listeners into it **before** those events are fired.

Will fix it in two weeks (on vacation now).

**Comment by hkcoyant** [comment]
Try manage like this:

```
var callSession        = null;
var remoteView         = null;
var coolPhone          = null;

$(function(){
    remoteView = document.getElementById('remoteView');
    ph_init();
});

function ph_init() {
            coolPhone = new JsSIP.UA(configuration);
            coolPhone.start();
            setPhoneEventHandlers(coolPhone);
    }
}

function setPhoneEventHandlers(phone) {
   phone.on('newRTCSession', function(e){
               callSession = e.session;
   }
}

function ph_call(number) {
    coolPhone.call(number, callOption);
    ph_wrtc_manager();
}

function ph_answer() {
    callSession.answer(callOption);
    ph_wrtc_manager();
}

function ph_wrtc_manager() {
    callSession.connection.onaddstream = function(e) {
        console.log('MEDIA STREAM ADDED');
        remoteView.srcObject = e.stream;
    }
    ....
}
```

working weel for mi, testing in chrome, firefox and opera.
If you need see full code tell mi, good luck

**Comment by jmillan** [comment]
I definitely think too that the right place to set the connection callbacks is on `session.on('peerconnection')`.

**Comment by jmillan** [comment]
Added small description in the doc.
