### ISSUE TITLE
jssip-cordova

### ISSUE THREAD

**Issue by pguillem** [versatica/JsSIP#413]
Thanks for this amazing work!
I was wondering what happened to the jssip-cordova plugin?

**Comment by saghul** [comment]
The only reference I can find to such project is https://github.com/davies147/jssip-cordova, which is not maintained by the jsSIP authors.  jsSIP will work fine in cordova, as long as you use the iosrtc plugin: https://github.com/eface2face/cordova-plugin-iosrtc

**Comment by ibc** [comment]
Please don't waste developers' time. Do you really know why you ask or why you'd need for such a jssip-cordova plugin? It is just because, given its name, you assume it is needed for JsSIP run in cordova iOS, right?

**Comment by pguillem** [comment]
Hello. The reason I asked is I found an external git reference for "jssip-cordova" under the versatica tree, which appeared to have been deleted a while ago. 

No need to feel irritated.. it was just a quick and simple 10 second question.

Best. Pedro

**Comment by ibc** [comment]
Sorry, but there is a jssip public mailing list for questions and doubts. We want to keep github issues just for bug reports or pull requets.

**Comment by pguillem** [comment]
For your reference, here is the old link:
https://docs.omniref.com/js/npm/jssip-cordova/0.1.0

**Comment by ibc** [comment]
Just use cordova-plugin-iosrtc.

**Comment by pguillem** [comment]
Will do. 
Thanks for sharing some light on this!!
