### ISSUE TITLE
Repeated REGISTER requests after websocket disconnection and recovery

### ISSUE THREAD

**Issue by pg94au** [versatica/JsSIP#414]
It is currently possible, after a websocket disconnection and recovery, for JsSIP to send double REGISTER requests to the SIP server, where the first request has not yet received a reply.

The attached log snippet includes the following sequence of events:
1. REGISTER with matching OK (the last successful registration).
2. REGISTER with 401 response.
3. REGISTER with no response due to disconnection.
4. <Websocket transport disconnects and reconnects>
5. REGISTER sent.
6. REGISTER sent (CSeq incremented).

[JsSIP_repeated_registrations.txt](https://github.com/versatica/JsSIP/files/650397/JsSIP_repeated_registrations.txt)

**Comment by pg94au** [comment]
I have more info on this.  It was due to a misunderstanding on my part about the isRegistered() method with respect to auto re-registration.  As I see now, isRegistered() will return false while not registered immediately after a disconnection, even though re-registration will happen automatically.  In other words, the double registration was due to my code calling register upon receiving the connected event, when JsSIP was already going to attempt a reconnect on its own.

Having said that, should a call to register be ignored (or return an error) when the user agent is already either registered or in the process or registering?

**Comment by jmillan** [comment]
Thanks for the information @pg94au. Now you can prevent it to happen.

> Having said that, should a call to register be ignored (or return an error) when the user agent is already either registered

It's legitimate to re-register.

> or in the process or registering?

We should avoid sending a Register while there is an ongoing Register request. Lets keep the issue open until it's fixed.
