### ISSUE TITLE
Doesn't run on Node. (trying README example)

### ISSUE THREAD

**Issue by williamkapke** [versatica/JsSIP#415]
There are references to `window` in the 3.x.x code- does this no longer support node?

https://github.com/versatica/JsSIP/blob/0d6be044ed67d26a88a2f0b13e7a7e4cd3c417bb/lib/RTCSession.js#L249

**Comment by ibc** [comment]
> does this no longer support node?

Unfair question as you can not probe that JsSIP did run in Node **before**, right?

Node does not natively implement the WebRTC spec/API so, no, you cannot make "audio/video calls" with JsSIP running on Node.

However, you can use JsSIP within a Node app for SIP signaling purposes (REGISTER, MESSAGE, etc).

**Comment by williamkapke** [comment]
Ok. Sorry- didn't mean to be unfair :/

I'm new to JsSIP so I just saw the readme say "Runs in the browser and Node.js." and then I tried the example.

Thanks for the reply.

**Comment by ibc** [comment]
NP ;)
