### ISSUE TITLE
Issue in JsSIP instance creation

### ISSUE THREAD

**Issue by bhartichets005** [versatica/JsSIP#416]
Hi,

When i trying to run this code in javascript firstly i am getting an issue i.e. JsSIP not defined. So to use JsSIP.WebSocketInterface, how can i create instance for JsSIP in javascript ?

**Comment by jmillan** [comment]
This is not a bug.

If JsSIP is not defined then the issue is that you haven't loaded it. Check that.

Please use the mailing list for questions.

**Comment by bhartichets005** [comment]
Hi jmillan
Can you please help me to load JsSIP ?
I am bit confuse to add JsSIP on my page

**Comment by ibc** [comment]
Not here please.
