### ISSUE TITLE
Problems in chrome with iceTransportPolicy: 'relay'

### ISSUE THREAD

**Issue by martingerman81** [versatica/JsSIP#417]
Hi,

I am using jssip version 2.0.2 and when I have configured on the pcConfig iceTransportPolicy: 'relay' and also a turn server.
On firefox this work perfectly but on chrome haven't added the relay candidates only the host candidate.
Do you have any idea what is wrong?
Thanks.

BR,
  Martín.

**Comment by jmillan** [comment]
Not a JsSIP issue. Please use the mailing list.
