### ISSUE TITLE
SOCKET_STATUS_ERROR set or check in the wrong places

### ISSUE THREAD

**Issue by DKorablin** [versatica/JsSIP#418]
In function:

```js
function getSocket()
{
...
  this.sockets.forEach(function(socket) {
    if (socket.status === C.SOCKET_STATUS_ERROR) {
      return; // continue the array iteration
    }
...
}
````

status checked on 'weight' level { socket, weight, status }

But in function:

```js
function onDisconnect(error, code, reason) {
...
  // update socket status
  if (error) {
    this.socket.status = C.SOCKET_STATUS_ERROR;
  }
...
}
```

socket status updated at 'WebSocketInterface' level {sip_uri, url, via_transport,...}

Thats why check code in fucntion getSocket (socket.status === C.SOCKET_STATUS_ERROR) will newer be set to true.

How to test:

```js
var invalidServer = new JsSIP.WebSocketInterface('wss://unregisteredServer.zzz');
var enabledServer = new JsSIP.WebSocketInterface('wss://sip.example.com');
var configuration = {
  sockets : [ { socket: invalidServer, weight: 2 }, { socket: enabledServer, weight: 1 } ],
  uri     : 'sip:alice@example.com',
  ha1     : '350fe29ce3890bd85d105998b0a95cf7',
  realm   : 'sip.example.com'
};

var ua = new JsSIP.UA(configuration);
```

**Comment by brianjones-v4n** [comment]
We are struggling this this same issue.  If the primary wss server is down, the reconnect will not drop to the second or third option.

**Comment by jmillan** [comment]
Thanks for reporting. It will be fixes as soon as possible.

**Comment by ibc** [comment]
jssip 3.0.2, which includes the fix for this issue, is out.
