### ISSUE TITLE
What is the correct way to handle stream modifications in jssip v3.0.1?

### ISSUE THREAD

**Issue by vadirn** [versatica/JsSIP#420]
Currently I am using the following method of replacing mediaStream in order to swap between front/back cameras:

```javascript

// 1. stop current mediaStream tracks
// ...

// 2. getUserMedia with particular videoinput id passed in constraints, newMediaStream is the result
// ...

// 3. remove local streams from connection:
session.connection.getLocalStreams().forEach((stream) => {
  session.connection.removeStream(stream);
});

// 4. add new stream to connection
session.connection.addStream(newMediaStream);

// 5. handle negotiationneeded event
session.connection.onnegotiationneeded = () => {
  if (session.connection.localDescription.type === 'offer') {
     session.connection.createOffer().then((offer) => session.connection.setLocalDescription(offer))
            .then(() => {
              // set srcObject for video html elements, that represent local and remote video streams
            })
            .catch((e) => {
              console.log(e);
            });
          }
}
```

Unfortunately in some cases this leads to missing remote stream, sometimes it helps to swap cameras a couple of times and remote stream reappears.

**Comment by ibc** [comment]
1. Mangle your `RTCPeerConnection` (add streams, remove them, etc) as desired by accessing `session.connection`.
1. Call `session.renegotiate()` as documented in the JsSIP API.

**Comment by vineetStartele** [comment]
i use session.connection method at client side but it give me error

**Comment by vineetStartele** [comment]
> 1. Mangle your `RTCPeerConnection` (add streams, remove them, etc) as desired by accessing `session.connection`.
> 2. Call `session.renegotiate()` as documented in the JsSIP API.
 i used session.connection at client side but it give me error
