### ISSUE TITLE
Add event to know when RTCPeerConnection has been created

### ISSUE THREAD

**Issue by lopezdonaque** [versatica/JsSIP#421]
It's necessary to listen events like "iceconnectionstatechange", "addstream", etc. just after created.
The current "peerconnection" event is fired after call to "self.connection.addStream(stream);" so "addstream" event is already fired.

You could move "self.emit('peerconnection', { peerconnection: self.connection });" into "createRTCConnection" method.

**Comment by ibc** [comment]
Makes sense. However, my personal preference is moving to a complete SIP-WebRTC decoupled design, as noted in #427.

Anyhow, after the `peerconnection` event you can check the current `pc.iceConnectionState` and `pc.getRemoteStreams()` via the `session.connection` member (which points to the underlying `RTCPeerConnection`. In addition you can set your listeners in that moment.

**Comment by jmillan** [comment]
Hi,

@ibc, I would also add the 'peerconnection' event inside 'RTCSession::createRTCConnection', just for code cleanliness. Do you think this would have any side effect on any implementation? I can make the change in a minute.

**Comment by ibc** [comment]
It makes sense

**Comment by jmillan** [comment]
Working on es6 branch. Will add this once it's merged.

**Comment by omidkh68** [comment]
> Working on es6 branch. Will add this once it's merged.

where is es6 branch?
I can't find it.

**Comment by ibc** [comment]
> > Working on es6 branch. Will add this once it's merged.
> 
> 
> 
> where is es6 branch?
> 
> I can't find it.
> 
> 

It was done 4 years ago and merged into master branch.

**Comment by omidkh68** [comment]
> > > Working on es6 branch. Will add this once it's merged.
> > 
> > 
> > where is es6 branch?
> > I can't find it.
> 
> It was done 4 years ago and merged into master branch.

🤦🏻‍♂️ 👍🏽
