### ISSUE TITLE
Will you accept a pull-request to have jssip call a callback to get a new secret every time it registers?

### ISSUE THREAD

**Issue by elbow** [versatica/JsSIP#422]
Hi,

Since its hard to keep a password secret we want to use ephemeral "one-time" passwords when our client code needs one.  So the idea is that we want to be able to pass a "hook" function such that when Registrator is about to re-register it will call this hook and only then (on a further callback) execute the register.

In our application the callback function would call our server-side to make a new password.  The backend saves this password to authenticate the register, and sends it back in jssip to be used from the jssip side.

Others may have other ideas as to how to use such a hook.

Would you accept a pull request for a change like this?

Thanks,
Steve

**Comment by jmillan** [comment]
Hi,

JsSIP already allows resetting certain configuration attributes. See [doc].(http://jssip.net/documentation/3.0.x/api/ua/#method_set)

You can perfectly retrieve the new password by whatever means, reset it and re-register the UA via `UA.register()` method.
