### ISSUE TITLE
Remove 'pranswer' stuff

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#428]
`pranswer` does not work in current browsers and, in fact, it seems that it may be removed from the spec so no vendor will try to fix it.

The [pranswer WebRTC demo](https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/) does not even work in Chrome, and it fail in Firefox ("pranswer not implemented"). Also, lot of related bug reports in Chrome regarding this subject, such as:

* https://bugs.chromium.org/p/webrtc/issues/detail?id=3349

It's clear that JsSIP must avoid using `pranswer`. If a 180/183 with SDP arrives, we must call `setRemoteDescription()` with type `answer` and, later when the 200 arrives with a SDP answer:

1. `pc.createOffer()` => `offer`
1. `pc.setLocalDescription(offer)`
1. `pc.setRemoteDescription(answer)`

**Comment by ibc** [comment]
Please Александр, test your scenario with the [no-pranswer](https://github.com/versatica/JsSIP/tree/no-pranswer) branch.

Just follow the [BUILDING](https://github.com/versatica/JsSIP/blob/master/BUILDING.md) steps modified as follows:

```bash
$ git clone https://github.com/versatica/JsSIP.git JsSIP
$ cd JsSIP
$ git checkout no-pranswer
```

**Comment by Pechenn** [comment]
Works! It works!
Have an error at log (Uncaught (in promise) TypeError: Cannot read property 'signalingState' of undefined
    at jssip.js:15892) but everything is works!

**Comment by ibc** [comment]
There was a typo. Please, update (`git pull`), build it again, and test again.

BTW: Probably the early media works even with the typo, but later you should have issues when the 200 OK arrives, right?

**Comment by Pechenn** [comment]
strange i have rebuild it and replace but this error still appears at 200.
i hear playback before and after answer so everything looks fine --(I do not check outgoing media)

**Comment by ibc** [comment]
> strange i have rebuild it and replace but this error still appears at 200.

Have you run `gulp`? I didn't in my last commit so the error was not fixed in the bundled file under `dist/`.

**Comment by ibc** [comment]
BTW bundled updated in the branch right now.

**Comment by Pechenn** [comment]
Yeah now at last test(after pull and rebuild) everything was fine. no any errors were appear.

**Comment by ibc** [comment]
Great, will merge into master and release a new version. Thanks for testing!

**Comment by Pechenn** [comment]
and you)

**Comment by ibc** [comment]
JsSIP 3.0.6 is out :)
