### ISSUE TITLE
UA disconnected event error flag is incorrect

### ISSUE THREAD

**Issue by nicketson** [versatica/JsSIP#431]
According to the documentation [here](http://jssip.net/documentation/3.0.x/api/ua/#event_disconnected), when the UA fires the disconnected event, an error flag should be set.

When this event is fired due to an abrupt WebSocket disconnect, the error flag is set to false. Shouldn't the e.wasClean argument in [WebSocketInteface.js onClose function](https://github.com/versatica/JsSIP/blob/master/lib/WebSocketInterface.js#L130) be negated?

`this.ondisconnect(!e.wasClean, e.code, e.reason);`

**Comment by ibc** [comment]
Please, use the public mailing list for questions.

`e.wasClean` is set by the browser itself, and it values depends on the WS disconnection type. JsSIP doe snot mangle/override it.

**Comment by nicketson** [comment]
I understand that e.wasClean is set by the browser.

The logic is incorrect. In the WebSocket's onClose handler, wasClean will be set to FALSE if the socket was closed abnormally. This is being passed as the "error" argument to the WebSocketInterface's ondisconnected handler. The result is that the UA generated disconnected events which have the "error" event data property set to FALSE when an error has occurred.

**Comment by ibc** [comment]
Thanks @nicketson. It is fixed in 3.0.7.
BTW take into account that now, the  UA's `disconnected` event as a single `data` argument which is an object (as the doc you pointed above states).

**Comment by nicketson** [comment]
Thank you. Last version we were using was 0.7.4. JsSIP has really improved!
