### ISSUE TITLE
happens 'icecandidate' never call with event.candidate=false

### ISSUE THREAD

**Issue by barmoleg** [versatica/JsSIP#433]
function createSucceeded(desc) {
    var listener;
    connection.addEventListener('icecandidate', listener = function(event) {
      var candidate = event.candidate;
      if (! candidate) { //-- Never happens

may be use promise?

**Comment by svarunan** [comment]
event.candidate will not be false, last event's candidate will be `undefined` when ice gathering is completed. 
I feel you might also be seeing issues like in https://github.com/versatica/JsSIP/issues/432

**Comment by ibc** [comment]
@barmoleg as you may check, JsSIP does not remove/mangle listeners given to the underlying peerconnection:

https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.js#L1544

JsSIP uses adapter.js, but AFAIS such a library neither:

https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js

So, if `candidate` is never falsy/undefined/null, that's out of the scope of JsSIP and it's just a pure native `RTCPeerConnection` subject.
