### ISSUE TITLE
Asterisk and Chrome 57

### ISSUE THREAD

**Issue by bleuscyther** [versatica/JsSIP#434]
After the latest chrome update jsSIP calls are failing.

> setRemoteDescriptionOnFailure
> **Failed to set remote answer sdp: Session error code: ERROR_CONTENT. Session error description: rtcpMuxPolicy is 'require', but media description does not contain 'a=rtcp-mux'..**
> Stats Tables
> googTrack_0476d349-021f-42f5-ad02-2c0a2e2e0bec (googTrack)
> googLibjingleSession_8061029230695182849 (googLibjingleSession)
> googCertificate_7B:31:A5:A9:CF:B7:57:EA:45:90:44:14:32:4F:D3:D7:EF:C8:AC:B3:38:3F:37:3E:2F:C1:E8:62:91:83:B9:0D (googCertificate)
> Channel-audio-1 (googComponent)
> ssrc_1177667937_send (ssrc)
> Stats graphs for ssrc_1177667937_send (audio)

This issue has been reported by others : 
- https://github.com/voxbone-workshop/webrtc-js/issues/54
- https://groups.google.com/forum/#!topic/jssip/zSrG0O3T2To
- https://nimblea.pe/monkey-business/2017/01/19/webrtc-asterisk-and-chrome-57/

and a fix has been proposed

```javascript
let sip = new JsSIP.UA( _config_ );
sip.call({
      ...
     pcConfig: {rtcpMuxPolicy: 'negotiate'}.
      ...
}}

```

My concern is that the browser throws this deprecation warning :

> rtcpMuxPolicy option is being considered for removal and may be removed no earlier than M60

reference to that here : 

- https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/OP2SGSWF5lo/discussion
- http://stackoverflow.com/questions/42688499/sipml5-negotiate-rtcpmuxpolicy

I post this here as a reference for other devs who have the problem and maybe if a patch is necessary after that .

**Comment by ibc** [comment]
> I post this here as a reference for other devs who have the problem and maybe if a patch is necessary after that .

A patch where? this is an open issue/limitation in Asterisk which does not support `rtcp-mux`.

**Comment by scgm11** [comment]
asterisk 13.15 comes with rtcpmux check:

chan_sip:
https://issues.asterisk.org/jira/browse/ASTERISK-26846

and 
chan_pjsip:

https://issues.asterisk.org/jira/browse/ASTERISK-26732

**Comment by ibc** [comment]
Nice to know. Thanks.

I will close this issue since it's not an issue in JsSIP at all, and I don't want to keep an open issue just to warn developers about a limitation in Asterisk.
