### ISSUE TITLE
1090 Call 1085 Answer the phone appears flashing

### ISSUE THREAD

**Issue by fsungzyl** [versatica/JsSIP#435]
The following is the log：

jssip.js:21591 JsSIP:WebSocketInterface new() [url:"ws://192.168.1.96:5066"] +0ms
jssip.js:21591 JsSIP:UA new() [configuration:Object] +14ms
jssip.js:21591 JsSIP:Transport new() +4ms
jssip.js:21591 JsSIP:UA configuration parameters after validation: +0ms
jssip.js:21591 JsSIP:UA - via_host: "o9a1ce4nm4mi.invalid" +0ms
jssip.js:21591 JsSIP:UA - contact_uri: {"parameters":{"transport":"ws"},"headers":{}} +0ms
jssip.js:21591 JsSIP:UA - password: NOT SHOWN +0ms
jssip.js:21591 JsSIP:UA - realm: null +0ms
jssip.js:21591 JsSIP:UA - ha1: NOT SHOWN +0ms
jssip.js:21591 JsSIP:UA - register_expires: 600 +0ms
jssip.js:21591 JsSIP:UA - register: true +0ms
jssip.js:21591 JsSIP:UA - registrar_server: sip:192.168.1.96 +1ms
jssip.js:21591 JsSIP:UA - use_preloaded_route: false +0ms
jssip.js:21591 JsSIP:UA - no_answer_timeout: 60000 +0ms
jssip.js:21591 JsSIP:UA - session_timers: true +0ms
jssip.js:21591 JsSIP:UA - uri: sip:1090@192.168.1.96 +0ms
jssip.js:21591 JsSIP:UA - display_name: "User1" +0ms
jssip.js:21591 JsSIP:UA - instance_id: "6eff355e-a550-4b7b-a918-ce25ef37a701" +0ms
jssip.js:21591 JsSIP:UA - jssip_id: "qts0m" +0ms
jssip.js:21591 JsSIP:UA - hostport_params: "192.168.1.96" +0ms
jssip.js:21591 JsSIP:UA - authorization_user: "1090" +0ms
jssip.js:21591 JsSIP:UA start() +1ms
jssip.js:21591 JsSIP:Transport connect() +0ms
jssip.js:21591 JsSIP:WebSocketInterface connect() +0ms
jssip.js:21591 JsSIP:WebSocketInterface connecting to WebSocket ws://192.168.1.96:5066 +1ms
jssip.js:21591 JsSIP:WebSocketInterface WebSocket ws://192.168.1.96:5066 connected +25ms
jssip.js:21591 JsSIP:Transport send() +5ms
jssip.js:21591 JsSIP:Transport sending message:

REGISTER sip:192.168.1.96 SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK8842428
Max-Forwards: 69
To: <sip:1090@192.168.1.96>
From: "User1" <sip:1090@192.168.1.96>;tag=op8dkn0q9f
Call-ID: sm9fn6agovv0v9sjamu8kc
CSeq: 1 REGISTER
Contact: <sip:4u62q9h6@o9a1ce4nm4mi.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:6eff355e-a550-4b7b-a918-ce25ef37a701>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: path,gruu,outbound
User-Agent: JsSIP 3.0.4
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +204ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK8842428;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=op8dkn0q9f
To: <sip:1090@192.168.1.96>;tag=e57y8DjK8NvtQ
Call-ID: sm9fn6agovv0v9sjamu8kc
CSeq: 1 REGISTER
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
WWW-Authenticate: Digest realm="192.168.1.96", nonce="71a33ca8-c8f4-4212-8efe-6051ac8d23cd", algorithm=MD5, qop="auth"
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:DigestAuthentication authenticate() | response generated +10ms
jssip.js:21591 JsSIP:Transport send() +1ms
jssip.js:21591 JsSIP:Transport sending message:

REGISTER sip:192.168.1.96 SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1440592
Max-Forwards: 69
To: <sip:1090@192.168.1.96>
From: "User1" <sip:1090@192.168.1.96>;tag=op8dkn0q9f
Call-ID: sm9fn6agovv0v9sjamu8kc
CSeq: 2 REGISTER
Authorization: Digest algorithm=MD5, username="1090", realm="192.168.1.96", nonce="71a33ca8-c8f4-4212-8efe-6051ac8d23cd", uri="sip:192.168.1.96", response="08569f4b76599cd365f6d2898cc5ed92", qop=auth, cnonce="guk481743eg4", nc=00000001
Contact: <sip:4u62q9h6@o9a1ce4nm4mi.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:6eff355e-a550-4b7b-a918-ce25ef37a701>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: path,gruu,outbound
User-Agent: JsSIP 3.0.4
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +12ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1440592;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=op8dkn0q9f
To: <sip:1090@192.168.1.96>;tag=Fe1Qa92p5yjDK
Call-ID: sm9fn6agovv0v9sjamu8kc
CSeq: 2 REGISTER
Contact: <sip:4u62q9h6@o9a1ce4nm4mi.invalid;transport=ws>;expires=600
Date: Fri, 07 Apr 2017 09:28:34 GMT
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:UA call() +3ms
jssip.js:21591 JsSIP:RTCSession new +0ms
jssip.js:21591 JsSIP:RTCSession connect() +1ms
jssip.js:21591 JsSIP:RTCSession newRTCSession() +7ms
jssip.js:21591 JsSIP:RTCSession emit "peerconnection" +11ms
jssip.js:21591 JsSIP:RTCSession session connecting +0ms
jssip.js:21591 JsSIP:RTCSession emit "connecting" +0ms
jssip.js:21591 JsSIP:RTCSession createLocalDescription() +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +25ms
jssip.js:21591 JsSIP:Transport received text message:

NOTIFY sip:4u62q9h6@o9a1ce4nm4mi.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WS 192.168.1.96:5066;branch=z9hG4bKagUFp5yHFKQem
Route: <sip:4u62q9h6@192.168.1.122:56374>;transport=ws
Max-Forwards: 70
From: <sip:1090@192.168.1.96>;tag=gQtgc4Kt278Ze
To: <sip:1090@192.168.1.96>
Call-ID: 698bf7bb-9617-1235-adb0-000c296e460f
CSeq: 105442593 NOTIFY
Contact: <sip:mod_sofia@192.168.1.96:5060>
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Event: message-summary
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Subscription-State: terminated;reason=noresource
Content-Type: application/simple-message-summary
Content-Length: 91

Messages-Waiting: yes
Message-Account: sip:1090@192.168.1.96
Voice-Message: 4/0 (0/0)

 +0ms
jssip.js:21591 JsSIP:Transport send() +1ms
jssip.js:21591 JsSIP:Transport sending message:

SIP/2.0 405 Method Not Allowed
Via: SIP/2.0/WS 192.168.1.96:5066;branch=z9hG4bKagUFp5yHFKQem
To: <sip:1090@192.168.1.96>;tag=6s6r98inje
From: <sip:1090@192.168.1.96>;tag=gQtgc4Kt278Ze
Call-ID: 698bf7bb-9617-1235-adb0-000c296e460f
CSeq: 105442593 NOTIFY
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: outbound
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:NonInviteServerTransaction Timer J expired for transaction z9hG4bKagUFp5yHFKQem +5ms
jssip.js:21591 JsSIP:RTCSession emit "sdp" +139ms
jssip.js:21591 JsSIP:RTCSession emit "sending" [request:OutgoingRequest] +0ms
jssip.js:21591 JsSIP:Transport send() +0ms
jssip.js:21591 JsSIP:Transport sending message:

INVITE sip:1085@192.168.1.96:5066 SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1636360
Max-Forwards: 69
To: <sip:1085@192.168.1.96:5066>
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6715 INVITE
X-Foo: foo
X-Bar: bar
Contact: <sip:4u62q9h6@o9a1ce4nm4mi.invalid;transport=ws;ob>
Content-Type: application/sdp
Session-Expires: 120
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: timer,ice,replaces,outbound
User-Agent: JsSIP 3.0.4
Content-Length: 2082

v=0
o=- 4329551263815296114 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS HQmvRgF624oiwpWqnKlcRmWB199sy6uDcYQn
m=audio 53782 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 192.168.1.122
a=rtcp:53784 IN IP4 192.168.1.122
a=candidate:2796479375 1 udp 2122255103 2001::9d38:6ab8:805:c216:250e:46c 53781 typ host generation 0 network-id 2 network-cost 50
a=candidate:1668076467 1 udp 2122194687 192.168.1.122 53782 typ host generation 0 network-id 1
a=candidate:2796479375 2 udp 2122255102 2001::9d38:6ab8:805:c216:250e:46c 53783 typ host generation 0 network-id 2 network-cost 50
a=candidate:1668076467 2 udp 2122194686 192.168.1.122 53784 typ host generation 0 network-id 1
a=candidate:3895271295 1 tcp 1518275327 2001::9d38:6ab8:805:c216:250e:46c 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:770649923 1 tcp 1518214911 192.168.1.122 9 typ host tcptype active generation 0 network-id 1
a=candidate:3895271295 2 tcp 1518275326 2001::9d38:6ab8:805:c216:250e:46c 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:770649923 2 tcp 1518214910 192.168.1.122 9 typ host tcptype active generation 0 network-id 1
a=ice-ufrag:QVHj
a=ice-pwd:6VAiPn1GIExf8vTCSzL2/vOC
a=fingerprint:sha-256 FE:29:4F:D5:3F:A6:0C:80:78:FB:66:A5:D6:92:41:DB:BE:BA:88:38:FC:27:F6:04:78:AE:54:56:9B:FF:D0:10
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=ssrc:3642304460 cname:QMbyDNoZDpjjB1in
a=ssrc:3642304460 msid:HQmvRgF624oiwpWqnKlcRmWB199sy6uDcYQn ccf3eebe-794d-4d68-bbd5-acedfb71a120
a=ssrc:3642304460 mslabel:HQmvRgF624oiwpWqnKlcRmWB199sy6uDcYQn
a=ssrc:3642304460 label:ccf3eebe-794d-4d68-bbd5-acedfb71a120

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +15ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1636360;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
To: <sip:1085@192.168.1.96:5066>
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6715 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:RTCSession receiveInviteResponse() +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +0ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1636360;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
To: <sip:1085@192.168.1.96:5066>;tag=H0K9DZ4XZgZja
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6715 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Proxy-Authenticate: Digest realm="192.168.1.96", nonce="e5dc621d-358d-4e5d-9400-2f973d3fa768", algorithm=MD5, qop="auth"
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:Transport send() +0ms
jssip.js:21591 JsSIP:Transport sending message:

ACK sip:1085@192.168.1.96:5066 SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1636360
To: <sip:1085@192.168.1.96:5066>;tag=H0K9DZ4XZgZja
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6715 ACK
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:DigestAuthentication authenticate() | response generated +0ms
jssip.js:21591 JsSIP:Transport send() +0ms
jssip.js:21591 JsSIP:Transport sending message:

INVITE sip:1085@192.168.1.96:5066 SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK4736293
Max-Forwards: 69
To: <sip:1085@192.168.1.96:5066>
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6716 INVITE
Proxy-Authorization: Digest algorithm=MD5, username="1090", realm="192.168.1.96", nonce="e5dc621d-358d-4e5d-9400-2f973d3fa768", uri="sip:1085@192.168.1.96:5066", response="65ba32a38bcda01cc6321ac3c741ccaa", qop=auth, cnonce="u7feshvu0bfc", nc=00000001
X-Foo: foo
X-Bar: bar
Contact: <sip:4u62q9h6@o9a1ce4nm4mi.invalid;transport=ws;ob>
Content-Type: application/sdp
Session-Expires: 120
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: timer,ice,replaces,outbound
User-Agent: JsSIP 3.0.4
Content-Length: 2082

v=0
o=- 4329551263815296114 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS HQmvRgF624oiwpWqnKlcRmWB199sy6uDcYQn
m=audio 53782 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 192.168.1.122
a=rtcp:53784 IN IP4 192.168.1.122
a=candidate:2796479375 1 udp 2122255103 2001::9d38:6ab8:805:c216:250e:46c 53781 typ host generation 0 network-id 2 network-cost 50
a=candidate:1668076467 1 udp 2122194687 192.168.1.122 53782 typ host generation 0 network-id 1
a=candidate:2796479375 2 udp 2122255102 2001::9d38:6ab8:805:c216:250e:46c 53783 typ host generation 0 network-id 2 network-cost 50
a=candidate:1668076467 2 udp 2122194686 192.168.1.122 53784 typ host generation 0 network-id 1
a=candidate:3895271295 1 tcp 1518275327 2001::9d38:6ab8:805:c216:250e:46c 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:770649923 1 tcp 1518214911 192.168.1.122 9 typ host tcptype active generation 0 network-id 1
a=candidate:3895271295 2 tcp 1518275326 2001::9d38:6ab8:805:c216:250e:46c 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:770649923 2 tcp 1518214910 192.168.1.122 9 typ host tcptype active generation 0 network-id 1
a=ice-ufrag:QVHj
a=ice-pwd:6VAiPn1GIExf8vTCSzL2/vOC
a=fingerprint:sha-256 FE:29:4F:D5:3F:A6:0C:80:78:FB:66:A5:D6:92:41:DB:BE:BA:88:38:FC:27:F6:04:78:AE:54:56:9B:FF:D0:10
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=ssrc:3642304460 cname:QMbyDNoZDpjjB1in
a=ssrc:3642304460 msid:HQmvRgF624oiwpWqnKlcRmWB199sy6uDcYQn ccf3eebe-794d-4d68-bbd5-acedfb71a120
a=ssrc:3642304460 mslabel:HQmvRgF624oiwpWqnKlcRmWB199sy6uDcYQn
a=ssrc:3642304460 label:ccf3eebe-794d-4d68-bbd5-acedfb71a120

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:InviteClientTransaction Timer D expired for transaction z9hG4bK1636360 +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +24ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK4736293;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
To: <sip:1085@192.168.1.96:5066>
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6716 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:RTCSession receiveInviteResponse() +2ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +15ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 183 Session Progress
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK4736293;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
To: <sip:1085@192.168.1.96:5066>;tag=j9c2FtN1vSN5N
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6716 INVITE
Contact: <sip:1085@192.168.1.96:5060;transport=udp>
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 879
Remote-Party-ID: "1085" <sip:1085@192.168.1.96>;party=calling;privacy=off;screen=no

v=0
o=FreeSWITCH 1491538062 1491538063 IN IP4 192.168.1.96
s=FreeSWITCH
c=IN IP4 192.168.1.96
t=0 0
a=msid-semantic: WMS Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8N
m=audio 19252 UDP/TLS/RTP/SAVPF 111 126
a=rtpmap:111 opus/48000/2
a=fmtp:111 useinbandfec=1; minptime=10
a=rtpmap:126 telephone-event/8000
a=ptime:20
a=fingerprint:sha-256 74:A7:09:1B:72:E8:EA:71:E9:94:1A:C2:63:A4:C5:6E:E4:D8:ED:C0:7A:6B:FF:EB:19:31:85:AB:9C:19:19:92
a=setup:active
a=rtcp-mux
a=rtcp:19252 IN IP4 192.168.1.96
a=ice-ufrag:kkhWCIUfvIujnsW5
a=ice-pwd:qH2sV8VJpoIB68chjj4LRORd
a=candidate:8226848498 1 udp 659136 192.168.1.96 19252 typ host generation 0
a=end-of-candidates
a=ssrc:955570626 cname:S7V6bogCXqD8mSAL
a=ssrc:955570626 msid:Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8N a0
a=ssrc:955570626 mslabel:Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8N
a=ssrc:955570626 label:Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8Na0

 +0ms
jssip.js:21591 JsSIP:RTCSession receiveInviteResponse() +0ms
jssip.js:21591 JsSIP:Dialog new UAC dialog created with status EARLY +0ms
jssip.js:21591 JsSIP:RTCSession session progress +0ms
jssip.js:21591 JsSIP:RTCSession emit "progress" +0ms
index.html:53 call is in progress
jssip.js:21591 JsSIP:RTCSession emit "sdp" +0ms
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +9s
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK4736293;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
To: <sip:1085@192.168.1.96:5066>;tag=j9c2FtN1vSN5N
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6716 INVITE
Contact: <sip:1085@192.168.1.96:5060;transport=udp>
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Require: timer
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Session-Expires: 120;refresher=uac
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 879
Remote-Party-ID: "Outbound Call" <sip:1085@192.168.1.96>;party=calling;privacy=off;screen=no

v=0
o=FreeSWITCH 1491538062 1491538063 IN IP4 192.168.1.96
s=FreeSWITCH
c=IN IP4 192.168.1.96
t=0 0
a=msid-semantic: WMS Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8N
m=audio 19252 UDP/TLS/RTP/SAVPF 111 126
a=rtpmap:111 opus/48000/2
a=fmtp:111 useinbandfec=1; minptime=10
a=rtpmap:126 telephone-event/8000
a=ptime:20
a=fingerprint:sha-256 74:A7:09:1B:72:E8:EA:71:E9:94:1A:C2:63:A4:C5:6E:E4:D8:ED:C0:7A:6B:FF:EB:19:31:85:AB:9C:19:19:92
a=setup:active
a=rtcp-mux
a=rtcp:19252 IN IP4 192.168.1.96
a=ice-ufrag:kkhWCIUfvIujnsW5
a=ice-pwd:qH2sV8VJpoIB68chjj4LRORd
a=candidate:8226848498 1 udp 659136 192.168.1.96 19252 typ host generation 0
a=end-of-candidates
a=ssrc:955570626 cname:S7V6bogCXqD8mSAL
a=ssrc:955570626 msid:Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8N a0
a=ssrc:955570626 mslabel:Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8N
a=ssrc:955570626 label:Ze8ineDkBJjak5oCzCTGMsA7NXYoXO8Na0

 +0ms
jssip.js:21591 JsSIP:RTCSession receiveInviteResponse() +55ms
jssip.js:21591 JsSIP:Dialog dialog qts0mnhjmk1ilp53si3u30d73n7aq9j9c2FtN1vSN5N  changed to CONFIRMED state +1ms
jssip.js:21591 JsSIP:RTCSession emit "sdp" +1ms
jssip.js:21591 JsSIP:RTCSession session accepted +5ms
jssip.js:21591 JsSIP:RTCSession emit "accepted" +0ms
jssip.js:21591 JsSIP:RTCSession sendRequest() +1ms
jssip.js:21591 JsSIP:RTCSession:Request new | ACK +0ms
jssip.js:21591 JsSIP:Transport send() +3ms
jssip.js:21591 JsSIP:Transport sending message:

ACK sip:1085@192.168.1.96:5060;transport=udp SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK6572961
Max-Forwards: 69
To: <sip:1085@192.168.1.96:5066>;tag=j9c2FtN1vSN5N
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6716 ACK
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: outbound
User-Agent: JsSIP 3.0.4
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +1ms
jssip.js:21591 JsSIP:RTCSession session confirmed +0ms
jssip.js:21591 JsSIP:RTCSession emit "confirmed" +1ms
jssip.js:26701 URL.createObjectURL(stream) is deprecated! Use elem.srcObject = stream instead!
jssip.js:21591 JsSIP:RTCSession acceptAndTerminate() +1ms
jssip.js:21591 JsSIP:RTCSession sendRequest() +0ms
jssip.js:21591 JsSIP:RTCSession:Request new | ACK +0ms
jssip.js:21591 JsSIP:Transport send() +1ms
jssip.js:21591 JsSIP:Transport sending message:

ACK sip:1085@192.168.1.96:5060;transport=udp SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK1536116
Max-Forwards: 69
To: <sip:1085@192.168.1.96:5066>;tag=j9c2FtN1vSN5N
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6716 ACK
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: outbound
User-Agent: JsSIP 3.0.4
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:WebSocketInterface send() +1ms
jssip.js:21591 JsSIP:RTCSession sendRequest() +0ms
jssip.js:21591 JsSIP:RTCSession:Request new | BYE +1ms
jssip.js:21591 JsSIP:Transport send() +1ms
jssip.js:21591 JsSIP:Transport sending message:

BYE sip:1085@192.168.1.96:5060;transport=udp SIP/2.0
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK6428023
Max-Forwards: 69
To: <sip:1085@192.168.1.96:5066>;tag=j9c2FtN1vSN5N
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6717 BYE
Reason: SIP ;cause=488; text="Not Acceptable Here"
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: outbound
User-Agent: JsSIP 3.0.4
Content-Length: 0

 +1ms
jssip.js:21591 JsSIP:WebSocketInterface send() +0ms
jssip.js:21591 JsSIP:RTCSession session failed +1ms
jssip.js:21591 JsSIP:RTCSession close() +0ms
jssip.js:21591 JsSIP:RTCSession emit "failed" +1ms
index.html:54 call failed with cause: undefined
jssip.js:21770 JsSIP:ERROR:RTCSession emit "peerconnection:setremotedescriptionfailed" [error:TypeError: Cannot set property 'src' of null
    at RTCSession.confirmed (index.html:58)
    at RTCSession.EventEmitter.emit (jssip.js:21941)
    at RTCSession.confirmed (jssip.js:16459)
    at jssip.js:15899] +0ms
debug @ jssip.js:21770
(anonymous) @ jssip.js:15905
jssip.js:21591 JsSIP:WebSocketInterface received WebSocket message +13ms
jssip.js:21591 JsSIP:Transport received text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS o9a1ce4nm4mi.invalid;branch=z9hG4bK6428023;received=192.168.1.122;rport=56374
From: "User1" <sip:1090@192.168.1.96>;tag=30d73n7aq9
To: <sip:1085@192.168.1.96:5066>;tag=j9c2FtN1vSN5N
Call-ID: qts0mnhjmk1ilp53si3u
CSeq: 6717 BYE
User-Agent: FreeSWITCH-mod_sofia/1.6.12+git~20161011T134956Z~b91a0a6f2b~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Content-Length: 0

 +0ms
jssip.js:21591 JsSIP:RTCSession:Request onSuccessResponse +1ms

**Comment by ibc** [comment]
Please use the public jssip mailing list for questions and explain in there what the problem is (phone flashing is not descriptive).

**Comment by fsungzyl** [comment]
What do you mean?

**Comment by fsungzyl** [comment]
After the answer to the phone immediately hang up the situation
