### ISSUE TITLE
Not registering with Asterisk

### ISSUE THREAD

**Issue by tedd77** [versatica/JsSIP#438]
Hello,
I have tried to configure with Asterisk 13.14 , it mentions registered and then immediately unregistered.
The weird thing is that I still can make outgoing calls. 
I know it is something to do with the protocol or some hack_in_xx but sadly I cannot find the solution.
Thank you for your help.

**Comment by ibc** [comment]
Usage questions in the mailing list, please.

**Comment by tedd77** [comment]
Sure thank you.
Could you please let me know where to find the mailing list?

**Comment by ibc** [comment]
In the front page of jssip.net, in the README of the project in GitHub, and in Google by looking for "jssip mailing list". Did you actually tried to look for it?

**Comment by tedd77** [comment]
I did post on the mailing list. 
I could find it. Thank you
I hope there will be some reaction to my request.
