### ISSUE TITLE
Bad Media Description on Call

### ISSUE THREAD

**Issue by jcferranm** [versatica/JsSIP#440]
Hi. 

When I use library in my project, or when I use your Demo project using my asterisk server, I receive the message "Bad Media Description" when I do a call. In debug mode, the message showed is: "Called with an SDP without ice-ufrag and ice-pwd".

Reading in forums, the parameters ice-ufrag and ice-pwd are missing in SDP. In my logs, the SDP info attached to "PROCESSING" have not ice info. but 'INVITE' and others have it.

Asterisk is configured to use SDP and I've installed all needed libraries.

Any idea?

Thanks

**Comment by ibc** [comment]
Sorry, not here.
