### ISSUE TITLE
Missing createOffer constraints?

### ISSUE THREAD

**Issue by garysoed** [versatica/JsSIP#443]
See this [line](https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.js#L2309)

In my integration with JsSIP, I can't get the caller to receive any audios. Checking chrome://webrtc-internal, I saw 2 calls to `createOffer`. One of them picks up the offer constraint I specified (`{offerToReceiveAudio: true}`), but the second one doesn't.

Shouldn't the line I linked above pick up the user specified offer constraint?

**Comment by garysoed** [comment]
NVM. I figured out my problem. I didn't autoplay the audio tag. It has nothing to do with the line. I pointed out.

**Comment by ibc** [comment]
Such a [line](https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.js#L2309) is not wrong. It's just used to emulate early-media, so before that line a proper `createOffer()` with constraints was called. You don't need to set offer constraints when calling `createOffer()` for the second time.
