### ISSUE TITLE
Does this support info being returned?

### ISSUE THREAD

**Issue by AppleTechy** [versatica/JsSIP#444]
Essentially the SIP info I have returns  multiple SRTP links and decryption keys. Will this library allow me to retrieve all that info to then be able to plugin that data into ffmpeg to decrypt the video and audio streams?

**Comment by ibc** [comment]
Questions to the public mailing list, please.

**Comment by AppleTechy** [comment]
@ibc Where might I find that? Just your personal email address listed in the readme?

**Comment by ibc** [comment]
Which readme?

**Comment by AppleTechy** [comment]
@ibc The README.md included in the package? Yours is listed as, ibc@aliax.net

**Comment by ibc** [comment]
http://jssip.net
