### ISSUE TITLE
jssip doesnt work with nodejs

### ISSUE THREAD

**Issue by si458** [versatica/JsSIP#446]
Hi,
im trying to setup a very basic app, 
ext 123 setup on nodejs,
ext 456 on mobile, 

ring 123 from 456 

error in nodejs: UA.js:558
if (window.RTCPeerConnection) {
ReferenceError: window is not defined

any way around this or does jsSIP HAVE to be used in a browser?

**Comment by ibc** [comment]
Please, questions in the mailing list.
