### ISSUE TITLE
How to set stun servers?

### ISSUE THREAD

**Issue by michaelstephendavies** [versatica/JsSIP#449]
Hi

Version 0.5.0 had a parameter `stun_servers` but that was removed in [this commit](https://github.com/versatica/JsSIP/commit/8f37210c814e84edf6f7b6c73699953044df4922). The documentation for 0.6.0 doesn't mention that this parameter was removed, or what it was replaced by. How do you set the stun servers in 3.0.x?

**Comment by svarunan** [comment]
its a part of pcConfig options in 3.0.x
**pcConfig Object representing the RTCPeerConnection RTCConfiguration.**
```
pcConfig = {
        'iceServers': [
          { 'urls':['stun:stun.l.google.com:19302']}
        ]
      }
```

**Comment by michaelstephendavies** [comment]
Thanks

**Comment by ibc** [comment]
Please,  questions in the public mailing list.
