### ISSUE TITLE
Add Transfer API

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [versatica/JsSIP#45]
It'd be nice if the Session object supported some means of "transfer" for the call that would use one of the myriad of SIP means to transfer the call.

**Comment by mikollaay** [comment]
What's the status on this?

**Comment by ibc** [comment]
Not started. The complete list of specs (RFC) to implement would be very useful (given that "call transfer"  in SIP has been a full pain which lot of specs accomplishing with the same task).

**Comment by AlskiOnTheWeb** [comment]
There’s a fork of JSSIP where some of this stuff is implemented. I suggest you go that route as we have.






From: mikollaay
Sent: ‎Wednesday‎, ‎February‎ ‎25‎, ‎2015 ‎3‎:‎42‎ ‎PM
To: versatica/JsSIP
Cc: Alan Marcinkowski





What's the status on this?

**Comment by ibc** [comment]
@AlskiOnTheWeb you don't come here to recommend a fork of JsSIP, ok?

JsSIP is being actively maintained and improved, and today it is really robust and production-grade. It implements stuff like hold/mute MUCH better than any other JavaScript SIP library (including all those forks of JsSIP). Just check the list of [open issues](https://github.com/versatica/JsSIP/issues) in JsSIP and you will realize that there are no pending bugs to fix.

Of course there is room for new features, but just asking for all the stuff to be done without even providing any requested help is just so selfish. And coming here to recommend another similar software (a copy of JsSIP at the end) is just pathetic. Don't do it again.

**Comment by mikollaay** [comment]
@ibc in my opinion, JsSIP really the best library today.
I fully support you. But JsSIP very, very, very :) not enough transfer calls to can be applied in production call centers and in this question very, very need your help

**Comment by saghul** [comment]
If a company depends so badly on a fieature, I really find it hard to believe they can't get someone to write the code and contribute it back. But of course it's much easier to have someone else do it for free. This attitude is highly demoralizing, if it were my call I'd close all feature requests which don't have a patch attached in a month.

**Comment by ibc** [comment]
All those requesting this feature, I'll be clear:

* I no longer work in telco / VoIP environments.
* I use JsSIP for any purpose other than interconnecting with the PSTN or PBX/callcenters. 

So I won't spend my time implementing a feature I'm not interested in, unless:

* Somebody provides a full description of the **exact** specs (RFC's) that must be implemented, and/or
* Somebody making business with PBX/callcenters, with or without JsSIP, gives me money.

**Comment by AlskiOnTheWeb** [comment]
...We're not writing apps directly with your toolkit. Actually, it's a toolkit we recommend customers use. We know recommend different ones based on the features a customer might want to implement. I'm not saying you guys are bad by any means. We're just trying to make recommendations to people that are looking for this functionality.

Date: Thu, 26 Feb 2015 02:05:38 -0800

**Comment by ibc** [comment]
And I'm just asking for some minimal help (the exact specs/RFC's that must be implemented for having reliable transfer mechanism in JsSIP) and got nothing. My time is as important as the time of all those requesting a feature for free.

**Comment by ibc** [comment]
@AlskiOnTheWeb there is more people requesting this feature. I reopen the issue.

**Comment by wakamoleguy** [comment]
For reference, as best as I can tell, these are the relevant RFCs:

[SIP REFER Method](https://tools.ietf.org/html/rfc3515)
[SIP Replaces Header](https://tools.ietf.org/html/rfc3891)
[BCP for SIP Basic Transfer using REFER](https://tools.ietf.org/html/rfc5589#section-6)
[BCP for SIP Transfer with Consultative Hold using REFER w/Replaces](https://tools.ietf.org/html/rfc5589#section-7)

**Comment by kuanjava** [comment]
Please refer to the following url. I used this before.
http://sipml5.org/docgen/symbols/SIPml.Session.Call.html#transfer
Thanks.

**Comment by ibc** [comment]
Thanks a lot. I'll start with this stuff soon.

**Comment by axonaro** [comment]
What are your plans for adding this features ?

**Comment by ibc** [comment]
July.

**Comment by jack4026** [comment]
Hello! I'm looking forward to your great work of "Call Transfer API". Has there been any progress on the issue? Please let me know if you're not quite busy. Thank you in advance!

**Comment by jmillan** [comment]
Hi!

It will be pushed this month.

**Comment by MichaelAllenMiller** [comment]
:+1:

**Comment by jmillan** [comment]
Hi,

REFER support has been pushed into master branch.

Basic or Blind as well as Attended transfers are easily achieved by making use of the new RTCSession API:

[refer() Method](http://localhost:3000/documentation/0.7.x/api/session/#method_refer): generates an outgoing in-dialog REFER request. Optionally, a RTCSession instance to be replaced can be provided.

[refer Event](http://localhost:3000/documentation/0.7.x/api/session/#event_refer): fired when receiving an in-dialog REFER request. If consent is granted, the corresponding outgoing RTCSession is generated to the Refer-To resource.

[replaces Event](http://localhost:3000/documentation/0.7.x/api/session/#event_replaces): fired when receiving an out of dialog INVITE request pointing to the current RTCSession through the Replaces header field. If consent is granted, the corresponding incoming RTCSession is generated and the current one is terminated on the new one's establishment.

**Comment by jmillan** [comment]
The jssip.net website will be updated whiting the next hour with the pointed documentation.

**Comment by ibc** [comment]
Good work!

JsSIP 0.7.0 is out there, so let's close this issue.
