### ISSUE TITLE
Setup as a VOIP Server

### ISSUE THREAD

**Issue by vinodmap** [versatica/JsSIP#451]
This may not be the right place to ask this question, I apologize if so. I was sent over to JsSIP from another service provider for this question.  I am using a different service provider for two way video communications.  But, I also need something where I can plug in regular phone calls also.  For example, does this system have a way for someone to call into a regular phone number (e.g., a 1-800 # or other), and then the server can connect them via audio only (no video) to another computer based client. I need a system that is able to do computer <-> computer audio only, but also regular phone (phone#) -> computer audio only.  I would not need it to be computer -> phone number.   Does JsSIP have this functionality?   I tried the demo and see that it does two way video.

**Comment by jmillan** [comment]
Please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/jssip).
