### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by fcaride** [versatica/JsSIP#453]
Hi, im trying to add this library to my React Native application. 

What ive done:
npm install jssip --save
added "import JsSIP from 'jssip'" 

Im getting:
Unable to resolve module `util` from `/Users/fernandocaride/Documents/nxt/zero2/node_modules/jssip/lib/UA.js`: Module does not exist in the module map

Ive tried deleting node_modules and doing npm install again but nothing:(
What im doing wrong?
Thanks for your time!

**Comment by fcaride** [comment]
I sent to the mailling list

**Comment by ibc** [comment]
Let reopen. JsSIP should work as NPM dependency into a React project. Do you use browserify or webpack?

**Comment by fcaride** [comment]
Yes i used this utility https://github.com/mvayngrib/rn-nodeify which acts like browserify and it could run the app but really slow (loding time of 1 minute). But when i tried to make :

`    var socket = new JsSIP.WebSocketInterface('wss://ded01.xentric.co');
    var configuration = {
      sockets  : [ socket ],
      uri      : 'sip:4551pc@zerouy.xentric.co',
      password : 'qwerty4321'
    };
    
    var ua = new JsSIP.UA(configuration);`

it crashes when does the last line. It returns 

> Utils.escapeUser is not a function. (In 'Utils.escapeUser(this.user)', 'Utils.escapeUser' is undefined)
Thanks!

**Comment by ibc** [comment]
Interesting. Utils.js is like this:

```js
var Utils = {};

module.exports = Utils;

Utils.escapeUser = function(...) { ... }
```

Maybe `rn-nodeify` does not like that. Can you check the JsSIP [es6 branch](https://github.com/versatica/JsSIP/tree/es6)? (but wait a bit, since the same error would happen, we are gonna change that soon).

**Comment by fcaride** [comment]
Ok thanks! I tried using that branch and now when im doing var ua = new JsSIP.UA(configuration); i get Utils.escapeUser is not a function. I'll guess i have to wait you to change that haha. Can you post here when you are done?

Thanks! :D

**Comment by ibc** [comment]
Yep, please wait until done. We'll update here.

**Comment by fcaride** [comment]
Is there a way to make this project independent of 'util' and 'events'  libraries? It would be great not using browserify.

**Comment by ibc** [comment]
That's exactly what the es6 branch does :)

**Comment by ibc** [comment]
BTW, if you don't mind, please use for now the bundled/minified version of JsSIP:

http://jssip.net/download/releases/

Just include it into a `<script>` tag in your HTML and use it as `window.JsSIP` for now. It will work.
Later, when we fix this and release a new version, you will just need to add `import JsSIP from 'jssip'` in your code.

**Comment by jmillan** [comment]
@fcaride,

> Utils.escapeUser is not a function. (In 'Utils.escapeUser(this.user)', 'Utils.escapeUser' is undefined)

Can you give a try to the current [es6](https://github.com/versatica/JsSIP/tree/es6) branch?

Let us know it you still run with this issue. 

Thanks

**Comment by fcaride** [comment]
Hi Thanks for your response!

Now im getting: 'WebRTC not supported' When trying to make a call

Thanks!

**Comment by ibc** [comment]
> Now im getting: 'WebRTC not supported' When trying to make a call

That's obviously related to a different subject. Not sure which browser you are using, nor how you are configuring your JsSIP UA. Anyhow, please use the mailing list for usage questions or problems (this issue is finished). JsSIP depends on the browser WebRTC engine and, if so, it just works.

Thanks for reporting your original issue.

**Comment by fcaride** [comment]
Im trying to use it in a React Native application, i suppose it wont work no matter how haha. Thanks for your help

**Comment by ibc** [comment]
You need [this](https://github.com/oney/react-native-webrtc). However Ive never tested it.

**Comment by fcaride** [comment]
Ok thanks! ill try that

**Comment by fcaride** [comment]
Im trying to use that library and it uses the same headers of the original one. It would be great if you could make a branch in your github to use "react-native-webrtc" dependency instead of "webrtc-adapter". Do you see this possible? Thanks!

**Comment by ibc** [comment]
Please, let's not continue in this issue. The original subject was fixed. Let's do questions in the public mailing list. Thanks.
