### ISSUE TITLE
oniceconnectionstatechange failed 

### ISSUE THREAD

**Issue by morrain** [versatica/JsSIP#454]
hi,all.

I'm using JsSIP on my Web.

But  I get failed status in oniceconnectionstatechange event when hold the call .But I can't got more infos.

thx!

**Comment by ibc** [comment]
Usage questions/problems in the mailing list, please.

**Comment by morrain** [comment]
mailing list? cloud you please give me some guidance to get more info？because i cannot find this kind of questions in any mailing list.

**Comment by morrain** [comment]
could you pls show me where i can get the mailing list because i cannot find by myself.  thanks in advance

**Comment by ibc** [comment]
May I know where have you looked for the JsSIP mailing list?

**Comment by ibc** [comment]
If you search "jssip mailing list" in Google, you get it.
If you check the README file here in the JsSIP GitHub, you get it.
If you check the homepage of the jssip.net website, you get it.

**Comment by morrain** [comment]
ok,i got it ,thx
