### ISSUE TITLE
JSSIP received freeze video frame

### ISSUE THREAD

**Issue by BroWater** [versatica/JsSIP#455]
**Scenario:**
JSSIP <-> Kamailio-proxy (4.2)<-> classical SIP client

**JSSIP settings:**  
- use https://tryit.jssip.net/
- used browser is Google Chrome 60.0.3112.101  (Not tested in other browsers yet, ex: FireFox)
   
**Result:**
In most cases, it worked normally. 
However ,

 _sometimes JSSIP got freeze frame after call started for 2~3 seconds,_

and the other side still received the media stream from JSSIP smoothly.
The JSSIP side didn't recover then unless the call was hung up and started again,
It doesn't matter which side started the call.
Until now I cannot find the reproducible steps.

I checked whether JSSIP side did receive the video SRTP stream or not by capturing the packets,
but the packets showed that the browser indeed obtained the media contents,
then I just wonder if it's the issue of the decoder  the browser used.

Does anyone know the possible cause?
Any additional information  I need to supply?

Thanks.

**Comment by ibc** [comment]
JsSIP does not control the RTP+RTCP engine. That's up to the browser itself (its WebRTC stack).

You may want to check whether your remote SIP endpoint supports NACK and FIR/PLI RTCP feedback messages. But this is not an issue in JsSIP at all.
