### ISSUE TITLE
Update WebRTC Adapter version

### ISSUE THREAD

**Issue by iclems** [versatica/JsSIP#456]
With Edge and Safari technology preview now supporting properly WebRTC, other SIP libraries get instant support for these new browsers thanks to the last version of WebRTC adapter. 

It'd be great to test and update using the latest version.

**Comment by jmillan** [comment]
Thanks for reporting @iclems 

New version is out with upgraded dependencies

**Comment by iclems** [comment]
Thank you @jmillan I will start testing with the new browsers!
