### ISSUE TITLE
Cannot read property 'id' of undefined at receiveNotify when refer() is used

### ISSUE THREAD

**Issue by btaens** [versatica/JsSIP#457]
When using an RTCSession's refer() method, an error is thrown by receiveNotify(), saying request.event.params doesn't exist.

The request that is sent looks like this:
{event: "refer"}

Even though it throws an error, the transfer still does happen without a problem.

Both Chrome and Firefox are affected the same way.

**Comment by jmillan** [comment]
Can you please attach a browser console?

**Comment by btaens** [comment]
I'm afraid this just put the error slightly off.
Now I get the following error:
RTCSession.js:2048 Uncaught TypeError: referSubscriber.receiveNotify is not a function
    at RTCSession.receiveNotify (RTCSession.js:2048)
    at RTCSession.receiveRequest (RTCSession.js:1367)
    at Dialog.receiveRequest (Dialog.js:214)
    at UA.receiveRequest (UA.js:609)
    at UA.onTransportData (UA.js:1201)
    at Transport.onData (Transport.js:229)
    at WebSocketInterface.onMessage (WebSocketInterface.js:143)

The problem stems from the IncomingRequest it is inspecting not having the event.params.id property.
I've saved the console output. I've also logged the IncomingRequest it receives when the error occurs:
[jssip.txt](https://github.com/versatica/JsSIP/files/1307992/jssip.txt)

**Comment by jmillan** [comment]
@btaens,

Sorry for the long delay and thanks for the PR. Would you please sign the [CLA](http://jssip.net/contribute/) before merging?

thanks
