### ISSUE TITLE
Safari will not support offerToReceiveAudio

### ISSUE THREAD

**Issue by iclems** [versatica/JsSIP#458]
Per this thread, Safari WebRTC will not support the legacy createOffer with offerToReceiveAudio. 

https://bugs.webkit.org/show_bug.cgi?id=176157#c1

**Comment by ibc** [comment]
True, but JsSIP relies on adapter.js, which must be updated (it may fix that or not).

**Comment by jmillan** [comment]
Closing the issue since we are relaying on the adapter nowadays. Well keep it updated.
