### ISSUE TITLE
update authorization error

### ISSUE THREAD

**Issue by kolanski** [versatica/JsSIP#459]
Hi i found issue in call process. If we make are call and waited for update event, authorization fails with "Not supported auth algorithm" message. I tested it on latest ,2.0.0, 1.0.0 releases. In other side i have app builded on jssip 0.2.1 and this case working properly in this release.
Browser: firefox 55.0.3
SIP Server: officesip 3.5
Logs: https://pastebin.com/dLAeNQ1K
**Update**: Founded Workaround for this problem. Change value of sessionTimersExpires to big for never update event handle;

**Comment by jmillan** [comment]
Hi,

Digest authentication works properly in JsSIP. You may want to write to officesip support list why do they respond such "Not supported auth algorithm".

Any question please use the mailing list.
