### ISSUE TITLE
Hold call more then 2-3 min, unhold call can't resume

### ISSUE THREAD

**Issue by fastxyf** [versatica/JsSIP#460]
When hold call and unhold form browser quick, the call can resume.
But when hold call more then 2-3 min, unhold call , the call can't resume.

I guess this is the question is router block the audio/video connection port, because when hold call, browser  not send the keep alive packet, router will release the port.

Keeping webrtc streams/connections between webpages
https://stackoverflow.com/questions/35529455/keeping-webrtc-streams-connections-between-webpages

This link say use IceRestart can fix it, but i don't know how to do IceRestart.

**Comment by ibc** [comment]
No. The ICE and DTLS stays alive, and also RTCP over them.
Now, if your SIP server is closing the ICE+DTLS that's not a problem in JsSIP.

Please, let's move this problem to the mailing list, and specify your environment in there.
