### ISSUE TITLE
Missing example how to assign the audio/video streams

### ISSUE THREAD

**Issue by Huseriato** [versatica/JsSIP#462]
Hello,

I've problems to find the correct event to assign audio/video streams. The examples in the documentation are nowhere dealing with this. The examples I've found on GitHub are alle for versions < 3.0.

The documentation for 2.0 and mentions an event "addstream" which is missing in 3.0. Can you please update the examples or provide a little working demo that just deals with inbound/outbound calls an assigns the needed streams?

Thank you!

**Comment by ibc** [comment]
Please, questions in the mailing list.

**Comment by Huseriato** [comment]
I think this is not a real question. It's an request for completing the documentation. The addstream part had beem fully removed in documentation for 3.0.x. So the chapter "Getting started" is incomplete.

**Comment by ibc** [comment]
There is no documentation to complete. JsSIP does not want to be yet another "WebRTC API wrapper". The `JsSIP.RTCSession` class has a [connection](http://jssip.net/documentation/3.0.x/api/session/#attribute_connection) attribute pointing to the underlying `RTCPeerConnection` instance for the app to set events. That's what you must use.

Regarding usage examples, yes, there is one: 

https://github.com/versatica/tryit-jssip
