### ISSUE TITLE
JsSip answers on INFO in-dialog request with 403 response code.

### ISSUE THREAD

**Issue by tiglat** [versatica/JsSIP#463]
Hello.

We are working on own solution for WebPhone application and using JsSip 3.0.15 library for that project.

I would like to notify about an issue with receiving INFO request when early dialog is established (JsSip responded 180 with To tag). Scenario is following:
1. JsSip (our Webphone app) receives an initial INVITE
2. JsSip responds with Trying
3. JsSip sends 180 Ringing with To tag. Early dialog is established
4. JsSip receives INFO indialog request
5. JsSip answers 403 Wrong Status.
6. JsSip answers OK on the INVITE
7. Calling party sends ACK
8. JsSip doesn't match that ACK with existing dialog and re-transmits OK again and again.

It looks like JsSip doesn't accept indialog request INFO when the dialog state is EARLY.
However there is one more issue. After such request JsSip stops receiving ACK.

I found that source code where INFO is processed and fixed it. Could you please check if my fix is correct. I also attached log with the scenario described above.

Thank you 
Best regards
Kosntantin
[jssip issue.zip](https://github.com/versatica/JsSIP/files/1376323/jssip.issue.zip)

**Comment by davies147** [comment]
Hi Kosntantin,

Personally I will not open a ZIP file from someone I do not know. Sorry :)

Are you able to use GitHub to present the patch? I assume you will already
have an account?

Even if you don't use git on your desktop, I believe you should be able to
edit the files by forking JsSIP into your account, editing the files
on-screen on the Github website, and then creating a pull-request of the
resultant changes. The pull request can then be associated with your issue.

Cheers,
Steve

**Comment by jmillan** [comment]
Hi tiglat,

JsSIP 3.0.17 is out, fixing the issue. Thanks for reporting.

Yes, please, next time do send a Pull Request or even paste your patch here if it's very small. I would not open a .zip file that easy.

Kind regards.

**Comment by tiglat** [comment]
Thank you guys! 
Github doesn't accept js files to be attached here, that is why I used the zip file. Sorry. Next time I will make pull request.
Today will test a new revision of the lib.
Best regards
Konstantin

**Comment by tiglat** [comment]
It looks like you made mistake in the changelog. You wrote "RTCSession: process NOTIFY in early state.". But you have changed INFO behavior.

**Comment by jmillan** [comment]
You're right.

I've fixed it and force pushed, so please, If you're building JsSIP yourself, remove the last two commits (git reset --hard head~2) and then git pull.

**Comment by tiglat** [comment]
Thank you very much for quick response. It saved time for our development.
Best regards.

**Comment by jmillan** [comment]
Thanks to you for reporting.

Happy JsSIP-ing!
