### ISSUE TITLE
INFO received in early dialog state breaks ACK processing.

### ISSUE THREAD

**Issue by tiglat** [versatica/JsSIP#464]
Hi guys!

Unfortunately there is a new issue with INFO in early dialog state.

When INFO is received after Ringing and before OK is sent, JsSip stops processing ACK request normally. JsSip starts to retransmit OK regardless ACK was received.

I could not fix the issue. 

Please find two log files in the attachment.

Best regards
Konstantin
[bad scenario - info before ack.txt](https://github.com/versatica/JsSIP/files/1379718/bad.scenario.-.info.before.ack.txt)
[good scenario - no info before ack.txt](https://github.com/versatica/JsSIP/files/1379719/good.scenario.-.no.info.before.ack.txt)

**Comment by tiglat** [comment]
Probably I have found the root cause. Remote sequence number was updated with INFO CSeq and ACK doesn't match the current dialog. That is wrong. ACK must have sequence number of the initial INVITE. So you need to update function checkInDialogRequest in Dialog class somehow.

**Comment by tiglat** [comment]
By the way, checkInDialogRequest function should not check CSeq from my point of view. Because CSeq is not a part of dialog identity. This check could be a part of some sanity checks but it should not used to identify if a request belongs to a dialog. Wrong CSeq doesn't mean that the message is not matched to some dialog. It is matched but it is incorrect.

**Comment by jmillan** [comment]
I do think the dialog should check the CSeq, of course. A different thing is that we should consider also receiving a legitimate ACK with a lower CSeq than the current remote one.

**Comment by tiglat** [comment]
Ideally we need to store in dialog context CSeq of request (reInvite) which should be acknowledged and use this number when ACK is received. Because today it looks like that re-Invites do not work too.

**Comment by jmillan** [comment]
Yes, work is in progress.

**Comment by jmillan** [comment]
@tiglat, please give it a try to 3.0.18

**Comment by tiglat** [comment]
Great! 
It works well for us.
Thanks a lot.
