### ISSUE TITLE
network issue

### ISSUE THREAD

**Issue by aze2201** [versatica/JsSIP#465]
When I make call from device to web I see below ERROR. from WebRTC/WebSocket side seems some issue.
`
ERROR[32330][C-0000001f]: chan_sip.c:4263 __sip_reliable_xmit: Serious Network Trouble; __sip_xmit returns error for pkt data`

**Comment by aze2201** [comment]
???

**Comment by ibc** [comment]
Clearly not a JsSIP issue. Your problem is in Asterisk chan_sip. JsSIP does not break a WebSocket. Please ask in the Asterisk forum.
