### ISSUE TITLE
3.0.19 is SERIOUSLY broken

### ISSUE THREAD

**Issue by gdaszuta** [versatica/JsSIP#467]
Hi, guys, I hate to be the bearer of bad news, but the ES6 rewrite in the latest release is a serious cock-up.

For start, function utf8Encode(str) in lib/utils has been rewritten in way, that makes in impossible to work – someone replaced string AND String into str, which probably was meant to not use variable name similar to prototype, but – surprise, surprise – string instances don't have .fromCharCode method, it only exists in String constructor.

Fixing that, I've got some other error – "Uncaught TypeError: Cannot assign to read only property 'password' of object '#<Object>' at UA.set (UA.js:394)". Got there, fixed that, ok, but there is still something not right. 

I've got no more time to look around, so that's all from me at the moment – but please, guys, roll back this release immediately before someones underside got seriously bitten.

Regards,
G

```
diff --git a/lib/UA.js b/lib/UA.js
index 02364c7..5907aaa 100644
--- a/lib/UA.js
+++ b/lib/UA.js
@@ -901,7 +901,7 @@ module.exports = class UA extends EventEmitter
     {
       if (Object.prototype.hasOwnProperty.call(this._configuration, parameter))
       {
-        if (writable_parameters.indexOf(parameter))
+        if (writable_parameters.indexOf(parameter) !== -1)
         {
           Object.defineProperty(this._configuration, parameter, {
             writable     : true,
diff --git a/lib/Utils.js b/lib/Utils.js
index 53e1a62..ed7abe5 100644
--- a/lib/Utils.js
+++ b/lib/Utils.js
@@ -386,18 +386,18 @@ exports.calculateMD5 = (string) =>
 
       if (c < 128)
       {
-        utftext += str.fromCharCode(c);
+        utftext += String.fromCharCode(c);
       }
       else if ((c > 127) && (c < 2048))
       {
-        utftext += str.fromCharCode((c >> 6) | 192);
-        utftext += str.fromCharCode((c & 63) | 128);
+        utftext += String.fromCharCode((c >> 6) | 192);
+        utftext += String.fromCharCode((c & 63) | 128);
       }
       else
       {
-        utftext += str.fromCharCode((c >> 12) | 224);
-        utftext += str.fromCharCode(((c >> 6) & 63) | 128);
-        utftext += str.fromCharCode((c & 63) | 128);
+        utftext += String.fromCharCode((c >> 12) | 224);
+        utftext += String.fromCharCode(((c >> 6) & 63) | 128);
+        utftext += String.fromCharCode((c & 63) | 128);
       }
     }
 
```

**Comment by jmillan** [comment]
Thanks very much  @gdaszuta.

**Comment by michelepra** [comment]
Also Dialog.js line 148
    const eventHandlers = options.eventHanlders || {};
to 
    const eventHandlers = options.eventHandlers || {};

**Comment by jmillan** [comment]
Thanks @michelepra, it has been fixed.

**Comment by michelepra** [comment]
thanks to you for immediatly fix
