### ISSUE TITLE
Error when terminatingSessions

### ISSUE THREAD

**Issue by johnryan** [versatica/JsSIP#469]
I've noticed that if I try to call `terminateSessions` when a call has been initiated but has not been answered like so:

`this.webRTCAgent.terminateSessions();`

i get an error: 

`this._request.cancel is not a function`

and the call is not ended. Is this an expected behavior? It seems to be that calling `terminateSessions` should end all active sessions regardless of whether they have been answered.

**Comment by jmillan** [comment]
Hi @johnryan,

Which JsSIP version are you using?

**Comment by johnryan** [comment]
@jmillan sorry should have included that, currently using `3.0.18`

**Comment by jmillan** [comment]
Can you reproduce it?

Could you try the latest version?

**Comment by johnryan** [comment]
@jmillan sorry for the delay, here's a jsfiddle that reproduces the issue: https://jsfiddle.net/qbzu4zu7/

Basically what i'm seeing is if i initiate a session then press the hangup button immediately i get the error. One thing to note is that i was not able to reproduce the error on an older version of the jssip code (here's the original fiddle i forked: https://jsfiddle.net/msqenm70/1/).

Please let me know if i can provide any more information.

**Comment by jmillan** [comment]
I imagine that SIP authentication is involved here.

Let me check it.

**Comment by gummibjorn** [comment]
Facing the same issue in `3.0.21`. 

1. Sending an authenticated INVITE
2. Getting a provisional Response 1XX Ringing...
3. Trying to terminate the Session i got from UA.call()
4. Results in `this._request.cancel is not a function`

Any fixes?

**Comment by gummibjorn** [comment]
nice
