### ISSUE TITLE
Not compatible with create-react-app after 3.0.19

### ISSUE THREAD

**Issue by kachkaev** [versatica/JsSIP#472]
We are using `jssip` as a dependency for [`react-sip`](https://github.com/callthemonline/react-sip) inside a [`create-react-app`](https://github.com/facebookincubator/create-react-app) project. The latter is one of the most popular webpack boilerplates.

After upgrading from 3.0.18 to 3.0.19+, `npm run build` no longer works and shows the following error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/jssip/lib/Constants.js:4


Read more here: http://bit.ly/2tRViJ9
```

What could you guys suggest?

**Comment by jmillan** [comment]
Hi @kachkaev,

We may just create a building stage that transpiles the ES6 code into ES5 seeing that ES6 is still so widely uncovered.

Thanks for reporting.

**Comment by ibc** [comment]
Since 3.0.19 JsSIP is written in ECMAScript 6, so in order to use it as a dependency in browserify or webpack you need to "babelify" it to ECMAScript 5. I don't know webpack but in browserify we use some `transforms`to transpile the whole app and its dependencies into ES5.

If that does not work in webpack (doesn't it?) you could just load the transpiled JsSIP file located in `dist/jssip.min.js`.

**Comment by kachkaev** [comment]
@ibc although linking to `dist/jssip.min.js` is possible, it's not ideal because there are fewer options to tree-shake, reuse deps, etc. Traspiling to ES5 before publishing is still a good practice, so it'd be good if you could support that. IMO `package.json`'s `main` field should point to a ES5 file, not a ES6 one.

See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify for details.

**Comment by ibc** [comment]
>  although linking to dist/jssip.min.js is possible, it's not ideal because there are fewer options to tree-shake, reuse deps, etc. Traspiling to ES5 before publishing is still a good practice, so it'd be good if you could support that. IMO package.json's main field should point to a ES5 file, not a ES6 one.

I think that is contradictory. Indeed, if package.json `main` points to the minified ES5 file, deps would not be reused.

Anyway, what is the problem with `create-react-app`? Doesn't it rely on browserify or webpack? I do this in browserify within ES6 applications with JsSIP as dependency and it works fine:

https://github.com/versatica/tryit-jssip/blob/master/gulpfile.js#L64

Why that is not feasible for `react-create-app`?

**Comment by kachkaev** [comment]
`create-react-app` does rely on webpack, but their opinion is that all the stuff in `node_modules` has to be in es5. If that's not the case for one of the modules, things work fine in development (because Chrome understands ES6), but fails during `npm run build` because webpack is configured to not transpile ES6 to ES5 in `node_modules`. Even the most recently released libraries like `react 16` are transpiled to ES5 while publishing.

**Comment by ibc** [comment]
Understood. Then we have a problem:

Whether to point to the transpiled `dist/jssip.js` file in packake.json `main` or not.

1. If yes, all of us using browserify/webpakc with `babel` to transpile all the app and its dependencies won't be able to reuse deps (such as the `debug` module).
1. If not, users of `create-react-app` will have your problem.

So what should we do? and why directly loading `dist/jssip.js` (rather than `main` in package.json) is not a valid solution for those using `create-react-app`?

AFAIS `create-react-app` uses webpack. Again, I don't know webpack but does it allow something similar to the `browserify` option in packake.json? I mean something like this:

https://github.com/versatica/mediasoup-client/blob/master/package.json#L22

**Comment by kachkaev** [comment]
Perhaps you could just have a `dist` folder that has the same structure as `src` but with ES6 transpiled to ES5 (e.g. \`  turned into '). This will allow you to use the latest features for develop yet still make the module widely applicable.

From what I know, `create-react-app` is not the only webpack-based boilerplate that chooses not to transpile stuff inside `node_modules`. Doing so is technically possible, but becomes very time-consuming especially in rather large apps. Because the developers are better off with only ES5 modules in `node_modules`, library maintainers are encouraged to publish transpiled (but not combined or minified) code on npm. In addition to build times, problem with ES6+ is in a large variety of flavours and variations as of today. This means that from `npm install xyz` is not enough anymore for some projects dependencies. The worst scenario is when there are two modules that require conflicting babel configs.

**Comment by ibc** [comment]
I don't think having a `dist` folder with same structure as `lib` is something maintainable.

**Comment by kachkaev** [comment]
There is no need for maintaining both, one just needs to run babel before publishing. lib stays in the repo and dist lands npm. I’m not a pro in setting up this process, but could help if you are interested.

**Comment by ibc** [comment]
So we may do something like [here](https://github.com/minhtranite/react-tooltip-component), right?

This is, having all the current ES6 code in `src/` and then a gulp task that babelifies each file in `src/` to `lib/`. Is that?

**Comment by kachkaev** [comment]
@ibc, that's right. Your `lib/` folder (or `dist/`, depending on how you want to call it) does not even have to be under source control if you wish. There is an option to add a `prepublish` script to `package.json`, which will automatically babelify your `src/` before each `publish`. In that case, `lib/` (or `dist/`) can be added to `.gitignore`.

When submitting a PR, contributors won't have to update any code other than in `src/`.

I once contributed to a repo which had both `src/` and `dist/` and updated both by mistake because of not knowing how babelify builds work at that time. If your repo has no code but in `src/`, this may help avoid similar confusions in future.

**Comment by kachkaev** [comment]
Not sure if this is the best example, but you can have a look at https://github.com/callthemonline/react-sip that we're doing based on your library :–)

**Comment by ibc** [comment]
Working on it.

**Comment by ibc** [comment]
@kachkaev may you try the "babel" branch?

**Comment by kachkaev** [comment]
Thanks for making that commit @ibc! Looks good. I'm not sure if keeping `dist` and `lib-es5` is necessary in the git repo, but this is just an opinion, not a rule. I also see a potential danger is not having `prepublishOnly` in `package.json`, because this leaves a chance to `npm publish` a version where `dist` and `lib-es5` are not up-to-date. However, if you haven’t had this problem before, should be good!

When someone submits a PR in future, do you expect them to only change `lib` or all three folders?

**Comment by ibc** [comment]
Adding @jmillan to the party:

https://github.com/versatica/JsSIP/tree/babel

**Comment by jmillan** [comment]
Super!

Well done @ibc

**Comment by ibc** [comment]
Let's reopen until merged.

**Comment by ibc** [comment]
@kachkaev 

> Thanks for making that commit @ibc! Looks good and works in my create-react-app project.

So you confirm that it works as expected in your environment, right? We are not able to test it so need double confirmation :)

> I'm not sure if keeping dist and lib-es5 is necessary in the git repo, but this is just my opinion, not a community rule.

AFAIU keeping `lib-es5/` is needed since that's the entry point of the lib ("main": "lib-es5/JsSIP.js").

Regarding `dist`, it's also needed since `bower.json` points to it.

> I also see a potential danger is not having prepublishOnly in package.json, because this leaves a chance to npm publish a version where dist and lib-es5 are not up-to-date. However, if you haven’t had this problem before, should be good!

Nah, we always run `gulp` before publishing, and it does everything :)

> When someone submits a PR in future, do you expect them to only change lib or all three folders?

We should document that just code under `lib/` should be modified.

**Comment by kachkaev** [comment]
> So you confirm that it works as expected in your environment, right? We are not able to test it so need double confirmation :)

Yep, after I cloned the new branch and did `npm link` in my create-react-app project, all worked!

> AFAIU keeping lib-es5/ is needed since that's the entry point of the lib ("main": "lib-es5/JsSIP.js").

I understand. However the fact that a file inside `lib-es5` is mentioned in `package.json` does not require that file to be a part of the git repo. The folder can be added to `.gitignore` and generated every time before `npm publish` (either by calling a gulp task or by mentioning it in `package.json` as a script named `prepublishOnly`). A similar principle applies to `dist/`: those files can be simply  uploaded to a CDN or attached on the [releases page](https://github.com/versatica/JsSIP/releases). Example:
https://github.com/facebook/react/releases

If the git repo only contains the source code in `lib/`, there'll be no question about which folders to edit and at what times to update the derived js files.

I'm not saying that the way I describe is the only true way, just sharing my thoughts on how I'd organise things :–)

**Comment by kachkaev** [comment]
Hi @ibc! When about are you planning to turn this into a release? We're working on [react-sip](https://github.com/callthemonline/react-sip) v0.5 (which is downstream for `jssip`) and curious if we can update your library from `3.0.18` as a part of the release.

**Comment by ibc** [comment]
Sure. Please ping here on Monday or next week.

**Comment by jmillan** [comment]
I really like the `prepublishOnly` concept, which I didn't know. I've just removed `lib-es5` folder from the repo.

**Comment by jmillan** [comment]
Removed also `dist` from sources.

It is now generated on npm `install` event as well as on `prepublishOnly`

**Comment by jmillan** [comment]
Hi,

`dist` folder remains in the repo since it is needed for Bower.

**Comment by jmillan** [comment]
Thanks a lot @kachkaev for reporting and helping figuring out the solution :-)
