### ISSUE TITLE
"getusermediafailed" TypeError: Illegal constructor

### ISSUE THREAD

**Issue by pedrogaldino** [versatica/JsSIP#475]
Hello!
I'm having some problems when i try to start a call on mobile devices (using ionic with cordova).

The code bellow works fine to connect with the Asterisk WebRTC server:

var socket = new JsSIP.WebSocketInterface('wss://myserver:8089/ws');

var configuration = {
	sockets: [socket],
	uri: 'sip:100@myserver',
	password: '1000001',
	realm: 'myserver'
};

var phone = new JsSIP.UA(configuration);

But when i call:

var eventHandlers = {
	'progress': function (e) {
		console.log('call is in progress');
	},
	'failed': function (e) {
		console.log('call failed with cause: ' + e.data.cause);
	},
	'ended': function (e) {
	        console.log('call ended with cause: ' + e.data.cause);
	},
	'confirmed': function (e) {
			console.log('call confirmed');
	}
};

var options = {
	'eventHandlers': eventHandlers,
	'mediaConstraints': { 'audio': true, 'video': false }
};

var session = this.phone.call('s', options);

I get this error event:
JsSIP:ERROR:RTCSession emit "getusermediafailed" [error:TypeError: Illegal constructor

I'm missing something?

**Comment by pedrogaldino** [comment]
Here more logs after call function is called

```
phone.call('s');

jssip.js:9 JsSIP:UA call() +13m
jssip.js:9 JsSIP:RTCSession new +13m
jssip.js:9 JsSIP:RTCSession connect() +1ms
jssip.js:9 JsSIP:RTCSession emit "peerconnection" +3ms
jssip.js:9 JsSIP:RTCSession newRTCSession() +1ms
t {_events: Object, _maxListeners: undefined, _id: "t67n5d8ekpbk4nbaktkcre017aqkdl", _ua: t, _status: 0…}
jssip.js:9 JsSIP:RTCSession session failed +10ms
jssip.js:9 JsSIP:RTCSession close() +1ms
jssip.js:9 JsSIP:RTCSession emit "failed" +1ms
jssip.js:9 JsSIP:ERROR:RTCSession emit "getusermediafailed" [error:TypeError: Illegal constructor] +13m
```

**Comment by ibc** [comment]
I'm sorry but we cannot handle ionic/cordova issues here. They are obviously related to their WebRTC stack/plugin.
