### ISSUE TITLE
Hold() fail in firefox - getLocalStreams deprecated

### ISSUE THREAD

**Issue by hkcoyant** [versatica/JsSIP#476]
Browser console message:
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.

Code Line 17379 in jssip 3.1.0

Enviroment:
Firefox 56.0 (64-bit) / Ubuntu 17.10
Tested whit JsSip: 3.1.0 / 3.0.24 / 3.0.28

*Note: Still Run well in Chrome Versión 62.0.3202.89

**Comment by ibc** [comment]
Yes. As explained in some other issue or mailing list thread, we won't modernize WebRTC API usage within JsSIP until browsers become in sync.

**Comment by hkcoyant** [comment]
@ibc perfect! thanks for answering. Regards!
