### ISSUE TITLE
P-Header support

### ISSUE THREAD

**Issue by garysoed** [versatica/JsSIP#487]
[RFC 3455](https://tools.ietf.org/html/rfc3455)

Is this currently being worked on? I have a ~~hacky~~ working implementation of the P-Associated-URI part in my fork, but it'll take some effort to turn it into a PR. If this feature is coming soon, I would rather wait for it to be done. Otherwise, I'll work on the PR.

Thanks!

**Comment by jmillan** [comment]
AFAIK there is nothing to do in JsSIP regarding to `P-Associated-URI` but to provide a mechanism to gather such header field upon re-registrations.

We may create a new `UA` event: `reregister` or just fire `register` everytime we receive a `200 OK` for a registration request, and let the user code register to the first or all registration events with `ua.once()` or `ua.on()` respectively.

**Comment by garysoed** [comment]
I haven't checked the latest version of JsSIP (still using 3.0.7), but in my implementation, I had to:

1.  Add support for JsSIP to parse the `P-Associated-URI` as a multi header.
1.  Get the `P-Associated-URI` through the response headers.
1.  Pass the `P-Preferred-Identity` through the extra headers.

Currently JsSIP doesn't support those parameters since users have to get them through the extra headers. Do we want to make additional properties / parameters for them? How about validating them?

> We may create a new UA event: reregister or just fire register everytime we receive a 200 OK for a registration request

I believe JsSIP is already firing `register` every time it receives a 200 OK. My local implementation works for reregistration.

I can send you a PR to support `P-Associated-URI` as multi headers, but I think the rest of the feature needs a design input from JsSIP team.

Let me know what you think. Thanks!

**Comment by jmillan** [comment]
Closing the issue. Feel free to make a PR.
