### ISSUE TITLE
Socket configuration {socket: ..., weight:1} works, but log  print JsSIP:ERROR:Socket...

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#494]
When used socket configuration {socket: socket1, weight:1}  it works, but log print not relevant error: 

"JsSIP:ERROR:Socket missing or invalid JsSIP.Socket url property".

To make log cleaner could be used the fix:  Swap 'if' and 'else' parts in Config.js line 71:

          if (Object.prototype.hasOwnProperty.call(socket, 'socket') &&
                   Socket.isSocket(socket.socket))
          {
            _sockets.push(socket);
          }
          else if (Socket.isSocket(socket))
          {
            _sockets.push({ socket: socket });
          }

**Comment by jmillan** [comment]
The change is ready in new version.

Thanks!
