### ISSUE TITLE
user denied media access

### ISSUE THREAD

**Issue by akhilreddyjirra** [versatica/JsSIP#497]
environment :
FreePBX 14.0.1.24 
Asterisk :14.7.5
used Proto: chansip and  pjsip
websocket URI : wss://pbx.domainurl:8089/ws
URl Used: https://tryit.jssip.net
Browser: chrome Version 64.0.3282.119  and Firefox Quantum (58.0.1 (64-bit) )

Error: 
Try to call from web socket to web socket 

Getting error "**User Denied Media Access**"

Expected: Make calls smooth

**Comment by ibc** [comment]
Please, don't report here user problems using the demo.

**Comment by hkcoyant** [comment]
@akhilreddyjirra "User Denied Media Access" mean these, the user is blocking media access to website in browser, he needs allow the access:
![wwww](https://user-images.githubusercontent.com/6413893/35572269-07b16e0e-05b3-11e8-840b-cc8310b1d215.jpg)
