### ISSUE TITLE
JsSip 3.0.15 version - noaudio on the webrtc side

### ISSUE THREAD

**Issue by zenichev** [versatica/JsSIP#501]
Hi community.

We experience the problem with no-audio (on the webrtc side) with scheme:
webRTC -> kamailio -> rtpengine -> asterisk

Problem appeared since we have moved to new JsSip release, 3.0.15.
The older one was 2.0.3 (with it worked fine). So when I get back to 2.0.3, it works as expected, and vice-versa - no audio when I move to 3.0.15.

rtpengine version: ngcp-rtpengine 6.0.0.0 0mr6.2.0.0
Moved to: ngcp-rtpengine 6.2.0.0 0mr6.2.0.0
It didn't help.

Tried to use different browsers such as FireFox, Chrome etc. The problem appears with all of them.

JsSip console doesn't show any errors, nor it hints on the problem.
JsSip dump from console with debug mode:
https://gist.github.com/zenichev/566021962f81a42e6ad20b7bb7f0b1b6

Here is rtpengine log (7 lvl of verbosity) no errors at all:
https://gist.github.com/zenichev/f1c3f369a6b31370c4f8729d3ebbf3b0

I compared several rtpengine logs (jssip2.0.3 and jssip3.0.15). With 3.0.15 it doesn't contain any errors, warnings that can break the audio stream.

But I noticed the difference in logs.

JsSip 2.0.3
https://gist.github.com/zenichev/da25d302595e6eaa176fefcdf8187704

JsSip 3.0.15
https://gist.github.com/zenichev/8ed38f6c79cb23eab9f0e23e604373fb

The difference is, that log of 2.0.3 version contains these two rows in answer to webrtc:
Received ICE/STUN response code 0 for candidate pair hhiDJAfDzmlPtKHO:0:1 from webrtc.device.ip:42450 to kamailio.server.ip
Received ICE/STUN response code 0 for candidate pair 3Sy5Kr6LLnichxbL:0:1 from webrtc.device.ip:42450 to kamailio.server.ip

While log of 3.0.15 contains only one such row for one candidate pair
Received ICE/STUN response code 0 for candidate pair hhiDJAfDzmlPtKHO:0:1 from webrtc.device.ip:49846 to kamailio.server.ip

And one more thing.
Log of 2.0.3 contains such row:
Successful STUN binding request from webrtc.device.ip:42450
While 3.0.15 doesn't.

Other things look the similar, no huge dissimilarities.

It seems to me, that the problem is with ICE, it looks really like a problem with NAT.
I'm not trying to prove that the problem is with JsSip, I just trying to find out how to fix this.

I know it doesn't look like a bug, but I've lost more than 1 month with no success.
So I hope someone can hint where to dig in.

**Comment by jmillan** [comment]
Please attach the JsSIP logs (with SIP traces) for a session with each version.  Only the one for 3.0.15 was attached.

**Comment by ibc** [comment]
Can you please paste the SDP offer of Chrome and the received 200 OK in both scenarios (working jssip 2.0.3 and failing jssip 3.0.15)?

Also, not sure if related, but consider whether your server side supports rtcp-mux (this is, RTP and RTCP over the same port). This includes both your rtpengine and Asterisk. AFAIR latest version of Asterisk supports rtcp-mux, and Chrome by default assumes rtcp-mux (and will mandate it soon). This is related to the `rtcpMuxPolicy` setting in the PeerConnection configuration object (`pcConfig` in JsSIP):

* https://www.w3.org/TR/webrtc/#rtcrtcpmuxpolicy-enum
* http://jssip.net/documentation/3.2.x/api/ua/#method_call
* http://jssip.net/documentation/3.2.x/api/session/#method_answer
* https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/OP2SGSWF5lo

**Comment by zenichev** [comment]
Sorry for the delayed response.

Here is full logs with traces.

2.0.3:
https://gist.github.com/zenichev/6e248575ca6e3ae110ae51637eb27957

3.0.15:
https://gist.github.com/zenichev/396835204879c09545ed3ac98166a98a

I noticed an interesting thing, that while using the 3.0.15 version, I have more candidates in invite.
For example, this time tun device was included in candidates.
I will get deeper with it.

**Comment by ibc** [comment]
Not sure if Chrome does this ok, but in 3.0.15 the SDP offer has `c=IN IP4 tunnel.ip.address` which is supposed to be the selected local IP for sending/receiving media. I'm pretty sure that, being a TUN device, the remote server cannot reach you in that IP.

Said that, jssip 2.X uses the `rtcninja` dependency which includes some options to timeout local ICE gathering by using custom `pcConfig` settings that are not standard so are no longer available in jssip 3.X:

https://github.com/eface2face/rtcninja.js/blob/master/docs/RTCPeerConnection.md#new-rtcninjartcpeerconnectionpcconfig-constructor

Please confirm whether you are using those `rtcninja` cusotm settings in your calls.

**Comment by zenichev** [comment]
@ibc 
I will check as soon as possible and report here.

**Comment by zenichev** [comment]
Problem solved by adding connection attribute.

**Comment by adejongh** [comment]
Example, if you don't mind?  Could save some other people some time.

**Comment by ibc** [comment]
Which "connection" attribute? And where did you put that?

**Comment by zenichev** [comment]
http://jssip.net/documentation/3.2.x/api/session/#attribute_connection

The underlying RTCPeerConnection instance associated to this session. Use it to set events related to WebRTC (such as onaddstream*, onaddtrack, etc).

event.session.connection.addEventListener('addstream', function (event) {
     _remoteVideo.srcObject = event.stream;
});

**Comment by talbahir** [comment]
First I'd like to give 1000 thanks to jmillan for the hard work and creation of JsSIP.
I'm new to WebRTC, and wracked my head for days about why all works in my Asterisk/Ubuntu telephony system, all but sound in the WEB phone. I end up adding the below code and solved it. 
My 1 cent contribution - I'd expect the  call() function to accept the Audio and optionally the Video objects as  MANDATORY parameters.

Something like this: ua.call(cTarget, oAudio[, oVideo] [,options])

Personally, till then, here is what works for me:
Before the ua.start():
	window.oSipAudio = document.createElement("audio");

	window.oCall = ua.call(target,options); //options
	window.oCall.connection.onaddstream = function(e)
		{
		window.oSipAudio.srcObject = e.stream;
		// I think no need. 2.28.19: window.oSipAudio.play()
		}

Also - In the icecandidate event, I'd add to the event 3ed parameter: lLast.
lLast should be placed to true when last candidate added, so you could run the ready() upon it and save 15 seconds delay.
Like:
	  'icecandidate': function(e) 
			{
			n(e.candidate.candidate);
			if (e.lLast) {e.ready();}
			}
Again, 1000 thanks.
