### ISSUE TITLE
rtcOfferConstraints not respected in outbound dial

### ISSUE THREAD

**Issue by johnryan** [versatica/JsSIP#503]
It appears that the rtcOfferConstraints is not picked up despite being set in the dial options:

I see this in the webrtc-internals in chrome:
```
options: {offerToReceiveVideo: 0, offerToReceiveAudio: 1, voiceActivityDetection: true, iceRestart: false}
```
Despite setting:
```
rtcOfferConstraints: {
      offerToReceiveAudio: {exact: 1},
 }
```

https://jsfiddle.net/qmz4eLo3/

**Comment by ibc** [comment]
Not a bug. Chrome's webrtc-internals show what Chrome understands after it processes the given settings/params. Same happens in getUserMedia and so on.
