### ISSUE TITLE
ua.call documentation issue

### ISSUE THREAD

**Issue by mattdimeo** [versatica/JsSIP#504]
The ua.call documentation for 3.2.x on the website has a snippet:
    // HTML5 <video> elements in which local and remote video will be shown
    var views = {
      'selfView':   document.getElementById('my-video'),
      'remoteView': document.getElementById('peer-video')
    };
This object is not used in the following code.

in 3.2.4, the header documentation in UA.js for ua.call has "-param {object} views", suggesting it should be passed to the method, but the actual signature of the method is call(target, options), with no view parameter.

Finally, the tryit demo code calls it as MyPhone.call(uri, selfView, remoteView, {audio: true, video: $('#video').is(':checked')}); which is a four-parameter form that matches neither the inline call() documentation, the call() signature, or the online documentation snippet.

I'd offer a patch to fix this if I had the first clue how this was all actually supposed to work.  I found this while trying to get an audio call working (microphone works but hear no audio).

**Comment by ibc** [comment]
> in 3.2.4, the header documentation in UA.js for ua.call has "-param {object} views", suggesting it should be passed to the method, but the actual signature of the method is call(target, options), with no view parameter.

Well, that's just an old comment (fixed/removed now in master). Please, the only source of documentation of the JsSIP API is the one exposed in the [website](http://jssip.net/documentation/).


> Finally, the tryit demo code calls it as MyPhone.call(uri, selfView, remoteView, {audio: true, video: $('#video').is(':checked')}); which is a four-parameter form that matches neither the inline call() documentation, the call() signature, or the online documentation snippet.

That's just a different `call()` method. Please, check what is inside it. There, inside, is where `ua.call()` is called.

Again, the doc is in the website, and not in the tryit demo app.


I'd offer a patch to fix this if I had the first clue how this was all actually supposed to work.  I found this while trying to get an audio call working (microphone works but hear no audio).

Thanks, but there is nothing to fix (unless you find a bug in the official documentation).

**Comment by mattdimeo** [comment]
Isn't the unused views object in the official documentation a bug?

**Comment by ibc** [comment]
Well, it's just a typo in a example code. Can be removed, yes.
