### ISSUE TITLE
JsSIP does not respect Allow header

### ISSUE THREAD

**Issue by mEkblom** [versatica/JsSIP#506]
It seems that JsSIP does not respect the Allow header from other UAs. In our case this causes interrupted calls, JsSIP sends an UPDATE and because it does not get a response it terminates the call after 75 seconds (caused by timer). We have no way of influensing what other UAs send so we can't implement UPDATE there. Respecting the Allow header would solve the problem.

With the following Allow header:
`Allow: INVITE, ACK, CANCEL, BYE, NOTIFY`
JsSIP should not send any UPDATEs, I hope this will get fixed soon.

**Comment by ibc** [comment]
Well, if the other endpoint does not support UPDATE it **MUST** reply "405 Method Not Supported" rather than nothing, so that's a bug in the other endpoint. You can, anyway, disable Session Timers in JsSIP or even using re-INVITE rather than UPDATE for Session Timers:

http://jssip.net/documentation/3.2.x/api/ua_configuration_parameters/#parameter_session_timers_refresh_method

**Comment by mEkblom** [comment]
Sure it is an error (not replying at all) but this is PSTN call so we have no idea where it goes wrong. We can't implement a response on our side...

We would very much appreciate if JsSIP would respect the Allow header (because that what is for). This happens in multiple environments so apperently it is not uncommon that there will be no reponse to an UPDATE (happened with some ip conferencing software also).

Thank you for the suggested work-around, we will look into it. But respecting the Allow header would be the preferred solution.

**Comment by ibc** [comment]
The fact that there is a bug somewhere in the PSTN does not mean that the solution should be in JsSIP side. The SIP UPDATE method was defined in 2002. It's unbelievable that in 2018 there are SIP servers/endpoints that do not implement it or, worse, they don't reply 405 (which is defined and explained in RFC 3261). We cannot assume that JsSIP must provide solutions or workarounds for thirdy party problems.

I'll reopen this issue to properly react on the remote `Allow` header.

**Comment by mEkblom** [comment]
Thank you and I completly agree with you but sadly in a real production environment we have to live with all kinds of hard/soft phone endpoints and oddities.

I noticed in the RFC that "entities that insert the Session-Expires header field SHOULD NOT choose values of less than 30 minutes" but it seems that you by default use the minimum 90 seconds. You might also consider to change this (there seems to be no config setting for this).

**Comment by ibc** [comment]
Honestly, I don't understand why `Session-Expires` should not be placed if less than 30 minutes. But, anyway, the RFC clearly says:

>  In other words, SIP entities MUST be prepared to handle
   Session-Expires header field values of any duration greater than 90
   seconds

That's a **MUST** which overcomes the **SHOULD** :)

**Comment by mEkblom** [comment]
Maybe I missunderstand you but there is no requirement that it should not be set if less than 30 minutes. The requirement is that "The absolute minimum for the Session-Expires header field is 90 seconds" but the recommended _defualt_ value should be 30 minutes, expressed as "1800 seconds (30 minutes) is RECOMMENDED as the value for the Session-Expires header".

Thus, JsSIP should set the **default** value to 1800 seconds and not 90 if the RFC is to be followed closely. Also I would suggest introducing a `session_timer_refresh_seconds`.

**Comment by ibc** [comment]
> Thus, JsSIP should set the default value to 1800 seconds and not 90 if the RFC is to be followed closely.

1800 seconds is just a ridiculous value regardless the RFC states that. It's 100% useless.

**Comment by jmillan** [comment]
Closing. This concrete issue is fixes by simply setting to 'invite' the session timer refresh method:
http://jssip.net/documentation/3.2.x/api/ua_configuration_parameters/#parameter_session_timers_refresh_method

Other than that, we'll consider in the future how to act upon received Allow header as more use cases happen.
