### ISSUE TITLE
Jssip configuration with kamailio

### ISSUE THREAD

**Issue by kossivi1984** [versatica/JsSIP#507]
i need the link for an example jssip configuration to inter connected kamailio.
i need the help please ?

**Comment by kossivi1984** [comment]
i need to configure jssip and the interconnected with kamailio. Can someone help me please?

**Comment by ibc** [comment]
You clearly have read this, right?:

> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use the JsSIP Google Group instead:
> 
> https://groups.google.com/forum/#!forum/jssip

Bye.
