### ISSUE TITLE
no session.on("addstream",...) event

### ISSUE THREAD

**Issue by cracker0dks** [versatica/JsSIP#510]
Hey,
here is my code:
```
coolPhone.on('newRTCSession', function(data){ 
    var session = data.session; 
    session.on("addstream",function(e){  
    //Not called
    }
}
```
But addstream is never called... however if I replace it with:
`session.connection.addEventListener('addstream', (e) => { //Called }`
it works. But should also work with .on(...) if you ask me :)

Version JsSIP v3.2.7

**Comment by ibc** [comment]
```js
session.on("addstream",function(e){  
```

Why should that event work? where is it documented?

http://jssip.net/documentation/3.2.x/api/session/#section_events

**Comment by cracker0dks** [comment]
tought so because of: https://gist.github.com/dtolb/79e813d45fac6488e4c67993b393ddda
but you are right it was removed from the api.

**Comment by ibc** [comment]
That's very old, yes. We no longer want to expose a "PeerConnection API wrapper" but, instead, take the PeerConnection itself.
