### ISSUE TITLE
Disconnected event does not deliver data object

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [versatica/JsSIP#511]
jssipInstance.on('disconnected', function(data) { // code here });

The data object is undefined. Concerning the documentation there should be at least socket, error, code and reason in the data object.

**Comment by jmillan** [comment]
True, the `error` data attribute should be there and should be set to `false` in this case, when the transport is closed by the user. 

`code` and `reason`  data attributes are optional and related to disconnection errors. They do not apply here.

http://jssip.net/documentation/3.2.x/api/socket/#event_ondisconnect

Thanks for reporting, I'll update it.

**Comment by ibc** [comment]
In fact, the payload of the `disconnected` event should be refactored. It assumes WebSocket, but that's just when we use the WebSocket transport.

**Comment by jmillan** [comment]
>  It assumes WebSocket, but that's just when we use the WebSocket transport.

Can you point it in the code?

**Comment by ibc** [comment]
Not in the code but in the doc: http://jssip.net/documentation/3.2.x/api/ua/#event_disconnected

**Comment by jmillan** [comment]
> Not in the code but in the doc: http://jssip.net/documentation/3.2.x/api/ua/#event_disconnected

Aha, true. I'll synchronise it ASAP.

**Comment by mariomurrent-softwaresolutions** [comment]
So there will be no more parameters for the disconnect event?

**Comment by jmillan** [comment]
Those documented here: http://jssip.net/documentation/3.2.x/api/ua/#event_disconnected

**Comment by jmillan** [comment]
`UA:disconnected` event payload has been fixed for that case where it was empty.

After reviewing the doc I see that it's aligned with the implementation. Such event does not assume `WebSocket`, but `Jssip:Socket` instance.

**Comment by jmillan** [comment]
If there's any comment on this regard, please speak up.
