### ISSUE TITLE
Question about use of createOffer()

### ISSUE THREAD

**Issue by davies147** [versatica/JsSIP#512]
`pc.createOffer` is used in two scenarios within JsSIP. One in `RTCSession_createLocalDescription`, and one in `RTCSession._receiveInviteResponse` within the 200 response handler.

I have 2 questions about the second use of createOffer().

1) Should `this._rtcOfferConstraints` be passed into createOffer()? The first method always does this, but the second passes no parameters. Personally I have no issues with this because I do not pass any specific constraints to JsSIP.

2) Should the 200 response handler be "more clever" in how it handles received SDP? If the session is in C.STATUS_1XX_RECEIVED, and the SDP is identical to the previously received SDP, then can the renegotiate be skipped completely?

I'm happy to look at coding this, but want some feedback first please.

**Comment by jmillan** [comment]
Hi,

1. The `createOffer()` in the 2XX response handler merely avoids calling `pc.setRemoteDescription()` with a `answer` type description without having been supplied a previous offer, which would result in an error. It probably makes sense to provide it the same option as for the initial one.

2. I prefer to let the media handler do its work and let it decide whether it has something to do with the SDP or nothing at all.
