### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by bohtm4711** [versatica/JsSIP#513]
I've noticed, even when using the demo on the JsSIP website, that while communication is open the memory consumed by the application gradually increases and increases, without ever coming down.

It isn't extremely aggressive, perhaps 5mb per minute, but over the course of an hour or two this can become heavy for lower end machines.

Has anyone else observed the same behaviour?  Could an improvement be made in the library to release memory allocated for portions of the stream that have already been played and therefore are no longer needed?

Here is the demo I was referring to:
https://tryit.jssip.net/

**Comment by bohtm4711** [comment]
I had the same thought initially, but when I try pure WebRTC demoes the memory gradually goes up at the same pace and then gets released.

So the memory goes up 5-10mb and then drops back to where it was.

But WebRTC with JsSIP seems to cause the memory to never release.  Maybe JsSIP has some reference preventing the browser from releasing the memory?

Here are a couple WebRTC demoes I tried:

https://webrtc.github.io/samples/src/content/devices/input-output/

https://appr.tc

**Comment by jmillan** [comment]
After trying [tryit-jssip.net](https://tryit.jssip.net) I see that in fact a leak exists. The JS memory of the tabs running the website grow indefinitely.

How to see it, from Chrome: `Settings -> More tools -> Task Manager`

Press secondary button on the table header and enable `Javascript Memory`. The value inside parentheses represent the amount of memory consumed by the objects accessible in the page.

@bohtm4711 , would you be so kind to open an issue in https://github.com/versatica/tryit-jssip?

Beware that we don't provide maintenance of that demo site, so don't expect an immediate fix.

Thanks for the report.

**Comment by bohtm4711** [comment]
@jmillan Thank you for verifying.  I can open a separate ticket for the demo if you like, but to be honest I think it is an issue with the JsSIP library, not the demo.  I've tested and seen the same behaviour in two other projects that are using the library.

Let me know what you prefer, but I would suggest we re-open this issue and investigate within the library, instead of the demo.

**Comment by jmillan** [comment]
@bohtm4711, check the Chrome task manager and compare with https://appr.tc for example. The memory grows as well. May be related to the statistic information stored by RTCPeerConnection internally.

**Comment by jmillan** [comment]
Closing the issue given that the behaviour is common to WebRTC implementations. Nothing we can see in JsSIP specifically.
