### ISSUE TITLE
FR: From 3.1.3 there is no more dist folder containing jssip.min.js 

### ISSUE THREAD

**Issue by mburger81** [versatica/JsSIP#514]
Not sure why do you removed with the integration of the es5-lib the build/dist folder, but I think for some of us it is very useful if we can still download your latest builded and minified javascript file.

What do you think?

**Comment by ibc** [comment]
I don't understand what you mean. The  `dist/` folder still exists in the Git repository. It just does not exist in the NPM package because it's not needed there at all.


If you want the minified file, take it from the Git repo or from the downloads site: http://jssip.net/download/

**Comment by ibc** [comment]
I don't understand why you'd tell webpack to load a minified js rather than relying in the main entry in package.json.
