### ISSUE TITLE
SIP password can be seen from console log.

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#515]
In console log, in one place used:  **password: NOT SHOWN**
But in other place it can be seen in configuration, that printed in:

UA.js line 50:   debug('new() [configuration:%o]', configuration);

![jssip pwd](https://user-images.githubusercontent.com/10967586/38610454-924323f6-3d89-11e8-8303-bb736cbb1484.png)

**Comment by ibc** [comment]
Irrelevant. You can get the SIP password from JavaScript anyway.
