### ISSUE TITLE
有回音（电流音）

### ISSUE THREAD

**Issue by jonsen-liu** [versatica/JsSIP#516]
Hello, is there an echo or noise JSSIP can solve? I saw a piece of code ‘if (!navigator.mediaDevices) {
    navigator.mediaDevices = {
      getUserMedia: getUserMediaPromise_,
      enumerateDevices: function() {
        Return new Promise(function(resolve) {
          Var kinds = {audio: 'audioinput', video: 'videoinput'};
          Return window.MediaStreamTrack.getSources(function(devices) {
            Resolve(devices.map(function(device) {
              Return {label: device.label,
                Kind: kinds[device.kind],
                deviceId: device.id,
                groupId: ''};
            }));
          });
        });
      },
      getSupportedConstraints: function() {
        Return {
          deviceId: true, echoCancellation: true, facingMode: true,
          frameRate: true, height: true, width: true
        };
      }
    };’
Is this used to solve the echo or noise? But ‘!navigator.mediaDevices’ is always 'false' when I run it.

**Comment by ibc** [comment]
Please just the public mailing list for questions. Also, take into account that your question is not related to JsSIP at all, so you rather ask in any generic form

**Comment by jonsen-liu** [comment]
Sorry, it may be that my expression is not clear. I'm using JSSIP to make web video calls. Every time I open a voice, I have my own voice, but the demo you provided doesn't have my own voice. I've been looking for it for a long time. No way to find, so I think you can help me. As for WebRTC, I use the same one.

**Comment by ibc** [comment]
You may want to mute the `<audio>` or `<video>` element in which you place your local `MediaStream`.  That's not related to JsSIP at all.

**Comment by jonsen-liu** [comment]
Thanks, I got it
