### ISSUE TITLE
Presence feature

### ISSUE THREAD

**Issue by cmargulhano** [versatica/JsSIP#520]
I saw on the site that there is a presence feature.
How can we implement?
I didn't see any documentation about this feature.

**Comment by ibc** [comment]
Please, use the mailing list for questions.

**Comment by cmargulhano** [comment]
Ok thanks a lot for your answer.
I saw you answer here: https://groups.google.com/forum/#!topic/jssip/bafEKFbduJ0
best regards
Cláudio

**Comment by elarafy** [comment]
Please provide the solution if still exist I am not able to access this link
