### ISSUE TITLE
ICE Candidates not added to SDP offer

### ISSUE THREAD

**Issue by dmneasis** [versatica/JsSIP#522]
I'm using JsSIP  in a mobile implementation with an Asterisk backend. I can successfully register to the Asterisk server, and start a call. Then, I can successfully gather the ICE candidates, I get the "null candidate" and "ready" gets fired. However, I can't find the candidates inside the SDP offer to be sent and the call drops.

Now: how to fix this? Can I manually add the ICE candidates to the SDP in some way?

**Comment by ibc** [comment]
Please use the mailing list for questions or problems.
