### ISSUE TITLE
3 Way Call Conference

### ISSUE THREAD

**Issue by akgautam** [versatica/JsSIP#523]
Hello Team,

How can we implement the 3 Ways Call Conference?

![image](https://user-images.githubusercontent.com/15329822/42169162-9111ccca-7e30-11e8-82e4-9401f443a58a.png)

**Comment by ibc** [comment]
Yes, sure! You can do it in the public mailing list.

**Comment by akgautam** [comment]
Where is public mailing list?

**Comment by ibc** [comment]
> Where is public mailing list?

It's told in the text you ignored when you opened a new issue here:

> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use the JsSIP Google Group instead:
> 
> https://groups.google.com/forum/#!forum/jssip
