### ISSUE TITLE
About Jssip Cannot create so many PeerConnection,

### ISSUE THREAD

**Issue by hanweimin** [versatica/JsSIP#532]
I must to repeat a call session, so i set a time by setTimout() function , from call to confrim and hangup, next one by one, but, a later time while show Cannot create so many PeerConnection give me, should i to do this?

if you not see me, you can get this url https://stackoverflow.com/questions/49532939/how-to-clear-rtcpeerconnection-webrtc?answertab=active#tab-top,   

thinks !!

**Comment by ibc** [comment]
Let's discuss this in the mailing list, please. This is not a bug in JsSIP but in Chrome. Said that, test this script in your browser to realize that, even setting the `pc` to null`, it raises an error after creating 500 peerconnections:

```js
for (let i = 0; i <= 512; i++)
{
	console.warn('creating PeerConnection number %s', i);

	pc = new RTCPeerConnection({ iceServers: [] });
	pc.close();
	pc = null;
}
```

**Comment by ibc** [comment]
Or, you can try this more advanced code. It will throw `Cannot create so many PeerConnections` after more than 500 peerconnections. And it will do it regardless you comment or not the `pc = null` line.

```js
let i = 0;

createPeerConnection();

function createPeerConnection()
{
	i++;

	let pc = new RTCPeerConnection({ iceServers: [] });

	console.warn('PC %s created', i);

	pc.onsignalingstatechange = () =>
	{
		if (pc.signalingState !== 'closed')
			return;

		console.warn('PC %s closed', i);

		pc = null; // This does not improve anything.

		setTimeout(() => createPeerConnection(), 100);
	};

	setTimeout(() => pc.close(), 25);
}
```

**Comment by fippo** [comment]
@alvestrand do you have the chrome bug number for this?

**Comment by hanweimin** [comment]
> Or, you can try this more advanced code. It will throw `Cannot create so many PeerConnections` after more than 500 peerconnections. And it will do it regardless you comment or not the `pc = null` line.


hellow, i used by jssip.js[http://www.jssip.net/] , here is not a close function for me to used, 

my views e.g:
----------------------------------------------
let jssipUa = new JsSIP.UA(ua_config);

jssipUa.on('newRTCSession', function(e) {
	let RTC           = e,
	request       = e.request,
	call          = e.session,
	session       = e.session,
	call_id       = request.call_id,
	self          = this;

        call.on('accepted', (e)=>{
              let remoteStreamSrc = URL.createObjectURL(remoteStream);
              remote_element.setAttribute('src', remoteStreamSrc);

             ..................
        });

       call.on('confirmed', function() {
             setTimeout(()=>{
                  session.terminate();
	          jssipUa.call(target, call_opts);
	    }, 10000);
        }
});
-------------------------------------

when a calling had create and accept by confirm function while it`s will auto hangup by session.terminate() and create a new calling.... one by one,     

but my qustion is give me Cannot create so many PeerConnections run later more , i don`t should to do this
