### ISSUE TITLE
Check new Chrome and Firefox versions

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#533]
As reported here, latest versions of both browsers cannot establish a media communication:

https://groups.google.com/forum/#!topic/jssip/GEVluQboAgM

Of course, we should also consider upgrading the internal WebRTC API usage of JsSIP and move to "tracks" (instead of "streams") and also use the Transceiver and/or the RtpSender/RtpReceiver APIs.

Or we may just consider decoupling the WebRTC stack from JsSIP into a separate library and make JsSIP just a SIP library.

**Comment by pavelsc** [comment]
I checked reported issues and have slightly different results - in FF Nightly 64.0a1 outgoing audio calls are possible, but incoming audio calls cannot be answered. Is there any quick workaround?

**Comment by ibc** [comment]
No, there is no "quick workaround". This must be properly investigated.

**Comment by rossbcan** [comment]
I have no audio problems incoming/outgoing with both FF and Chrome current releases:

FF: 62.0.2 (64 Bit) up to date
Google Chrome is up to date
Version 69.0.3497.100 (Official Build) (64-bit)

Video failures described here: https://groups.google.com/forum/#!topic/jssip/GEVluQboAgM

Using JsSIP 3.2.12 and this client: https://www.rossco.org/JsSip_test.htm

Regards;
Bill

**Comment by ekadesign** [comment]
if your connect losting with 'bad media description' and you can see something about rtcp_mux in the webrtc-internals you need put this code in the options object 
`        pcConfig: {
          rtcpMuxPolicy: 'negotiate'
        }`

**Comment by Arinteck** [comment]
Have the same issue and waiting for fix or workaround.

**Comment by Arinteck** [comment]
> put this on your options section, after constraints
pcConfig: { rtcpMuxPolicy: 'negotiate' }

Unfortunately, It doesn't work :(

**Comment by ibc** [comment]
> Unfortunately, It doesn't work :(

Because nowhere it's said that it's a proper "fix" for the issue.

**Comment by ekadesign** [comment]
> > put this on your options section, after constraints
> > `pcConfig: { rtcpMuxPolicy: 'negotiate' }`
> 
> To fix what?

to fix MuxPolicy. Special for chrome. If you have same issue on your firefox, you need to check your audio device and permissions.

**Comment by ibc** [comment]
> to fix MuxPolicy. Special for chrome. If you have same issue on your firefox, you need to check your audio device and permissions.

Sorry Konstantin, what you say is completely unrelated to the problem described in this issue. This is not about `rtcpMuxPolicy` at all (properly supported by both Chrome and Firefox) nor about "audio device permissions".

**Comment by rossbcan** [comment]
@ibc Is the fix (WebRTC API updates) in the works? I would hate to have to change stacks to meet production schedule.
Has the effort / changes been scoped, resources assigned?

**Comment by ibc** [comment]
Well, JsSIP is a community driven project and we, the developers and maintainers get no money from it. So not sure what to say about "allocating resources". If you need this fix for your production environment you can priorize it via donation.

**Comment by ibc** [comment]
@rossbcan

![ce41nauwwaaqfic1](https://user-images.githubusercontent.com/16191/46358599-a19aad80-c667-11e8-9605-a7bb9c334b16.jpg)

**Comment by rossbcan** [comment]
@Ibc - Hah!

I heard you, and, if I was not a garage entrepreneur, on a shoestring budget, I would be donating from my (daddy warbucks) corporate employer, even before "needy socialists" (is there any other kind?)

Alas, I can only hope that this issue is correctly perceived as a show stopper and fixed, B4 I am forced to find alternatives (or, do the media connections in my app)

Great picture. I also share your disdain for the "something from nothing" crowd (which is always from "other people's" money).

And, I do intend to "give back" with my demo app, far easier than tryit-jssip (which I believe you once called "spaghetti code" and, I agree. Definitely not KISS.

I chose JsSIP, because I admire / respect your work.

</rant

**Comment by feonit** [comment]
If I add this adapter `webrtc-adapter` to build code, then I catch the error `BAD_MEDIA_DESCRIPTION`
in this strings:
```js
/* ... */
var _answer = new RTCSessionDescription({
  type: 'answer',
  sdp: _e.sdp
});

this._connectionPromiseQueue = this._connectionPromiseQueue.then(function () {
  // Be ready for 200 with SDP after a 180/183 with SDP.
  // We created a SDP 'answer' for it, so check the current signaling state.
  if (_this22._connection.signalingState === 'stable') {
    return _this22._connection.createOffer(_this22._rtcOfferConstraints).then(function (offer) {
      return _this22._connection.setLocalDescription(offer);
    }).catch(function (error) {
      _this22._acceptAndTerminate(response, 500, error.toString());

      _this22._failed('local', response, JsSIP_C.causes.WEBRTC_ERROR);
    });
  }
}).then(function () {
  _this22._connection.setRemoteDescription(_answer).then(function () {
    // Handle Session Timers.
    _this22._handleSessionTimersInIncomingResponse(response);

    _this22._accepted('remote', response);

    _this22.sendRequest(JsSIP_C.ACK);

    _this22._confirmed('local', null);
  }).catch(function (error) {
    _this22._acceptAndTerminate(response, 488, 'Not Acceptable Here');

    _this22._failed('remote', response, JsSIP_C.causes.BAD_MEDIA_DESCRIPTION);

/* ... */
```

where `console.log(_answer.sdp)` console shows:

```js
v=0
o=- 2 1548090765696 IN IP4 /*my ip...*/
s=MediaMixerSession
c=IN IP4 /*my ip...*/
t=0 0
a=ice-lite
m=audio 55978 UDP/TLS/RTP/SAVPF 111 9 0 8
c=IN IP4 /*my ip...*/
a=sendrecv
a=rtcp-mux
a=mid:audio
a=candidate:1 1 UDP 33554431 /*my ip...*/ 55978 typ host
a=ice-ufrag:1E101D202B2877EA
a=ice-pwd:63C3E15FD511E7D65732483B7BE44BFB76F2EEB0006E
a=fingerprint:sha-256 BF:91:BD:43:99:63:BE:2E:B2:DA:E3:27:8A:10:3A:F8:00:A1:D2:D4:F5:90:CF:80:07:5F:B5:AD:71:E6:3C:D2
a=setup:passive
a=connection:new
a=ssrc:323441880 cname:2@lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf
a=ssrc:323441880 mslabel:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf
a=ssrc:323441880 msid:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf a0
a=ssrc:323441880 label:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccfa0
a=rtpmap:111 opus/48000/2
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
m=video 59954 UDP/TLS/RTP/SAVPF 96 108 119 101 99 97 109 122 107 121 120
c=IN IP4 /*my ip...*/
a=sendrecv
a=rtcp-mux
a=mid:video
a=framerate:30
a=candidate:1 1 UDP 33554431 /*my ip...*/ 59954 typ host
a=ice-ufrag:25ECD61924FDC95F
a=ice-pwd:A919CA5B0BE654E8F54BEB8E1CAB876BC1332E335178
a=fingerprint:sha-256 BF:91:BD:43:99:63:BE:2E:B2:DA:E3:27:8A:10:3A:F8:00:A1:D2:D4:F5:90:CF:80:07:5F:B5:AD:71:E6:3C:D2
a=setup:passive
a=connection:new
a=ssrc-group:FID 1683972439 1096594626
a=ssrc:1683972439 cname:2@lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf
a=ssrc:1683972439 mslabel:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf
a=ssrc:1683972439 msid:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf v0
a=ssrc:1683972439 label:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccfv0
a=ssrc:1096594626 cname:2@lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf
a=ssrc:1096594626 mslabel:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf
a=ssrc:1096594626 msid:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccf v0
a=ssrc:1096594626 label:lms15161-9d02445f-f5f7-4563-9833-caa7c91b9ccfv0
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 goog-remb
a=rtpmap:108 H264/90000
a=fmtp:108 profile-level-id=4d0032; packetization-mode=1
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 goog-remb
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=96
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=96
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=96
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=96
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=96
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=96
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=96
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=96
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* ccm fir
a=rtcp-fb:* ccm tmmbr
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
```

And without that adapter in chrome it works but not in FF

If i add how suggested in https://github.com/versatica/JsSIP/issues/533
```
pcConfig: { rtcpMuxPolicy: 'negotiate' }
```

It does not help

Google Chrome 71.0
FF 62.0

**Comment by luanyata** [comment]
Firefox 68 for Mac OS run

**Comment by jmillan** [comment]
Re-tested  [demo](https://tryit.jssip.net) in modern browsers in Mac OS with no issue.
