### ISSUE TITLE
newRTCSession connection is null

### ISSUE THREAD

**Issue by mxp100** [versatica/JsSIP#536]
version 3.2.13

`        this.phone.on('newRTCSession', (e) => {
            let session = e.session;

            this.addSession(session);

            if (session.direction === 'incoming') {
                $('#btnAnswer').removeClass('d-none');
                session.answer({
                    mediaConstraints: {
                        audio: true,
                        video: false,
                    }
                });
            }

            session.connection.addEventListener('addstream', (event) => {
                this.audio.src = window.URL.createObjectURL(event.stream);
                this.audio.play();
            });

        });`

BUG! session.connection is null (it works correctly in 3.2.12)

**Comment by jmillan** [comment]
Yes..,

3.2.13 has actually modified this, making it symmetric for outgoing and incoming calls. `UA.New newRTCSession` fires first (without RTCPeerConnection yet) and later `RTCSession.connection` fires when the RTCPeerConnection is created.

My mistake for not having created a new mayor release. Let me fix it.

**Comment by jmillan** [comment]
Hi,

The change 3.2.13 release has been reverted since it requires a mayor version upgrade for a cosmetic change.

Thanks for reporting @mxp100
