### ISSUE TITLE
Outgoing call Bad media description

### ISSUE THREAD

**Issue by 3dluis** [versatica/JsSIP#537]
When answering an outgoing call, the bad media description error is occurring. I have a listener for the peerconnection addstream event and it does not work, something has to do with permissions or microphone or audio resource. I am using asterisk as pbx.

this.session.on('peerconnection', function(call) {
      call.peerconnection.addEventListener('addstream', function (e) {
        // set remote audio stream
        this.remoteAudio.src = window.URL.createObjectURL(e.stream);
       // this.remoteAudio.play();
      });
    });

**Comment by ibc** [comment]
Please, use the public mailing list for usage questions/problems.
