### ISSUE TITLE
SIP Issue User Denied Media Access (JsSIP 0.7.11)

### ISSUE THREAD

**Issue by adnanghazanfar** [versatica/JsSIP#546]
I am facing a very weird issue with JsSIP (0.7.11). Our scenario is we originate phone and then SIP account and bridge both legs(from the backend Freeswitch). In browser I auto answer the call in this case. When I originate second leg I mean SIP account for some users(using latest chrome on windows 7) call is failing with "User Denied Media Access", In browser I dont see notification to allow/block mic. For the same users when they originate call from the browser call is going through with no issues.

Our code is 
sipPhone.on( 'newRTCSession', function ( rtcSession ) {
       rtcSession.session.answer()
       handlersForSession(rtcSession.session)
}

handlersForSession:function(session){

        session.on('progress',function(e) {
            UTILITY.logMessageWithTimeStamp('Call in progress')
            console.log(e)
        })

        session.on('accepted',function(e) {
            UTILITY.logMessageWithTimeStamp('Call Accepted with details below')
            console.log(e)
        })

        session.on('confirmed',function(e) {
            UTILITY.logMessageWithTimeStamp('Call confirmed with details below')
            console.log(e)
        })

        session.on('addstream',function(e) {
            UTILITY.logMessageWithTimeStamp('Reached in Add Stream')
            console.log(e)
            document.getElementById('audio_of_remote_side').srcObject = e.stream;

        })

        session.on('failed',function(e) {
            console.log('Call Failed with reason below')
            console.log(e)
        })

        session.on('ended',function(e) {
            UTILITY.logMessageWithTimeStamp("Call Ended with details below: ")
            console.log(e)
        })

}

​JsSIP log :
Connected to FS
Registered to FS
Have come to newRTC Session
Auto answered.
Call in Progress with details below: 
{originator: "local", response: null}
Call Failed with reason below
{originator: "local", message: null, cause: "User Denied Media Access"}cause: "User Denied Media Access"message: nulloriginator: "local"__proto__: Object​

​I tried passing below options to answer method but now call is terminating immediately with no error. Can anyone please help me on this.

var callOption = {
    mediaConstraints: {'audio': true, 'video': false},
    rtcOfferConstraints: {'offerToReceiveAudio': true, 'offerToReceiveVideo': false},
    sessionTimersExpires: 7200
};

rtcSession.session.answer(callOption)

**Comment by ibc** [comment]
Mailing list.
