### ISSUE TITLE
there is a   problem  when i answer a call 

### ISSUE THREAD

**Issue by tianzhenjiu** [versatica/JsSIP#557]
when  i  anser a call  it's throw a exception:"Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp.“  in  chrome
and    when i  use  firfox  throw  "Invalid description, no ice-ufrag attribute"

how  can i  solve  it?

**Comment by tianzhenjiu** [comment]
help me ! why r  u close it?

**Comment by ibc** [comment]
Because you ignored the issue template and instructions to use the mailing list for questions.
