### ISSUE TITLE
REGISTER OK without Contact ignored. So response 401, don't fire event 'registrationFailed'

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#558]
In the last version: 3.3.2
REGISTER OK without Contact is ignored.
So if use wrong user name/password, SIP server answer 401 Unauthorized.
The SIP response don't contains 'Contact', so will be ignored.
Event 'registrationFailed' that was created in previous versions, don't created now.

sending message:

REGISTER sip:audiocodes.com SIP/2.0
Via: SIP/2.0/WSS b4hss34vj6l1.invalid;branch=z9hG4bK8449099
Max-Forwards: 69
To: <sip:web1@audiocodes.com>
From: "Web1" <sip:web1@audiocodes.com>;tag=setnj0bd9v
Call-ID: h0k99rrs7fll1daha70uql
CSeq: 1 REGISTER
X-SBC: AudioCodes Mediant
Contact: <sip:3f1c3m5e@b4hss34vj6l1.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:fcef384d-3e88-4d0d-8a7d-f95cf35f17cb>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: path,gruu,outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 0

14:25:07.385 jssip.js:26607 send()
14:25:07.601 jssip.js:26607 received WebSocket message
14:25:07.601 jssip.js:26607 received text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS b4hss34vj6l1.invalid;branch=z9hG4bK8449099
From: "Web1" <sip:web1@audiocodes.com>;tag=setnj0bd9v
To: <sip:web1@audiocodes.com>;tag=1c1705502188
Call-ID: h0k99rrs7fll1daha70uql
CSeq: 1 REGISTER
www-authenticate: Digest realm="DefaultSipRealm",nonce="Mjk0OTczMTQ0MToxNDMxMzIwMTY3",qop="auth",algorithm=MD5
Content-Length: 0

14:25:07.612 jssip.js:26607 authenticate() | response generated
14:25:07.614 jssip.js:26607 send()
14:25:07.615 jssip.js:26607 sending message:

REGISTER sip:audiocodes.com SIP/2.0
Via: SIP/2.0/WSS b4hss34vj6l1.invalid;branch=z9hG4bK7858254
Max-Forwards: 69
To: <sip:web1@audiocodes.com>
From: "Web1" <sip:web1@audiocodes.com>;tag=setnj0bd9v
Call-ID: h0k99rrs7fll1daha70uql
CSeq: 2 REGISTER
Authorization: Digest algorithm=MD5, username="web1", realm="DefaultSipRealm", nonce="Mjk0OTczMTQ0MToxNDMxMzIwMTY3", uri="sip:audiocodes.com", response="4d0d5efc437c0c09ff9d023e76d43c2d", qop=auth, cnonce="f1ipkfe974c4", nc=00000001
X-SBC: AudioCodes Mediant
Contact: <sip:3f1c3m5e@b4hss34vj6l1.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:fcef384d-3e88-4d0d-8a7d-f95cf35f17cb>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: path,gruu,outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 0

14:25:07.615 jssip.js:26607 send()
14:25:07.830 jssip.js:26607 received WebSocket message
14:25:07.831 jssip.js:26607 received text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS b4hss34vj6l1.invalid;branch=z9hG4bK7858254
From: "Web1" <sip:web1@audiocodes.com>;tag=setnj0bd9v
To: <sip:web1@audiocodes.com>;tag=1c1119337271
Call-ID: h0k99rrs7fll1daha70uql
CSeq: 2 REGISTER
www-authenticate: Digest realm="DefaultSipRealm",nonce="Mjk0OTczMTY3MToyMDUyOTcyMzc4",qop="auth",algorithm=MD5
Content-Length: 0

14:25:07.836 jssip.js:26607 **no Contact header in response to REGISTER, response ignored**

**Comment by ibc** [comment]
You are right. Thanks for reporting. It should be fixed now in master.

**Comment by ibc** [comment]
jssip 3.3.3 released.
