### ISSUE TITLE
logging the intermediate values of DIGEST computations

### ISSUE THREAD

**Issue by dpocock** [versatica/JsSIP#561]
I added some extra logging in reSIProcate to log the DIGEST computations on the server side.  https://github.com/resiprocate/resiprocate/commit/e6d84cc85e10e4171e6acfca2938318767cb31f5

The things that are really useful for comparison between client and server:
- when using auth-int, the size of the message body - specifically, the number of bytes given to the hash function, not just the value of the Content-Length header
- the A2 value, before it is hashed (when using auth-int, the MD5 hash of the body should appear as it is part of A2)
- the value that will be hashed to create the "response" parameter, in other words, log "A1:nonce:A2"

Note: the A1 value can be used to impersonate a user.  An attacker doesn't need to know the user's password, they only need the A1 value.  So I recommend that any logging of this value is only visible when explicitly requested by a developer, e.g. at the "debug" level and maybe with a configuration setting to permit logging of sensitive values during debugging.  These precautions are not necessary when logging the A2 value.

**Comment by ibc** [comment]
Hi Daniel, JsSIP does not log to the console the `ha1` value provided by the app. Is there anything that should be changed in JsSIP in your opinion?

**Comment by dpocock** [comment]
Where you do this (it is repeated in a few places):
```
ha2 = Utils.calculateMD5("".concat(this._method, ":").concat(this._uri));
```
it would be very useful to log the string before doing MD5

E.g
```
a2 = "".concat(this._method, ":").concat(this._uri);
log(a2);
ha2 = Utils.calculateMD5(a2);
```

Same for the response:

```
this._response = Utils.calculateMD5("".concat(this._ha1, ":").concat(this._nonce, ":").concat(ha2));
```

and here:

```
ha2 = Utils.calculateMD5("".concat(this._method, ":").concat(this._uri,":").concat(Utils.calculateMD5(body ? body : '')));
```

it would be useful to do something like this:
```
_body = body ? body : '';
log("Body length = " ....
a2 = "".concat(this._method, ":").concat(this._uri, ":").concat(Utils.calculateMD5(_body));
log(a2);
ha2 = Utils.calculateMD5(a2);
```

**Comment by jmillan** [comment]
Hi @dpocock,

I still don't see how is it useful to log such information.

**Comment by dpocock** [comment]
If the response string on the client and server don't match, it allows us to find the root cause more quickly, e.g. logging the body length just before MD5 allows us to see if some of the body has been truncated somewhere.  Otherwise the response string is opaque and the reason for a mismatch is impossible to guess.

**Comment by jmillan** [comment]
:+1:

**Comment by ibc** [comment]
I've added some logs in the `authenticate()` method (it logs the `qop` and the value of `a2`). It does not print the body length since it requires some computation and it can be readt from the `Content-Length` anyway.

**Comment by dpocock** [comment]
@ibc thanks for the fast response on this.  The reason I suggested body length is in case the body is truncated or a byte is lost before doing the MD5 calculation.  In such situations, the Content-Length header may not match the size of the body that was hashed.  The body MD5 is visible when logging the A2 value, so at least somebody can see that the MD5 value matches on client and server.  But if they ever fail to match, the length would be a useful clue to begin troubleshooting.

**Comment by ibc** [comment]
You can inspect/print the body length in your JS app before the SIP message does even leave the browser, and then correlate it with the digest logs added today in JsSIP latest version.
