### ISSUE TITLE
Script Errors in Internet Explorer 11

### ISSUE THREAD

**Issue by MarkusElmer** [versatica/JsSIP#568]
Hi
According to the Interoperability section Web Sockets are supported by IE11.
If i use JsSIP with IE11 it crashes because of Script/Syntax Errors. Are there any Polyfills i can use or is IE11 not supported in general by JsSIP. Even the test page fails in IE11: http://tryit.jssip.net/
Best Regards
Markus

**Comment by ibc** [comment]
Please, use the JsSIP public mailing list for questions.

**Comment by MarkusElmer** [comment]
sry
