### ISSUE TITLE
registered event is not fired after us start

### ISSUE THREAD

**Issue by ceniymei** [versatica/JsSIP#570]
Hi,

I have a problem with the registered event.After UA start and sip 200 is received, the registered event is not triggered. I checked other event like connected, connecting. They are working except registered.

JsSIP  version , 3.3.5

``
    config.register = true;
    this.ua = new JsSIP.UA(config);
    this.ua.start();
    this.ua.on("registered", function() {
      console.log("registered");
    });
``

Sip register response
<img width="446" src="https://user-images.githubusercontent.com/4560845/54286061-13dfc880-45de-11e9-8259-30bc2cbd8d42.png">

Thanks
Ceniy Mei

**Comment by ibc** [comment]
Please, usage questions/problems in the public mailing list.
