### ISSUE TITLE
window is not defdined 

### ISSUE THREAD

**Issue by Maxmaxmaximus3** [versatica/JsSIP#571]
nodejs

![image](https://user-images.githubusercontent.com/47686234/54769290-f4feb900-4c11-11e9-8f32-b1af9f3aee22.png)

**Comment by ibc** [comment]
Yes, you cannot use JsSIP in Node to make SIP calls.

**Comment by iMegaMaximus2** [comment]
@ibc 

https://www.npmjs.com/package/jssip

![image](https://user-images.githubusercontent.com/49617181/57971775-2211e280-799b-11e9-82c9-0b642eddda4f.png)

**Comment by ibc** [comment]
Fuck you @iMegaMaximus2.

**Comment by iMegaMaximus2** [comment]
> Fuck you @iMegaMaximus2.

**I threw a report. This behavior is not allowed on github**
