### ISSUE TITLE
Tryit JsSIP Not work on Safari 12.* on macOS Mojave

### ISSUE THREAD

**Issue by rafaelrmou** [versatica/JsSIP#575]
1 - Open Safari 12 on macOS Mojave (First Device)
2 - Acess Tryit.jssip.net
3 - Login with one extension
4 - Open Safari 12 on macOS Mojave (Second Device)
5 - Acess Tryit.jssip.net
6 - Login with one extension
7 - Make a video call
8 - App crash (Gray screen)

**Comment by ibc** [comment]
It's possible, but we don't want to have issues here in the JsSIP project just because the demo apps fails with a specific browser. If you can specify and details what fails feel free to open a new issue explaining it.
