### ISSUE TITLE
The JSSIP library is not working correctly in Safari 12 of the macOS Mojave

### ISSUE THREAD

**Issue by rafaelrmou** [versatica/JsSIP#576]
The JSSIP library is not working correctly in Safari 12 of the macOS Mojave .

It turns out that the getRemoteStreams function is always returning null or empty after a call is answered or performed.

Even by placing the required properties in the video fields (playinline, autoplay and controls), the library is not able to retrieve the remote stream with the getRemoteStreams method.

**Comment by ibc** [comment]
Yes, definitely we have to modernize the internal WebRTC API usage. Known issue.

**Comment by rafaelrmou** [comment]
Is there a plan to apply this update? I tested with WebRTC (https://appr.tc/) and noticed it works normally.

Any prevision? I need this update with a certain emergency. I am willing to help financially with a contribution to the project.

**Comment by ibc** [comment]
Contact us privately at info@versatica.com and we'll discuss it.
