### ISSUE TITLE
not able to hear receiver voice , however receiver is able to listen dialler voice

### ISSUE THREAD

**Issue by piyushSinghalDemo** [versatica/JsSIP#579]
var socket = new JsSIP.WebSocketInterface(‘domain ip’);

       // Add the sip uri, socket and password and pass it to User Agent
       var configuration = {
           stun_server: “stun.l.google.com:19302”,
           sockets: [socket],
           uri: ‘uri’,
           password: number,
           authorization_user: number + “”,
           display_name: number + “”,
           hostport_params: “domain”,
           // no_answer_timeout: 60000,
           realm: “domain”,
           register: true,
           // register_expires: 600,
           use_preloaded_route: false,
           session_timers: false
       };

       using media 
     "https://www.soundjay.com/button/sounds/beep-01a.mp3"

   session.on('addstream', function(e){
                  incomingCallAudio.pause();
                    console.log(e.stream)
                    var remoteView = document.getElementById('search-remote-view')
                   remoteView.src = window.URL.createObjectURL(e.stream);
                   remoteView.play();
                });

**Comment by ibc** [comment]
Use the mailing list for usage questions or problems.
