### ISSUE TITLE
Incompatible SDP issue with telnyx sip points

### ISSUE THREAD

**Issue by amsabalecha** [versatica/JsSIP#582]
Hello There,

I'm trying to implement JSSIP with Telnyx SIP endpoint. in which endpoint are registered successfully, But outgoing calls getting cut just after one ring and in case of an incoming call, event of incoming is shown in the dev console but calls not working. 
In case of an outgoing call I'm getting error code 488 and Error was **cause: "Incompatible SDP"**
you can check below error object that is actual hangup cause of the call.
I talk with Telnyx support and they ask me to change the audio codec setting (**It is an issue with the media attributes**) with call. can you guys help me how can I change media attributes?. Last reply from Telnyx support is _(The only thing I can say is to try to make it so the codec used is a=rtpmap:0 PCMU/8000)_

{
  "headers": {
    "Via": [
      {
        "raw": "SIP/2.0/WSS sip.telnyx.com;rport=39746;received=27.109.18.82;branch=z9hG4bK9285430",
        "parsed": {
          "protocol": "SIP",
          "transport": "WSS",
          "host_type": "IPv4",
          "host": "sip.telnyx.com",
          "received": "27.109.18.82",
          "branch": "z9hG4bK9285430"
        }
      }
    ],
    "Max-Forwards": [
      {
        "raw": "68",
        "parsed": 68
      }
    ],
    "From": [
      {
        "raw": "<sip:hasnen8****@sip.telnyx.com>;tag=1e3hkfmgdn",
        "parsed": {
          "uri": {
            "parameters": {},
            "headers": {}
          },
          "parameters": {
            "tag": "1e3hkfmgdn"
          }
        }
      }
    ],
    "To": [
      {
        "raw": "<sip:+1228200****@sip.telnyx.com>;tag=0U70QDFQ3Fj9e",
        "parsed": {
          "uri": {
            "parameters": {},
            "headers": {}
          },
          "parameters": {
            "tag": "0U70QDFQ3Fj9e"
          }
        }
      }
    ],
    "Call-ID": [
      {
        "raw": "4h44gqe8oiiau272dh5e",
        "parsed": "4h44gqe8oiiau272dh5e"
      }
    ],
    "CSeq": [
      {
        "raw": "3131 INVITE",
        "parsed": {
          "value": 3131,
          "method": "INVITE"
        }
      }
    ],
    "Allow": [
      {
        "raw": "INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, NOTIFY"
      }
    ],
    "Supported": [
      {
        "raw": "path, replaces"
      }
    ],
    "Allow-Events": [
      {
        "raw": "talk, hold, conference, refer"
      }
    ],
    "Reason": [
      {
        "raw": "Q.850;cause=88;text=\"INCOMPATIBLE_DESTINATION\""
      }
    ],
    "Content-Length": [
      {
        "raw": "0",
        "parsed": 0
      }
    ]
  },
  "status_code": 488,
  "reason_phrase": "Not Acceptable Here",
  "data": "SIP/2.0 488 Not Acceptable Here\r\nVia: SIP/2.0/WSS sip.telnyx.com;rport=39746;received=27.109.18.82;branch=z9hG4bK9285430\r\nMax-Forwards: 68\r\nFrom: <sip:hasnen****@sip.telnyx.com>;tag=1e3hkfmgdn\r\nTo: <sip:+1228200****@sip.telnyx.com>;tag=0U70QDFQ3Fj9e\r\nCall-ID: 4h44gqe8oiiau272dh5e\r\nCSeq: 3131 INVITE\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, NOTIFY\r\nSupported: path, replaces\r\nAllow-Events: talk, hold, conference, refer\r\nReason: Q.850;cause=88;text=\"INCOMPATIBLE_DESTINATION\"\r\nContent-Length: 0\r\n\r\n",
  "via": {
    "protocol": "SIP",
    "transport": "WSS",
    "host_type": "IPv4",
    "host": "sip.telnyx.com",
    "received": "27.109.18.82",
    "branch": "z9hG4bK9285430"
  },
  "via_branch": "z9hG4bK9285430",
  "from": {
    "uri": {
      "parameters": {},
      "headers": {}
    },
    "parameters": {
      "tag": "1e3hkfmgdn"
    }
  },
  "from_tag": "1e3hkfmgdn",
  "to": {
    "uri": {
      "parameters": {},
      "headers": {}
    },
    "parameters": {
      "tag": "0U70QDFQ3Fj9e"
    }
  },
  "to_tag": "0U70QDFQ3Fj9e",
  "call_id": "4h44gqe8oiiau272dh5e",
  "cseq": 3131,
  "method": "INVITE",
  "body": ""
}

**Comment by ibc** [comment]
Sorry. Do not open an issue report in JsSIP GitHub asking for free support for your business. We are not free consultants.

**Comment by gh-hao** [comment]
> Hello There,
> 
> I'm trying to implement JSSIP with Telnyx SIP endpoint. in which endpoint are registered successfully, But outgoing calls getting cut just after one ring and in case of an incoming call, event of incoming is shown in the dev console but calls not working. In case of an outgoing call I'm getting error code 488 and Error was **cause: "Incompatible SDP"** you can check below error object that is actual hangup cause of the call. I talk with Telnyx support and they ask me to change the audio codec setting (**It is an issue with the media attributes**) with call. can you guys help me how can I change media attributes?. Last reply from Telnyx support is _(The only thing I can say is to try to make it so the codec used is a=rtpmap:0 PCMU/8000)_
> 
> { "headers": { "Via": [ { "raw": "SIP/2.0/WSS sip.telnyx.com;rport=39746;received=27.109.18.82;branch=z9hG4bK9285430", "parsed": { "protocol": "SIP", "transport": "WSS", "host_type": "IPv4", "host": "sip.telnyx.com", "received": "27.109.18.82", "branch": "z9hG4bK9285430" } } ], "Max-Forwards": [ { "raw": "68", "parsed": 68 } ], "From": [ { "raw": "sip:hasnen8****@sip.telnyx.com;tag=1e3hkfmgdn", "parsed": { "uri": { "parameters": {}, "headers": {} }, "parameters": { "tag": "1e3hkfmgdn" } } } ], "To": [ { "raw": "sip:+1228200****@sip.telnyx.com;tag=0U70QDFQ3Fj9e", "parsed": { "uri": { "parameters": {}, "headers": {} }, "parameters": { "tag": "0U70QDFQ3Fj9e" } } } ], "Call-ID": [ { "raw": "4h44gqe8oiiau272dh5e", "parsed": "4h44gqe8oiiau272dh5e" } ], "CSeq": [ { "raw": "3131 INVITE", "parsed": { "value": 3131, "method": "INVITE" } } ], "Allow": [ { "raw": "INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, NOTIFY" } ], "Supported": [ { "raw": "path, replaces" } ], "Allow-Events": [ { "raw": "talk, hold, conference, refer" } ], "Reason": [ { "raw": "Q.850;cause=88;text="INCOMPATIBLE_DESTINATION"" } ], "Content-Length": [ { "raw": "0", "parsed": 0 } ] }, "status_code": 488, "reason_phrase": "Not Acceptable Here", "data": "SIP/2.0 488 Not Acceptable Here\r\nVia: SIP/2.0/WSS sip.telnyx.com;rport=39746;received=27.109.18.82;branch=z9hG4bK9285430\r\nMax-Forwards: 68\r\nFrom: sip:hasnen****@sip.telnyx.com;tag=1e3hkfmgdn\r\nTo: sip:+1228200****@sip.telnyx.com;tag=0U70QDFQ3Fj9e\r\nCall-ID: 4h44gqe8oiiau272dh5e\r\nCSeq: 3131 INVITE\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, NOTIFY\r\nSupported: path, replaces\r\nAllow-Events: talk, hold, conference, refer\r\nReason: Q.850;cause=88;text="INCOMPATIBLE_DESTINATION"\r\nContent-Length: 0\r\n\r\n", "via": { "protocol": "SIP", "transport": "WSS", "host_type": "IPv4", "host": "sip.telnyx.com", "received": "27.109.18.82", "branch": "z9hG4bK9285430" }, "via_branch": "z9hG4bK9285430", "from": { "uri": { "parameters": {}, "headers": {} }, "parameters": { "tag": "1e3hkfmgdn" } }, "from_tag": "1e3hkfmgdn", "to": { "uri": { "parameters": {}, "headers": {} }, "parameters": { "tag": "0U70QDFQ3Fj9e" } }, "to_tag": "0U70QDFQ3Fj9e", "call_id": "4h44gqe8oiiau272dh5e", "cseq": 3131, "method": "INVITE", "body": "" }

怎么解决的？我也遇到了
