### ISSUE TITLE
Possible enhancement: add support of arbitrary in dialog NOTIFY

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#583]
Currently JsSIP has some limited built-in support of incoming in dialog NOTIFY.
Proposal: supports arbitrary incoming in dialog NOTIFY.

It can be implemented, for example likes:

RTCSession.js:  function receiveRequest(request):

```
case JsSIP_C.NOTIFY:
          // in dialog sipNotify event  modification.
          const e = {event: request.event, request: request, taken: false};
          this.emit('sipEvent', e);
          if(e.taken){  // set e.taken = true if consume incoming NOTIFY, otherwise used default JsSIP functionality.
            request.reply(200);
            break;
          }
          // end of modification	
```

**Comment by ibc** [comment]
SIP NOTIFYs should just be received within a SIP dialog previously created by sending a SUBSCRIBE to the remote. In SIP you cannot send a out of dialog NOTIFY.

**Comment by ibc** [comment]
However, JsSIP supports receiving out of dialog NOTIFY via the [ua.on('sipEvent')](https://jssip.net/documentation/3.3.x/api/ua/#event_sipEvent) event.
