### ISSUE TITLE
Add NOTIFY to Allow header

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#586]
Improvement: add NOTIFY to Allow header

JsSIP supports out of dialog incoming NOTIFY, and also uses it for call transfer (with REFER message) so seems will be correct if it  will be set in Allow header.

Possible change:

Constants.js
ALLOWED_METHODS     : 'INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,**NOTIFY**',

**Comment by jmillan** [comment]
Just published anew version with the change.

Thanks @ikq!
