### ISSUE TITLE
Cant run in nodejs

### ISSUE THREAD

**Issue by MegaMaxmaxmaximus** [versatica/JsSIP#591]
https://jssip.net/download/

![image](https://user-images.githubusercontent.com/53569597/64063713-a31a8000-cc00-11e9-880d-e4d103d86e9c.png)

npm is node package manager, but i cant run js sip in nodejs.
write that it is not suitable to run in node js

**Comment by MegaMaxmaxmaximus** [comment]
**here one guy swore me with obscenities when I told him about this bug. is he still in your team? didn't kick him out? hi wanted to convey from Russia**

**Comment by ibc** [comment]
Hi, I'm still here. And I'll be here forever because I'm project coauthor.

And you are a stupid poor troll that will be banned.
