### ISSUE TITLE
Web to Android Call Does not connects RTP Timeout

### ISSUE THREAD

**Issue by ForGuru** [versatica/JsSIP#592]
Hi,

I have Android and iOS SIP WebRTC SDK. which is working fine fo Audio and Video Calls 

Android to ioS and iOS to Android -> Works fine
iOS to Web and Web to iOS -> Works fine 

Android to Web Works Fine

but for Web to Android Call is Answered but Media is not connected.

On Firefox it give error "ICE failed, see about:webrtc for more details"

on Chrome no error but just call stuck when answered on Android.

**SDP in Invite from FireFox** 

> v=0
> o=mozilla...THIS_IS_SDPARTA-68.0.2 4947611113498368814 0 IN IP4 0.0.0.0
> s=-
> t=0 0
> a=sendrecv
> a=fingerprint:sha-256 AB:C3:EA:B2:DB:86:54:5A:56:28:53:4C:65:4F:4E:97:35:CD:87:FC:B6:A3:75:AD:32:65:51:3D:D9:B8:AF:C9
> a=group:BUNDLE 0 1
> a=ice-options:trickle
> a=msid-semantic:WMS *
> m=audio 64122 UDP/TLS/RTP/SAVPF 109 9 0 8 101
> c=IN IP4 176.9.75.12
> a=candidate:0 1 UDP 2122252543 192.168.1.103 56706 typ host
> a=candidate:5 1 TCP 2105524479 192.168.1.103 9 typ host tcptype active
> a=candidate:0 2 UDP 2122252542 192.168.1.103 59213 typ host
> a=candidate:5 2 TCP 2105524478 192.168.1.103 9 typ host tcptype active
> a=candidate:1 1 UDP 1686052863 202.166.160.162 56706 typ srflx raddr 192.168.1.103 rport 56706
> a=candidate:1 2 UDP 1686052862 202.166.160.162 59213 typ srflx raddr 192.168.1.103 rport 59213
> a=candidate:4 1 UDP 92216831 176.9.75.12 64122 typ relay raddr 176.9.75.12 rport 64122
> a=candidate:4 2 UDP 92216830 5.9.205.188 57775 typ relay raddr 5.9.205.188 rport 57775
> a=sendrecv
> a=end-of-candidates
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
> a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
> a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
> a=fmtp:101 0-15
> a=ice-pwd:419858c6201ad7c9b1cb38151684adc1
> a=ice-ufrag:97ea7e68
> a=mid:0
> a=msid:{b2dc80e9-cf3e-664f-b500-c489935fc0b9} {cea545c2-1c73-f44e-afa7-d191d70c25e7}
> a=rtcp:57775 IN IP4 5.9.205.188
> a=rtcp-mux
> a=rtpmap:109 opus/48000/2
> a=rtpmap:9 G722/8000/1
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:101 telephone-event/8000
> a=setup:actpass
> a=ssrc:2019681429 cname:{1ee7e4f9-bf45-4243-80ee-46102400c76e}
> m=video 61624 UDP/TLS/RTP/SAVPF 120 121 126 97
> c=IN IP4 176.9.75.12
> a=candidate:0 1 UDP 2122252543 192.168.1.103 60581 typ host
> a=candidate:5 1 TCP 2105524479 192.168.1.103 9 typ host tcptype active
> a=candidate:0 2 UDP 2122252542 192.168.1.103 50654 typ host
> a=candidate:5 2 TCP 2105524478 192.168.1.103 9 typ host tcptype active
> a=candidate:1 1 UDP 1686052863 202.166.160.162 60581 typ srflx raddr 192.168.1.103 rport 60581
> a=candidate:1 2 UDP 1686052862 202.166.160.162 50654 typ srflx raddr 192.168.1.103 rport 50654
> a=candidate:4 1 UDP 92216831 176.9.75.12 61624 typ relay raddr 176.9.75.12 rport 61624
> a=candidate:4 2 UDP 92216830 5.9.205.188 50216 typ relay raddr 5.9.205.188 rport 50216
> a=sendrecv
> a=end-of-candidates
> a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
> a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
> a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
> a=fmtp:120 max-fs=12288;max-fr=60
> a=fmtp:121 max-fs=12288;max-fr=60
> a=ice-pwd:419858c6201ad7c9b1cb38151684adc1
> a=ice-ufrag:97ea7e68
> a=mid:1
> a=msid:{b2dc80e9-cf3e-664f-b500-c489935fc0b9} {cf5056e7-a25b-3e41-9dd0-a136c799ca30}
> a=rtcp:50216 IN IP4 5.9.205.188
> a=rtcp-fb:120 nack
> a=rtcp-fb:120 nack pli
> a=rtcp-fb:120 ccm fir
> a=rtcp-fb:120 goog-remb
> a=rtcp-fb:121 nack
> a=rtcp-fb:121 nack pli
> a=rtcp-fb:121 ccm fir
> a=rtcp-fb:121 goog-remb
> a=rtcp-fb:126 nack
> a=rtcp-fb:126 nack pli
> a=rtcp-fb:126 ccm fir
> a=rtcp-fb:126 goog-remb
> a=rtcp-fb:97 nack
> a=rtcp-fb:97 nack pli
> a=rtcp-fb:97 ccm fir
> a=rtcp-fb:97 goog-remb
> a=rtcp-mux
> a=rtpmap:120 VP8/90000
> a=rtpmap:121 VP9/90000
> a=rtpmap:126 H264/90000
> a=rtpmap:97 H264/90000
> a=setup:actpass
> a=ssrc:2501741935 cname:{1ee7e4f9-bf45-4243-80ee-46102400c76e}

**SDP received on Web from Android**

> v=0
> o=- 3556996588696827129 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=msid-semantic: WMS ARDAMS
> m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=candidate:0 1 UDP 2122252543 192.168.1.103 56706 typ host
> a=candidate:5 1 TCP 2105524479 192.168.1.103 9 typ host tcptype active
> a=candidate:0 2 UDP 2122252542 192.168.1.103 59213 typ host
> a=candidate:5 2 TCP 2105524478 192.168.1.103 9 typ host tcptype active
> a=candidate:1 1 UDP 1686052863 202.166.160.162 56706 typ srflx raddr 192.168.1.103 rport 56706
> a=candidate:1 2 UDP 1686052862 202.166.160.162 59213 typ srflx raddr 192.168.1.103 rport 59213
> a=candidate:4 1 UDP 92216831 176.9.75.12 64122 typ relay raddr 176.9.75.12 rport 64122
> a=candidate:4 2 UDP 92216830 5.9.205.188 57775 typ relay raddr 5.9.205.188 rport 57775
> a=ice-ufrag:dcDh
> a=ice-pwd:mPlCBw9TN4b6tiW6m2h/E4b+
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 DC:22:4A:D6:59:ED:5E:1B:9D:57:83:6C:E1:91:EA:15:CD:01:9E:BA:D8:47:33:88:13:EB:C7:D0:9D:62:8F:54
> a=setup:active
> a=mid:0
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=sendrecv
> a=rtcp-mux
> a=rtpmap:109 opus/48000/2
> a=fmtp:109 minptime=10;useinbandfec=1
> a=rtpmap:9 G722/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:101 telephone-event/8000
> a=ssrc:1953094702 cname:ybkM2rfQB1JIv/Jf
> a=ssrc:1953094702 msid:ARDAMS ARDAMSa0
> a=ssrc:1953094702 mslabel:ARDAMS
> a=ssrc:1953094702 label:ARDAMSa0
> m=video 9 UDP/TLS/RTP/SAVPF 120 121
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=candidate:0 1 UDP 2122252543 192.168.1.103 60581 typ host
> a=candidate:5 1 TCP 2105524479 192.168.1.103 9 typ host tcptype active
> a=candidate:0 2 UDP 2122252542 192.168.1.103 50654 typ host
> a=candidate:5 2 TCP 2105524478 192.168.1.103 9 typ host tcptype active
> a=candidate:1 1 UDP 1686052863 202.166.160.162 60581 typ srflx raddr 192.168.1.103 rport 60581
> a=candidate:1 2 UDP 1686052862 202.166.160.162 50654 typ srflx raddr 192.168.1.103 rport 50654
> a=candidate:4 1 UDP 92216831 176.9.75.12 61624 typ relay raddr 176.9.75.12 rport 61624
> a=candidate:4 2 UDP 92216830 5.9.205.188 50216 typ relay raddr 5.9.205.188 rport 50216
> a=ice-ufrag:dcDh
> a=ice-pwd:mPlCBw9TN4b6tiW6m2h/E4b+
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 DC:22:4A:D6:59:ED:5E:1B:9D:57:83:6C:E1:91:EA:15:CD:01:9E:BA:D8:47:33:88:13:EB:C7:D0:9D:62:8F:54
> a=setup:active
> a=mid:1
> a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=sendrecv
> a=rtcp-mux
> a=rtpmap:120 VP8/90000
> a=rtcp-fb:120 goog-remb
> a=rtcp-fb:120 ccm fir
> a=rtcp-fb:120 nack
> a=rtcp-fb:120 nack pli
> a=rtpmap:121 VP9/90000
> a=rtcp-fb:121 goog-remb
> a=rtcp-fb:121 ccm fir
> a=rtcp-fb:121 nack
> a=rtcp-fb:121 nack pli
> a=ssrc:2802353049 cname:ybkM2rfQB1JIv/Jf
> a=ssrc:2802353049 msid:ARDAMS ARDAMSv0
> a=ssrc:2802353049 mslabel:ARDAMS
> a=ssrc:2802353049 label:ARDAMSv0

> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use the JsSIP Google Group instead:
> 
> https://groups.google.com/forum/#!forum/jssip
> 
> If you have found a bug in the software, or want to propose a new well documented feature or improvement, please delete this text and continue. :)

**Comment by ibc** [comment]
> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use the JsSIP Google Group instead:

https://groups.google.com/forum/#!forum/jssip

**Comment by ForGuru** [comment]
@ibc Thanks for reply, I have posted there but couldnt get any response / solution.
