### ISSUE TITLE
Exponential backoff in reconnect not working as expected

### ISSUE THREAD

**Issue by KraftyKraft** [versatica/JsSIP#594]
Hello!

We noticed something odd with the JsSIP's backoff when reconnecting sockets a couple of weeks ago.
![reconnect_spam](https://user-images.githubusercontent.com/12397197/65423006-49286700-de08-11e9-8612-70659f312979.png)
It's a bit spammy, and the "null" seconds part indicates that something odd is up.

I believe that something like what follows is happening:
 - the user doesn't provide a `connection_recovery_max_interval` in the configuration object passed to the UA on initialisation
 - it defaults to a `null` value:
https://github.com/versatica/JsSIP/blob/7995c3296b68019128f93c406fe9784323347ed4/lib/Config.js#L39
 - the default parameter to `Transport`'s constructor won't kick in since it receives a defined object (with keys mapping to `null`). So the defaults of 2 and 30 seconds are not set.
 - since `k > null` for all positive numbers `k`, the following block is entered:
https://github.com/versatica/JsSIP/blob/01cf25a3bd7c3c04aeecf6619013bb6875bce9de/lib/Transport.js#L212
 - the backoff is set to `null`, and the reconnection attempt is executed immediately.

I've created a PR with a suggested fix - hope that's OK.

Thanks!

**Comment by jmillan** [comment]
Hi @KraftyKraft,

The PR has been accepted and applied to 3.3.8 version.

Thanks!

**Comment by KraftyKraft** [comment]
Thanks, and thanks for a great lib :)
