### ISSUE TITLE
JSSIP->Peerconnection onaddstream method is not getting called

### ISSUE THREAD

**Issue by krishnapsarthi** [versatica/JsSIP#595]
Hello,

Currently i am facing issue for onaddstream is not getting called.

```
peerconnection: e => {
               this._peerConnection = e.peerconnection;
               this._peerConnection.onaddstream = e => {
                   this._ontrack(e);
                   this._setState(STATE.CONNECTED);
               };
               if (this._hasTransceivers && !this._sendingAudio) {
                   this._peerConnection.addTransceiver('audio');
               }
           }
```
In above code peerconnection code executes but onaddstream does not called and also tried with onTrack but it gives undefined in peerconnection object.

Please let me know is there any fix for this?

Thanks,
Krishna

**Comment by jmillan** [comment]
Please use mailing list for usage questions.
