### ISSUE TITLE
RTCSession.resetLocalMedia() does not exist

### ISSUE THREAD

**Issue by zymbolic** [versatica/JsSIP#607]
The official documentation for JsSIP version 3.3.x suggests that a function RTCSession.resetLocalMedia should exist. [Here's the link to the function's documentation](https://jssip.net/documentation/3.3.x/api/session/#method_resetLocalMedia).

This function appears to have been deprecated and removed at some point. Looking through the history of this repo, I can see that it existed at some point, and was implemented in October 2015, but no such function appears to exist currently. When I attempt to call resetLocalMedia() in my program I get the following error:

`TypeError: this.sessions.currentSession.resetLocalMedia is not a function`

The documentation needs to be updated to remove references to this function that no longer exists.

**Comment by ibc** [comment]
Thanks, done.
