### ISSUE TITLE
Add a method to access the headers from request

### ISSUE THREAD

**Issue by joelact** [versatica/JsSIP#611]
Hi guys!

Do you think that you could add a method to the RTCSession to access headers from request, or make the request object public, like in the example:

`session.getHeader('from');`

or

`session.request.getHeader('from');`

I'm using this to access a specific header that I want:

`session._request.getHeader('from')`

Waiting for an answer...

Best Regards

**Comment by ibc** [comment]
Please, use the mailing list for questions. Do not open issues here for that.

BTW there is already an API to get SIP headers in SIP messages. A SIP session does not have headers. A SIP message does.
