### ISSUE TITLE
Offer in response to an INVITE no-sdp reflects remote hold state

### ISSUE THREAD

**Issue by RobyMcAndrew** [versatica/JsSIP#612]
If we are put on-hold by the remote, and then we receive a INVITE without sdp, we generate an offer reflecting the remotes request. 
[RFC 6337](https://tools.ietf.org/html/rfc6337#section-5.1) states:

> A UA should send an offer that indicates what it, and its user, are
   interested in using/doing at that time, without regard for what the
   other party in the call may have indicated previously.  This is the
   case even when the offer is sent in response to an INVITE or re-
   INVITE that contains no offer.

This is a fairly common sequence for performing call transfers, and as it stands it results in the client not sending audio. 

I think this can be solved by clearing the _remoteHold flag when we receive a re-INVITE without sdp (RTCSession.js line 2062 onwards)  thus:

    // Request without SDP.
    if (!request.body)
    {
      this._late_sdp = true;
      this._remoteHold = false;

I've tested this with a fairly recent version of JsSIP, and it is working for our use case.

**Comment by ibc** [comment]
Please, send a PR.

**Comment by RobyMcAndrew** [comment]
Done. From further testing, we have tweaked the patch slightly.

**Comment by jmillan** [comment]
PR was already applied.
