### ISSUE TITLE
antiglobal error in chrome

### ISSUE THREAD

**Issue by vovanb** [versatica/JsSIP#621]
I just tried https://tryit.jssip.net/ and opened demo page and got below error:

antiglobal() | globals do not match:
+ P
+ callstatsjssip
+ jssip
+ UA
+ __VUE_DEVTOOLS_TOAST__
- ___browserSync___oldSocketIo
- JSON3
- io
- ___browserSync___
- MediaStream
- RTCPeerConnection
- jssipCallstats
antiglobal @ antiglobal.js:58

Is it something that I should skip ? Tried to make call from local linphone - did not work...

**Comment by ibc** [comment]
The Leeryver Symptom (in Spanish “Leer-y-ver”, in English “Read-and-see”):

“I never look at the logs when things work fine so, when they don’t, I look at the logs for the first time and whichever first warning/error line I see I blame it.”
