### ISSUE TITLE
Event ended does not fire when the session call has been terminated

### ISSUE THREAD

**Issue by hung211097** [versatica/JsSIP#626]
Hi, I've got a problem with the event ended. When I click to end the call, I've seen the ACK BYE sent but the other hasn't received it. The other just retry to send message to catch the signal with the ended user about 30s until it does not received responses, it sends the ACK BYE too. I don't know what the problem is. Sorry for my bad explanation. Thank you.

**Comment by ibc** [comment]
Use the mailing list, please. You clearly read this when creating this issue:

> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use the JsSIP Google Group instead:
> 
> https://groups.google.com/forum/#!forum/jssip
