### ISSUE TITLE
problem with sendDTMF

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#630]
When in JsSIP 3.4.5 used:
session.sendDTMF(tone, {transportType: 'RFC2833'});

throws exception:
Uncaught TypeError: invalid transportType: RFC2833

When used valid value of transportType

I think that RTCSession.js piece of code:

 if (
          transportType !== JsSIP_C.DTMF_TRANSPORT.INFO ||
          transportType !== JsSIP_C.DTMF_TRANSPORT.RFC2833
        )
        {
          throw new TypeError(`invalid transportType: ${transportType}`);
        }

Should be changed to:

 if (
          transportType !== JsSIP_C.DTMF_TRANSPORT.INFO **&&**
          transportType !== JsSIP_C.DTMF_TRANSPORT.RFC2833
        )
        {
          throw new TypeError(`invalid transportType: ${transportType}`);
        }
 
( || should be changed to &&)
Thanks.

**Comment by ibc** [comment]
Good catch. Fixing it.

**Comment by ibc** [comment]
Released in JsSIP 3.4.6, thanks
