### ISSUE TITLE
Allow use # in sip uri

### ISSUE THREAD

**Issue by alexmelnikov** [versatica/JsSIP#631]
RFC allow use # https://www.tech-invite.com/fo-abnf/tinv-fo-abnf-sipuritu.html#phonedigit-hex
But if call's From is "sip:**123#4**@172.30.0.76:5070" We have parse error.

Need to add # to the Grammar.pegjs:
`mark        = "#" / "-" / "_" / "." / "!" / "~" / "*" / "'" / "(" / ")"`

I can't do pull request, because I don't know, how right generate Grammar.js =)

**Comment by rshpount** [comment]
I think you are incorrect: "#" is not allowed in SIP userinfo part:
https://www.tech-invite.com/fo-abnf/tinv-fo-abnf-sipuriui.html

It is definitely not a mark:
https://www.tech-invite.com/fo-abnf/tinv-fo-abnf-siprules.html#mark

I think you are confusing sip and tel URI.

You must URL encode # in SIP URI user info as %23.

**Comment by ibc** [comment]
Right, not a bug.
