### ISSUE TITLE
[Question] about WebRTC peer configuration

### ISSUE THREAD

**Issue by ktiniatros** [versatica/JsSIP#634]
Hello!

At this line:
https://github.com/versatica/JsSIP/blob/96188fc57c0771d6db00ac7ee9e2ba98c8e4716e/lib/RTCSession.js#L370

you initiate the `RTCPeerConnection`.

As far as I understand from the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection), the constructor takes one dictionary (the configuration), so why do you pass the `rtcConstraints` too there?
To be clear, I just want to understand! (no intention to criticise or anything :)

Thank you for the great work on the library!

**Comment by ibc** [comment]
Just to allow passing Chrome old/deprecated/proprietary params that were there in first versions of WebRTC in Chrome.
