### ISSUE TITLE
Why not use @types/jssip which has already widely used?

### ISSUE THREAD

**Issue by hxl-dy** [versatica/JsSIP#636]
It is obviously that `@types/jssip` is more functional.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jssip/index.d.ts

vs

https://github.com/versatica/JsSIP/blob/master/lib/JsSIP.d.ts

**Comment by jmillan** [comment]
Firstly I had no idea of the existence of @types/jssip. Anyways, the types in JsSIP itself are way more complete.
