### ISSUE TITLE
JsSIP keepalive ( OPTIONS )

### ISSUE THREAD

**Issue by volga629-1** [versatica/JsSIP#644]
Hello Everyone,
UA reply on keepalive  404 (OPTIONS), because it request  user name in R-URI, but generally it not require, I think it possible to do exception for OPTIONS method in UA.js line  

```
// Check that request URI points to us.
if (request.ruri.user !== this._configuration.uri.user &&
request.ruri.user !== this._contact.uri.user)
{
debug('Request-URI does not point to us');
if (request.method !== JsSIP_C.ACK)
{
request.reply_sl(404);
}

return;
}
```
Screnshot

![keepalive](https://user-images.githubusercontent.com/59034879/86818637-ffd69a80-c05c-11ea-9613-a5a7ac843003.png)

**Comment by ibc** [comment]
> I think it possible to do exception for OPTIONS method in UA.js line

You think that based on what exactly? JsSIP follows the RFC here.

BTW use the mailing list for questions, please.
