### ISSUE TITLE
Bug with exports in version 3.5.3

### ISSUE THREAD

**Issue by ashlanderDesign** [versatica/JsSIP#651]
I found this strange exports in lib/JsSIP.d.ts

`export * as C from './Constants'`
`export * as Exceptions from './Exceptions'`
`export * as Utils from './Utils'`
`export * as Grammar from './Grammar'`

When I tried to run my angular app, which has this package as a dependency, it crashes, saying that exports are wrong
I tried to fix it and it actually worked

`import * as C from './Constants';`
`import * as Exceptions from './Exceptions';`
`import * as Utils from './Utils';`
`import * as Grammar from './Grammar';`

`export { C, Exceptions, Utils, Grammar};`

**Comment by ibc** [comment]
@jmillan the `JsSIP.d.ts` is a file created by us, it's not autogenerated, right?

**Comment by jmillan** [comment]
@ibc, right

**Comment by jmillan** [comment]
Done in new version.

Thanks for reporting @ashlanderDesign
