### ISSUE TITLE
SDP Event Call after setLocalDescription 

### ISSUE THREAD

**Issue by varghesepaul** [versatica/JsSIP#654]
Hi Team, 
I am trying to change the OPUS parameter in the webrtc SDP offer. setLocalDescription is being called before the SDP connection event.
 
1. connection.createOffer    : https://github.com/versatica/JsSIP/blob/3.5.4/lib/RTCSession.js#L1867 
2. connection.setLocalDescription(desc) : https://github.com/versatica/JsSIP/blob/3.5.4/lib/RTCSession.js#L1893 
3. this.emit('sdp', e); https://github.com/versatica/JsSIP/blob/3.5.4/lib/RTCSession.js#L1940 

The updated SDP in INVITE is being sent to the websocket server but the webrtc setLocalDescription doesn't have the updated SDP. 

I tried to modify the code to call this.emit('sdp', e) before connection.setLocalDescription(desc) and it is working for me. Also removed the this.emit('sdp',e) from the Icegahering ready function. 

   createOffer()
   .then((desc) => {
        debug("sending the sdp");
        const e = { originator: 'local', type: desc.type, sdp: desc.sdp };
        this.emit('sdp', e);
        desc.sdp = e.sdp;
        return Promise.resolve(desc);
      })
      // Set local description.
   .then((desc) => {
        return connection.setLocalDescription(desc)

Can you please have a look and check if this can be improved in the code ? or Am I missing something ?.

**Comment by jmillan** [comment]
Can you please post your question to the mailing list and indicate which opus parameter are you trying to change?
