### ISSUE TITLE
Register to asterisk on another port...  

### ISSUE THREAD

**Issue by DarkNightHome** [versatica/JsSIP#658]
ws - proxy_pass on enginx url: IP/ws -> ipasterisk:8088/asterisk/ws
i set 
.
        let ua = new JsSIP.UA({           
            sockets: [ wss ],                                                                               
            registrar_server: '127.0.0.1:5160',                                                                
            uri: 'sip:1001@127.0.0.1:5160',                                                                    
            password : '12345678',                                                               
        }); 
but asterisk say connection to 5060 port and try to auth on 5060-chan_sip module
5160 - port is configured for pjsip module... 

if i turnoff chan_sip... on asterisk and set default port 5060 on pjsip module, then connection sucsessfully and all work... but try switch to another port and no connection....

`phone.html:17 initializing
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface new() [url:"wss://192.168.78.230/ws"] +0ms
jssip-3.5.3.min.js:9 JsSIP:UA new() [configuration:{sockets: Array(1), registrar_server: "127.0.0.1:5160", uri: "sip:1001@127.0.0.1:5160", password: "12345678"}] +0ms
jssip-3.5.3.min.js:9 JsSIP:Transport new() +0ms
jssip-3.5.3.min.js:9 JsSIP:UA configuration parameters after validation: +40ms
jssip-3.5.3.min.js:9 JsSIP:UA - authorization_user: "1001" +3ms
jssip-3.5.3.min.js:9 JsSIP:UA - password: NOT SHOWN +5ms
jssip-3.5.3.min.js:9 JsSIP:UA - realm: null +0ms
jssip-3.5.3.min.js:9 JsSIP:UA - ha1: NOT SHOWN +2ms
jssip-3.5.3.min.js:9 JsSIP:UA - display_name: null +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - uri: sip:1001@127.0.0.1:5160 +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - contact_uri: {"_parameters":{"transport":"ws"},"_headers":{},"_scheme":"sip","_user":"e7tsgqtj","_host":"tm2lg3eoisjk.invalid","_port":null} +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - instance_id: "c7de22d3-0fa5-486e-a542-92731cf0afb5" +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - use_preloaded_route: false +0ms
jssip-3.5.3.min.js:9 JsSIP:UA - session_timers: true +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - session_timers_refresh_method: "UPDATE" +9ms
jssip-3.5.3.min.js:9 JsSIP:UA - no_answer_timeout: 60000 +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - register: true +3ms
jssip-3.5.3.min.js:9 JsSIP:UA - register_expires: 600 +2ms
jssip-3.5.3.min.js:9 JsSIP:UA - registrar_server: sip:127.0.0.1:5160 +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - connection_recovery_max_interval: 30 +1ms
jssip-3.5.3.min.js:9 JsSIP:UA - connection_recovery_min_interval: 2 +3ms
jssip-3.5.3.min.js:9 JsSIP:UA - via_host: "tm2lg3eoisjk.invalid" +1ms
jssip-3.5.3.min.js:9 JsSIP:UA start() +16ms
jssip-3.5.3.min.js:9 JsSIP:Transport connect() +61ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface connect() +132ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface connecting to WebSocket wss://192.168.78.230/ws +2ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface WebSocket wss://192.168.78.230/ws connected +248ms
phone.html:177 connected
jssip-3.5.3.min.js:9 JsSIP:Transport send() +266ms
jssip-3.5.3.min.js:9 JsSIP:Transport sending message:REGISTER sip:127.0.0.1:5160 SIP/2.0
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK2219547
Max-Forwards: 69
To: <sip:1001@127.0.0.1:5160>
From: <sip:1001@127.0.0.1:5160>;tag=60p66uaaq5
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 1 REGISTER
Contact: <sip:e7tsgqtj@tm2lg3eoisjk.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:c7de22d3-0fa5-486e-a542-92731cf0afb5>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: JsSIP 3.5.3
Content-Length: 0

 +3ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface send() +17ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface received WebSocket message +34ms
jssip-3.5.3.min.js:9 JsSIP:Transport received text message:SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK2219547;received=127.0.0.1;rport=39262
From: <sip:1001@127.0.0.1:5160>;tag=60p66uaaq5
To: <sip:1001@127.0.0.1:5160>;tag=as0d4ff046
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 1 REGISTER
Server: Asterisk PBX 16.2.1~dfsg-1+deb10u1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="49db0d47"
Content-Length: 0

 +36ms
jssip-3.5.3.min.js:9 JsSIP:DigestAuthentication authenticate() | using qop=null [a2:"REGISTER:sip:127.0.0.1:5160"] +0ms
jssip-3.5.3.min.js:9 JsSIP:DigestAuthentication authenticate() | response generated +2ms
jssip-3.5.3.min.js:9 JsSIP:Transport send() +43ms
jssip-3.5.3.min.js:9 JsSIP:Transport sending message:REGISTER sip:127.0.0.1:5160 SIP/2.0
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK9910469
Max-Forwards: 69
To: <sip:1001@127.0.0.1:5160>
From: <sip:1001@127.0.0.1:5160>;tag=60p66uaaq5
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 2 REGISTER
Authorization: Digest algorithm=MD5, username="1001", realm="asterisk", nonce="49db0d47", uri="sip:127.0.0.1:5160", response="73144a35c6d82d5e283841f83c7d241b"
Contact: <sip:e7tsgqtj@tm2lg3eoisjk.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:c7de22d3-0fa5-486e-a542-92731cf0afb5>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: JsSIP 3.5.3
Content-Length: 0

 +2ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface send() +46ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface received WebSocket message +20ms
jssip-3.5.3.min.js:9 JsSIP:Transport received text message:SIP/2.0 403 Forbidden
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK9910469;received=127.0.0.1;rport=39262
From: <sip:1001@127.0.0.1:5160>;tag=60p66uaaq5
To: <sip:1001@127.0.0.1:5160>;tag=as0d4ff046
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 2 REGISTER
Server: Asterisk PBX 16.2.1~dfsg-1+deb10u1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0

 +20ms
phone.html:224 registrationFailed
jssip-3.5.3.min.js:9 JsSIP:UA register() +5s
jssip-3.5.3.min.js:9 JsSIP:Transport send() +5s
jssip-3.5.3.min.js:9 JsSIP:Transport sending message:REGISTER sip:127.0.0.1:5160 SIP/2.0
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK3587579
Max-Forwards: 69
To: <sip:1001@127.0.0.1:5160>
From: <sip:1001@127.0.0.1:5160>;tag=bk0kk6c4tk
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 3 REGISTER
Contact: <sip:e7tsgqtj@tm2lg3eoisjk.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:c7de22d3-0fa5-486e-a542-92731cf0afb5>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: JsSIP 3.5.3
Content-Length: 0

 +1ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface send() +5s
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface received WebSocket message +10ms
jssip-3.5.3.min.js:9 JsSIP:Transport received text message:SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK3587579;received=127.0.0.1;rport=39262
From: <sip:1001@127.0.0.1:5160>;tag=bk0kk6c4tk
To: <sip:1001@127.0.0.1:5160>;tag=as0d4ff046
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 3 REGISTER
Server: Asterisk PBX 16.2.1~dfsg-1+deb10u1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="6e10194c"
Content-Length: 0

 +11ms
jssip-3.5.3.min.js:9 JsSIP:DigestAuthentication authenticate() | using qop=null [a2:"REGISTER:sip:127.0.0.1:5160"] +5s
jssip-3.5.3.min.js:9 JsSIP:DigestAuthentication authenticate() | response generated +2ms
jssip-3.5.3.min.js:9 JsSIP:Transport send() +12ms
jssip-3.5.3.min.js:9 JsSIP:Transport sending message:REGISTER sip:127.0.0.1:5160 SIP/2.0
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK1337886
Max-Forwards: 69
To: <sip:1001@127.0.0.1:5160>
From: <sip:1001@127.0.0.1:5160>;tag=bk0kk6c4tk
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 4 REGISTER
Authorization: Digest algorithm=MD5, username="1001", realm="asterisk", nonce="6e10194c", uri="sip:127.0.0.1:5160", response="e53b69f156b9558e0e484977d887160e"
Contact: <sip:e7tsgqtj@tm2lg3eoisjk.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:c7de22d3-0fa5-486e-a542-92731cf0afb5>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: JsSIP 3.5.3
Content-Length: 0

 +1ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface send() +14ms
jssip-3.5.3.min.js:9 JsSIP:WebSocketInterface received WebSocket message +32ms
jssip-3.5.3.min.js:9 JsSIP:Transport received text message:SIP/2.0 403 Forbidden
Via: SIP/2.0/WSS tm2lg3eoisjk.invalid;branch=z9hG4bK1337886;received=127.0.0.1;rport=39262
From: <sip:1001@127.0.0.1:5160>;tag=bk0kk6c4tk
To: <sip:1001@127.0.0.1:5160>;tag=as0d4ff046
Call-ID: kf53l0hmf8dl41ovjiodls
CSeq: 4 REGISTER
Server: Asterisk PBX 16.2.1~dfsg-1+deb10u1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0

 +34ms
phone.html:224 registrationFailed`
this log from browser

Connected to Asterisk 16.2.1~dfsg-1+deb10u1 currently running on asterisk (pid = 127)
[Aug  9 21:26:16] NOTICE[17419]: chan_sip.c:28934 handle_request_register: Registration from '<sip:1001@127.0.0.1:5160>' failed for '127.0.0.1:39262' - Wrong password
 that in asterisk cli...

**Comment by DarkNightHome** [comment]
root@asterisk:/var/www/html/webrtc# netstat -anp | grep asterisk
tcp        0      0 0.0.0.0:8088            0.0.0.0:*               LISTEN      127/asterisk
tcp        0      0 0.0.0.0:5038            0.0.0.0:*               LISTEN      127/asterisk
tcp        0      0 192.168.78.230:47424    192.168.78.230:3306     ESTABLISHED 127/asterisk
tcp        0      0 127.0.0.1:8088          127.0.0.1:39262         ESTABLISHED 127/asterisk
tcp        0      0 192.168.78.230:47422    192.168.78.230:3306     ESTABLISHED 127/asterisk
udp        0      0 0.0.0.0:12816           0.0.0.0:*                           127/asterisk
udp        0      0 0.0.0.0:5060            0.0.0.0:*                           127/asterisk
udp        0      0 0.0.0.0:5160            0.0.0.0:*                           127/asterisk
udp        0      0 0.0.0.0:55124           0.0.0.0:*                           127/asterisk
udp        0      0 0.0.0.0:9600            0.0.0.0:*                           127/asterisk
udp6       0      0 :::47284                :::*                                127/asterisk
unix  2      [ ACC ]     STREAM     LISTENING     7401339  127/asterisk         /var/run/asterisk/asterisk.ctl
unix  3      [ ]         STREAM     CONNECTED     43029    127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401884  127/asterisk         /var/run/asterisk/asterisk.ctl
unix  2      [ ]         DGRAM                    7401347  127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401883  17142/rasterisk
unix  3      [ ]         STREAM     CONNECTED     7401865  127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401866  127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401885  127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401867  127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401864  127/asterisk
unix  3      [ ]         STREAM     CONNECTED     7401886  127/asterisk

this proof asterisk listen port 5160

**Comment by ibc** [comment]
use the mailing list for questions, this is not a bug in JsSIP.
