### ISSUE TITLE
When 2 bindings in REGISTER response, UA picks first, may be wrong one

### ISSUE THREAD

**Issue by robdyck** [versatica/JsSIP#660]
REGISTER sip:bogus.com SIP/2.0
Via: SIP/2.0/WSS fyox8dun9bro.invalid;branch=z9hG4bK1207068
Max-Forwards: 69
To: <sip:2@bogus.com>
From: "test" <sip:2@bogus.com>;tag=lt0ij5aeov
Call-ID: i0iar5f6h8bh20h0r9rddk
CSeq: 2 REGISTER
Authorization: Digest algorithm=MD5, username="2", realm="bogus.com", nonce="5f416cb00000060881bee5e90a376c789961095a202b0c21", uri="sip:bogus.com", response="a0459874f88bd72a00ce745225bef769"
X-SBC: AudioCodes Mediant
Contact: <sip:2@fyox8dun9bro.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:ad4d2745-7af9-4cd1-928a-57431b573e70>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: AudioCodes-WebRTC
Content-Length: 0

###################################################

UA identifies itself
Contact: <sip:2@fyox8dun9bro.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:ad4d2745-7af9-4cd1-928a-57431b573e70>"

###################################################

SIP/2.0 200 OK
Via: SIP/2.0/WSS fyox8dun9bro.invalid;received=2001:9B5D;rport=58374;branch=z9hG4bK1207068
To: <sip:2@bogus.com>;tag=59de.c2453b00f1b28428be6b03f4e6ebf85d
From: "test" <sip:2@bogus.com>;tag=lt0ij5aeov
Call-ID: i0iar5f6h8bh20h0r9rddk
CSeq: 2 REGISTER
Contact: <sip:2@3hblrnvn3xlp.invalid;transport=ws>;expires=467;received="sip:[2001::380C]:47504;transport=wss";pub-gruu="sip:2@bogus.com:8000;gr=urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2";temp-gruu="sip:tgruu.AUUKVmIDQ2IFRBNcc0QCPQoFRgc3CxRjBhQBC2AIXTcFQgJDZ1QVYx1JVgxgHEdmAhIFXWMCQWVSQhMBYVkFNgZGWAAjQEk5VEhcHjYGHjVa@bogus.com:8000;gr";+sip.instance="urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2", <sip:2@fyox8dun9bro.invalid;transport=ws>;expires=600;received="sip:[2001:9B5D]:58374;transport=wss";pub-gruu="sip:2@bogus.com:8000;gr=urn:uuid:ad4d2745-7af9-4cd1-928a-57431b573e70";temp-gruu="sip:tgruu.AUUKVmIDQ2IFRBNcc0QCPQoFRgc3CxE3BBQBWWcEXWRRFgpDZ1IUYh1JAVYyHEVkBEMCDGYGQzYHQBMHY1gRIQUWBQZrUxhhABgDHGpDFDdb@bogus.com:8000;gr";+sip.instance="urn:uuid:ad4d2745-7af9-4cd1-928a-57431b573e70"
Server: OpenSIPS (3.0.2 (x86_64/linux))
Content-Length: 0

##################################################

Receives bindings from registrar
Contact: <sip:2@3hblrnvn3xlp
+sip.instance="urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2"
<sip:2@fyox8dun9bro
+sip.instance="urn:uuid:ad4d2745-7af9-4cd1-928a-57431b573e70"

The correct binding for this UA is the second one

The UA receives an INVITE and it is aswered
UA responds with Ringing and 200 OK

##################################################

SIP/2.0 180 Ringing
Record-Route: <sip:[2001:D2B4]:8000;transport=wss;lr;ftag=kph9o6qqeh>
Via: SIP/2.0/WSS [2001:D2B4]:8000;branch=z9hG4bKc264.ac551c86.1;i=67851a04
Via: SIP/2.0/WSS ad2r3g2pqrca.invalid;rport=38149;received=2001::D3C4;branch=z9hG4bK2031211
To: <sip:2@bogus.com>;tag=t7jup94926
From: "Rob" <sip:4@bogus.com>;tag=kph9o6qqeh
Call-ID: olcq29app6vj3r5utajt
CSeq: 4716 INVITE
Contact: <sip:2@bogus.com:8000;gr=urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2>
Supported: gruu,ice,replaces,outbound
Content-Length: 0

###################################################

Ringing response Contact
Contact: <sip:2@bogus.com:8000;gr=urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2>

##################################################

SIP/2.0 200 OK
Record-Route: <sip:[2001:D2B4]:8000;transport=wss;lr;ftag=kph9o6qqeh>
Via: SIP/2.0/WSS [2001:D2B4]:8000;branch=z9hG4bKc264.ac551c86.1;i=67851a04
Via: SIP/2.0/WSS ad2r3g2pqrca.invalid;rport=38149;received=2001::D3C4;branch=z9hG4bK2031211
To: <sip:2@bogus.com>;tag=t7jup94926
From: "Rob" <sip:4@bogus.com>;tag=kph9o6qqeh
Call-ID: olcq29app6vj3r5utajt
CSeq: 4716 INVITE
Contact: <sip:2@bogus.com:8000;gr=urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2>
X-Greeting: You are welcome !
Supported: gruu,ice,replaces,outbound
Content-Type: application/sdp
Content-Length: 1435

#####################################################

200 OK Contact
Contact: <sip:2@bogus.com:8000;gr=urn:uuid:d06d2e39-d521-4ee0-9eb3-752b630316b2>

The UA has mis-identified itself
ACK will be sent to other UA

#####################################################

**Comment by jmillan** [comment]
No where I see that it is legal having multiple pub-gruu/temp-gruu in the same Contact header field.

https://tools.ietf.org/html/rfc5627#section-5.2 indicates that the registrar server **MUST add a** temp-gruu or/and pub-gruu Contact header field parameter. It does not talk about multiple instances of them.

**Comment by robdyck** [comment]
Please consider reopening this issue.
```
            // Get the Contact pointing to us and update the expires value accordingly.
            const contact = contacts.find((element) => (
              element.uri.user === this._ua.contact.uri.user
            ));
```
This doesn't work because the user in each contact will be the same. We need to find the URI for our UA. The URIs are unique. It is not a GRUU issue although they should be included in the response if the UA supports it. Consider the example from above.
sip:2@3hblrnvn3xlp
sip:2@fyox8dun9bro
From the REGISTER above we see that the UA identified itself as sip:2@fyox8dun9bro. The function quoted here finds the first instance of user "2" and identifies itself as sip:2@3hblrnvn3xlp in the subsequent 200 OK. The ACK will be sent to sip:2@3hblrnvn3xlp and the call will fail.

**Comment by ibc** [comment]
If we do that (match the full Contact URI) it will fail to match it when the registrar server (i.e. Asterisk or others) change the Contact URI host part with the source public IP of the REGISTER.

**Comment by robdyck** [comment]
How do we keep the call from failing. This is easily reproduced as above. If the aswering UA happens to be the second on the list of contacts the call will fail.

**Comment by ibc** [comment]
Let's reopen. We'll reconsider.

**Comment by robdyck** [comment]
I was curious about the other major JS SIP implementation so I tested a UA based on their stack.
Assuming that the REGISTER response conains a list of two or more contacts, The two implementations use a similar way to extract their instance from the list. Both search the list for the first instance of their "user". The difference is that when their stack created the REGISTER request they gave the "user" a unique value, and not the "user" portion of the AOR.

**Comment by ibc** [comment]
@jmillan I think this makes sense:

- We just match the username of the SIP URI in the Contact (since some registrars replace the host part with the public IP for NAT purposes).
- So if we used a random username for every registration we would avoid this issue. Thoughts?

**Comment by robdyck** [comment]
With GRUU the contact is a unique identifier, not a unique location.
An example from the "other" stack
REGISTER
```
To: "Rob" <sip:4@bogus.com>
Contact: <sip:clj487a7@8aomuag5cvdm.invalid;transport=wss>;reg-id=1;+sip.instance="<urn:uuid:40239068-a0f4-4bd6-847f-4eb3e4248538>";expires=120
```
Response, pub and temp omitted. Three bindings. First binding is from JSSIP.
Contact

```
<sip:4@l0iop1v3c03w.invalid;transport=ws>;expires=5451

<sip:clj487a7@8aomuag5cvdm.invalid;transport=wss>;expires=120

<sip:4iaqmgkf@8d80vu7utbv6.invalid;transport=wss>;expires=12
```
As we see the user portion of the bindings from the "other" stack are unique.
Going back to the initial report above, the user "4" is not unique.

Something I just noticed now is the transport in the bindings. ws versus wss.

**Comment by robdyck** [comment]
I think it is best not to get hung up on GRUU. Going back to RFC3261, the REGISTER response is supposed to list all the bindings for an AOR. The issuing agent firstly must see that the registration was sucessful and secondly what is the expiry time for this agent. The registrar is allowed to ignore the agents request. Since we have multiple bindings, the agent must find its binding from the list so that it can know the actual expiry it should use.

So to the issue. The agent registers and receives an OK response with multiple bindings. The agent searches the list and mistakenly chooses an incorrect entry. The agent receives an INVITE that is subsequently answered at this agent. The agent issues an 200 OK which includes its contact which is incorrect. Apparently when it chose the wrong binding it adopted the identity of the binding. Actually if we look at 180 Ringing already we see that the agent has misidentified itself. The caller receives the 200 OK and sends an ACK to the identity it received. Yes, because of GRUU the identity has to be translated to a location by the proxy but that is not relevant. The proxy correctly translates the identity it received and routes it to the agent - the wrong agent. Our agent continues sending 200 OK unitl it times out and sends BYE.

**Comment by robdyck** [comment]
The simplest solutionnis to do what the other guys did. Create a unique user and then searh for that user from the binding list.
Parsing a uri adds some complexity but it would be unique. Maybe hash the URI to ease the search of the list.

**Comment by ibc** [comment]
> Parsing a uri adds some complexity but it would be unique. Maybe hash the URI to ease the search of the list.

I should insist here: We just match the username of the SIP URI in the Contact since some registrars replace the host part with the public IP for NAT purposes.

So, if I understand correctly, the easiest solution (which does not break anything) would just be this:

> So if we used a random username for every registration we would avoid this issue. 

is this ok?

BTW JsSIP has utilities to compare two SIP URIs following the rules of RFC 3261 perfectly.

**Comment by robdyck** [comment]
Perfect. Going back to the original report, in the binding list provided, two binding were using the same user. The search would terminate on the first instance of the user that was found. It might not be the one that pertains to that agent. With agents coming and going, their location in the list would chnage resulting in different agents failing at different times.

**Comment by jmillan** [comment]
It makes sense to me generating a unique URI user in the contact to avoid the problem.

**Comment by ibc** [comment]
> It makes sense to me generating a unique URI user in the contact to avoid the problem.

@robdyck just a boolean yes/no answer, please: would this change fix the issue?

**Comment by robdyck** [comment]
Yes

**Comment by ibc** [comment]
Ok, so I don't understand. We **already** use a random URI username at `Contact` header by default (unless the user provides a `contact_uri` in UA settings). Example:

```
Contact: <sip:ad5tq021@5qp4ftmn3f4l.invalid;transport=ws>;expires=600;pub-gruu="sip:iaki_lufxmr@tryit.jssip.net;gr=urn:uuid:fa156342-b38c-41e6-b4dd-331fe4ea1427";temp-gruu="sip:uloc-5f1ee42f-5c2-61f2-5279369b@tryit.jssip.net;gr";+sip.instance="<urn:uuid:fa156342-b38c-41e6-b4dd-331fe4ea1427>";reg-id=1
```

In `UA.js`:

```js
if (this._configuration.contact_uri)
{
  this._configuration.via_host = this._configuration.contact_uri.host;
}
else
{
  this._configuration.contact_uri = new URI('sip', Utils.createRandomToken(8), this._configuration.via_host, null, { transport: 'ws' });
}
```

@robdyck, since your `Contact` header looks like this:

```
Contact: sip:2@fyox8dun9bro.invalid;transport=ws;+sip.ice;reg-id=1;+sip.instance="urn:uuid:ad4d2745-7af9-4cd1-928a-57431b573e70";expires=600
```

It clearly means that you are giving a custom `contact_uri` in UA settings.

**Comment by robdyck** [comment]
If there is a custom contact URI it was not added explicitly. I am testing using an Audiocodes demo UA. It has settings for the server, the domain, user, password and display name. There is no custom contact setting. The user portion of the contact is apparently being taken from the user portion of the AOR of the registration. ( 2@bogus.com ).

**Comment by robdyck** [comment]
It appears that Audiocodes does indeed customize the contact URI.
```
        let t = {
            sockets: s,
            uri: "sip:" + this.account.user + "@" + this.serverConfig.domain,

            contact_uri: "sip:" + this.account.user + "@" + this._randomToken(12) + ".invalid;transport=ws",

            authorization_user: this.account.authUser,
            password: this.account.password,
            register: e,
            session_timers: this.account.useSessionTimer,
            register_expires: this.account.registerExpires,
            user_agent: this.u17,
            connection_recovery_min_interval: this.reconnectMin,
            connection_recovery_max_interval: this.reconnectMax
        };
this.jssipUA = new JsSIP.UA(t),
```
This is not a JsSIP issue. I am OK with closing it.

**Comment by ibc** [comment]
Thanks for confirming. If this is still a problem we may add a setting to force full URI comparison in Contact URI.
