### ISSUE TITLE
Missing documentation of version 3.5.x on https://jssip.net/documentation/

### ISSUE THREAD

**Issue by tzahari** [versatica/JsSIP#661]
Dear JsSIP Team,

On the webpage https://jssip.net/documentation/ is the api documentation missing for version 3.5.x!

Please add the documentation.

Thank you!

**Comment by jmillan** [comment]
3.5 Does not really come with new documentation. TypeScript typings where added. Will add the new entry to the doc thouh.

Thanks @tzahari

**Comment by jmillan** [comment]
BTW: We're not adding the documentation for TS. Not just know, since it's very probably that the hole JsSIP may be rewritten into TS and the doc will be autogenerated.

**Comment by ibc** [comment]
doc for 3.5.x added, it was just missing

**Comment by tzahari** [comment]
Thank you ...
