### ISSUE TITLE
Move "@types/node" to devDependencies

### ISSUE THREAD

**Issue by edvinv** [versatica/JsSIP#662]
@types/node should be under devDependencies otherwise node types will be included  and interfere with web project. You get problems like described in https://github.com/Microsoft/TypeScript/issues/9731.

**Comment by ibc** [comment]
And then it will fail if someone writes a JsSIP app for Node.js instead than for a browser, right?

**Comment by edvinv** [comment]
I have quickly check the code and it looks like that you have added @types/node only because you use NodeJS.EventEmitter in some *.d.ts files. So in node environment built-in module event is used but in browser environment github.com/Gozala/events is used? Maybe in this case will be better just to add @types/events. Of course it should be added to dependencies section in package.json.

In current situation all node types are included also in browser environment what can pose problems like different definition for setTimeout function etc...

P.S. first I thought that you use node only as part of build process and in such case @types/node should be in devDependencies section.

**Comment by ibc** [comment]
What is the way to go for a TypeScript app that exposes `EventEmitter` objects and must run in browser and Node?

**Comment by edvinv** [comment]
I don't think there is perfect solution but including node types will completely pollute browser environment. Maybe just import @types/events, this will certainly be ok for browser and should work in node too, because typescript uses structural inheritance.

**Comment by jmillan** [comment]
@types/node does no longer exist. We just require @types/events
