### ISSUE TITLE
Allow customizing reply headers

### ISSUE THREAD

**Issue by ilovett** [versatica/JsSIP#664]
Can we add a feature to customize the headers in the stateful/stateless reply messages?  I would be happy to create the PR for it, just want to make sure it would be accepted as an opt-in feature.

In particular I would like to add a `User-Agent` header for each reply message as well as `Allow` with certain allowed actions as well.

**Comment by jmillan** [comment]
Let's use the mailing list for questions please

**Comment by ilovett** [comment]
This is a feature request

**Comment by jmillan** [comment]
Yes, only that this is partially already doable by the existing API and the content of the thread may be useful for the rest of the users asking for it in the future.
