### ISSUE TITLE
Handle incoming BYE in WAITING_FOR_ANSWER state

### ISSUE THREAD

**Issue by karstenluedtke** [versatica/JsSIP#665]
The state machine for incoming calls switches from INVITE_RECEIVED
to WAITING_FOR_ANSWER almost immediately after receiving an INVITE.

Thus an incoming BYE (that was sent by the remote party instead of CANCEL)
should be processed the same as in INVITE_RECEIVED.

Expected behaviour:
UA shall send "200 OK" for the BYE, and "487 BYE Received" (or "Terminated") for the INVITE.

Actual behaviour:
UA sends "403 Wrong Status" for the BYE. 
Logs attached.

Proposed change:

diff --git a/lib/RTCSession.js b/lib/RTCSession.js
index 135f105..0fd6077 100644
--- a/lib/RTCSession.js
+++ b/lib/RTCSession.js
@@ -1499,7 +1499,8 @@ module.exports = class RTCSession extends EventEmitter
             request.reply(200);
             this._ended('remote', request, JsSIP_C.causes.BYE);
           }
`-`          else if (this._status === C.STATUS_INVITE_RECEIVED)
`+`          else if (this._status === C.STATUS_INVITE_RECEIVED ||
`+`                   this._status === C.STATUS_WAITING_FOR_ANSWER)
           {
             request.reply(200);
             this._request.reply(487, 'BYE Received');
[bye_received.diff.txt](https://github.com/versatica/JsSIP/files/5361357/bye_received.diff.txt)

[bye_received.log](https://github.com/versatica/JsSIP/files/5361340/bye_received.log)

**Comment by jmillan** [comment]
Good catch @karstenluedtke,

Would you please make a PR?

**Comment by jmillan** [comment]
New release has been created. Thanks @karstenluedtke!
