### ISSUE TITLE
Cannot read property of 'STATUS_TERMINATED' of undefined

### ISSUE THREAD

**Issue by acharlop** [versatica/JsSIP#673]
I'm getting intermittent errors from `RequestSender.js` with the error in title. Not quite sure how to do about giving you any more info.

Looks like it's from the line 118
`if (this._dialog.owner.status !== RTCSession.C.STATUS_TERMINATED)`

**Comment by ibc** [comment]
Unless you have really identified a real bug, use the mailing list for questions and usage problems, please.

**Comment by acharlop** [comment]
Yes this is a bug, I'm trying to ask for help how I can get you more information. There's a TODO in the line above, and I get console errors.

**Comment by ibc** [comment]
If this is a bug demonstrate how to reproduce it and explain when exactly it happens. Otherwise you are just asking us to spend time figuring out whether this is a bug or not.
