### ISSUE TITLE
REGISTER message rfc7118 conformance 

### ISSUE THREAD

**Issue by sergey-safarov** [versatica/JsSIP#680]
According to [rfc7118#section-5.2](https://tools.ietf.org/html/rfc7118#section-5.2)

>5.2.  SIP URI Transport Parameter
   This document defines the value "ws" as the transport parameter value
   for a SIP URI [RFC3986] to be contacted using the SIP WebSocket
   subprotocol as transport.

> The updated augmented BNF for this parameter is the following (the
   original BNF for this parameter can be found in [RFC3261]):

> transport-param  =/  "transport=" "ws"

And `REGISTER` example in same RFC

```
   REGISTER sip:proxy.example.com SIP/2.0
   Via: SIP/2.0/WSS df7jal23ls0d.invalid;branch=z9hG4bKasudf
   From: sip:alice@example.com;tag=65bnmj.34asd
   To: sip:alice@example.com
   Call-ID: aiuy7k9njasd
   CSeq: 1 REGISTER
   Max-Forwards: 70
   Supported: path, outbound, gruu
   Contact: <sip:alice@df7jal23ls0d.invalid;transport=ws>;reg-id=1
```

Could you add `";transport=ws"` to be more compliant with rfc7118.

**Comment by ibc** [comment]
This is a REGISTER sent from JsSIP:

`Contact: <sip:hpd58912@s0hlbkav24o0.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:d28db3e9-16cb-4727-ace2-12b8260e7cc2>";expires=600`
