### ISSUE TITLE
no audio through AudioContext

### ISSUE THREAD

**Issue by palka82** [versatica/JsSIP#681]
I am trying to play the voice stream into a specific ear (left or right).  But there is no voice. There is only voice through window.Audio (), but no separation. Why is there no voice through AudioContext.Destination ()?

`let audioCtx = new window.AudioContext();`
`let remoteAudio = new window.Audio();`
`        remoteAudio.autoplay = false;`
`        remoteAudio.muted = true;`
        remoteAudio.crossOrigin = 'anonymous';

let callOptions = {
            pcConfig:
                {
                    hackStripTcp: true, // Важно для хрома, чтоб он не тупил при звонке
                    rtcpMuxPolicy: 'negotiate', // Важно для хрома, чтоб работал multiplexing. Эту штуку обязательно нужно включить на астере.
                    iceServers: [],
                },
            mediaConstraints: {
                audio: true,
                video: false,
            },
            rtcOfferConstraints:
                {
                    offerToReceiveAudio: 1, // Принимаем только аудио
                    offerToReceiveVideo: 0,
                },
        };
phone = new JsSIP.UA(configuration);
            phone.on('newRTCSession', function(ev) {
                let newSession = ev.session;
                if (session) { // hangup any existing call
                    session.terminate();
                }
                session = newSession;
                session.on('peerconnection', (e) => {
                    console.log('peerconnection', e);
                    let logError = '';
                    const peerconnection = e.peerconnection;
                    peerconnection.ontrack = function(e) {
                        console.log('ontrack', e);
                        console.log('ontrack', audioCtx);
                        audioCtx.listener.setPosition(0, 0, 0);
                        //remoteAudio.srcObject = e.streams[0];
                        //remoteAudio.pause();
                        let source = audioCtx.createMediaStreamSource(e.streams[0]);
                        //let source = audioCtx.createMediaElementSource(remoteAudio);
                        let panNode = audioCtx.createStereoPanner();
                        panNode.pan.value = -1;
                        source.connect(panNode);
                        panNode.connect(audioCtx.destination);
                        //remoteAudio.muted = false;
                        // remoteAudio.play();
                    };
                    let remoteStream = new MediaStream();
                    console.log(peerconnection.getReceivers());
                    peerconnection.getReceivers().forEach(function(receiver) {
                        console.log(receiver);
                        remoteStream.addTrack(receiver.track);
                    });
                });
                if (session.direction === 'incoming') {
                    session.answer(callOptions);
                }`

**Comment by ibc** [comment]
Not here, sorry.
