### ISSUE TITLE
Grammar.parse can't parse header "Contact" that includes #

### ISSUE THREAD

**Issue by DrimerD** [versatica/JsSIP#687]
When webRtc trying to start a call and header <Contact> contains # symbol - webrtc can't send ACK and crash... because Grammar.parse can't parse this header.
I solve this problem the next way:
 I replace header symbol # to %23 (headerValue.replace('#', '%23'))

SIP/2.0 200 OK
Via: SIP/2.0/WSS olj5nvnia2a5.invalid;rport=42894;received=192.168.25.92;branch=z9hG4bK8024985
Record-Route: <sip:rE+E+4LTPqFh9AXAqAuaE8TAqBlcp44=@192.168.11.154:5060;transport=udp;r2=on;ftag=pv6omdbqub;lr;did=43e.9161>
Record-Route: <sip:rE+E+4LTPqFh9AXAqAuaE8TAqBlcp44=@192.168.11.154:5060;transport=ws;r2=on;ftag=pv6omdbqub;lr;did=43e.9161>
From: "Administrator User" <sip:admin!qa.com@mytp.iccswitch.com>;tag=pv6omdbqub
To: <sip:*%239240@mytp.iccswitch.com>;tag=Zja6mteyttjcp
Call-ID: pb7ksmaubtpfa6sn7fv5
CSeq: 7083 INVITE
Contact: <sip:*#9240@192.168.11.155:5060;transport=udp>
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY
Supported: precondition, 100rel, timer, path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 805
Remote-Party-ID: "*#9240" <sip:*#9240@mytp.iccswitch.com>;party=calling;privacy=off;screen=no
User-Agent: SBC-CISCO

v=0
o=FreeSWITCH 1612431323 1612431324 IN IP4 51.38.198.88
s=FreeSWITCH
c=IN IP4 51.38.198.88
t=0 0
a=msid-semantic: WMS VsbYryBaZyG6swTQZDxAv8e8c5qod6iY
m=audio 20548 UDP/TLS/RTP/SAVPF 0 126 13
a=ssrc:2083392747 cname:pkNGIeHxDdtWzdCp
a=ssrc:2083392747 msid:VsbYryBaZyG6swTQZDxAv8e8c5qod6iY a0
a=ssrc:2083392747 mslabel:VsbYryBaZyG6swTQZDxAv8e8c5qod6iY
a=ssrc:2083392747 label:VsbYryBaZyG6swTQZDxAv8e8c5qod6iYa0
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=rtpmap:13 CN/8000
a=sendrecv
a=rtcp:20548
a=rtcp-mux
a=setup:active
a=fingerprint:sha-1 91:BF:4E:0A:71:95:12:B0:B2:5E:2D:5B:5A:F0:7A:B4:FC:D7:86:AF
a=ptime:20
a=ice-ufrag:xL5R3Wuq
a=ice-pwd:r9l8phWSq2TSqUqsIoW6JMVPSC
a=candidate:5g40AIZHGYdp52Nq 1 UDP 2130706431 51.38.198.88 20548 typ host
a=end-of-candidates

**Comment by ibc** [comment]
Well, perhaps this happens because such a `#` in the SIP URI component of the `Contact` header is **NOT** valid according to ABNF grammar.

So please tell FreeSwitch developers about this bug in their code.
