### ISSUE TITLE
No audio after hold/unhold on incoming calls

### ISSUE THREAD

**Issue by abalashov** [versatica/JsSIP#691]
Using the latest stable release of JsSIP, the JsSIP endpoint ceases to transmit audio when `JsSIP.RTCSession.hold()` is engaged, and does not resume doing so when `JsSIP.RTCSession.unhold()` is called. 

(Because the SIP-WS/RTP gateway on the other side performs strict server-side NAT traversal and RTP latching, no RTP frames from JsSIP means no incoming frames show up, either, leading to no audio in either direction.)

This **only** happens:
* on incoming calls--that is, calls that have been `answer()`d. If an outbound `call()` is made and JsSIP places the remote user on hold, it continues to transmit RTP while in that state, as well as when it comes out of that state;

* only in Chrome (tested on Linux with 83.0.4103.61 and 89.0.4389.82 on OSX) and Safari (14.0.3); Firefox (86.0/Linux) continues to send audio throughout the hold cycle as on outbound calls.

I'm not sure if this is a bug, a novel quirk in Webkit-based browsers, or some API instrumentation problem on our side. 

How I put the session on hold:

```
   if(!session.isEstablished() || session.isOnHold().local)
     return;

   session.hold();
```

And off hold:

```
   if(!session.isEstablished() || !session.isOnHold().local)
      return;

   session.unhold();
```

To play out audio, we have an `Audio` element that is not attached to the DOM and is initialised on startup. When we `call()` or `answer()`, we add an event handler like this:

```
   session.connection.addEventListener('track', t => {
      this._audio.srcObject = t.streams[0];
      this._audio.play();
   });
```

Not that I think it makes a difference, since everything works fine on outgoing calls, but the server side is always DTLS-passive, offers / answers RTCP-MUX, and otherwise generates identical SDP answers in the `200 OK`s to JsSIP's re-invites when taking calls on/off hold. I've scrutinised the SDP answers for reinvites in outgoing vs incoming calls for any differences with a fine-toothed comb, and there aren't any apart from call/transaction/dialog-specific SIP fields.

Thank you very much in advance for any light you may be able to shed!

**Comment by ibc** [comment]
Not a bug in JsSIP. Please use the mailing list.

**Comment by abalashov** [comment]
Okay. Sorry about that.
