### ISSUE TITLE
MicroSIP client dial JSSIP via FreeSwitch-1.10.6-dev-5007~e5277a8~32bit sends ring event to voice mail after answer

### ISSUE THREAD

**Issue by Shark-y** [versatica/JsSIP#692]
Hi,
Is this a bug? Any help will be appreciated. Thanks  (log files attached)
1. Start MicroSIP client,  dial JSSIP (html code attached jssip.zip) - script auto accepts call , 
2. Accept call from JSSIP (INVITE looks ok, SIP 200 is sent  - see ring.log)
3. _FreeSwitch (Win32 DTLS v1.2) sends call to voice mail (MicroSip receives voicemail message)_
[freeswitch.log](https://github.com/versatica/JsSIP/files/6101911/freeswitch.log)
[ring.log](https://github.com/versatica/JsSIP/files/6101933/ring.log)
[connect.log](https://github.com/versatica/JsSIP/files/6101929/connect.log)
Here is the JSSIP test HTML I use - jssip.zip (compressed HTML so I can upload. Note: connect works, dial from JSSIP to MicroSip works)
[jssip.zip](https://github.com/versatica/JsSIP/files/6101944/jssip.zip)
**Notes:**
1. JSSP coonect works, Dial from JSSP to Microsip/Zoiper works.
2. MicroSIP - https://www.microsip.org/
3. Same thing occurs if I dial from Zoiper.
**Here is the INVITE - answer SIP 200 sequence (from ring.log)**
JsSIP:Transport received text message:

INVITE sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws SIP/2.0

Via: SIP/2.0/WSS 192.168.42.185:7443;branch=z9hG4bK5DeH431SQpZ0p

Route: <sip:ehab9fmc@192.168.42.185:52423>;transport=wss

Max-Forwards: 69

From: "Extension 1001" <sip:1001@192.168.42.185>;tag=BvcUt8Ncv2KQQ

To: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>

Call-ID: f6218b95-faba-1239-c385-9916c842b3cb

CSeq: 33052540 INVITE

Contact: <sip:mod_sofia@172.58.156.21:5060>

User-Agent: FreeSWITCH-mod_sofia/1.10.6-dev-5007~e5277a8~32bit

Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE

Supported: timer, path, replaces

Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer

Session-Expires: 120;refresher=uac

Min-SE: 120

Content-Type: application/sdp

Content-Disposition: session

Content-Length: 1144

X-FS-Support: update_display,send_info

Remote-Party-ID: "Extension 1001" <sip:1001@192.168.42.185>;party=calling;screen=yes;privacy=off

v=0

o=FreeSWITCH 1615193920 1615193921 IN IP4 192.168.42.185

s=FreeSWITCH

c=IN IP4 192.168.42.185

t=0 0

a=msid-semantic: WMS 7jkPiu3BxFY5YlvrZSj5Wf4JNx2ti2Zv

m=audio 18744 RTP/SAVPF 8 0 102 9 101 103

a=rtpmap:8 PCMA/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:102 opus/48000/2

a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40; stereo=1

a=rtpmap:9 G722/8000

a=rtpmap:101 telephone-event/8000

a=rtpmap:103 telephone-event/48000

a=fingerprint:sha-256 F7:D1:8D:57:AA:25:B0:28:2B:30:7D:B0:C0:E9:D7:0A:0B:8F:2E:11:9C:BF:75:2F:30:67:ED:15:CB:92:A5:60

a=setup:actpass

a=rtcp-mux

a=rtcp:18744 IN IP4 192.168.42.185

a=ssrc:1804308712 cname:D8ExKOnioX7jouqt

a=ssrc:1804308712 msid:7jkPiu3BxFY5YlvrZSj5Wf4JNx2ti2Zv a0

a=ssrc:1804308712 mslabel:7jkPiu3BxFY5YlvrZSj5Wf4JNx2ti2Zv

a=ssrc:1804308712 label:7jkPiu3BxFY5YlvrZSj5Wf4JNx2ti2Zva0

a=ice-ufrag:SlCfL6KlUQvyIyPF

a=ice-pwd:sOe5IaB1KKAZ7KbzL7SPzhEF

a=candidate:7199272615 1 udp 2130706431 192.168.42.185 18744 typ host generation 0

a=candidate:7199272615 2 udp 2130706431 192.168.42.185 18744 typ host generation 0

a=ptime:20

 +3m jssip-3.7.1.min.js:9:251234
JsSIP:Transport send() +7ms jssip-3.7.1.min.js:9:251234
JsSIP:Transport sending message:

SIP/2.0 100 Trying

Via: SIP/2.0/WSS 192.168.42.185:7443;branch=z9hG4bK5DeH431SQpZ0p

To: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>

From: "Extension 1001" <sip:1001@192.168.42.185>;tag=BvcUt8Ncv2KQQ

Call-ID: f6218b95-faba-1239-c385-9916c842b3cb

CSeq: 33052540 INVITE

Supported: timer,ice,replaces,outbound

Content-Length: 0

 +1ms jssip-3.7.1.min.js:9:251234
JsSIP:WebSocketInterface send() +10ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession new +0ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession init_incoming() +2ms jssip-3.7.1.min.js:9:251234
JsSIP:Dialog new UAS dialog created with status EARLY +0ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession newRTCSession() +1ms jssip-3.7.1.min.js:9:251234
[SIP] Call event incoming jssip.html:15:10
[SIP] ******* ANSWER jssip.html:15:10
JsSIP:RTCSession answer() +2ms jssip-3.7.1.min.js:9:251234
JsSIP:Dialog dialog f6218b95-faba-1239-c385-9916c842b3cb71urnlqaahBvcUt8Ncv2KQQ  changed to CONFIRMED state +2ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "peerconnection" +12ms jssip-3.7.1.min.js:9:251234
JsSIP:Transport send() +18ms jssip-3.7.1.min.js:9:251234
JsSIP:Transport sending message:

SIP/2.0 180 Ringing

Via: SIP/2.0/WSS 192.168.42.185:7443;branch=z9hG4bK5DeH431SQpZ0p

To: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>;tag=71urnlqaah

From: "Extension 1001" <sip:1001@192.168.42.185>;tag=BvcUt8Ncv2KQQ

Call-ID: f6218b95-faba-1239-c385-9916c842b3cb

CSeq: 33052540 INVITE

Contact: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>

Supported: timer,ice,replaces,outbound

Content-Length: 0

 +1ms jssip-3.7.1.min.js:9:251234
JsSIP:WebSocketInterface send() +18ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession session progress +2ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "progress" +0ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "sdp" +6s jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession session connecting +3ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "connecting" +2ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession createLocalDescription() +0ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "sdp" +14ms jssip-3.7.1.min.js:9:251234
JsSIP:Transport send() +7s jssip-3.7.1.min.js:9:251234
JsSIP:Transport sending message:

SIP/2.0 200 OK

Via: SIP/2.0/WSS 192.168.42.185:7443;branch=z9hG4bK5DeH431SQpZ0p

To: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>;tag=71urnlqaah

From: "Extension 1001" <sip:1001@192.168.42.185>;tag=BvcUt8Ncv2KQQ

Call-ID: f6218b95-faba-1239-c385-9916c842b3cb

CSeq: 33052540 INVITE

Contact: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>

Session-Expires: 120;refresher=uac

Supported: timer,ice,replaces,outbound

Content-Type: application/sdp

Content-Length: 1343

v=0

o=mozilla...THIS_IS_SDPARTA-86.0 6638910987847320033 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 8F:D6:F2:56:72:CE:38:8C:15:4C:3C:3C:03:82:AA:C6:7E:8B:96:9B:6F:AA:C6:8A:70:7E:B1:30:0F:B0:14:15

a=ice-options:trickle

a=msid-semantic:WMS *

m=audio 49387 RTP/SAVPF 8 0 102 9 101

c=IN IP4 172.26.96.1

a=candidate:0 1 UDP 2122252543 172.26.96.1 49387 typ host

a=candidate:1 1 UDP 2122055935 192.168.42.185 49388 typ host

a=candidate:2 1 UDP 2122187007 192.168.56.1 49389 typ host

a=candidate:3 1 UDP 2122121471 192.168.99.1 49390 typ host

a=candidate:4 1 TCP 2105524479 172.26.96.1 9 typ host tcptype active

a=candidate:5 1 TCP 2105327871 192.168.42.185 9 typ host tcptype active

a=candidate:6 1 TCP 2105458943 192.168.56.1 9 typ host tcptype active

a=candidate:7 1 TCP 2105393407 192.168.99.1 9 typ host tcptype active

a=sendrecv

a=end-of-candidates

a=fmtp:102 maxplaybackrate=48000;stereo=1;useinbandfec=1

a=fmtp:101 0-15

a=ice-pwd:d4aae272e5b04aef0b85f5079a5c6d1f

a=ice-ufrag:214a86ee

a=mid:0

a=msid:{5618135a-897f-46e7-b5bb-ebc17d6152c9} {28f60f6c-46db-46aa-87cd-1f1f5e561f87}

a=rtcp-mux

a=rtpmap:8 PCMA/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:102 opus/48000/2

a=rtpmap:9 G722/8000/1

a=rtpmap:101 telephone-event/8000

a=setup:active

a=ssrc:2822897356 cname:{c1d62ff3-abcb-472f-b664-76e7d4a48bf9}

 +0ms jssip-3.7.1.min.js:9:251234
JsSIP:WebSocketInterface send() +7s jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession session accepted +2ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "accepted" +0ms jssip-3.7.1.min.js:9:251234
JsSIP:WebSocketInterface received WebSocket message +28ms jssip-3.7.1.min.js:9:251234
JsSIP:Transport received text message:

ACK sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws SIP/2.0

Via: SIP/2.0/WSS 192.168.42.185:7443;branch=z9hG4bK6p795yjXmZNKj

Max-Forwards: 70

From: "Extension 1001" <sip:1001@192.168.42.185>;tag=BvcUt8Ncv2KQQ

To: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>;tag=71urnlqaah

Call-ID: f6218b95-faba-1239-c385-9916c842b3cb

CSeq: 33052540 ACK

Contact: <sip:mod_sofia@172.58.156.21:5060>

Content-Length: 0

 +28ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession receiveRequest() +32ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession session confirmed +0ms jssip-3.7.1.min.js:9:251234
JsSIP:RTCSession emit "confirmed" +1ms jssip-3.7.1.min.js:9:251234
JsSIP:WebSocketInterface received WebSocket message +6ms jssip-3.7.1.min.js:9:251234
JsSIP:Transport received text message:

BYE sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws SIP/2.0

Via: SIP/2.0/WSS 192.168.42.185:7443;branch=z9hG4bK7Z027S30H8B6D

Max-Forwards: 70

From: "Extension 1001" <sip:1001@192.168.42.185>;tag=BvcUt8Ncv2KQQ

To: <sip:ehab9fmc@lel5ec6qauj2.invalid;transport=ws>;tag=71urnlqaah

Call-ID: f6218b95-faba-1239-c385-9916c842b3cb

CSeq: 33052541 BYE

User-Agent: FreeSWITCH-mod_sofia/1.10.6-dev-5007~e5277a8~32bit

Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE

Supported: timer, path, replaces

Reason: Q.850;cause=88;text="INCOMPATIBLE_DESTINATION"

Content-Length: 0

**Comment by ibc** [comment]
Sorry, this cannot be a bug in JsSIP. Use the mailing list, please.

**Comment by Shark-y** [comment]
How do I access the mailing list? Thanks
