### ISSUE TITLE
Parser fails parsing `Contact` header if it contains a colon

### ISSUE THREAD

**Issue by rcidt** [versatica/JsSIP#698]
I am running JsSIP 3.7.2

JsSIP will throw `error parsing header "Contact"` if it receives a 200OK message that contains a `Contact` header with a colon, for example:

```
<sip:myname@1.2.3.4:5060;transport=udp>;expires=390,: <sip:r25vbuel@bnnnmsalf81i.invalid;transport=ws>;expires=30
```

**Comment by ibc** [comment]
Yes, of course, because such a Contact header is invalid due to, exactly, such a colon.
