### ISSUE TITLE
App is unable to re-REGISTER after Parser encounters an error

### ISSUE THREAD

**Issue by rcidt** [versatica/JsSIP#699]
**JsSIP Version**
3.7.2

**Current Behavior** 
The Parser throws an error due to an invalid Contact header (state no.2), the Registrator goes into an invalid state and the `ua.isRegistered`, `ua.register` and `ua.unregister` methods become unreliable.

**Expected Behavior**
If the Parser encounters an error (state no.2), this should not affect the Registrator.
Even though the Contact header is invalid, the UA should still be able to refresh the registration.

**Steps to Reproduce**
Start the UA and be registered.

Receive a SIP 200OK message with a header with the following format (take special notice of the colon in the middle):

`<sip:myname@1.2.3.4:5060;transport=udp>;expires=390,: <sip:r25vbuel@bnnnmsalf81i.invalid;transport=ws>;expires=30`

Upon receiving this Contact header, you will notice in `Grammar.js#computeErrorPosition`, the parser will be in "state no.2"

```       
        2. The parser successfully parsed only a part of the input.
       
           - |result !== null|
           - |pos < input.length|
           - |rightmostFailuresExpected| may or may not contain something
```

In the console, you will notice the following error is thrown:

`JsSIP:ERROR:Parser parseMessage() | +0ms error parsing header "Contact"`

Now make a call to `ua.unregister()`. You will notice the following message in the console:

`JsSIP:Registrator already unregistered +0ms`

Now make a call to `ua.register()`. You will notice the following message in the console:

`JsSIP:Registrator Register request in progress... +2s`

**Comment by ibc** [comment]
Not a bug. This is how SIP protocol works. If a REGISTER is sent a its response is never received, the UA will wait for Timer F (defined in RFC 3261) to expire. This is 32 seconds. After those 32 seconds, the REGISTER transaction will fail with "timeout error" and that will trigger `onRequestTimeout` event handler in `Registrator.js` in JsSIP, which will call `this._registrationFailure(null, JsSIP_C.causes.REQUEST_TIMEOUT);`, and that will reset `this._registering = false;`, so you can call `register()` again.

No bug here.

**Comment by rcidt** [comment]
Thanks for your reply @ibc. Is there any way to catch the error?

**Comment by ibc** [comment]
You have a problem with your SIP server which sends you an invalid Contact header. No error in JsSIP side. If JsSIP receives an **invalid** SIP message it discards it, nothing else. So timeout will happen and your `UA` will emit `registrationFailed` event as documented in the API:

https://jssip.net/documentation/3.7.x/api/ua/#event_registrationFailed

**Comment by rcidt** [comment]
@ibc you are correct, except `registrationFailed` is never emitted in this case.

**Comment by ibc** [comment]
It will be emit after 32 seconds.

**Comment by rcidt** [comment]
@ibc I don't see it happening after 32 seconds either.

**Comment by rcidt** [comment]
You are right, I see it now. Thank you

**Comment by kilimill** [comment]
Can i changed this time: 32 sec?
