### ISSUE TITLE
Session mute state when doing a renegotiate

### ISSUE THREAD

**Issue by karljohanwesterlund** [versatica/JsSIP#700]
* [Groups discussion](https://groups.google.com/g/jssip/c/Lt5wm4X1_Qg)
* JsSIP version: 3.6.1

I'm doing a renegotiate in a JsSIP implementation when a `ondevicechange` event is emitted. This works fine and the softphone is handling the change in device in all cases **but** when the RTCSession is muted.

When I do a renegotiate on a session that is muted the renegotiation is done and in my case the new device is starting to send audio from the newly selected device. The issue is that the RTCSession state still has the isMuted-flag enabled on audio, even though the RTCSession is sending audio.

Is this working as intended? Intuitively I feel as if the session is muted either there should be no audio sent, or that the `rtcsession._muted` flag should be "reset" on a renegotiate.

**Comment by ibc** [comment]
I don't understand the issue. What does happen when `ondevicechange` event is emitted? what do you do after that? are you replacing the local stream of the `RTCSession` with a new one that contains a new obtained audio track after doing `getUserMedia()`? how do you do it?

**Comment by karljohanwesterlund** [comment]
On the emission of `ondevicechange` I get a new stream of the new device that the client has changed to, and for the 
`session.connection` I replace the track something like
```
// User Alice somewhere mutes audio
session.mute({ audio: true });

// ... Later, a SIP renegotiation is done for Alice, like:
const stream = await navigator.mediaDevices.getUserMedia({ video: false, audio: {deviceId} });
const audioTracks = stream.getAudioTracks();
session.connection.getSenders().forEach(r => r.replaceTrack(audioTracks[0]));
session.renegotiate(undefined, () => {
    // Renegotiate done - Other part Bob can now hear Alice new audio track,
    // but Alice session.isMuted() still returns true:
    console.info('Muted state:', session.isMuted())
});
```

So the issue is that when Alice is muting her session, then does a `session.renegotiate`, the session claims to be muted, while the other part Bob can hear your audio from Alice new audio device but Alice `session.isMuted` still claims to be true.

**Comment by ibc** [comment]
Ok, I understand. However we cannot do nothing at JsSIP level. You are changing the stream by directly using the `session.connection` object, which is the underlying `RTCPeerConnection`, so JsSIP does not even realize of it and there is nothing it can do to mute new track(s) if `RTCSession` is currently audio/video muted.

So, for it to work, you need to check [session.isMuted()](https://jssip.net/documentation/3.7.x/api/session/#method_isMuted) and, if muted, set `track.enabled = false` before you replace the tracks.

BTW eventually we are gonna get rid of WebRTC in JsSIP (it will be externally managed).

**Comment by karljohanwesterlund** [comment]
Okay fair. Tampering with the session.connection object was from my understanding how the renegotiation was to be done

> Useful after modifying the local stream attached to the underlying RTCPeerConnection (via the connection attribute).

[3.6.x doc](https://jssip.net/documentation/3.6.x/api/session/#method_renegotiate) (3.7.x as well)

What's the plan in the future if I might ask?

**Comment by ibc** [comment]
Yes, I didn't mean that it's not correct. That's the way.

See ongoing PR about removing WebRTC stuff from JsSIP.
