### ISSUE TITLE
JsSIP.RTCSession is not accessible from TypeScript?

### ISSUE THREAD

**Issue by jlaine** [versatica/JsSIP#703]
I am trying to make use of JsSIP in an app written in TypeScript and having type definitions is great - thanks!

However, it looks as though the `RTCSession` type definitions are not exported, and as a result I don't see how to hold a (typed) reference to an RTCSession object. Is this by design?

Adding the following to JsSIP.d.ts fixes it for me:

`export {RTCSession} from './RTCSession';`

**Comment by jlaine** [comment]
Answering my own question, the following seems to work without any changes to JsSIP:

`import { RTCSession } from 'jssip/lib/RTCSession';`

**Comment by ibc** [comment]
> Answering my own question, the following seems to work without any changes to JsSIP:
> 
> `import { RTCSession } from 'jssip/lib/RTCSession';`

In theory it shouldn't be needed when you operate with a `session` object after creating/getting it via API, but it may depend on the text editor, etc. No idea honestly. It will work better when we move JsSIP entirely to TypeScript.
