### ISSUE TITLE
Circular dependency causes "TypeError: Cannot read property 'STATUS_TERMINATED' of undefined"

### ISSUE THREAD

**Issue by alexsharabaykoidt** [versatica/JsSIP#705]
_Versions: 3.7.0 - 3.7.5 (at least)_

The library build has circular dependency: `./UA` -> `./RTCSession` -> `./Dialog` -> `./Dialog/RequestSender` -> `../RTCSession`

Thus `RTCSession` is empty object inside `Dialog/RequestSender` and it doesn't have `C` (constants) property. And then when 491 status comes `RTCSession.C.STATUS_TERMINATED` cannot be executed without TypeError.

![image](https://user-images.githubusercontent.com/50661349/115740522-916a8b00-a397-11eb-9993-80f06c0bcf2a.png)

So i see two ways how to fix it:

1. Resolve circular dependency
2. Import RTCSession every time before its usage

**Comment by ibc** [comment]
> 2. Import RTCSession every time before its usage

Dynamic import is anti-pattern and does not work when using ES6 `import` (we'll migrate to that eventually).

> 1. Resolve circular dependency

Can you contribute with a PR?
