### ISSUE TITLE
`_this2._request_sender.send()` causes error in `Dialog/RequestSender`

### ISSUE THREAD

**Issue by alexsharabaykoidt** [versatica/JsSIP#706]
`Dialog/RequestSender` calls `_this2._request_sender.send()` in 491 status handler to make another request attempt.

But `_request_sender` doesn't exist so this line causes exception.

Looks like `this.send()` is good alternative for this line

**Comment by jmillan** [comment]
Can you please provide with the corresponding JsSIP logs?

**Comment by rcidt** [comment]
@jmillan Why do you need logs? Just look at the code, it's an obvious bug as `this._request_sender` is clearly undefined.

**Comment by rcidt** [comment]
@jmillan why do you need logs? If you simply [look at the code](https://github.com/versatica/JsSIP/blob/master/lib/Dialog/RequestSender.js#L121) you will easily notice that it's a bug/typo. `this._request_sender` is undefined.

**Comment by ibc** [comment]
Let's reopen.

**Comment by ibc** [comment]
PR https://github.com/versatica/JsSIP/pull/787

**Comment by jmillan** [comment]
Thanks for the report @alexsharabaykoidt and @rcidt
