### ISSUE TITLE
Looks like `this._request.cseq = this._dialog.local_seqnum += 1` is not enough in 491 status handler

### ISSUE THREAD

**Issue by alexsharabaykoidt** [versatica/JsSIP#707]
_Version: 3.7.0-3.7.5 (at least)_

The library increments `cseq` property in 491 status handler to make reattempt, but unfortunately it's not enough. Request header also should be updated, in this way for example:

`this._request.setHeader('cseq', ''.concat(this._request.cseq, ' ').concat(this._request.method))`

**Comment by jmillan** [comment]
Can you point to the exact file:line and be more specific?

**Comment by jmillan** [comment]
closed due to lack of information.
