### ISSUE TITLE
Demo with latest version?

### ISSUE THREAD

**Issue by gisheri** [versatica/JsSIP#710]
Is there a demo sip client that has been made with the latest jssip version? I'm new to sip in general, and trying to create a softphone, and it has been a difficult journey trying to learn the recipes for how to get functionality working. It seems like all examples I find throughout the web are using deprecated functions. It would be really helpful to see an updated working example to emulate

**Comment by gisheri** [comment]
Why did you close this issue without a comment? I really appreciate the work that has been put into this library, and for the typescript support you've added, but the docs and examples are sparse

**Comment by ibc** [comment]
Use the mailing list for questions, please.

**Comment by gisheri** [comment]
Ah, thank you
