### ISSUE TITLE
New Feature: allow to override debugerror

### ISSUE THREAD

**Issue by lamuertepeluda** [versatica/JsSIP#713]
## Use Case
I need to intercept the logs from both errors and standard debug log messages, e.g. for sending them to a backend. 

Logging standard messages is easy by overriding the debug.log function, e.g. as shown here: https://groups.google.com/g/jssip/c/5LWejj-N_sU, i.e.

```javascript
JsSIP.debug.log = (...args) => {
    const logString = args[0].replace(/%c/g, '');  // Remove coloring syntax used by debug tool.
    logger(logString);
};
```

Logging `debugerror` is however impossible, since it's internally defined and bound to console.warn() in an isolated scope.  
E.g. [like in this commit](https://github.com/versatica/JsSIP/commit/8b4e547c731c5ec92cbe44fd320c927104dddf02), or [here in the sources](https://github.com/versatica/JsSIP/blob/master/lib/WebSocketInterface.js#L5)

```javascript
var debugerror = require('debug')('JsSIP:ERROR:Socket');
debugerror.log = console.warn.bind(console);
```

Because of this implementation, [exposing the debug module as it's done here](https://github.com/versatica/JsSIP/blob/master/lib/JsSIP.js#L27) is not enough.

## Proposal

Have an option for overriding the default logger(s), with default to the current behaviour. 

I can try a PR if you like this idea.

**Comment by jmillan** [comment]
> Have an option for overriding the default logger(s), with default to the current behaviour.

Feel free to create a PR.
