### ISSUE TITLE
support for Trickle ICE (RFC 8840), updating list of RFCs?

### ISSUE THREAD

**Issue by dpocock** [versatica/JsSIP#716]
Does JsSIP support the combination of SIP and Trickle ICE, as in RFC 8840?

If yes, could you please add it to the list of RFCs on the web page?
https://jssip.net/documentation/3.7.x/overview/

Does it require any code or configuration settings from developers using JsSIP?  Or is it handled internally within the JsSIP library?

**Comment by ibc** [comment]
No, it doesn't.
Please, let's use the mailing list for questions.

**Comment by dpocock** [comment]
If it isn't supported, could you please reopen this as a feature request?  Or it has been decided not to add this feature at all?

**Comment by ibc** [comment]
We'll go in the other direction. We plan to drop built-in WebRTC support from JsSIP next major version, meaning that it will be up to the app to deal with WebRTC. JsSIP will focus on SIP protocol.

**Comment by dpocock** [comment]
Have you seen the way we divided reSIProcate into 3 layers?  Could that be a useful model for you?

- [resip/stack](https://github.com/resiprocate/resiprocate/tree/master/resip/stack) - transports, header parsing, message parsing
- [resip/dum](https://github.com/resiprocate/resiprocate/tree/master/resip/dum) - Dialog Usage Manager - manages a series of requests and responses that form a dialog (e.g. INVITE, 200, ACK)
- [resip/recon](https://github.com/resiprocate/resiprocate/tree/master/resip/recon) - the User Agent layer - that is where I'm currently tweaking things to work with Kurento.

WebRTC is therefore integrated at the resip/recon layer

**Comment by Dimon70007** [comment]
Hi @dpocock 
I am trying to implement tricle ice with jssip too. could you explain how the ice candidates should be send through jssip to remote side or may be paste a link on a resource with information about it?
