### ISSUE TITLE
high version chrome  erro SIP/2.0 502 Bad Gateway 

### ISSUE THREAD

**Issue by lmr520** [versatica/JsSIP#718]
chrome:版本 91.0.4472.106（正式版本） (x86_64)
jssip:3.2.15
react-sip:0.8.1
log:JsSIP:Transport received text message:SIP/2.0 502 Bad Gateway
Via: SIP/2.0/WSS ********;branch=z9hG4bK1634308;received=218.75.109.234;rport=53281
Max-Forwards: 69
From: <sip:****@*********:****>;tag=eo4gnp6bnl
To: <sip:*************@*********:****>;tag=y9gry2m24Dg2K
Call-ID: 63780cf794msp4fsg7cc
CSeq: 3118 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.4.13~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Reason: Q.850;cause=27;text="DESTINATION_OUT_OF_ORDER"
Content-Length: 0
Remote-Party-ID: "Outbound Call" <sip:*************@*********:>;party=calling;privacy=off;screen=no

**Comment by ibc** [comment]
Thanks. Closing.

**Comment by lmr520** [comment]
I'm just a beginner ，Can you give me some advice?

**Comment by lmr520** [comment]
@ibc
