### ISSUE TITLE
Only iceServers 

### ISSUE THREAD

**Issue by igorpopryadukhin** [versatica/JsSIP#725]
Sorry, the question is simple. Is it possible to somehow force the stun / turn candidates?

```js
var options = {
  'pcConfig': {
    'iceServers': [
      { 'urls': ['stun:a.example.com', 'stun:b.example.com'] },
      { 'urls': 'turn:example.com', 'username': 'foo', 'credential': ' 1234' }
    ]
  }
};
```
Does this mean that only the listed iceServers will be used?

**Comment by ibc** [comment]
Questions in the mailing list, please.
