### ISSUE TITLE
The domain name  maybe starts with a number, parseMessage error parsing header "From"

### ISSUE THREAD

**Issue by xuffang** [versatica/JsSIP#735]
Could you modify the source code with the follows？
jssip\lib-es5\Grammar.js 
![image](https://user-images.githubusercontent.com/44192866/133750494-39b6fc49-9b50-4764-aac0-07ff6c52abb0.png)
change into
![image](https://user-images.githubusercontent.com/44192866/133750675-90d51415-31a3-4cee-ac0a-aa51a4ef497e.png)

issues: 
![企业微信截图_16316735328110](https://user-images.githubusercontent.com/44192866/133750414-2da9397c-681d-4642-bc23-86aad08462e9.png)

**Comment by ibc** [comment]
Of course not. That an alpha regex so no numbers.

**Comment by xuffang** [comment]
> Of course not. That an alpha regex so no numbers.

The domain  name maybe start with a number, what is the impact of this modification?

**Comment by ibc** [comment]
> The domain name maybe start with a number.

We are talking about the top level (com, net, org, etc).

JsSIP implements the ABNF grammar of SIP protocol. No changes needed here.

**Comment by xuffang** [comment]
> > The domain name maybe start with a number.
> 
> We are talking about the top level (com, net, org, etc).
> 
> JsSIP implements the ABNF grammar of SIP protocol. No changes needed here.

oh...  Now our business encounters a domain name that starts with a number, do you have any good way to deal with it?

**Comment by ibc** [comment]
I talked about domain "too label". Now you are just talking about "domain". Hard to agree on what we are talking about. Write such a domain, please.

**Comment by xuffang** [comment]
> I talked about domain "too label". Now you are just talking about "domain". Hard to agree on what we are talking about. Write such a domain, please.

https://923xff.testpcloud.yeastarcloud.com

the domain like this above,  and the question we talking about is the options package of the registration reply cannot be parsed

![image](https://user-images.githubusercontent.com/44192866/134477248-4e6a83ef-ad3a-4aa8-bdf6-a6ab08532e65.png)

so we hope to change the function to pass the rules， tks~

**Comment by ibc** [comment]
I'm sorry. `923xff` is NOT a valid hostname or domain. That's not JsSIP decision but ABNF decision according to the URL grammar. To be clear:

- `923xff.com` is a valid domain (top level is "com")
- `923xff.example.net` is a valid domain (top level is "net")
- `923xff` is **NOT** a valid domain (top level is "923xff" which, according to URL ABNF rules, **MUST NOT** begin with a number).

Sorry, nothing to fix here. Make your remote endpoint behave **correctly** and do not generate an invalid hostname in the "From" header.

**Comment by xuffang** [comment]
> I'm sorry. `923xff` is NOT a valid hostname or domain. That's not JsSIP decision but ABNF decision according to the URL grammar. To be clear:
> 
> * `923xff.com` is a valid domain (top level is "com")
> * `923xff.example.net` is a valid domain (top level is "net")
> * `923xff` is **NOT** a valid domain (top level is "923xff" which, according to URL ABNF rules, **MUST NOT** begin with a number).
> 
> Sorry, nothing to fix here. Make your remote endpoint behave **correctly** and do not generate an invalid hostname in the "From" header.

Ok, thank you for your reply.
