### ISSUE TITLE
No event is emitted when internet connection disconnects 

### ISSUE THREAD

**Issue by chandrarishabh** [versatica/JsSIP#737]
When internet is temporarily disconnected, JsSIP user agent doesn't receive any event like `disconnected` or `unregistered`. 
Also, it doesn't reinitiate registration/connection, because after internet is reconnected, incoming/outgoing calls don't work.

My use case is to let user notify about the status of connection, so basically I want to know when JsSIP is ready to make calls. 
According to documentations, JsSIP has two methods exposed on JsSIP.UA, `.isConnected()` and `.isRegistered()` but unfortunately they return true even when internet is disconnected.  

Apologies if I missed something in how SIP/JsSIP works.

**Comment by ibc** [comment]
Please use only the mailing list for questions.
