### ISSUE TITLE
New feature: reconnect during a call in case of network change

### ISSUE THREAD

**Issue by makstheimba** [versatica/JsSIP#738]
Hi!  I'm currently trying to implement reconnect after network change _without losing a current call_ and noticed the following behavior:
- if network changes JsSIP continues to send packets over established websocket connection but receives no answer to those packets
- once INVITE for session prolongation is sent through that ws connection, it doesn't go through and that is being considered as critical transport error causing session termination.

I've tried to listen to `iceconnectionstatechange` which is triggered with `disconnected` if I change my network. And even though I'm able to renegotiate for ICE candidate successfully it doesn't matter cause ws connection is closes along with the session.

If it's not possible to add reconnection ability directly into JsSIP than how can I do it for my project only?

I would really like to receive some tips on how to proceed with adding such a feature 🙏. Thanks!

**Comment by ibc** [comment]
Please, ask in the mailing list.

**Comment by hjkltop** [comment]
hi，bro.  I also encountered the same problem. Can I see your solution? Thank you very much.

**Comment by makstheimba** [comment]
@hjkltop Hi! I did dig really dip into it and was even capable to implement reconnects in some way but it was still too unreliable.

I can give you some tips and may be you can implement it in your project perfectly.

First what you need to do is reimplement default websocket interface that is provided by JsSIP. Default interface is simply stays up for too long and it will only close and trigger reconnect in case of a critical error in JsSIP code.
You can copy whole default WS interface from JSSiP but modify code a little to call `ondisconnect` callback when websocket is disconnecting:
```
  ...
  disconnect() {
        logger.debug('disconnect()');

        if (this._ws) {
            // Unbind websocket event callbacks.
            this._ws.onopen = () => {};
            this._ws.onclose = () => {};
            this._ws.onmessage = () => {};
            this._ws.onerror = () => {};

            this._ws.close();
            this._ws = null;
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            (this.ondisconnect as any)(false);
            // NOTE: call to ondisconnect will trigger ws reconnection on JsSIP side
        }
    }
    
    reconnect() {
        this.disconnect(); // NOTE: JsSIP will try to reconnect automatically after transport disconnect
    }
```

So now your websocket interface will trigger reconnect in case somebody disconnects it. Second part is to find out when to actually disconnect a ws connection.

What I did was that after session has been established I've added ICEConnectionStateChangeListener to listen when ICE gets disrupted. In that case I try to reconnect ws and renegotiate ICE connection:

```
private addICEConnectionStateChangeListener(session: RTCSession) {
        let renegotiateTimer = 0;

        session.connection.addEventListener('iceconnectionstatechange', () => {
            const iceConnectionState = session.connection.iceConnectionState;
            logger.debug(`Ice connection state change: ${iceConnectionState}`);

            if (iceConnectionState === 'failed') {
                session.terminate({
                    cause: JsSIPConstants.causes.RTP_TIMEOUT,
                    status_code: 408,
                    reason_phrase: JsSIPConstants.causes.RTP_TIMEOUT,
                });
            } else if (iceConnectionState === 'disconnected') {
                if (renegotiateTimer !== 0) {
                    clearInterval(renegotiateTimer);
                }
                if (this.socket.isConnected() || this.socket.isConnecting()) {
                    logger.debug('reconnecting ws due to disconnected ice');
                    this.socket.reconnect();
                }
                let renegTries = 0;
                renegotiateTimer = window.setInterval(() => {
                    renegTries++;
                    logger.debug(`Ice renegotiate attempt ${renegTries}`);
                    if (renegTries >= maxIceRenegotiationAttempts) {
                        clearInterval(renegotiateTimer);
                    } else if (
                        iceConnectionState === 'disconnected' &&
                        this.userAgent.isConnected() &&
                        this.socket.isConnected() &&
                        this.connectionState === SipConnectionState.Connected
                    ) {
                        session.renegotiate(
                            {
                                rtcOfferConstraints: {
                                    offerToReceiveAudio: true,
                                    offerToReceiveVideo: false,
                                    iceRestart: true,
                                },
                            },
                            () => {
                                clearInterval(renegotiateTimer);
                            },
                        );
                    }
                }, 1000);
            }
        });
    }

```

In the end I got outgoing calls to reconnect pretty well. I did not figure out a problem with incoming calls though - reconnect on incoming calls only worked 1 time and after that there was no sound in a call. Note that your backend plays a huge role here too so may be you'll not encounter such issues or encounter something else 🙃
