### ISSUE TITLE
Unhandled null is not an object (evaluating 'this.server_transaction.receiveResponse')

### ISSUE THREAD

**Issue by staskobzar** [versatica/JsSIP#747]
Hello,

Some minor error that was caught by our sentry.
Unhadled TypeError on reply in SIPMessage.js file. Here is a screenshot with more information:
![image](https://user-images.githubusercontent.com/147280/138713388-3fcca990-1275-49c1-bd37-3b49bdb6a88c.png)

Not sure if I can handle it in my code. Let me know if I am wrong but I did not find a way to do it.

Thank you,
Stas

P.S. This happened only once for Safari 14.12, MacOS 10.15

**Comment by jmillan** [comment]
Without the logs there is little we can do here. Can you please reopen the issue once with the JsSIP logs?

**Comment by jmillan** [comment]
It would be helpful having the JsSIP browser console logs too so we can see the SIP messages.
