### ISSUE TITLE
SessionDirection enum is undefined

### ISSUE THREAD

**Issue by Catlike14** [versatica/JsSIP#750]
I'm using typescript and I need to detect the direction of a RTCSession. In according to typescript definition of RTCSession, the direction is a SessionDirection, that is an enum described here:

https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.d.ts#L17

However, when I try to use it, I get this error:

`TypeError: Cannot read properties of undefined (reading 'INCOMING')`

Here a reproduction: https://codesandbox.io/s/typescript-forked-ri3w0?file=/src/index.ts

**Comment by jmillan** [comment]
@phwb,

Any chance you could comment on this one?

**Comment by phwb** [comment]
Hi,
I'm on vacation right now.  I can review this problem in a few days

**Comment by Catlike14** [comment]
Same problem with `Originator`, described here:

[https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.d.ts#L22](https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.d.ts#L22)

I think that this happens with all enums.

**Comment by phwb** [comment]
@jmillan Hi, I fix this problem in https://github.com/versatica/JsSIP/pull/648

**Comment by jmillan** [comment]
Please, check your TS environment and whether the file is accessible, it clearly exposes the given type `SessionDirection`

**Comment by jmillan** [comment]
reopening, #648 waiting for @ibc 's approval.

**Comment by ibc** [comment]
merged

**Comment by Suxsem** [comment]
It's still an issue in the latest version. SessionDirection is undefined AT RUNTIME
