### ISSUE TITLE
Empty SDP

### ISSUE THREAD

**Issue by igorpopryadukhin** [versatica/JsSIP#751]
> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use the JsSIP Google Group instead:
> 
> https://groups.google.com/forum/#!forum/jssip
> 
> If you have found a bug in the software, or want to propose a new well documented feature or improvement, please delete this text and continue. :)
```js
    this._currentRTCSession = this._ua.call(number, {
      extraHeaders: [],
      pcConfig: {
        iceServers: [
          {
            urls: 'stun:stun.l.google.com:19302'
          }
        ]
      },
      mediaConstraints: {
        audio: true, // Только аудио
        video: false
      },
      rtcOfferConstraints: {
        offerToReceiveAudio: true, // Принимаем только аудио
        offerToReceiveVideo: false
      },
      rtcAnswerConstraints: {
        offerToReceiveAudio: true,
        offerToReceiveVideo: false
      }
    })
```
If you install STUN
![image](https://user-images.githubusercontent.com/48174353/141511908-1667bc87-1ec6-41d9-b896-75c33014e1c6.png)

If you remove STUN, then everything is fine
```js
pcConfig: {
        iceServers: []
      },
```
![image](https://user-images.githubusercontent.com/48174353/141512174-3b390466-10d0-4baf-9a34-64490eb56b69.png)

**Comment by ibc** [comment]
Please use the mailing list
