### ISSUE TITLE
JsSIP.WebSocketInterface is not a constructor

### ISSUE THREAD

**Issue by shreyshahh** [versatica/JsSIP#758]
I want to use this library in a Javascript project. But I am getting the following error,

**JsSIP.WebSocketInterface is not a constructor**

Error on 1st line,
`var socket = new JsSIP.WebSocketInterface('myserver');`

I have downloaded this file https://jssip.net/download/releases/jssip-0.2.0.js, do I need any other file to run this project?

**Comment by ibc** [comment]
That's wrong usage. Please use the mailing list for questions.
