### ISSUE TITLE
Possible error in incoming message handling

### ISSUE THREAD

**Issue by gebsl** [versatica/JsSIP#759]
Hi versatica team,

I have a special use case where I need to send a `100 Trying` before sending a `200 OK` in response to an incoming message. As this is (to my knowledge) not natively supported by JsSIP I tried using private properties to achieve this functionality.

My setup is as follows (simplified):

A message comes in and I handle it via the `newMessage` callback. Instead of calling `request.accept()`, I set the internal property `message._is_replied = true` so JsSIP does not respond to the incoming message with a `200 OK` automatically. Right after that I use `response.reply(100)` to send the `100 Trying`.

After some time I then call `response.reply(200)` to finish the transaction.

Like this:
``` javascript
agent.on('newMessage', (obj) => {
      obj.message._is_replied = true;
      obj.request.reply(100);

      // some async stuff that takes a while

      obj.request.reply(200);
}
```

Now the problem is that JsSIP always sends a `405 Method Not Supported` when doing this. I suspect the following line to be missing a `return` statement:
https://github.com/versatica/JsSIP/blob/3622683221d4c765fb26a63dd5cc1680990933df/lib/UA.js#L636

Because of that, JsSIP will always fall through the next `switch` statement, resulting in hitting the `default` handler within the switch, which is a reply with `405`.
https://github.com/versatica/JsSIP/blob/3622683221d4c765fb26a63dd5cc1680990933df/lib/UA.js#L725

I know that what I did is not according to intended use, so I can fully understand, if this issue will not further be handled. Nevertheless, I wanted to ask whether this is a bug within JsSIP or just wrong usage of the lib.

Thanks a lot!
gebsl

**Comment by ibc** [comment]
100 Trying just makes sense for INVITE requests as per RFC spec. It doesn't make any sense for MESSAGE. So you shouldn't do that.

Anyway, please use the mailing list for questions. This is not a bug in JsSIP since it follows the spec.

**Comment by gebsl** [comment]
Thanks a lot for the quick response!
