### ISSUE TITLE
Incoming call : "Safari browser" compatibility issue 

### ISSUE THREAD

**Issue by prabhatk** [versatica/JsSIP#763]
Safari browser:
There are no voice exchange b/w caller and callee in case of incoming call.

Chrome browser:
same code is working fine in chrome for incoming call.

**Comment by prabhatk** [comment]
> Safari browser: There are no voice exchange b/w caller and callee in case of incoming call.
> 
> Chrome browser: same code is working fine in chrome for incoming call.

no reason for closing this ticket?
along with me lot many developers are facing some issues in safari.

**Comment by ibc** [comment]
As the issue template says, please make questions in the mediasoup public forum. Yours is not an bug in mediasoup-client despite you know it or not.
