### ISSUE TITLE
ACK R-URI and case sensitivity of SIP URI

### ISSUE THREAD

**Issue by xuoguoto** [versatica/JsSIP#769]
I has been facing a problem with ACK packets not been recognised by JsSIP. Did some more digging into the source code of JsSIP. The condition that triggers the error message is:
https://github.com/versatica/JsSIP/blob/3ab1fa7c8e09231c41ca21657bf962323906d5fe/lib/UA.js#L560
```js
  /**
   * Request reception
   */
  receiveRequest(request)
  {
    const method = request.method;

    // Check that request URI points to us.
    if (request.ruri.user !== this._configuration.uri.user &&
        request.ruri.user !== this._contact.uri.user)
    {
      logger.debug('Request-URI does not point to us');
      if (request.method !== JsSIP_C.ACK)
      {
        request.reply_sl(404);
      }

      return;
    }
```

If I understand correctly if ruri.user is neither user in config or user in contact the request gets rejected.

R-URI is:
ACK sip:stg-cqd0r2-10020005@erx-staging-q01.mydomain.com;gr=urn:uuid:b8a691ff-f678-4866-8cf0-780d670e7e33 SIP/2.0

The SIP URI configured in tryjsip is sip:Stg-CQD0r2-10020005@erx-staging-q01.mydomain.com

This does not match, but if I change the SIP URI to
sip:stg-cqd0r2-10020005@erx-staging-q01.mydomain.com (all small case) it works fine. 

I am not sure if this is a bug or violates the any RFC

**Comment by ibc** [comment]
Questions in the mailing list, please.

**Comment by xuoguoto** [comment]
This is not a question, this is a bug. I have posted this question in the list and figured out the answer too. The problem here (IMHO) is that if the case of the username in SIP URI does not match RURI of an ACK packet JsSIP dees not recognise it as an answer.

**Comment by ibc** [comment]
You should prove that this is a bug by referencing the corresponding spec. Spoiler: the spec says that it must be as JsSIP does. You say this is a bug because it affects you. That's not a reason, sorry.
