### ISSUE TITLE
Rejecting a re-invite with "491 Request Pending" leaves RTCSession in broken state

### ISSUE THREAD

**Issue by zombiedk** [versatica/JsSIP#771]
If asterisk try to send a re invite with an update to P-Asserted-Identity at the same time at JsSIP wants to send it's Session-update
it will reply with a 491 Request Pending, but next time asterisk re-sends the failed re-invite JsSIP will respond with a 488 Not Acceptable Here

we are using JsSIP 3.8.2 and Asterisk 18.11.1
related to #668

[3bc936033217227a64fdaf974c2179c5.pcap.zip](https://github.com/versatica/JsSIP/files/8407713/3bc936033217227a64fdaf974c2179c5.pcap.zip)

**Comment by jmillan** [comment]
If you further investigated this please open an GH issue that shows the problem in detail.

**Comment by zombiedk** [comment]
Hi witch additional information is needed
