### ISSUE TITLE
one-way sound if remote is not using the first media format in 200 OK

### ISSUE THREAD

**Issue by zombiedk** [versatica/JsSIP#772]
have found a issue if Asterisk has decided to not use the first media format that JsSIP has replied with in the 200 OK
JsSIP do not check which format the RTP is and there for we end up with not hearing any sound in the JsSIP client
as I see it where it 2 ways to fix it

1. fix that JsSIP check which codec it is receiving
2. option preferred_codec_only ; Respond to a SIP invite with the single most preferred codec

https://issues.asterisk.org/jira/browse/ASTERISK-29978
[tcpdump-dev-asterisk.pcap.zip](https://github.com/versatica/JsSIP/files/8449754/tcpdump-dev-asterisk.pcap.zip)

**Comment by ibc** [comment]
JsSIP doesn't handle the RTC stack, that's browser's business. Please use the mailing list for questions. This is not a JsSIP issue.
