### ISSUE TITLE
answer() method doesn't work on Windows 11

### ISSUE THREAD

**Issue by 46and2** [versatica/JsSIP#773]
Hi everyone! I'm using jssip 3.9.0 and freeswitch 1.10.7.
Trying to make an incoming video call to a jssip client, but on Windows 11 the `answer()` method doesn't do anything at all. At the same time it does work fine on Mac, Ubuntu or older versions of Windows. Has anyone had the same issue?

**Comment by ibc** [comment]
Questions in the mailing list please.
