### ISSUE TITLE
ICE Gathering Fails 

### ISSUE THREAD

**Issue by murugancmi** [versatica/JsSIP#775]
ICE Gathering fail on chrome 100.0.4896.127 (MAc)

**Issue :** When we try to make calls we are getting an Incompatible SDP error 

**Platform:** JsSIP 03.9,Chrome 100.0.4896,Mac 64bit

**Desc:** W
![Screenshot 2022-04-26 at 11 39 45 AM](https://user-images.githubusercontent.com/25261553/165233550-80cb001a-057e-47c0-9e54-6a3fa1ce1a34.png)
hen we try to make calls on firefox,safari works fine, but when we try to make the call from chrome we face this issue, When we check SDP we find we never get the SRFLX address from the STUN server. We understand it from WebRTC stack, If we check WebRTC Trickle ICE still same issue

**Comment by murugancmi** [comment]
@ibc can i share this info in mailing group

**Comment by ibc** [comment]
The issue contains a screenshot of mediasoup-demo and you are reporting it in JsSIP. In any case, use the corresponding forum please rather than GitHub.

**Comment by murugancmi** [comment]
sent to forum with JsSIP Log

**Comment by murugancmi** [comment]
@ibc yes I know that Just I shared an issue in WebRTC ICE gathering on chrome 100.0.4896.127 (Mac), And I posted the same issue in the JSSIP forum please have a look https://groups.google.com/g/jssip/c/2oy5XHXmfrA :) ,Thanks for your good time
