### ISSUE TITLE
How to detect refer successfully and get info in refered Side

### ISSUE THREAD

**Issue by NguyenTrong-Du** [versatica/JsSIP#776]
Hi guys
I'm implementing transfer call feature.
A is holding session with B and calling on session with C. When click Transfer Button in A, sessions of A terminated and session between B and C established, but C didn't receive anything info about that transfer. I wanna get info of B and some data from A.
How to do it? I tried listening ua.on('newMessage'),  session.on('refer') but just fired in A

**Comment by ibc** [comment]
Please use the mailing list for questions.
