### ISSUE TITLE
Chrome Incompatible SDP

### ISSUE THREAD

**Issue by murugancmi** [versatica/JsSIP#781]
Dear Team, When we try to make a call from chrome we are getting an Incompatible SDP issue, If we try from other browsers (Firefox, old version chrome it works fine)

**JsSIP Version :** 3.9.1

**Browser:** Chrome Version 102.0.5005.115 (Official Build) (x86_64)

**OS:** Mac Monterey

**SIP Trace**

INVITE sip:9198@xxxxxxxx SIP/2.0
Route: <sip:xxxx;transport=ws;lr>
Via: SIP/2.0/WSS vu0mo87bs2na.invalid;branch=z9hG4bK172428
Max-Forwards: 69
To: <sip:919894396168@sbcind.telecmi.com>
From: "murugan" <sip:444_2224258@sbxxxxxxcom>;tag=mngk0vqr9c
Call-ID: d86jg7k6aa8jc7u3mb2v
CSeq: 4898 INVITE
Proxy-Authorization: Digest algorithm=MD5, username="444_2224258", realm="sbcind.telecmi.com", nonce="Yq7xLmKu8AKPspMcrVAUr0liqprnXTOF", uri="sip:919894396168@sbcind.telecmi.com", response="32cbcb6dd2f3529da38b5c7a97c8c5cb"
Contact: <sip:b187u6vm@vu0mo87bs2na.invalid;transport=ws;ob>
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: ice,replaces,outbound
User-Agent: PIOPIYJS
Content-Length: 1595

v=0
o=- 5354425416260233741 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS DKMZpHGQAbCKjmxbBmc7JIxGViolXM6v27wq
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Ep9W
a=ice-pwd:Lk3ll9AbOLM1XbHSzn0BldiN
a=ice-options:trickle
a=fingerprint:sha-256 C7:64:2F:33:A4:76:DD:9C:AF:E8:20:DE:DD:CC:CE:99:E5:38:72:29:DB:7D:03:9E:A5:B6:C5:66:38:D2:0A:55
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:DKMZpHGQAbCKjmxbBmc7JIxGViolXM6v27wq 30ebe6af-951a-4e72-b47d-ea18c390f963
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:565990563 cname:dERTuCPgKhPGkvIB
a=ssrc:565990563 msid:DKMZpHGQAbCKjmxbBmc7JIxGViolXM6v27wq 30ebe6af-951a-4e72-b47d-ea18c390f963
a=ssrc:565990563 mslabel:DKMZpHGQAbCKjmxbBmc7JIxGViolXM6v27wq
a=ssrc:565990563 label:30ebe6af-951a-4e72-b47d-ea18c390f963

**Comment by ibc** [comment]
Please don't report issues not related to JsSIP here, no matter you still may think it's a JsSIP issue. It's not.
