### ISSUE TITLE
Video only call has m lines for both audio and video in SDP

### ISSUE THREAD

**Issue by mremski** [versatica/JsSIP#785]
Trying to initiate a video only call, the SDP contains m=audio and m=video blocks.
Setting mediaConstraints to { audio: true, video: false} the SDP contains only the m=audio block.

Using options with mediaConstraints set as follows, the created SDP for the SIP invite has both media blocks.
    var options = {
      'eventHandlers': eventHandlers,
      'sessionTimersExpires': 1800,
      'mediaConstraints': { 'audio': false, 'video': true},
      'pcConfig': {
        'bundlePolicy': 'max-compat',
        'rtcpMuxPolicy': 'require',
        'iceServers': [
          { 'urls': iceUrls }
        ]
      },
    };

Is this expected or should it create only a video block in the SDP.
If expected, should modifying the sdp in the 'sdp' event handler to remove the m=audio block work?
Other SIP stacks allow a video only call.

This is with 3.9.1 in a NodeJs environment.

**Comment by ibc** [comment]
Please ask on the public mailing list.
