### ISSUE TITLE
Failed to set remote answer sdp: Failed to apply the description for m= section with mid='0': Failed to set SSL role for the transport

### ISSUE THREAD

**Issue by Neil-Song** [versatica/JsSIP#795]
Hi all,

I did renegotiate scenario，sent reinvite to server,and received 200 OK from server, and I got a exception as below:

emit "peerconnection:setremotedescriptionfailed" [error:DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to apply the description for m= section with mid='0': Failed to set SSL role for the transport.]

The reinvite message sent to server is following:

INVITE sip:gw+kam@192.168.10.80:5080;transport=tcp;gw=kam SIP/2.0
Route: <sip:192.168.10.80:7443;transport=ws;r2=on;lr;ftag=XgcagK3crNUpc;did=863.246;nat=yes;rtp=bridge;rtp=ws>
Route: <sip:192.168.10.80:5062;transport=tcp;r2=on;lr;ftag=XgcagK3crNUpc;did=863.246;nat=yes;rtp=bridge;rtp=ws>
Via: SIP/2.0/WSS m0p7c6fbs37g.invalid;branch=z9hG4bK929731
Max-Forwards: 69
To: <sip:10002@192.168.10.80>;tag=XgcagK3crNUpc
From: <sip:10001@192.168.10.80:5062>;tag=1pveqv9ef1
Call-ID: d8d7a222-ec96-123b-f29c-000c29c333a2
CSeq: 6010 INVITE
Contact: <sip:qepjrujk@m0p7c6fbs37g.invalid;transport=ws>
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: ice,replaces,outbound
User-Agent: JsSIP 3.10.0
Content-Length: 1719

v=0
o=- 7048011177055558637 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS IadOa9jMDPrBUsVAHJ3QRV4dEfYVoL0uNvg7
m=audio 58426 UDP/TLS/RTP/SAVPF 0 8 101 111 63 103 104 9 106 105 13 110 112 113
c=IN IP4 192.168.10.153
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1468171865 1 udp 2122260223 192.168.10.153 58426 typ host generation 0 network-id 1 network-cost 10
a=candidate:2837992141 1 tcp 1518280447 192.168.10.153 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:141a
a=ice-pwd:Czc/w4LdwV8Eprad+CrDbdLa
a=ice-options:trickle
a=fingerprint:sha-256 2D:EE:BA:5D:C0:22:0E:9B:29:3E:13:34:00:DB:D3:38:11:4F:E0:F6:6F:F1:19:60:5A:86:2E:76:A5:18:D7:F6
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:IadOa9jMDPrBUsVAHJ3QRV4dEfYVoL0uNvg7 c82eb527-54d9-4de5-910a-4dab46dd6c47
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=ssrc:764725272 cname:+npn42wK/0k044Rl
a=ssrc:764725272 msid:IadOa9jMDPrBUsVAHJ3QRV4dEfYVoL0uNvg7 c82eb527-54d9-4de5-910a-4dab46dd6c47

the 200 OK（SDP）message received from server as below:

SIP/2.0 200 OK
Via: SIP/2.0/WSS m0p7c6fbs37g.invalid;received=192.168.10.153;branch=z9hG4bK929731
Record-Route: <sip:192.168.10.80:5062;transport=tcp;r2=on;lr;ftag=XgcagK3crNUpc;did=863.246>
Record-Route: <sip:192.168.10.80:7443;transport=ws;r2=on;lr;ftag=XgcagK3crNUpc;did=863.246>
From: <sip:10001@192.168.10.80:5062>;tag=1pveqv9ef1
To: <sip:10002@192.168.10.80>;tag=XgcagK3crNUpc
Call-ID: d8d7a222-ec96-123b-f29c-000c29c333a2
CSeq: 6010 INVITE
Contact: <sip:gw+kam@192.168.10.80:5080;transport=tcp;gw=kam;alias=192.168.10.80~49060~2>
User-Agent: FS
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Content-Type: application/sdp
Content-Length: 939

v=0
o=FreeSWITCH 1669920468 1669920470 IN IP4 192.168.10.80
s=FreeSWITCH
c=IN IP4 192.168.10.80
t=0 0
a=msid-semantic: WMS jDVs73HY9TYgcDfKDTrbLUZo4Z0ENhtW
m=audio 32364 UDP/TLS/RTP/SAVPF 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=ptime:20
a=sendrecv
a=fingerprint:sha-256 C9:3C:3C:1F:39:EA:BB:EE:C7:8E:5F:22:84:F0:2B:A8:E0:1D:AA:23:5F:CB:94:55:A3:CC:8F:9B:51:3C:5B:4C
a=setup:active
a=rtcp-mux
a=rtcp:32364 IN IP4 192.168.10.80
a=ice-ufrag:4qkFbaU50KzDRTqs
a=ice-pwd:Yv0X7mWuy1TccSl69vCbwm7m
a=candidate:6864678522 1 udp 2130706431 192.168.10.80 32364 typ host generation 0
a=candidate:6864678522 2 udp 2130706430 192.168.10.80 32364 typ host generation 0
a=end-of-candidates
a=ssrc:2817795256 cname:KffI8Mw8wlfzOk9i
a=ssrc:2817795256 msid:jDVs73HY9TYgcDfKDTrbLUZo4Z0ENhtW a0
a=ssrc:2817795256 mslabel:jDVs73HY9TYgcDfKDTrbLUZo4Z0ENhtW
a=ssrc:2817795256 label:jDVs73HY9TYgcDfKDTrbLUZo4Z0ENhtWa0

**Comment by ibc** [comment]
Something wrong in FreeSwitch. Please use the mailing list for usage problems. This is NOT an issue in JsSIP.

**Comment by Neil-Song** [comment]
Hi ,


Glad to get your reply,I will check the FreeSwitch configuration.


Thanks a lot.




Neil




无缘飘雪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "versatica/JsSIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [versatica/JsSIP] Failed to set remote answer sdp: Failed to apply the description for m= section with mid='0': Failed to set SSL role for the transport (Issue #795)





 
Something wrong in FreeSwitch. Please use the mailing list for usage problems. This is NOT an issue in JsSIP.

**Comment by Neil-Song** [comment]
Hi ,


I discussed this issue with FreeSWITCH side，but we do not check out the wrong reason.


could you please show me the wrong line in SDP info,Thanks.




Neil




无缘飘雪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "无缘飘雪"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 晚上6:14
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [versatica/JsSIP] Failed to set remote answer sdp: Failed to apply the description for m= section with mid='0': Failed to set SSL role for the transport (Issue #795)



Hi ,


Glad to get your reply,I will check the FreeSwitch configuration.


Thanks a lot.




Neil




无缘飘雪
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "versatica/JsSIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [versatica/JsSIP] Failed to set remote answer sdp: Failed to apply the description for m= section with mid='0': Failed to set SSL role for the transport (Issue #795)





 
Something wrong in FreeSwitch. Please use the mailing list for usage problems. This is NOT an issue in JsSIP.
