### ISSUE TITLE
Getting error on npm start in angular as `Module '"events"' has no exported member 'Listener'.`

### ISSUE THREAD

**Issue by dnyaneshwerEquentis** [versatica/JsSIP#799]
I am getting following error in my angular project.

Error: node_modules/jssip/lib/RTCSession.d.ts:1:23 - error TS2305: Module '"events"' has no exported member 'Listener'.

I am using angular 14 and typescript version 4.8.4

Any help on this would be much appreciated?

**Comment by tzahari** [comment]
I found a workaround form https://stackoverflow.com/a/74989759
But this is only a workaround and not a fix.

**Comment by jmillan** [comment]
This has been fixed in the latest release.
