### ISSUE TITLE
Recording audio on Apple iOS not working

### ISSUE THREAD

**Issue by Abbyzhoum** [versatica/JsSIP#803]
Hello,

I need help....
I use JsSip successfully to make a call on Windows system. If I try to do the same on iOS (on an iPhone running version 13.3)  I only get one side audio when I switch the output audio device of iPhone to speaker or earpiece.

The speaker or earpiece is switched on iphone, but the webrtc side does not push the voice stream to the server. So I think something is wrong, maybe JsSIP or  code module of iOS.

When I switch the output audio device of the iphone to the speaker, the input audio device is also switched, I don't know if this is the cause of the problem.

![1675409392959](https://user-images.githubusercontent.com/38661489/216538816-187ad191-042c-4716-958a-96f790846fcc.png)

**Comment by ibc** [comment]
Use the JsSIP mailing list for usage problems. This is not a bug in JsSIP.
