### ISSUE TITLE
Trying to use jssip on react-native 0.70.7

### ISSUE THREAD

**Issue by ronaldblanco** [versatica/JsSIP#811]
Hello, I am trying to use jssip 3.7.6 in react-native 0.70.7 (upgrading from react-native 0.63.3) with react-native-webrtc 1.84.0 after some updates and testings from references of the project react-native-jssip (deprecate) i am able to start a call successfully but always the Remote SDP that arrive to my freeswitch server does not have any a=candidate: and the call ends as INCOMPATIBLE_DESTINATION I am sending pcConfig on the options for the call correctly and the information arrived until the new RTCPeerConnection(pcConfig, rtcConstraints) but always the candidates are empty.
Any idea to how to address or fix this?

To reproduce: Reusing the folder lib-es5 from react-native-jssip on jssip it is allowing me to start the call with this problem (without the folder i am getting 0 activity and nothing arrive to my pbx server).
node version 18.15.0

**Comment by ronaldblanco** [comment]
OK, thanks.

**Comment by rcidt** [comment]
@ibc the google group seems to have been taken down. Is there an alternative place to get support?

@ronaldblanco did you ever get a resolution to your issue?

**Comment by ibc** [comment]
> the google group seems to have been taken down. Is there an alternative place to get support?

The Discussions tab here in GH.
