### ISSUE TITLE
JsSIP (Failed / Ended) Event not fired when call ended by remote party without receive

### ISSUE THREAD

**Issue by Mitul29** [versatica/JsSIP#813]
Hello!

I am using the JSSip (Version 3.10.0) library on my project. And I'm trying to set up an event handler to fire when the remote party terminates the call without receiving it, but it isn't firing any events ("ended or failed"). But when the client ends the call after receiving the event (ended), it does fire.

I also checked the documentation (in the [JsSIP demo](https://tryit.jssip.net/)) and checked that scenario with the same steps; the call did not end after terminating from the remote side without being answered.

So In my case i didn't get any event that detect client terminate call. How can i detect it?

Can anyone help me finding the solution regarding this scenario?

Thanks and Regards!

**Comment by ibc** [comment]
Use the mailing list for usage questions/problems, please.

**Comment by Mitul29** [comment]
I Already added this question to the mailing list but didn't get any answer.

**Comment by ibc** [comment]
> I Already added this question to the mailing list but didn't get any answer.

Not my problem, sorry. That doesn't justify that you open a ticket here.
