### ISSUE TITLE
Demo Down?

### ISSUE THREAD

**Issue by redvivi** [versatica/JsSIP#820]
Hey there!

Loading the https://tryit.jssip.net/ demo and entering a random user name leads up to "Call" button being greyed out, same after opening the generated SIP URL.

Error log comes up as:
[Error] WebSocket connection to 'wss://tryit.jssip.net:10443/' failed: Could not connect to the server.

Can you please fix it?

**Comment by ibc** [comment]
Please don't open an issue in JsSIP lib project to say that the demo is down.
