### ISSUE TITLE
Change type of request in OutgoingRTCSessionEvent to OutgoingRequest

### ISSUE THREAD

**Issue by SergioFatalist** [versatica/JsSIP#821]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `jssip@3.10.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/jssip/lib/UA.d.ts b/node_modules/jssip/lib/UA.d.ts
index 13798d3..1e51f3d 100644
--- a/node_modules/jssip/lib/UA.d.ts
+++ b/node_modules/jssip/lib/UA.d.ts
@@ -55,7 +55,7 @@ export interface IncomingRTCSessionEvent {
 export interface OutgoingRTCSessionEvent {
   originator: Originator.LOCAL;
   session: RTCSession;
-  request: IncomingRequest;
+  request: OutgoingRequest;
 }
 
 export type RTCSessionEvent = IncomingRTCSessionEvent | OutgoingRTCSessionEvent;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AlijiEmmanuel-dev** [comment]
I was just about to report this issue. It has not been fixed.

**Comment by ibc** [comment]
Fixed in https://github.com/versatica/JsSIP/pull/846
