### ISSUE TITLE
UA.call or any other method not working as expected with VueJS

### ISSUE THREAD

**Issue by alitainfotech** [versatica/JsSIP#823]
```
const socket = new JsSIP.WebSocketInterface("ws://127.0.0.1:8000");
const configuration = {
  sockets: [socket],
  uri: `sip:${userName}@example.com`,
  password: userPassword,
};

this.ua = new JsSIP.UA(configuration);
this.ua.start();
```

When I call ```this.ua.call("sip:bob@example.com")``` it throws ```'get' on proxy: property 'uri' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Object]' but got '[object Object]')```

If I destructure ```this.ua``` and run ```call``` method it will throw ```call is not a function```

Please guide me on how to resolve this issue.

**Comment by ibc** [comment]
I'm afraid you are doing something wrong (no idea what). Please ask in the JsSIP mailing list. This is not a bug.
