### ISSUE TITLE
UnMute Call

### ISSUE THREAD

**Issue by VGrytsenko2022** [versatica/JsSIP#831]
Hello 
Let me ask you a question. Stuck with a problem unmute call. My code
// ========
// UNMUTE\MUTE CALL
// ========

//UNMUTE
this.muteAudio = function () {
    if (session.isMuted().audio === true) {
        session.mute({
            audio: false,
            video: false

        });
        component.$server.auEvent(EventType.MUTED, "Microphone unmuted");
//MUTE    
} else if (session.isMuted().audio === false) {
        session.mute({
            audio: true,
            video: false

        });
        component.$server.auEvent(EventType.UNMUTED, "Microphone muted");
    }
}

//MUTE - Works good
//UNMUTE - Sound doesn't come back

Please tell me what is my mistake?

**Comment by VGrytsenko2022** [comment]
I realized my mistake. the correct code looks like this, everything works, sorry ...
// ========
// UNMUTE\MUTE CALL
// ========
this.muteAudio = function () {
    if (session.isMuted().audio === true) {
        session.unmute({
            audio: true,
            video: false
        });

    } else if (session.isMuted().audio === false) {
        session.mute({
            audio: true,
            video: false
        });
    }
}

**Comment by ibc** [comment]
Next time, questions in the mailing list, please.
