### ISSUE TITLE
Play audio or tone to remote user.

### ISSUE THREAD

**Issue by jahoppe** [versatica/JsSIP#840]
I would like to see the ability to play an audio file or tone (specifying frequency and pitch) to the remote user while not blocking the audio stream.   This can be used for playing a call recording notification beep (or tone) to the other party every X seconds.  We can use it to play a previously recorded perfect answer right before the agent starts to speak.  It would allow us to have an answering machine type functionality for incoming calls.  

playback(audio file name and location);
playback(various options for playing a tone);

NOTE: It would have to handle not only peer to peer connections, but also peer to Asterisk connections.   I don't know if there would be a distinction between these two scenarios, so I am bringing it up.

Thanks

**Comment by jahoppe** [comment]
playback(audio file name);
playback(options for playing tone);

**Comment by ibc** [comment]
Sorry, that's not the purpose of JsSIP.
