### ISSUE TITLE
import JsSIP from "jssip"; 打印JsSIP undefined

### ISSUE THREAD

**Issue by jianggangsheng** [versatica/JsSIP#842]
"jssip": "^3.10.1",
"rollup": "^4.9.1",

在rollup中使用jssip
打印JsSIP undefined
import JsSIP from "jssip";
console.log(JsSIP, "JsSIP");

**Comment by ibc** [comment]
Please use the mailing list.

**Comment by jianggangsheng** [comment]
> 请使用邮件列表。

什么？
