### ISSUE TITLE
Add custom header JsSIP - Asterisk

### ISSUE THREAD

**Issue by lilslimxdgxxxx** [versatica/JsSIP#850]
I'm trying to add X-LadingCode to sip header so asterisk can read it

I tried
>        uaRef.current.call(`sip:${numberInfor?.phoneNumber}@${hostName}${port ? `:${port}` : ''}`, {
>         extraHeaders: ['X-LadingCode: 100']
>       })
In asterisk:
![ảnh](https://github.com/versatica/JsSIP/assets/166002431/f8db9945-a390-49c9-a4a6-e4da05e5f302)
I can call normally but the sip header X-LadingCode always blank
![ảnh](https://github.com/versatica/JsSIP/assets/166002431/f49a8b61-fb79-4f69-a64a-0e20da24c919)

You guys have any idea what I'm missing?

**Comment by ibc** [comment]
Questions or usage problems in the mailing list, please, not in GitHub.
