### ISSUE TITLE
JsSIP processing re-INVITE

### ISSUE THREAD

**Issue by happytulubi** [versatica/JsSIP#852]
Now there is a call scenario where freeswitch ->webrtc (jsSIP) voice is normal and the video cannot be displayed. May I ask if jsSIP receives re INVITE and how to process the video

1、Freeswitch initiates a call to jsSIP without carrying video encoding
1、jsSIP receives INVITE with  in SDP
2、jsSIP answers with "SIP/2.0 100 Trying"
3、jsSIP answers with "SIP/2.0 180 Ringing"
4、user picks up a call, jsSIP answers with "SIP/2.0 200 OK"
5、Freeswitch answers with "ACK SIP/2.0"
6、Freeswitch sends re-INVITE to jsSIP and carries video encoding
7、jsSIP answers with "SIP/2.0 100 Trying"
8、jsSIP answers with "SIP/2.0 200 OK"

**Comment by ibc** [comment]
Questions in the mailing list, please.
