### ISSUE TITLE
Why is there a 2-second delay when exiting? According to the source code, it seems to have no practical significance.

### ISSUE THREAD

**Issue by Makaite** [versatica/JsSIP#865]
> Please, do NOT open an issue if you have problems or questions regarding the use of JsSIP. Use GitHub Discussions instead:
> 
> https://github.com/versatica/JsSIP/discussions
> 
> If you have found a bug in the software, or want to propose a new well documented feature or improvement, please delete this text and continue. :)

**Comment by Makaite** [comment]
I have found an explanation:If there are session wait a bit so CANCEL/BYE can be sent and their responses received.But my understanding is that before triggering the close, you need to wait for a message from the server and respond to it. Is this understanding correct.

**Comment by ibc** [comment]
Please open a discussion for this rather than an issue.

**Comment by Makaite** [comment]
I'm sorry,I will delete this issue.
