### ISSUE TITLE
Feature request: save failure cause on RTCSession object

### ISSUE THREAD

**Issue by sebakerckhof** [versatica/JsSIP#883]
Currently the only way to get the failure cause is by listening to the 'failed' event.

However, in an application the the code setting up the call and the code/component displaying the status of a call might be quite disconnected from each other. However, in order not to miss a failed event, the listener has to be attached right after setting up the call.
This means that the code setting up the call would need to listen to the failed event and pass on the failure cause.
This could be avoided if the failure reason was stored on the RTC session.

I'm willing to provide a PR for this if this is deemed acceptable.

**Comment by ibc** [comment]
The listener must be attached immediately after creating the session and the application is responsible of storing it. A low level library should not expose getters just to make half of the work that corresponds to the parent application.
