### ISSUE TITLE
chunk-UQWBJQZ5.js?v=135a6e89:2332 Uncaught TypeError: 'get' on proxy: property 'uri' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Object]' but got '[object Object]')

### ISSUE THREAD

**Issue by shrkx** [versatica/JsSIP#886]
拨号的代码

         const options = {
                mediaConstraints: { audio: true, video: true, mandatory: { maxWidth: 640, maxHeight: 360 } },
                mediaStream: this.localStream,
            };

            // Start the call
            this.outgoingSession = this.userAgent.call(this.sipPhoneNumber, options);
            
            错误提示
            chunk-UQWBJQZ5.js?v=135a6e89:2332 Uncaught TypeError: 'get' on proxy: property 'uri' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Object]' but got '[object Object]')

**Comment by mwanikigeorge** [comment]
@ibc Why did u close the issue without a comment, i have the same issue

**Comment by mwanikigeorge** [comment]
@ibc Thanks for the response 
Am still having the same issue even if i pass plain strings 

In my scenario i have a voice class that initialises the userAgent in the constructor 

```
constructor() {
    this.userAgent = new JsSIP.UA(configuration);
    this.userAgent.start(); 

    this.options = {
      eventHandlers: eventHandlers,
      mediaConstraints: { audio: true, video: false },
    };
}
```

then i have a makeCall method 

```
public async makeCall(options) {
this.userAgent.call(`sip:targetNumber@bonga.com`, this.options);
}
```

What am i doing wrong ?

If i make a call immediately in the constructor it works

**Comment by ibc** [comment]
> Am still having the same issue even if i pass plain strings

I've seen this problem many times reported by different people in different libs I own. And yes, finally it was always caused by the user storing things in Vue or MobX and later passing those values to JsSIP or other libs that require pure native types rather than Proxy values. So if you are using Vue or MobX, investigate your code.

**Comment by mwanikigeorge** [comment]
Got it working Thanks @ibc 

For anyone experiencing the same issue in vue js use the toRaw() from vue to get pure objects without losing methods 

```
import { toRaw } from "vue";

makeCall(target) {
    const UA = toRaw(this.userAgent);
    UA.call(target,options)
}
```
